### ISSUE TITLE
I CANT CHANGE DEFAULT DISPLAY ANYMORE

### ISSUE THREAD

**Issue by temtekmedia** [nomacs/nomacs#1008]
Out of nowhere the program asked me something about which display i want to see the frameless mode images at, i didnt select anything and now by default the frameless mode pictures go on the wrong display and there is no way to change that, didnt find any settings anywhere. Please fix/help!

**Comment by leejuyuu** [comment]
Hello @temtekmedia, maybe you hit the F10 key and entered the frameless mode. Have you tried hitting F10 again to exit the frameless mode?

**Comment by scrubbbbs** [comment]
The context menu (right-click) allows leaving the frameless mode if you don't know the shortcut key. #1136 discontinues the choose monitor dialog so frameless mode can't get stuck on one monitor.

**Comment by scrubbbbs** [comment]
There is no way this happens without frameless mode. In that case, it only happens if there is more than one monitor connected. 3.19 also adds the monitor setting to context menu.
