### ISSUE TITLE
Feature request : add a "multi-folder scrolling view" in panels>Thumbnail Preview

### ISSUE THREAD

**Issue by quatrecouleurs** [nomacs/nomacs#101]
I'm a very enthousiast user of nomacs which is a lightweight and straight forward app. I use it to quickly showcase my work in many contexts. There is a function that would just make it perfect.

"Thumbnail Preview" mode shows only one folder at a time. It would be great if it could autoload the previous / next folder in a vertical scrolling fashion. Like a sort of a tree of Thumbnails. So one could blazingly fast sort through his pictures to look for a special one.

Actually there are a lot of threads on support forums that ask for this very question (a behaviour shotwell and other database-based apps have)... But so far no app has included this option. As you have already a "recursive folder scan" option, this would just add to it greatly for us intensive users.

**Comment by diemmarkus** [comment]
very late response here
we would need to fundamentally change the architecture to get this with a *good enough* performance. given that and our time resources, this feature won't come, sorry.
