### ISSUE TITLE
webp not loading

### ISSUE THREAD

**Issue by Vozf** [nomacs/nomacs#1010]
"sorry I could not load the content"
Latest build, win 10.

**Comment by Vozf** [comment]
img https://gofile.io/d/GtMJ8b

**Comment by novomesk** [comment]
What installer is the "latest build" you are referring to?

**Comment by Vozf** [comment]
[3.17.2289 Beta](https://github.com/nomacs/nomacs/releases/tag/3.17.2287)

**Comment by novomesk** [comment]
I don't know how to reproduce your problem, it works here:

![screenshot_1010](https://github.com/nomacs/nomacs/assets/52529860/3404e0ca-b528-4536-843c-88744475a4a9)

**Comment by Vozf** [comment]
Is it win10?
this is the what I get 
![image](https://github.com/nomacs/nomacs/assets/22998537/cfd1d0bb-e3f5-426a-84ca-feddcb2ff4ed)

**Comment by novomesk** [comment]
I can get the same message when I manually delete `C:\Program Files\nomacs\bin\imageformats\qwebp.dll` file.

Can you check if the DLL is present and if it is loaded by `nomacs.exe` process when executed?

**Comment by Vozf** [comment]
Indeed I don't have this file. though I'm quite sure that I didn't interfere with installations and program directory

**Comment by Vozf** [comment]
Could you upload this dll?

**Comment by novomesk** [comment]
You can find the DLL inside https://github.com/nomacs/nomacs/releases/download/3.17.2287/nomacs-portable-win.zip archive.

**Comment by Vozf** [comment]
thanks for your help. It works now
