### ISSUE TITLE
Path of libnomacsCore.dylib is not updated on macOS

### ISSUE THREAD

**Issue by Dark-Schneider-666** [nomacs/nomacs#1013]
**Describe the bug**
The app always tries to load libnomacsCore.dylib from the created "build" folder to compile.
Also the app icon is not set.

**To Reproduce**
1) Follow the instructions for compiling on macOS with Apple Silicon.
2) Works fine, but no matter if you use 'make install' or copy, at the time we rename or delete the build folder it cannot open because cannot find libnomacsCore.dylib.

**Expected behavior**
Be able to install or place the app anywhere.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version Sonoma

**Additional context**
SOLVED this:
1) Compile, but DO NOT INSTALL with 'make install'.
2) Just change (not deleting all) the rpath "/<nomacs-clone_folder>/build" by "usr/local/lib", using the install_name_tool -rpath parameter (instead the -delete_rpath), leaving the others (that are homebrew library folders), for both the 'libnomacsCore.dylib' library and 'nomacs.app/Contents/MacOS/nomacs' binary.
3) Copy or move the libnomacsCore.dylib to /usr/local/lib, no admin permission required.
4) Copy or move nomacs.app to /Applications or any other location.
5) Delete the nomacs github clone folder.
6) Now we can launch nomacs.app and works fine, taking the libnomacsCore.dylib from /usr/local/lib.

Then the installer 'make install' could be updated to make this, installing the app at /Applications folder and placing the libnomacsCore.dylib at /usr/local/lib.

The icon issue was solved just dragging manually into file info, maybe there is a command line tool for that.

**Comment by scrubbbbs** [comment]
The `make install` command should do this since 97bbcd5f3cf9083068be039b1b37f6203f2b9e08. Note that this will not create a stand-alone bundle yet (not all libraries are packaged).
