### ISSUE TITLE
Bug: File ratings not updated

### ISSUE THREAD

**Issue by nanatsuhachi** [nomacs/nomacs#1018]
**Translated at DeepL.

I have updated nomacs to the latest version and the ratings I have made on nomacs are not reflected in the image files and revert back to before the ratings.
The OS is Win11 and the file I am trying to manipulate is a JPEG.

**Comment by leejuyuu** [comment]
Thanks for the report! Because this is a duplicate of #909, I will close this issue. Please head to the linked issue for further discussions.
