### ISSUE TITLE
qt5-default is not available in Ubuntu 22.04.2

### ISSUE THREAD

**Issue by andy8025** [nomacs/nomacs#1024]
I am trying to compile "3.17.2289 Beta" on Ubuntu 22.04.2 LTS.  Unable to install the required 'qt5-default' library.

**$ sudo apt-get install debhelper cdbs qt5-qmake qttools5-dev-tools qt5-default qttools5-dev libqt5svg5-dev qt5-image-formats-plugins libexiv2-dev libraw-dev libopencv-dev cmake libtiff-dev libquazip5-dev libwebp-dev git build-essential lcov libzip-dev**

Package qt5-default is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or is only available from another source

E: Package 'qt5-default' has no installation candidate

**~/nomacs/build$ cmake ../ImageLounge/ .**

CMake Error at cmake/Utils.cmake:21 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" (requested
  version 5.15.0) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake

 Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:98 (NMC_FINDQT)

-- Configuring incomplete, errors occurred!

**Comment by leejuyuu** [comment]
Thanks for reporting! This is due to Ubuntu dropping this package in 21.04. Replace `qt5-default` with `qtbase5-dev` then nomacs will compile. I've opened a PR to update the build instructions.
