### ISSUE TITLE
Compiling Nomacs from downloaded zip gets "not a git repository" error

### ISSUE THREAD

**Issue by LinuxBeaver** [nomacs/nomacs#1034]
`-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib64/ccache/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- A release build (non-debug). Debugging outputs are silently ignored.
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0") 
-- Checking for module 'exiv2>=0.27'
--   Found exiv2, version 0.27.6
-- exiv2 version by pkg-config: 0.27.6
-- exiv2 contains exiv2.hpp, using it
-- Found OpenCV: /usr (found version "4.7.0") found components: core imgproc 
-- Checking for module 'libraw>=0.12.0'
--   Found libraw, version 0.21.2
-- Found TIFF: /usr/lib64/libtiff.so (found version "4.4.0")  
-- QUAZIP: QuaZip-1 for Qt5 found
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Traceback (most recent call last):
  File "/home/contrast/Desktop/nomacs-master/ImageLounge/../scripts/versionupdate.py", line 141, in <module>
    update(args.inputfile, args.copy)
  File "/home/contrast/Desktop/nomacs-master/ImageLounge/../scripts/versionupdate.py", line 42, in update
    l = add_git_tag_string(l)
`

The warning `Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).` got my attention. 

While compiling my disk only had 700mb of diskspace. I am assuming this is the cause and if I free up more disk space it will work.

**Comment by LinuxBeaver** [comment]
I got it to compile by grabbing the file from Github via the command line, but it didn't work with the file I downloaded from Github a few months ago just by requesting to download the zip.

![image](https://github.com/nomacs/nomacs/assets/78667207/ee1db1c1-5764-4188-a904-36540fc71508)

anyhow its working so who cares. 

![image](https://github.com/nomacs/nomacs/assets/78667207/f801569a-4267-43fd-b9e7-0b9bbc08a50a)

**Comment by leejuyuu** [comment]
Hello @LinuxBeaver, thanks for reporting! I confirm that building from the zip source archive (at a4ac23007bb6806a80944d05dda3819714c0eb06) failed. 


```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Traceback (most recent call last):
  File "/home/tzu-yu/Downloads/nomacs-master/ImageLounge/../scripts/versionupdate.py", line 141, in <module>
    update(args.inputfile, args.copy)
  File "/home/tzu-yu/Downloads/nomacs-master/ImageLounge/../scripts/versionupdate.py", line 42, in update
    l = add_git_tag_string(l)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tzu-yu/Downloads/nomacs-master/ImageLounge/../scripts/versionupdate.py", line 107, in add_git_tag_string
    v[-2] = git_tag()
            ^^^^^^^^^
  File "/home/tzu-yu/Downloads/nomacs-master/ImageLounge/../scripts/versionupdate.py", line 116, in git_tag
    tag = subprocess.check_output(["git", "rev-parse", "HEAD"])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.
make[2]: *** [CMakeFiles/nomacsCore.dir/build.make:977: libnomacsCore.so.3.17.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:136: CMakeFiles/nomacsCore.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

It would seem that nomacs tags the build with info from the Git repository, so building will require cloning. 

@novomesk Do you think this is something we should fix? Or should I just add a note (like "please clone the repository instead of downloading the zip") in the build instructions of README?

**Comment by novomesk** [comment]
@leejuyuu it is something which should be fixed. We just need someone who understand those scripts.

**Comment by leejuyuu** [comment]
Sure, I could take a look later. I am tagging this as a confirmed bug.

**Comment by novomesk** [comment]
Maybe edit versionupdate.py like this?

```
def git_tag():
    import subprocess
    try:
        tag = subprocess.check_output(["git", "rev-parse", "HEAD"])
        tag = tag.strip().decode("utf-8")
    except subprocess.CalledProcessError as e:
        tag = ""

    return tag
```
