### ISSUE TITLE
Request: JPG compression level setting

### ISSUE THREAD

**Issue by muzso** [nomacs/nomacs#104]
It'd be nice to be able to set a compression level (a 1-100 percentage?) in Settings for the JPG (and possibly other?) format, when image adjustments (changes) are saved to disk.

Currently the saved JPG image is somewhere around 10 - 25 % size (in bytes) of the original. Sounds like a significant loss of quality (of course I know that working with JPG in itself is a major loss of quality, but I guess you see my point with this request).

P.S.: thanks in advance for considering this change request. :-)

**Comment by diemmarkus** [comment]
thanks for the hint (up to now we used Qt's default quality value here - which is indeed low).
So I have changed the default quality to be 97 (which is pretty much ok) - expert users can change this value in Settings > Editor
![img-2017-04-20 14 11 07](https://cloud.githubusercontent.com/assets/4182443/25230177/58a2f1ae-25d3-11e7-8a8b-1ac194e866b0.png)
