### ISSUE TITLE
"Fit to page" DPI for printing

### ISSUE THREAD

**Issue by protist** [nomacs/nomacs#105]
After selecting `Print`, the "Print Preview" window has the option to change the DPI. This effectively "zooms" the image for printing. It would be useful to have a "Fit to page" option, i.e. the DPI where the image fills the page exactly.

**Comment by diemmarkus** [comment]
thanks for reporting! - this is the default behavior now

**Comment by DJCrashdummy** [comment]
sorry for bumping this old issue, but is it somehow possible for the user to restore the old behavior to print "as it is" and not fit the whole page (some images get pretty ugly/unusable this big). it seems that there is nothing "print related" in the settings. :thinking: 

i can't even find a setting/button in the print preview to print 1:1 this one time. am i just blind, or was this function completely removed and i have to set the DPI manually every time?
