### ISSUE TITLE
Status bar displays wrong zoom value instead of 100%

### ISSUE THREAD

**Issue by tkzv** [nomacs/nomacs#1068]
**Describe the bug**
When I change image zoom (with up/down arrows or mouse wheel), when it becomes 100%, the status bar displays the previous value. Though, when I set 100% zoom with Ctrl-1, status bar correctly displays 100%; the gray panel at lower left also displays the correct value.

**To Reproduce**
1. Open an image.
2. Make sure status bar is visible.
3. Press Ctrl-1 to reset zoom to 100%.
4. Press the up arrow — the image is displayed at 150%, the panel at lower left and the status bar correctly indicate 150% zoom.
5. Press the down arrow — the image is displayed at 100%, the panel at lower left shows correct 100%, but the status bar still says 150%.
6. Press the down arrow — the image is displayed at 50%, the panel at lower left and the status bar correctly indicate 50% zoom.
7. Press the up arrow 2 times — zoom changes to 75%, then to 100%, the panel at lower left correctly shows those values, but the status bar says 75% for both.
8. Change zoom with the mouse wheel — same as above: correct values in status bar for all but 100%.

**Expected behavior**
The status bar should always display the correct magnification value.

**Desktop:**
 - OS: Gentoo Linux
 - Version 3.16.224-r6

**Additional context**
There were no errors in console.

**Comment by leejuyuu** [comment]
Thanks for reporting, reproduced with nomacs 3.17.2295 (94e9adaa) on Arch Linux.
