### ISSUE TITLE
Cannot load very large images (AVIF)

### ISSUE THREAD

**Issue by olekolek1000** [nomacs/nomacs#1075]
**Describe the bug**
Opening an 10000x5000px .avif image causes Qt6 to fail with this message:
```
[WARNING] QImageIOHandler: Rejecting image as it exceeds the current allocation limit of 256 megabytes
[WARNING] Memory cannot be allocated
```

**To Reproduce**
Test avif image (10000x5000px):
[test.avif.zip](https://github.com/nomacs/nomacs/files/15351232/test.avif.zip)

**Desktop**
- Arch Linux newest
- Qt 6.7.0

**Comment by novomesk** [comment]
This is expected because nomacs is fully prepared for Qt6 yet, unfortunately.

However, you may try to suggest the Arch package maintainer of nomacs to include following commit/patch

https://github.com/nomacs/nomacs/commit/6acba757ec5340dedb128ee2bc1a0b0885e2166d

**Comment by olekolek1000** [comment]
Okay, I see the fix is already in the `master` branch. Thanks!
