### ISSUE TITLE
Nomacs doesn't crop an image at a specified aspect ratio

### ISSUE THREAD

**Issue by BaumGuard** [nomacs/nomacs#1076]
**Describe the bug**
When trying to crop an image at a certain aspect ratio, the ratio chosen isn't being applied to the selection area. This means that one can freely select an area without the selected ratio. As a workaround one can enter the ratio in the text fields next to the drop-down menu.

**To Reproduce**
1. Open an image in nomacs
2. Change into cropping mode (either by right click -> Edit -> Crop Image or by clicking the corresponding symbol in the bar on the top)
3. Select an aspect ratio (e.g. 16:9)
4. Select an area in the image

**Expected behavior**
Normally the area selected should have the specified ratio, but the ratio isn't applied to the selection and to the text fields next to the drop-down menu

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - nomacs Version: 3.17.2295

**Comment by leejuyuu** [comment]
Thanks for reporting, confirmed on Arch Linux, nomacs 3.17.2295 (94e9adaa).

**Comment by pbentkowski** [comment]
I have the same problem. I compiled from the git repo on 6 Jun 2024 with **no** plugins.

- OS: Tuxedo OS 3 
- nomacs Version: 3.17.2297 (cc3bf6d0)
- OpenCV: 4.5.4
- Qt:  6.7.0

**Comment by pbentkowski** [comment]
A follow-up… I compiled Nomacs the same day, also on Tuxedo OS 3, but on a computer where the OS is installed from scratch. And **cropping works**! The difference seems to be the version of the Qt library.

- OS: Tuxedo OS 3
- nomacs Version: 3.17.2297 (bac800e5)
- OpenCV: 4.5.4
- Qt: 5.15.13

Probably, because of other project, the first computer is set to preffer Qt6.

**Comment by leejuyuu** [comment]
@pbentkowski Thanks for testing this! I confirm that this is caused by changing from Qt5 to Qt6. This is caused by a missing signal connection.

```
[WARNING] QMetaObject::connectSlotsByName: No matching signal for on_ratioBox_currentIndexChanged(QString)
```

I am working on looking through all the auto signal connections, hopefully this can be fixed soon!

**Comment by scrubbbbs** [comment]
@leejuyuu are you removing them? I think you should as they break when renaming the widget. Also could replace them with the new signal/slot syntax which catches mistakes at compile time.

**Comment by leejuyuu** [comment]
Yes, I just happened to mentioned in #1093 :)

**Comment by leejuyuu** [comment]
@BaumGuard, @pbentkowski If you are available, please help test whether #1096 fixes this issue (and if it breaks other things). Thanks!

**Comment by BaumGuard** [comment]
I tried all versions available in the Manjaro repo and in the AUR but the problem occurs in every one of them. The versions are:
- 3.17.2295-3 (nomacs, nomacs-qt6-git)
- 3.2.0 (nomacs-git)

**Comment by leejuyuu** [comment]
@BaumGuard, sorry, the fix has not been released, so it requires building from source to test.

**Comment by pbentkowski** [comment]
@leejuyuu All right! I did a quick test. I cloned a fresh version from the main repo, pulled the #1096 fix, and compiled it, and it seems to work. All the fixed aspect ratios hold their proportions when pulled by the corner. They stop when I pull by the "grab point" in the middle of the side, which, I think, is an intended behaviour.

I don't see any difference between the behaviour "No Aspect Ration" and "User Defined". Is User Defined some user-made pre-set? Some weird things happen when I switch between aspect ratios. I clicked like a mad monkey, and, for example, the crop area's size got smaller with each change.  Also, sometimes, I get VERTICAL aspect ratios, which should not happen.  BUT IT NEVER HANGED! I pressed Escape, and I could start cropping again. 
[Screencast_20240609_233138.webm](https://github.com/nomacs/nomacs/assets/18704224/521173ca-415d-498c-b190-3f96f5f85bed)

**Comment by leejuyuu** [comment]
@pbentkowski thanks for testing and the detailed feedback! The "user-defined" seems to have been weird, e.g. #598.

**Comment by pbentkowski** [comment]
> I tried all versions available in the Manjaro repo and in the AUR but the problem occurs in every one of them. The versions are:
> 
You have to clone the repository (I assume you can install _gh_ tool, which most distros allow) and enter the directory:
```Bash
gh repo clone nomacs/nomacs
cd nomacs
```
then pull the #1096 fix:
```Bash
gh pr checkout 1096
```
Then the usual download & install of the dependencies (may vary on different distros) and compilation as described on the main page (https://github.com/nomacs/nomacs?tab=readme-ov-file#build-nomacs-ubuntu). If successful, you can run it straight from the build directory (no system installation required):
```Bash
nomacs
```
