### ISSUE TITLE
Icon and font colors incorrect in light theme when the system/platform theme is Dark

### ISSUE THREAD

**Issue by Martin-Eckleben** [nomacs/nomacs#1080]
Font is black and I have no clue why and no setting for it.
Also most icons are good after setting icon color manually but these X are basically invisible :)

![image](https://github.com/nomacs/nomacs/assets/1571683/a54d647e-6856-4dc9-92e4-fe80fdaa0d63)

Settings:
![image](https://github.com/nomacs/nomacs/assets/1571683/f5abd433-5982-41e2-9570-9f8b038d2294)

Should I post a PR?

Thank all of you for your hard work! :+1:  :wave: 

nomacs
![image](https://github.com/nomacs/nomacs/assets/1571683/691eada3-a844-4345-b0d6-8c90b9120e14)
OS: Manjaro

**Comment by leejuyuu** [comment]
@Martin-Eckleben, PRs are welcome!

**Comment by scrubbbbs** [comment]
@leejuyuu I see what you are saying, but #943 comes from the fact that the default theme is broken which is the greater issue. On second thought, I think we should close #943 as a duplicate and keep #1080 since it has screenshots.
