### ISSUE TITLE
Nomacs documentation does not exist.

### ISSUE THREAD

**Issue by Poobslag** [nomacs/nomacs#1088]
**Describe the bug**
The Nomacs menu includes a ? -> Documentation button. The button takes you to a page which reports "Page not found :( The page you are looking for doesn't exist or has been moved."

**To Reproduce**
1. Go to '? -> Documentation'
2. The documentation is not shown, and instead a "Page Not Found" error is reported.

**Expected behavior**
The documentation should be shown.

**Screenshots**
![image](https://github.com/nomacs/nomacs/assets/5902413/2dbd3982-3065-46f1-b603-5fcec4a6e97a)

![image](https://github.com/nomacs/nomacs/assets/5902413/bda23418-1930-4ba0-b335-17526f308f17)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version 22H2

**Additional context**
None

**Comment by scrubbbbs** [comment]
Not so much dead link as there isn't anything to link to. The [wiki](https://github.com/nomacs/nomacs/wiki) seems to be  open to contributors, should we use it?

**Comment by leejuyuu** [comment]
That one should be linked to https://nomacs.org/docs/. Thanks for reporting!
