### ISSUE TITLE
Mount point/drive probing issue with card reader on Windows

### ISSUE THREAD

**Issue by qazo** [nomacs/nomacs#110]
Each time I open nomacs i get [this messagebox error](http://i.imgur.com/807viRI.png). I'm not sure, but I think that it could be caused by the File Explorer probing for mounted devices. If I'm right, then the reason that I get this popup would be having a Card reader that doesn't have a card mounted; since readers have static drive numbers.

**Comment by apfeltee** [comment]
I have the same issue. I've run nomacs with [DrMemory](https://github.com/DynamoRIO/drmemory), and found the likely culprit:

    NtCreateFile
        [...]
        arg 2: ... "\??\D:\Qt\qt-everywhere-opensource-src-5.7.0-x64\qtbase\qtlogging.ini", att=...
        [...]

I've removed the unimportant bits. Basically, it tries to access a folder that, I assume, would only ever exist on some sort of CD/DVD provided by Qt.  
Other than downgrading to a previous version (or building nomacs yourself), I don't really see a solution. :frowning_face:

**Comment by diemmarkus** [comment]
thanks for reporting! This seems to be a Qt issue that we have to investigate further! Could you please try our current [beta](http://download.nomacs.org/msi-setup/nomacs-setup.msi)? This is built with Qt 5.8 - the issue might be resolved there (if we are lucky).

**Comment by diemmarkus** [comment]
could you toggle _Use Log File_ in `Preferences > Advanced` and see if the error still exists?

**Comment by qazo** [comment]
Huh, funny thing is I don't have this problem anymore; with or without an sd card. Tried reproducing it but couldn't. Strange thing is that I'm still running the same version (22 Mar 2017 - 3.6.1.1108).

Anyways, thanks for the assistance.

**Comment by mederly** [comment]
Hello. I have the same problem: when starting nomacs, I get the above mentioned error ("There is no disk in the drive. Please insert a disk into drive D:"). It is both with 3.7.0.1109 [x64] / Qt 5.8.0 and 3.6.1.1108 [x64] / Qt 5.7.0. I have enabled logging to file, but there's nothing relevant in the files.

Having written this... it seems there is a workaround: I changed drive letter for card reader from D: to N: - and the problem is gone.

**Comment by pro-gramer** [comment]
Thanks mederly for that temporary FIX. I changed D drive letter to Z and that removed the annoying "Nomacs.exe no disk" error that appears everytime i open an image file.
https://i.imgur.com/rTxvpci.jpg
https://i.imgur.com/VJ0Gp1K.jpg
this error happens to me only when I unplug the sd card and the D drive stays transparent.
I'm using desktop win 10. the sd card is plugged in my epson scanner sd card slot (my desktop does not have an actual sd slot).
when sd card is plugged in the printer i get NO error.
I'm guessing the error happens whenever you have an empty sd card reader/slot with a drive letter "D".

**Comment by diemmarkus** [comment]
is this issue still present in nomacs 3.14?
