### ISSUE TITLE
Nomacs won't start anymore, looking for libopencv_imgproc.so.409

### ISSUE THREAD

**Issue by rado84-github** [nomacs/nomacs#1105]
**Describe the bug**
Nomacs won't start anymore, looking for libopencv_imgproc.so.409

**To Reproduce**
1. Set any image to be opened with nomacs. It won't open.
2. Open terminal, type "nomacs" and press enter. You'll see this message:
"nomacs: error while loading shared libraries: libopencv_imgproc.so.409"

**Expected behavior**
Nomacs should start

**Screenshots**

**Desktop (please complete the following information):**
 OS: Arch.
Desktop: Cinnamon.

**Additional context**
The only way I could fix this was to downgrade opencv & python-opencv to v 4.9.0.

**Comment by leejuyuu** [comment]
Hello, did you install with the nomacs AUR package? When any underlying library is upgraded, the nomacs executable should be recompiled to recognize the new ones. Please try rebuilding (run makepkg) again.

**Comment by leybodv** [comment]
@leejuyuu I have the same issue and reinstalling the package did not help me.

**Comment by leejuyuu** [comment]
I tested, you have to recompile, not simply reinstall. Edit the PKGBUILD and increase the pkgrel, and run `makepkg -sic`.

**Comment by jnschaible** [comment]
I had this issue, can confirm a recompile fixes it. If you use yay, just do a cleanbuild

**Comment by leybodv** [comment]
I use pikaur, and `pikaur --sync --rebuild nomacs` helped, indeed. Thanks!

**Comment by leejuyuu** [comment]
Closing as completed.
