### ISSUE TITLE
No exit keybinding

### ISSUE THREAD

**Issue by o9000** [nomacs/nomacs#111]
Most Qt applications, including Qt Creator, use Ctrl+Q to exit the program. On nomacs, the menu entry does not have this keybinding associated by default. I use nomacs to view images in many different folders, so I exit it a lot. It would be great if I didn't have to use the mouse to close it.

I know it can be added in settings, just wondering why it is not the default.

**Comment by diemmarkus** [comment]
The default shortcut is Alt+F4 (which is also pretty common for closing windows). But as you said, you can assign Ctrl+Q to the Exit command using `Edit > Keyboard Shortcuts`.

**Comment by 07416** [comment]
Solved, there's now "Close on Esc" setting in general settings.
