### ISSUE TITLE
No description found for display resolution ("high DPI")

### ISSUE THREAD

**Issue by mabra** [nomacs/nomacs#1113]
**Describe the bug**

**To Reproduce**

**Expected behavior**
Open man file, find parameters for display resoltion.
BUT man file is more or less a surrogat.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu]
Debian 10, XFCE
**Additional context**
For other programs, passing "QT_AUTO_SCREEN_SCALE_FACTOR=1"
(or similar - dont know about the nomacs GUI base).
I am running nomacs out of a chroot, because Debian'ist
are too lazy to put the best image tool into their repository ...
Thanks!

**Comment by leejuyuu** [comment]
@mabra I don't understand your issue. What do you want to achieve but cannot?

As far as I know, nomacs does not support HiDPI properly now. There's an open PR https://github.com/nomacs/nomacs/pull/1102.

**Comment by mabra** [comment]
I want to have a larger display - but not for all apps (this is possible by changing displays DPI value, say, from 96 to 112.
Many apps, probably depending on their graphics libray allow to start them with setting envionment variable, for QT for example to "QT_AUTO_SCREEN_SCALE_FACTOR=1.5" to achieve this.
For my jedit (was only used for testing in the same chroot like nomacs), this was working (with another variable).
Thanks for the pointer, will have a look into it.

**Comment by scrubbbbs** [comment]
@mabra  nomacs is DPI-aware which means it will rescale the UI to the display DPI. So it does support HiDPI properly; #1102 was a misguided attempt at "fixing" something that wasn't broken.

QT_FONT_DPI overrides the display DPI and thus is the correct way to scale the nomacs UI. QT_SCALE_FACTOR, and others are for debugging applications that are not DPI-aware, using this with nomacs will not scale things correctly.

If this works for you please let us know so we can close this bug report

**Comment by mabra** [comment]
Thank you very much.
This really works!

**Comment by voidastro4** [comment]
On Sway when using scale 2 nomacs displays UI elements corretly but it scales images to a 1080p target instead of 4K.
Upscaling artifacts are evident.

A solution is to undo the scaling Nomacs performed with QT_SCALE_FACTOR=0.5  but this isn't desirable.

**Comment by scrubbbbs** [comment]
@voidastro4 QT_SCALE_FACTOR should not be in the environment passed to nomacs. Nomacs is DPI-aware and scales everything correctly if given the *correct* display DPI, which might not be present (especially on X11, but maybe due to drivers or multi-monitor setups).

Does `QT_SCALE_FACTOR= QT_FONT_DPI=200 nomacs` work?  If not you might play around with `QT_WAYLAND_FORCE_DPI=` set to `96` or `physical`.

Also it would be nice to know if this is a Wayland problem or Sway problem.

**Comment by voidastro4** [comment]
In the absence of that env var it scales UI correctly but the image is not scaled correctly.
I have since abandoned nomacs in favor of qview which doesn't have this problem (and happens to consume less ram).

**Comment by leejuyuu** [comment]
@voidastro4 Glad to hear that you've found something that works for you. Would you mind opening a separate issue to show us how to reproduce the problem that you've encountered? If possible, attach some screenshots so we know what's the problem and the desired outcome. Thanks!

**Comment by voidastro4** [comment]
> @voidastro4 Glad to hear that you've found something that works for you. Would you mind opening a separate issue to show us how to reproduce the problem that you've encountered? If possible, attach some screenshots so we know what's the problem and the desired outcome. Thanks!

https://github.com/nomacs/nomacs/issues/1126

**Comment by leejuyuu** [comment]
Thanks!
