### ISSUE TITLE
Title bar doesn't follow dark theme in Windows 11

### ISSUE THREAD

**Issue by Solarflame5** [nomacs/nomacs#1118]
**Describe the bug**
Apps can set their title bar color to dark in Windows 11, nomacs doesn't support this and always shows a light title bar.

**To Reproduce**
1. Set nomacs theme to dark
2. Title bar stays light

**Expected behavior**
Title bar turns dark

**Screenshots**
![image](https://github.com/nomacs/nomacs/assets/47642904/4ab16b97-861f-4b56-85b7-06de4cc719a8)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version: 23H2

**Comment by scrubbbbs** [comment]
This is possible by using internal windows APIs. Example [here](https://github.com/scrubbbbs/cbird/blob/3c0f82e51e737dadef4db94a89374922d7361d8b/src/qtutil.cpp#L642).

**Comment by leejuyuu** [comment]
>  The same issue existed in the Blender software, and it was fixed in release 3.3. I don’t have any information about the code or programming, but I am adding the relevant links here in case they are helpful. Thank you for your great app! ❤️
> 
> [Blender 3.3 Release Notes](https://developer.blender.org/docs/release_notes/3.3/user_interface/#:~:text=Windows%3A%20title%20Bar%20will%20respect%20operating%20system%20%22Dark%20Mode%22%20setting.)
> [Fixing Issue](https://projects.blender.org/blender/blender/commit/ddbac88c08ef)
> [Fixing Issue](https://archive.blender.org/developer/D14847)

_Originally posted by @mahdishalchian in https://github.com/nomacs/nomacs/issues/1140#issuecomment-2440756242_

**Comment by scrubbbbs** [comment]
This will be fixed in #1140 however Qt 6.8.0 or later is required which isn't in the appveyor workflow yet.
