### ISSUE TITLE
When sorted by time and have images with the same time stamps, deleting one of those images selects the wrong next image

### ISSUE THREAD

**Issue by mikescha** [nomacs/nomacs#1125]
When you have a folder with images with the same time stamps, deleting one of those images causes the view to change to the next image with a different time stamp instead of changing to the next one in the list. This only happens if the sort order is changed to be sorted by date.

To reproduce:
1. Make a new folder on your desktop
2. Run Paint, draw a black circle, and save it to the new folder
3. Wait a minute to ensure the time changes
4. Draw something else on the picture so you can distinguish it from the first, and save it to the same folder with a new name
5. Go to that new folder in File Explorer, select the first image, and copy and paste it a few times
6. Sort the folder by date
7. Right-click the first image, Open with..., Nomacs
8. Right-click the image in Nomacs, Sort, by Date Modified
9. Show the Thumbnail panel and verify that you have several copies of your first image in a row, and the last image is the one you saved in step 4. The light-blue selection rectangle should be on the first image in the list.
10. Press the Delete key or press the Delete button on the toolbar

Result: The image is deleted, but the selection jumps to the last image in the list instead of the next one.

Expect: The image is deleted, and the selection goes to the next one in the sequence shown in the thumbnails instead of the next time stamp.

I ran into this because I have a number of photos from a whale watching trip, where many of the images have the same time stamp because they were taken in quick succession. I am trying to delete the ones I don't want, but this issue is making it very difficult!

**Comment by scrubbbbs** [comment]
Confirmed, however the sort doesn't seem to be the problem. When I delete from the thumbnail panel I lose the selection focus entirely and cannot get it back with arrow keys. I think there are some related/duplicate issues on this but I can't seem to find them at the moment.
