### ISSUE TITLE
Bug on dark theme (KDE)

### ISSUE THREAD

**Issue by felipe-jr** [nomacs/nomacs#1127]
All the letters become dark on the dark theme 
![image](https://github.com/user-attachments/assets/02ab03e1-ae27-4924-8bf7-56654356c332)

**Comment by leejuyuu** [comment]
Maybe duplicate of #943 and/or #1080? This might be the theme getting partially applied. The system wants dark theme so the background is grey, while nomacs defaults to light theme so the fonts are black.

**Comment by scrubbbbs** [comment]
Yes it is definitely the broken light theme; the dark theme sets the colors correctly, and the system theme uses all/most colors from the system.

**Comment by scrubbbbs** [comment]
Definitely duplicate of #1080
