### ISSUE TITLE
Frameless (Win11) obstructed by what appears like a Mask on WideScreen Monitor.

### ISSUE THREAD

**Issue by bbecausereasonss** [nomacs/nomacs#1134]
See Video.

I'm having a weird issue where I cannot drag a frameless window on my ultra wide monitor because it gets cut off almost like there are masks on the left/right side of my monitor over it. Disappears.

https://github.com/user-attachments/assets/efc28b76-b3f2-4857-83ea-93a7c79f059d

Win11X64, Latest Pre-Release build of Nomacs

**Comment by leejuyuu** [comment]
Please specify the exact version and commit you are using. You can find them in `? > About nomacs`.

**Comment by bbecausereasonss** [comment]
[3.19.0 Testing Qt6 build on Windows](https://github.com/nomacs/nomacs/releases/tag/3.19.0)

**Comment by leejuyuu** [comment]
Reproduced nomacs 3.19.0 (eca2377d). This is a regression. The 3.17.2295 is still functional.

The problem seems to be we are dragging the image inside the viewport instead of dragging the window, i.e. the obstruction is the window boundary.

**Comment by scrubbbbs** [comment]
Thanks, most likely something I've done recently, I'm looking into it.

**Comment by leejuyuu** [comment]
@scrubbbbs  For your info, I only tested this on Windows 11.

**Comment by leejuyuu** [comment]
@bbecausereasonss There's a PR that should fix this. You can test it with the builds from https://ci.appveyor.com/project/novomesk/nomacs/builds/50319582.
