### ISSUE TITLE
Batch processing crop fails

### ISSUE THREAD

**Issue by leejuyuu** [nomacs/nomacs#1139]
i just installed 3.19.0, now the batch processing fails:
```
processing /Users/xxx/Downloads/FCI_hres_OPE__true_color_flames_20240723T033000.png
[Transform Batch] image 22272 x 22272 cropped to x12971 y3334 w1880 h1136
Original filename added to Exif
Could not save: /Users/xxx/Downloads/cropped/FCI_hres_OPE__true_color_flames_20240723T033000
Ui - a lot of things went wrong. Your original file can be found here: 
Unknown error
I did not delete the original because I detected 2 failure(s).
```

the same issue seems to also exist with the latest `master`.

_Originally posted by @sjoro in https://github.com/nomacs/nomacs/issues/1138#issuecomment-2250042688_

**Comment by leejuyuu** [comment]
Confirmed on Arch, nomacs 3.19.0 (eca2377d).

Steps to reproduce:

1. Select one input file (I used png) in batch processing.
2. Setup Transform > Crop with a crop rectangle with some size (eg. 20 x 20).
3. On the Output page, select an empty directory, and set the settings as follows
![image](https://github.com/user-attachments/assets/2fd13a41-37a1-4171-a7b3-50c4fdc171a8)

4. Execute the batch processing, and observe the same message in the batch log.

**Comment by leejuyuu** [comment]
@sjoro The batch processing functions when changing the "Keep Extension" in the "Filename" block to "Convert To". Please see if this works for you.

I see that the New Filename has no extension, could be the source of the problem.

**Comment by leejuyuu** [comment]
@sjoro Thanks for testing! Does the crop rectangle position work correctly for you as well?

**Comment by sjoro** [comment]
yes, works as expected.
