### ISSUE TITLE
Qt6 build with quazip-qt6

### ISSUE THREAD

**Issue by eddiezato** [nomacs/nomacs#1144]
Tried building nomacs-qt6 with quazip-qt6 in msys2/clang64. Everything works. But need to configure quazip-qt6 search:

https://github.com/nomacs/nomacs/blob/97bbcd5f3cf9083068be039b1b37f6203f2b9e08/ImageLounge/cmake/Unix.cmake#L114-L119
`-DQT_VERSION_MAJOR=6`
```C
find_package(QuaZip-Qt${QT_VERSION_MAJOR} QUIET)
if (QuaZip-Qt${QT_VERSION_MAJOR}_FOUND)
    message(STATUS "QUAZIP: QuaZip-1 for Qt${QT_VERSION_MAJOR} found")
    set(QUAZIP_LIBRARIES QuaZip::QuaZip)
    add_definitions(-DWITH_QUAZIP)
    add_definitions(-DWITH_QUAZIP1)
    ...
endif (QuaZip-Qt${QT_VERSION_MAJOR}_FOUND)
```

**Comment by scrubbbbs** [comment]
Thank you, this is one of the last things missing for Qt 6 build.
