### ISSUE TITLE
nomacs silently refuses to open files with no extension

### ISSUE THREAD

**Issue by protist** [nomacs/nomacs#115]
To replicate:
1. Have two (image) files in a directory: `a.png` and `b.png`
2. Rename `a.png` to `a`
3. Attempt to open `a` in nomacs

Expected results:
* Image `a` is opened in nomacs

Observed results:
* Image `b.png` is opened in nomacs

Gwenview, image viewer, okular, etc. open up `a` fine. `file a` shows it as `PNG image data`.

Oddly enough, if there is only `a` in the directory, nomacs partially recognises it as an image. It displays fine, but there is an index overlay on the top left. Also, up an d down arrows scale the image, but the mouse scroll wheel does not. Pressing left or right pops up `/path/to/directory does not contain any image`.

nomacs 3.6.1
Arch Linux (up-to-date)

**Comment by eadmaster** [comment]
also, if the extension is wrong, emacs may suggest to rename the file like Irfanview does...

**Comment by vext01** [comment]
Same problem here.

My gopher client wrote out a file named `/tmp/tmpctjb9n76` which nomacs will not open. `feh` is ok with it though.

It's a jpeg.

**Comment by protist** [comment]
Thank you for the fix. I can confirm that the latest version works as expected.

**Comment by Ultimatedude10** [comment]
sadly this does not work on version 3.17.2263
