### ISSUE TITLE
Missing Thumbnails for JXL Files

### ISSUE THREAD

**Issue by fraxgut** [nomacs/nomacs#1151]
**Describe the Bug**  
JXL files don't display thumbnail previews when Nomacs is the default image viewer. When browsing a directory containing JXL files in Windows Explorer, they appear without preview thumbnails.

**To Reproduce**  
Steps to reproduce the issue:
1. Navigate to a directory containing JXL image files.
2. Browse the files in the directory.
3. Notice that the JXL files lack thumbnail previews when Nomacs is the default image viewer (associated file type).

**Expected Behavior**  
JXL files should display thumbnail previews in Windows Explorer when Nomacs is the associated file type, similar to other supported image formats, for easier identification and browsing.

**Screenshots**  
![image](https://github.com/user-attachments/assets/59329c59-a725-4a8f-b61b-18bb9c4ebb57)

**Desktop Setup:**
- **OS:** Windows 10 Enterprise LTSC IoT 21H2
- **Version:** 3.19.0 Testing (Pre-release)

**Additional Context**  
Classical theme in use, meaning no Visual Style (.msstyle) is active.

**Comment by fraxgut** [comment]
> In order to see thumbnails in Windows Explorer, you some something like https://www.reddit.com/r/jpegxl/comments/ms48z3/jpeg_xl_windows_imaging_component_wic_explorer/

This solution works, but is there a way to achieve this directly through Nomacs without having to register a DLL separately?

**Comment by scrubbbbs** [comment]
> This solution works, but is there a way to achieve this directly through Nomacs without having to register a DLL separately?

Nope, nomacs does not provide any integration plugins for Windows Explorer, as the focus is on cross-platform development.
