### ISSUE TITLE
Release of 3.19.1

### ISSUE THREAD

**Issue by novomesk** [nomacs/nomacs#1153]
Hello,

@leejuyuu  and @scrubbbbs 

I am thinking of make new release build at the end of next week.

Is there something urgent or top important you would like to contribute before that?

**Comment by leejuyuu** [comment]
No, I don't have anything urgent.

**Comment by scrubbbbs** [comment]
I don't have anything.

**Comment by novomesk** [comment]
https://github.com/nomacs/nomacs/releases/tag/3.19.1
