### ISSUE TITLE
Drag-n-Drop is boken for KDE Dolphin file manager

### ISSUE THREAD

**Issue by derlunz** [nomacs/nomacs#116]
Dropping image files from KDE's dolphin file manager [`dolphin --version == 16.04.03`], into
nomacs [master](nomacs/nomacs@7a9ac6d1c89dee) currently fails.

Drops from dolphin come as mimeType `text/uri-list`, which `hasText()` and `hasUrls()`. The current drag-n-drop code doesn't cope with this content, and messes up the dropped URL.

**Comment by diemmarkus** [comment]
thanks again!
