### ISSUE TITLE
Unable to find executable: core_tests_NOT_BUILT

### ISSUE THREAD

**Issue by novomesk** [nomacs/nomacs#1178]
Hi @leejuyuu ,

Gentoo Linux maintainers encountered the test error (below).

I think it could be solved by removing `EXCLUDE_FROM_ALL` from the following line:

https://github.com/nomacs/nomacs/blob/a09e9047e7e315e3256c9f6681040d516f12543b/ImageLounge/CMakeLists.txt#L123

```
>>> Source compiled.
>>> Test phase: media-gfx/nomacs-3.19.1
 * Source directory (CMAKE_USE_DIR): "/var/tmp/portage/media-gfx/nomacs-3.19.1/work/nomacs-3.19.1/ImageLounge"
 * Build directory  (BUILD_DIR):     "/var/tmp/portage/media-gfx/nomacs-3.19.1/work/nomacs-3.19.1/ImageLounge_build"
ctest -j 4 --test-load 999
Test project /var/tmp/portage/media-gfx/nomacs-3.19.1/work/nomacs-3.19.1/ImageLounge_build
    Start 1: core_tests_NOT_BUILT
Could not find executable core_tests_NOT_BUILT
Looked in the following places:
core_tests_NOT_BUILT
core_tests_NOT_BUILT
Release/core_tests_NOT_BUILT
Release/core_tests_NOT_BUILT
Debug/core_tests_NOT_BUILT
Debug/core_tests_NOT_BUILT
MinSizeRel/core_tests_NOT_BUILT
MinSizeRel/core_tests_NOT_BUILT
RelWithDebInfo/core_tests_NOT_BUILT
RelWithDebInfo/core_tests_NOT_BUILT
Deployment/core_tests_NOT_BUILT
Deployment/core_tests_NOT_BUILT
Development/core_tests_NOT_BUILT
Development/core_tests_NOT_BUILT
Unable to find executable: core_tests_NOT_BUILT
1/1 Test #1: core_tests_NOT_BUILT .............***Not Run   0.00 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.00 sec

The following tests FAILED:
          1 - core_tests_NOT_BUILT (Not Run)
Errors while running CTest
Output from these tests are in: /var/tmp/portage/media-gfx/nomacs-3.19.1/work/nomacs-3.19.1/ImageLounge_build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```

**Comment by leejuyuu** [comment]
Do you have more context? How did they build the binaries and what was the CMake output? Did they have GoogleTest installed? Because otherwise test binaries will be skipped.

There's a `check` target that will build the tests and run them.
https://github.com/nomacs/nomacs/blob/f49aba6fe08a2944c19f19a6e0bbaa8b6711f576/.github/workflows/linux.yml#L53-L56

**Comment by novomesk** [comment]
I think those Gentoo scripts call something like `ctest`

but I will fail because core_tests target is not built by default.

You can get similar result by calling  `ninja test` or `make test`

**Comment by leejuyuu** [comment]
Please try `make check`. I set this target for testing. This target will ruc ctest for you.

**Comment by novomesk** [comment]
The `check` target works.

The suggestion is to make it easier/convenient for the maintainers so everything works with default test target.

**Comment by leejuyuu** [comment]
I think `check` is also commonly used target? Maybe we just need to document it.

**Comment by novomesk** [comment]
I think if we build `core_tests` by default, remove the `check` target, everything will be more simple.

And we can use the `test` target to run testing.

If you don't agree, at least let us document the usage of `check`

**Comment by leejuyuu** [comment]
The `core_tests` are not built by design. The tests depend on GoogleTest, while nomacs itself does not. Including the tests in the `all` target will make the optional dependency necessary, so I avoided that.
