### ISSUE TITLE
Batch provessing ignores resize

### ISSUE THREAD

**Issue by commander-keen** [nomacs/nomacs#118]
Nomacs 3.6 seems to ignore the resize option for me.
Tried to feed it with three pictures over 5000 pixels width, chose 25% for resizing and the output image has the original size instead of the reduzed size.

Renaming for example works though.

Linux Mint 18.1 KDE

**Comment by diemmarkus** [comment]
no feature without a bug : ) -> thanks!

**Comment by JakePhan** [comment]
I have the same issue as of today.

Arch Linux.

**Comment by david007co** [comment]
Same problem here... It only resizes when combined with other feature, like rotate.

**Comment by arnisjuraga** [comment]
Same here

**Comment by diemmarkus** [comment]
Hi,
this is now fixed - you can update nomacs here: http://download.nomacs.org/ 
please do not forget to uninstall prior versions (for we changed the installer).

**Comment by arnisjuraga** [comment]
@diemmarkus Thanks! I did already and it works fine with latest version! Cheers!
