### ISSUE TITLE
Segmentation fault (core dumped) when run as ordinary user

### ISSUE THREAD

**Issue by QiangF** [nomacs/nomacs#1185]
This is the error message:

    q@mypc:.config$ nomacs
    [INFO] Hi there
    [INFO] Metadata support for BMFF formats is active.
    [INFO] plugins dir set to:  "/usr/lib/nomacs-plugins"
    [INFO] loaded app mode: 0
    [INFO] local client created in:  1 ms
    [INFO] theme loaded from "/usr/share/nomacs/Image Lounge/themes/Light-Theme.css"
    [INFO] CSS loaded from:  ":/nomacs/stylesheet.css"
    [INFO] restore geometry: QRect(1,20 1342x987) windowState: QFlags<Qt::WindowState>(WindowNoState)
    [INFO] init window: appMode: 0 maximized: false fullscreen: false geometry: QRect(1,20 1342x987) windowState: QFlags<Qt::WindowState>(WindowNoState)
    Segmentation fault (core dumped)
    

This is the coredump:

    q@mypc:.config$ coredumpctl gdb 12603
               PID: 12603 (nomacs)
               UID: 1000 (q)
               GID: 998 (wheel)
            Signal: 11 (SEGV)
         Timestamp: Fri 2024-11-08 08:58:09 CST (51min ago)
      Command Line: nomacs
        Executable: /usr/bin/nomacs
     Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/tmux-spawn-20a057da-c20c-41dc-a2ce-754460b67b8d.scope
              Unit: user@1000.service
         User Unit: tmux-spawn-20a057da-c20c-41dc-a2ce-754460b67b8d.scope
             Slice: user-1000.slice
         Owner UID: 1000 (q)
           Boot ID: c3e3acbc43304c0b9a3131eeab64d7c1
        Machine ID: 52e12d57920d49c186460f8171e56f04
          Hostname: mypc
           Storage: /var/lib/systemd/coredump/core.nomacs.1000.c3e3acbc43304c0b9a3131eeab64d7c1.12603.1731027489000000.zst (present)
      Size on Disk: 2M
           Message: Process 12603 (nomacs) of user 1000 dumped core.
    
                    Stack trace of thread 12603:
                    #0  0x000079a7326b3eef malloc (libc.so.6 + 0xa4eef)
                    #1  0x000079a73268d2e4 _IO_file_doallocate (libc.so.6 + 0x7e2e4)
                    #2  0x000079a73269c714 _IO_doallocbuf (libc.so.6 + 0x8d714)
                    #3  0x000079a73269a3f5 _IO_file_underflow (libc.so.6 + 0x8b3f5)
                    #4  0x000079a73269c7c2 _IO_default_uflow (libc.so.6 + 0x8d7c2)
                    #5  0x000079a73268ef4b _IO_getline_info (libc.so.6 + 0x7ff4b)
                    #6  0x000079a73268dc86 _IO_fgets (libc.so.6 + 0x7ec86)
                    #7  0x000079a734987589 n/a (libxcb-cursor.so.0 + 0x2589)
                    #8  0x000079a73498782a n/a (libxcb-cursor.so.0 + 0x282a)
                    #9  0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #10 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #11 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #12 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #13 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #14 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #15 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #16 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #17 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #18 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #19 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #20 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #21 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #22 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #23 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #24 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #25 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #26 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #27 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #28 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #29 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #30 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #31 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #32 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #33 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #34 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #35 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #36 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #37 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #38 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #39 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #40 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #41 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #42 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #43 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #44 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #45 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #46 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #47 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #48 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #49 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #50 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #51 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #52 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #53 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #54 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #55 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #56 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #57 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #58 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #59 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #60 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #61 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #62 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
                    #63 0x000079a734987975 n/a (libxcb-cursor.so.0 + 0x2975)
    
                    Stack trace of thread 12606:
                    #0  0x000079a73269fa19 n/a (libc.so.6 + 0x90a19)
                    #1  0x000079a7326a27e2 pthread_cond_timedwait (libc.so.6 + 0x937e2)
                    #2  0x000079a732adcfc8 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt6Core.so.6 + 0x2dcfc8)
                    #3  0x000079a732ade9d5 n/a (libQt6Core.so.6 + 0x2de9d5)
                    #4  0x000079a732ad840f n/a (libQt6Core.so.6 + 0x2d840f)
                    #5  0x000079a7326a339d n/a (libc.so.6 + 0x9439d)
                    #6  0x000079a73272849c n/a (libc.so.6 + 0x11949c)
    
                    Stack trace of thread 12604:
                    #0  0x000079a73271abb0 ppoll (libc.so.6 + 0x10bbb0)
                    #1  0x000079a72f452227 n/a (libglib-2.0.so.0 + 0xc0227)
                    #2  0x000079a72f3eea55 g_main_context_iteration (libglib-2.0.so.0 + 0x5ca55)
                    #3  0x000079a732bbf71d _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt6Core.so.6 + 0x3bf71d)
                    #4  0x000079a732964566 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt6Core.so.6 + 0x164566)
                    #5  0x000079a732a57072 _ZN7QThread4execEv (libQt6Core.so.6 + 0x257072)
                    #6  0x000079a73217379e n/a (libQt6DBus.so.6 + 0x2e79e)
                    #7  0x000079a732ad840f n/a (libQt6Core.so.6 + 0x2d840f)
                    #8  0x000079a7326a339d n/a (libc.so.6 + 0x9439d)
                    #9  0x000079a73272849c n/a (libc.so.6 + 0x11949c)
    
                    Stack trace of thread 12609:
                    #0  0x000079a73269fa19 n/a (libc.so.6 + 0x90a19)
                    #1  0x000079a7326a27e2 pthread_cond_timedwait (libc.so.6 + 0x937e2)
                    #2  0x000079a732adcfc8 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt6Core.so.6 + 0x2dcfc8)
                    #3  0x000079a732ade9d5 n/a (libQt6Core.so.6 + 0x2de9d5)
                    #4  0x000079a732ad840f n/a (libQt6Core.so.6 + 0x2d840f)
                    #5  0x000079a7326a339d n/a (libc.so.6 + 0x9439d)
                    #6  0x000079a73272849c n/a (libc.so.6 + 0x11949c)
    
                    Stack trace of thread 12608:
                    #0  0x000079a73269fa19 n/a (libc.so.6 + 0x90a19)
                    #1  0x000079a7326a27e2 pthread_cond_timedwait (libc.so.6 + 0x937e2)
                    #2  0x000079a732adcfc8 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt6Core.so.6 + 0x2dcfc8)
                    #3  0x000079a732ade9d5 n/a (libQt6Core.so.6 + 0x2de9d5)
                    #4  0x000079a732ad840f n/a (libQt6Core.so.6 + 0x2d840f)
                    #5  0x000079a7326a339d n/a (libc.so.6 + 0x9439d)
                    #6  0x000079a73272849c n/a (libc.so.6 + 0x11949c)
    
                    Stack trace of thread 12607:
                    #0  0x000079a73269fa19 n/a (libc.so.6 + 0x90a19)
                    #1  0x000079a7326a27e2 pthread_cond_timedwait (libc.so.6 + 0x937e2)
                    #2  0x000079a732adcfc8 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt6Core.so.6 + 0x2dcfc8)
                    #3  0x000079a732ade9d5 n/a (libQt6Core.so.6 + 0x2de9d5)
                    #4  0x000079a732ad840f n/a (libQt6Core.so.6 + 0x2d840f)
                    #5  0x000079a7326a339d n/a (libc.so.6 + 0x9439d)
                    #6  0x000079a73272849c n/a (libc.so.6 + 0x11949c)
    
                    Stack trace of thread 12605:
                    #0  0x000079a73271a63d __poll (libc.so.6 + 0x10b63d)
                    #1  0x000079a72f18b20b n/a (libxcb.so.1 + 0xd20b)
                    #2  0x000079a72f18cf3d xcb_wait_for_event (libxcb.so.1 + 0xef3d)
                    #3  0x000079a72aba7c39 n/a (libQt6XcbQpa.so.6 + 0x4fc39)
                    #4  0x000079a732ad840f n/a (libQt6Core.so.6 + 0x2d840f)
                    #5  0x000079a7326a339d n/a (libc.so.6 + 0x9439d)
                    #6  0x000079a73272849c n/a (libc.so.6 + 0x11949c)
                    ELF object binary architecture: AMD x86-64

**Comment by kemlath** [comment]
This segfault behaviour is back on kernel: 6.17.0-109014
Nomacs can only be run via "sudo nomacs"

```
Process 14613 (nomacs) of user 1000 dumped core.
                                                
                                                Module libsystemd.so.0 from deb systemd-255.4-1ubuntu8.12.amd64
                                                Module libgfortran.so.5 from deb gcc-14-14.2.0-4ubuntu2~24.04.1.amd64
                                                Module libgomp.so.1 from deb gcc-14-14.2.0-4ubuntu2~24.04.1.amd64
                                                Module libzstd.so.1 from deb libzstd-1.5.5+dfsg2-2build1.1.amd64
                                                Module libgcc_s.so.1 from deb gcc-14-14.2.0-4ubuntu2~24.04.1.amd64
                                                Module libstdc++.so.6 from deb gcc-14-14.2.0-4ubuntu2~24.04.1.amd64
                                                Stack trace of thread 14623:
                                                #0  0x0000000f00000006 n/a (n/a + 0x0)
                                                #1  0x00007eef66e7539d _ZNK3nmc11DkMetaDataT12getThumbnailEv (libnomacsCore.so.3 + 0x27539d)
                                                #2  0x00007eef66eb3fb5 _ZN3nmc11DkThumbNail13computeInternERK7QString14QSharedPointerI10QByteArrayEii (libnomacsCore.so.3 + 0x2b3fb5)
                                                #3  0x00007eef66eb4ad5 _ZN3nmc12DkThumbNailT11computeCallERK7QString14QSharedPointerI10QByteArrayEii (libnomacsCore.so.3 + 0x2b4ad5)
                                                #4  0x00007eef66eae901 n/a (libnomacsCore.so.3 + 0x2ae901)
                                                #5  0x00007eef66e09f29 n/a (libnomacsCore.so.3 + 0x209f29)
                                                #6  0x00007eef65adeab9 n/a (libQt5Core.so.5 + 0xdeab9)
                                                #7  0x00007eef65adb674 n/a (libQt5Core.so.5 + 0xdb674)
                                                #8  0x00007eef6569caa4 start_thread (libc.so.6 + 0x9caa4)
                                                #9  0x00007eef65729c6c __clone3 (libc.so.6 + 0x129c6c)
                                                
                                                Stack trace of thread 14613:
                                                #0  0x00007eef6619e724 n/a (libQt5Widgets.so.5 + 0x19e724)
                                                #1  0x00007eef6619ea10 _ZNK7QWidget11mapToGlobalERK6QPoint (libQt5Widgets.so.5 + 0x19ea10)
                                                #2  0x00007eef6620c04a n/a (libQt5Widgets.so.5 + 0x20c04a)
                                                #3  0x00007eef66214e48 n/a (libQt5Widgets.so.5 + 0x214e48)
                                                #4  0x00007eef66216626 n/a (libQt5Widgets.so.5 + 0x216626)
                                                #5  0x00007eef6621c385 n/a (libQt5Widgets.so.5 + 0x21c385)
                                                #6  0x00007eef661b148d _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5 + 0x1b148d)
                                                #7  0x00007eef6616bd45 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x16bd45)
                                                #8  0x00007eef65cd8118 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2d8118)
                                                #9  0x00007eef661acb1e _ZNK7QWidget14ensurePolishedEv (libQt5Widgets.so.5 + 0x1acb1e)
                                                #10 0x00007eef661acb55 _ZNK7QWidget14ensurePolishedEv (libQt5Widgets.so.5 + 0x1acb55)
                                                #11 0x00007eef661b0798 _ZN14QWidgetPrivate10setVisibleEb (libQt5Widgets.so.5 + 0x1b0798)
                                                #12 0x00007eef66d629bf _ZN3nmc12DkFadeWidget10setVisibleEbb (libnomacsCore.so.3 + 0x1629bf)
                                                #13 0x00007eef66d6020d _ZN3nmc12DkFadeWidget4showEb (libnomacsCore.so.3 + 0x16020d)
                                                #14 0x00007eef66df53e2 _ZN3nmc17DkRecentDirWidget12createLayoutEv (libnomacsCore.so.3 + 0x1f53e2)
                                                #15 0x00007eef66def312 _ZN3nmc17DkRecentDirWidgetC1ERKNS_11DkRecentDirEP7QWidget (libnomacsCore.so.3 + 0x1ef312)
                                                #16 0x00007eef66df59e6 _ZN3nmc19DkRecentFilesWidget10updateListEv (libnomacsCore.so.3 + 0x1f59e6)
                                                #17 0x00007eef66df5f29 _ZN3nmc19DkRecentFilesWidget10setVisibleEb (libnomacsCore.so.3 + 0x1f5f29)
                                                #18 0x00007eef66193fcb _ZN14QStackedLayout15setCurrentIndexEi (libQt5Widgets.so.5 + 0x193fcb)
                                                #19 0x00007eef6619493a _ZN14QStackedLayout12insertWidgetEiP7QWidget (libQt5Widgets.so.5 + 0x19493a)
                                                #20 0x00007eef66d7f72d _ZN3nmc15DkCentralWidget15showRecentFilesEb (libnomacsCore.so.3 + 0x17f72d)
                                                #21 0x00007eef65d12dbf n/a (libQt5Core.so.5 + 0x312dbf)
                                                #22 0x00007eef65d171eb n/a (libQt5Core.so.5 + 0x3171eb)
                                                #23 0x00007eef65d0624b _ZN7QObject5eventEP6QEvent (libQt5Core.so.5 + 0x30624b)
                                                #24 0x00007eef6616bd45 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x16bd45)
                                                #25 0x00007eef65cd8118 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2d8118)
                                                #26 0x00007eef65d345ab _ZN14QTimerInfoList14activateTimersEv (libQt5Core.so.5 + 0x3345ab)
                                                #27 0x00007eef65d34ed9 n/a (libQt5Core.so.5 + 0x334ed9)
                                                #28 0x00007eef63b14585 n/a (libglib-2.0.so.0 + 0x5d585)
                                                #29 0x00007eef63b73977 n/a (libglib-2.0.so.0 + 0xbc977)
                                                #30 0x00007eef63b13a23 g_main_context_iteration (libglib-2.0.so.0 + 0x5ca23)
                                                #31 0x00007eef65d35296 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x335296)
                                                #32 0x00007eef65cd6a7b _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2d6a7b)
                                                #33 0x00007eef65cdf3e8 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x2df3e8)
                                                #34 0x0000631b32de6030 main (nomacs + 0x5030)
                                                #35 0x00007eef6562a1ca __libc_start_call_main (libc.so.6 + 0x2a1ca)
                                                #36 0x00007eef6562a28b __libc_start_main_impl (libc.so.6 + 0x2a28b)
                                                #37 0x0000631b32de6d25 _start (nomacs + 0x5d25)
                                                
                                                Stack trace of thread 14615:
                                                #0  0x00007eef6572728d syscall (libc.so.6 + 0x12728d)
                                                #1  0x00007eef63b6d52d g_cond_wait (libglib-2.0.so.0 + 0xb652d)
                                                #2  0x00007eef63ade58b n/a (libglib-2.0.so.0 + 0x2758b)
                                                #3  0x00007eef63b43c43 n/a (libglib-2.0.so.0 + 0x8cc43)
                                                #4  0x00007eef63b42e62 n/a (libglib-2.0.so.0 + 0x8be62)
                                                #5  0x00007eef6569caa4 start_thread (libc.so.6 + 0x9caa4)
                                                #6  0x00007eef65729c6c __clone3 (libc.so.6 + 0x129c6c)
                                                
                                                Stack trace of thread 14614:
                                                #0  0x00007eef6571b4fd __GI___poll (libc.so.6 + 0x11b4fd)
                                                #1  0x00007eef62d708ca n/a (libxcb.so.1 + 0xc8ca)
                                                #2  0x00007eef62d7228c xcb_wait_for_event (libxcb.so.1 + 0xe28c)
                                                #3  0x00007eef600fbba0 n/a (libQt5XcbQpa.so.5 + 0x74ba0)
                                                #4  0x00007eef65adb674 n/a (libQt5Core.so.5 + 0xdb674)
                                                #5  0x00007eef6569caa4 start_thread (libc.so.6 + 0x9caa4)
                                                #6  0x00007eef65729c6c __clone3 (libc.so.6 + 0x129c6c)
                                                
                                                Stack trace of thread 14619:
                                                #0  0x00007eef65698d71 __futex_abstimed_wait_common64 (libc.so.6 + 0x98d71)
                                                #1  0x00007eef6569b7ed __pthread_cond_wait_common (libc.so.6 + 0x9b7ed)
                                                #2  0x00007eef4d199edd n/a (libgallium-25.2.8-0ubuntu0.24.04.1.so + 0x599edd)
                                                #3  0x00007eef4d165fbb n/a (libgallium-25.2.8-0ubuntu0.24.04.1.so + 0x565fbb)
                                                #4  0x00007eef4d199e0c n/a (libgallium-25.2.8-0ubuntu0.24.04.1.so + 0x599e0c)
                                                #5  0x00007eef6569caa4 start_thread (libc.so.6 + 0x9caa4)
                                                #6  0x00007eef65729c6c __clone3 (libc.so.6 + 0x129c6c)
                                                
                                                Stack trace of thread 14617:
                                                #0  0x00007eef6571b4fd __GI___poll (libc.so.6 + 0x11b4fd)
                                                #1  0x00007eef63b738ce n/a (libglib-2.0.so.0 + 0xbc8ce)
                                                #2  0x00007eef63b14f47 g_main_loop_run (libglib-2.0.so.0 + 0x5df47)
                                                #3  0x00007eef5e981582 n/a (libgio-2.0.so.0 + 0x11a582)
                                                #4  0x00007eef63b42e62 n/a (libglib-2.0.so.0 + 0x8be62)
                                                #5  0x00007eef6569caa4 start_thread (libc.so.6 + 0x9caa4)
                                                #6  0x00007eef65729c6c __clone3 (libc.so.6 + 0x129c6c)
                                                
                                                Stack trace of thread 14616:
                                                #0  0x00007eef6571b4fd __GI___poll (libc.so.6 + 0x11b4fd)
                                                #1  0x00007eef63b738ce n/a (libglib-2.0.so.0 + 0xbc8ce)
                                                #2  0x00007eef63b13a23 g_main_context_iteration (libglib-2.0.so.0 + 0x5ca23)
                                                #3  0x00007eef63b13a79 n/a (libglib-2.0.so.0 + 0x5ca79)
                                                #4  0x00007eef63b42e62 n/a (libglib-2.0.so.0 + 0x8be62)
                                                #5  0x00007eef6569caa4 start_thread (libc.so.6 + 0x9caa4)
                                                #6  0x00007eef65729c6c __clone3 (libc.so.6 + 0x129c6c)
                                                
                                                Stack trace of thread 14618:
                                                #0  0x00007eef6571b4fd __GI___poll (libc.so.6 + 0x11b4fd)
                                                #1  0x00007eef63b738ce n/a (libglib-2.0.so.0 + 0xbc8ce)
                                                #2  0x00007eef63b13a23 g_main_context_iteration (libglib-2.0.so.0 + 0x5ca23)
                                                #3  0x00007eef65d35279 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x335279)
                                                #4  0x00007eef65cd6a7b _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2d6a7b)
                                                #5  0x00007eef65ada36b _ZN7QThread4execEv (libQt5Core.so.5 + 0xda36b)
                                                #6  0x00007eef6000d15b n/a (libQt5DBus.so.5 + 0x1915b)
                                                #7  0x00007eef65adb674 n/a (libQt5Core.so.5 + 0xdb674)
                                                #8  0x00007eef6569caa4 start_thread (libc.so.6 + 0x9caa4)
                                                #9  0x00007eef65729c6c __clone3 (libc.so.6 + 0x129c6c)
                                                
                                                Stack trace of thread 14620:
                                                #0  0x00007eef65698d71 __futex_abstimed_wait_common64 (libc.so.6 + 0x98d71)
                                                #1  0x00007eef6569b7ed __pthread_cond_wait_common (libc.so.6 + 0x9b7ed)
                                                #2  0x00007eef4d199edd n/a (libgallium-25.2.8-0ubuntu0.24.04.1.so + 0x599edd)
                                                #3  0x00007eef4d165fbb n/a (libgallium-25.2.8-0ubuntu0.24.04.1.so + 0x565fbb)
                                                #4  0x00007eef4d199e0c n/a (libgallium-25.2.8-0ubuntu0.24.04.1.so + 0x599e0c)
                                                #5  0x00007eef6569caa4 start_thread (libc.so.6 + 0x9caa4)
                                                #6  0x00007eef65729c6c __clone3 (libc.so.6 + 0x129c6c)
                                                ELF object binary architecture: AMD x86-64
```
