### ISSUE TITLE
 nomacs traverses (some) directories in funky/non-lexical order on (some) linux systems

### ISSUE THREAD

**Issue by derlunz** [nomacs/nomacs#119]
When I traverse a directory with the cursor keys with the image in focus, I get random ordered images. The same holds for the filter widget. A pattern matches appear already unsorted.
The issue does _not_ appear on another kubuntu 16.04 machine.

The good system runs:
  - kubuntu 16.04 
  - `nomacs 3.6.0-1~96~ubuntu16.04.1 amd64` from  ppa (`http://ppa.launchpad.net/nomacs/stable/ubuntu xenial main`) 
  - qt 5.6.1-ish. See the package versions here: [package-versions](https://github.com/nomacs/nomacs/files/1009097/ubuntu-qt-libs-good.txt), [linked-libraries](https://github.com/nomacs/nomacs/files/1009132/nomacs-file-order-good-ldd-unbuntu.txt)

The bad system has a similar setup:
 - kubuntu 16.04
 - nomacs `3.6.0-1~96~ubuntu16.04.1 amd64` from ppa
 - qt 5.6.1-ish. See the package versions here: [package-versions](https://github.com/nomacs/nomacs/files/1010491/ubuntu-qt-libs-bad.txt), [linked-libraries](https://github.com/nomacs/nomacs/files/1010490/nomac-file-order-bad-ldd-ubuntu.txt)
 - cuda

A direcory sample looks like: 
```
rect_00000000_00.png
rect_00000000_01.png
rect_00000000_02.png
rect_00000000_03.png
rect_00000001_00.png
rect_00000001_01.png
rect_00000001_02.png
rect_00000001_03.png
rect_00000002_00.png
rect_00000002_01.png
rect_00000002_02.png
rect_00000002_03.png
rect_00000003_00.png
rect_00000003_01.png
rect_00000003_02.png
 rect_00000003_03.png
```
Sample images can be generated using this GNU Make/ImageMagick [generator](https://gist.github.com/derlunz/e078eb18db182f30e49ef5c3bab5a5ab).

**Comment by scrubbbbs** [comment]
Old issue and cannot reproduce on 3.19
