### ISSUE TITLE
Qt5 compiling error

### ISSUE THREAD

**Issue by Ilya87** [nomacs/nomacs#12]
I do
cd nomacs/ImageLounge
  cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_QT5=ON -DENABLE_QUAZIP=OFF -DQT_QMAKE_EXECUTABLE=/usr/bin/qmake-qt5
then make
and get the following error message:

irtual void nmc::DkThumbsView::mouseMoveEvent(QMouseEvent*)»:
/home/ilya/build/lxqt/nomacs/src/nomacs/ImageLounge/src/DkThumbsWidgets.cpp:1398:33: error: invalid use of incomplete type «class QDrag»
     QDrag* drag = new QDrag(this);
                                 ^
In file included from /usr/include/qt/QtWidgets/qtreeview.h:37:0,
                 from /usr/include/qt/QtWidgets/QTreeView:1,
                 from /home/ilya/build/lxqt/nomacs/src/nomacs/ImageLounge/src/DkWidgets.h:55,
                 from /home/ilya/build/lxqt/nomacs/src/nomacs/ImageLounge/src/DkThumbsWidgets.h:32,
                 from /home/ilya/build/lxqt/nomacs/src/nomacs/ImageLounge/src/DkThumbsWidgets.cpp:28:
/usr/include/qt/QtWidgets/qabstractitemview.h:48:7: error: forward declaration of «class QDrag»
 class QDrag;
       ^
/home/ilya/build/lxqt/nomacs/src/nomacs/ImageLounge/src/DkThumbsWidgets.cpp:1399:9: error: invalid use of incomplete type «class QDrag»
     drag->setMimeData(mimeData);
         ^
In file included from /usr/include/qt/QtWidgets/qtreeview.h:37:0,
                 from /usr/include/qt/QtWidgets/QTreeView:1,
                 from /home/ilya/build/lxqt/nomacs/src/nomacs/ImageLounge/src/DkWidgets.h:55,
                 from /home/ilya/build/lxqt/nomacs/src/nomacs/ImageLounge/src/DkThumbsWidgets.h:32,
                 from /home/ilya/build/lxqt/nomacs/src/nomacs/ImageLounge/src/DkThumbsWidgets.cpp:28:
/usr/include/qt/QtWidgets/qabstractitemview.h:48:7: ошибка: forward declaration of «class QDrag»
 class QDrag;
       ^
/home/ilya/build/lxqt/nomacs/src/nomacs/ImageLounge/src/DkThumbsWidgets.cpp:1400:37: error: invalid use of incomplete type «class QDrag»
     Qt::DropAction dropAction = drag->exec(Qt::CopyAction);
                                     ^
In file included from /usr/include/qt/QtWidgets/qtreeview.h:37:0,
                 from /usr/include/qt/QtWidgets/QTreeView:1,
                 from /home/ilya/build/lxqt/nomacs/src/nomacs/ImageLounge/src/DkWidgets.h:55,
                 from /home/ilya/build/lxqt/nomacs/src/nomacs/ImageLounge/src/DkThumbsWidgets.h:32,
                 from /home/ilya/build/lxqt/nomacs/src/nomacs/ImageLounge/src/DkThumbsWidgets.cpp:28:
/usr/include/qt/QtWidgets/qabstractitemview.h:48:7: error: forward declaration of «class QDrag»
 class QDrag;

**Comment by Ilya87** [comment]
The solution, as I found out, is to add line #include <QDrag> to /src/DkThumbsWidgets.h file after #include <QProcess> line.

**Comment by sfiel** [comment]
Thank you very much ... we will add this
