### ISSUE TITLE
Appveyor: Use Qt 6.8.0 or later

### ISSUE THREAD

**Issue by scrubbbbs** [nomacs/nomacs#1208]
Appveyor doesn't seem to include 6.8.0 in the windows image yet. This is a reminder to update appveyor.yml file when that becomes available, as that is required in #1140 to change the title bar color.

**Comment by novomesk** [comment]
What happens if Qt 6.7.x is used or someone builds nomacs using Qt 5.15.x ?

**Comment by scrubbbbs** [comment]
The window title bar won't respond to nomacs theme changes, it will follow the platform theme,

**Comment by novomesk** [comment]
Qt 6.8.1 is being used on AppVeyor now.
