### ISSUE TITLE
Batch processing resize FAIL

### ISSUE THREAD

**Issue by maniootek** [nomacs/nomacs#1218]
Batch processing resize FAIL

**Describe the bug**
When attempting to use the batch processing feature to resize images, the process fails. After applying the resize adjustment, the program displays an error stating that it cannot save the file and reports multiple failures.

**To Reproduce**
Go to the batch processing tool in Nomac.
Select several images for processing.
Choose the resize adjustment option.
Specify the output directory.
Start the batch process.
Observe the error after processing begins.

**Expected behavior**
The program should successfully resize all selected images and save them in the specified output directory without errors.

**Screenshots**
Screenshot attached
![2024-12-13 12_34_47-New Issue · nomacs_nomacs](https://github.com/user-attachments/assets/d0d05835-977b-43d6-b80e-e4b6efd18da7)

**Desktop**
 - OS: Windows 10 64-bit
 - Version 22H2

**Additional context**
No additional context

**Comment by leejuyuu** [comment]
Hello @maniootek, what is the nomacs version you are using? You can find it in `? > About nomacs`.

This issue sounds like https://github.com/nomacs/nomacs/issues/1139. You could try 3.19.1 or use the work around mentioned [here](https://github.com/nomacs/nomacs/issues/1139#issuecomment-2250984002)

**Comment by maniootek** [comment]
3.17.2297 (x64)
workaround to set fixed extension working, thank you

**Comment by leejuyuu** [comment]
Thanks! I'm closing this as completed.
