### ISSUE TITLE
The Anti-Aliasing Toggle has no effect

### ISSUE THREAD

**Issue by derlunz** [nomacs/nomacs#122]
Affected Versions:
- master `git: 3.6.1-48-g3494189-dirty`
- packages: `3.6.0-1~96~ubuntu16.04.1`

![nomacs-antialiasing-defunct](https://cloud.githubusercontent.com/assets/1619633/26191369/e561071c-3bad-11e7-98f1-1d9e48ef225d.png)

**Comment by diemmarkus** [comment]
anti - aliasing is working properly. note: it is a display property & only if an image has more pixels than the screen - it has any effect (we can see the pixels rendered in your screenshot - so it has no effect). here is what it's supposed to do (the circle shows the real difference):
![img-2017-05-22 11 01 25](https://cloud.githubusercontent.com/assets/4182443/26300371/2fc4dada-3ede-11e7-8b23-f2d27dad6035.png)
![img-2017-05-22 11 01 12](https://cloud.githubusercontent.com/assets/4182443/26300380/32e0c15c-3ede-11e7-9114-c87edbb883e1.png)

p.s.: if you want to interpolate pixels when zooming (though I would not recommend it : ) you can change the settings in `Preferences > Settings > Show pixels if zoom level is above` ...

**Comment by derlunz** [comment]
Now I getit. Thanks for the clarification

**Comment by Chillstice** [comment]
btw sometimes nomacs randomly for whatever reason sets antiAliasing=false in the config per a note in #581.
It does this even when the Anti Aliasing check box is checked.
The solution is to go to the Editor tab in the settings, search for antiAliasing, and manually change it from `false` to `true`.
This seems to persist after editing.
