### ISSUE TITLE
Blurry large files

### ISSUE THREAD

**Issue by ghost** [nomacs/nomacs#125]
Large images (6000x4000px, raw or jpeg) are blurred (compared with other image viewers, same file) when the zoom is set to "fit to window" with anti aliasing on. With anti aliasing off, they are too pixelated, of course. Small images are fine. Also, the blur disappears when the zoom is set at 100%, looking identical to other image viewers I compared it with.

**Comment by diemmarkus** [comment]
could you provide a screenshot of nomacs compared to another viewer please? (so we can better understand the issue)

**Comment by cristianmos** [comment]
![screenshot_nomacs_zoom to fit_23 4 blur](https://cloud.githubusercontent.com/assets/28788471/26547717/17467022-4479-11e7-9274-a7373e687302.png)
![screenshot_gimp_zoom at 25](https://cloud.githubusercontent.com/assets/28788471/26547724/1f965e9a-4479-11e7-884f-a7328f4f1077.png)
![screenshot_xnview_zoom to fit](https://cloud.githubusercontent.com/assets/28788471/26547736/2975c5ae-4479-11e7-8b46-9692b6b4c534.png)
![screenshot_pantheon photos_zoom to fit](https://cloud.githubusercontent.com/assets/28788471/26547740/2e2b963c-4479-11e7-85e2-ddca1642cf18.png)

**Comment by diemmarkus** [comment]
understood - thanks! could you be so kind and provide the test image too (since it's a pretty nice sample for aliasing artifacts)

**Comment by cristianmos** [comment]
![dsc_8934](https://cloud.githubusercontent.com/assets/28788471/26553606/0b57f7d8-4495-11e7-9614-e11f87d2bd4e.jpg)

Here it is.

**Comment by diemmarkus** [comment]
thanks...
I have tested your image using different interpolations:
![img-2017-05-29 16 55 44](https://cloud.githubusercontent.com/assets/4182443/26554411/34fe88e0-4490-11e7-96a8-df82f6b406bb.png)
![img-2017-05-29 16 57 01](https://cloud.githubusercontent.com/assets/4182443/26554413/3826a32c-4490-11e7-9a61-c0fedcf3341f.png)
1. nomacs (old) == your version, I then aligned the image rectangle with the screen pixels (middle) - but there does not seem to be a huge effect. nomacs @25% (right) is of course much better
2. different interpolations - I would say lanczos may be best - but it's hard to tell...

do you have any suggestions?

**Comment by cristianmos** [comment]
I can't really tell which interpolation is better from these samples. So I've just updated Nomacs through ppa. At 23.4% (zoom to fit, window maximized) is still blurred. Zooming the image between zoom to fit and around 50% (with mouse scroll) makes it pixelated. After 50% zoom the image starts to look very well. At 100% the image in Nomacs looks identical to Gimp. I have a 1920x1080 screen.

**Comment by diemmarkus** [comment]
Interpolation was improved in v3.10
