### ISSUE TITLE
Empty cardrider (D:) warning - The device does not have a disk. Insert disk into the device D:.

### ISSUE THREAD

**Issue by SaintDI** [nomacs/nomacs#126]
Hello, nomacs team.
This is a low priority issue, but quite annoing.

Each time I open any image, no matter where and what image I open, I get the message:

> The device does not have a disk." Insert disk into the device D:.

Disk D is an empty (without memory card) cardreader in my laptop.

After the warning window is closed, images are opened normally. If I disable or delete the device, the error does not appear. Now, I temporarily deleted the card reader, because I do not need it, but it seems to me that nomacs does not have to check which disks I have in the system, until I try to open the images located there.

Here is the Windows log entry:

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Popup" Guid="{47BFA2B7-BD54-4FAC-B70B-29021084CA8F}" /> 
  <EventID>26</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2017-05-26T14:06:24.026822000Z" /> 
  <EventRecordID>2491</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="640" ThreadID="756" /> 
  <Channel>System</Channel> 
  <Computer>ULTRABOOK</Computer> 
  <Security UserID="..." /> 
  </System>
- <EventData>
  <Data Name="Caption">nomacs.exe - Диск отсутствует</Data> 
  <Data Name="Message">В устройстве нет диска. Вставьте диск в устройство D:.</Data> 
  </EventData>
  </Event>
```

Windows 10 (1703 15063.296) x64
Tested on nomacs 3.6.1.1108 x64
Tested on nomacs 3.6.1.1108 x64 - portable

P.S.: Thanks for your work. Good image viewers are not so much - you have one of the best.

**Comment by diemmarkus** [comment]
Hi,

thanks for reporting - the issue seems to be the same as #110 (we'll have a look at it).

cheers,
markus
