### ISSUE TITLE
The new "Image Adjustments" tool is very very bad

### ISSUE THREAD

**Issue by HerborenInVlammen** [nomacs/nomacs#127]
I have been a 110% proponent, user, and defender of Nomacs since day one.  I love it, and use it daily.  However, let me be blunt:

Your new "Image Adjustments" tool is very very bad.  Not only is it bad.  It is useless.  Even on a tiny 30k jpg it takes forever to respond; the sliders basically do not work; the available tools are not the tools one would use daily... where is brightness/contrast, gamma, etc... in other words, the tools that one uses on images the most?

The previous tool was wonderful.  It was not broken.  It worked.  Best of all, it was useful daily.

The new one is nothing short of a mistake.  A bad mistake.  It does not work.  It sucks.  I could continue to tell you how bad it is, but I think I have made my point...

Ubuntu Xenial, PClinuxOS, and Xubuntu.  It sucks on all of them.  On Windows it functions better, but no by much, and it is still lacking all the usefull tools it used to have.

Please drop it and go back to that which was wonderful.

Thanks for listening...

**Comment by diemmarkus** [comment]
Hi,

I guess _very very bad_ is much worse than bad. There are three reasons why the sliders could be slugish:
- the preview image is comparably large (i.e. ~300 px)
- your machine has one CPU
- nomacs is set to use only one thread

It's not true, that there is no brightness/gamma - we have grouped useful functions. So you find 'gamma' in the Exposure group (which replaces contrast) and 'brightness' in the Hue/Saturation group.

cheers,
markus

Sorry, but your report reminds me of a recent statement 😈 
_‘The Germans are bad, very bad’_ - Trump
