### ISSUE TITLE
error folder "does not contain any image"

### ISSUE THREAD

**Issue by toze3** [nomacs/nomacs#129]
When I open an image raw in a folder it does not allow to scroll and view other images, have to open individually to see.

Already tryed to reinstall without sucess

using windows 10

**Comment by diemmarkus** [comment]
Hi,

thanks for reporting. Can you open `Edit > Settings > File Associations` and see if _Browse_ is checked for Canon Raw images:
![img-2017-06-14 15 59 46](https://user-images.githubusercontent.com/4182443/27136166-d7b3f4d0-511a-11e7-85be-590b082dbcd9.png)

btw. which extensions do the images have?

cheers,
markus

**Comment by toze3** [comment]
Yes, that was the first option I checked.

i set was default viewer in windows, and it opens the raw's very well even dual iso (magic lantern) raw.

but then it says that message. Please look at image, you will see a folder with images and then it open an image, but gives that message and don't allow to scroll and see other raw.
<a href="http://s682.photobucket.com/user/toze3/media/Foruns_WEB/Screenshot%202017-06-14%2017.08.05.png.html" target="_blank"><img src="http://i682.photobucket.com/albums/vv182/toze3/Foruns_WEB/Screenshot%202017-06-14%2017.08.05.png" border="0" alt=" photo Screenshot 2017-06-14 17.08.05.png"/></a>

**Comment by diemmarkus** [comment]
I cannot reproduce this issue on my system. I guess you are using nomacs 3.6.1?! Could you send me (developers@nomacs.org) your settings `Edit > Settings > Export Settings`)?

**Comment by diemmarkus** [comment]
solved - right? (comment for me: there seems to be an issue with the x86 executable)

**Comment by toze3** [comment]
Solved by renaming the x86 folder, in order to not use the x86 executable, not a clean solution.

Don't know why when I define the x64 version as default on windows it still open with the x86!
