### ISSUE TITLE
Build Nomacs on Ubuntu 14.04 

### ISSUE THREAD

**Issue by alyosama** [nomacs/nomacs#13]
Hi all ,

i am trying to build nomacs for master branch but i found this , what should i do ? 

Thanks

[  1%] Building CXX object CMakeFiles/nomacs.dir/src/DkViewPort.cpp.o
In file included from /usr/include/exiv2/metadatum.hpp:39:0,
                 from /usr/include/exiv2/exif.hpp:34,
                 from /usr/include/exiv2/bmpimage.hpp:34,
                 from /usr/include/exiv2/exiv2.hpp:35,
                 from /home/aly/projects/gsoc_projects/nomacs/ImageLounge/src/DkMetaData.h:49,
                 from /home/aly/projects/gsoc_projects/nomacs/ImageLounge/src/DkBasicLoader.h:37,
                 from /home/aly/projects/gsoc_projects/nomacs/ImageLounge/src/DkImage.h:104,
                 from /home/aly/projects/gsoc_projects/nomacs/ImageLounge/src/DkViewPort.h:69,
                 from /home/aly/projects/gsoc_projects/nomacs/ImageLounge/src/DkViewPort.cpp:28:
/usr/include/exiv2/value.hpp:984:25: note: attribute for ‘struct Exiv2::DateValue::Date’ must follow the ‘struct’ keyword
         EXIV2API struct Date
                         ^
/home/aly/projects/gsoc_projects/nomacs/ImageLounge/src/DkViewPort.cpp: In member function ‘virtual void nmc::DkViewPortContrast::setImage(QImage)’:
/home/aly/projects/gsoc_projects/nomacs/ImageLounge/src/DkViewPort.cpp:2776:4: error: ‘vector’ was not declared in this scope
    vector<Mat> planes;
    ^
/home/aly/projects/gsoc_projects/nomacs/ImageLounge/src/DkViewPort.cpp:2776:4: note: suggested alternative:
In file included from /usr/include/c++/4.8/vector:64:0,
                 from /usr/include/qt5/QtCore/qmetatype.h:56,
                 from /usr/include/qt5/QtCore/qobject.h:56,
                 from /usr/include/qt5/QtWidgets/qwidget.h:46,
                 from /usr/include/qt5/QtWidgets/qdesktopwidget.h:45,
                 from /usr/include/qt5/QtWidgets/QDesktopWidget:1,
                 from /home/aly/projects/gsoc_projects/nomacs/ImageLounge/src/DkViewPort.h:31,
                 from /home/aly/projects/gsoc_projects/nomacs/ImageLounge/src/DkViewPort.cpp:28:
/usr/include/c++/4.8/bits/stl_vector.h:210:11: note:   ‘std::vector’
     class vector : protected _Vector_base<_Tp, _Alloc>
           ^
/home/aly/projects/gsoc_projects/nomacs/ImageLounge/src/DkViewPort.cpp:2776:14: error: expected primary-expression before ‘>’ token
    vector<Mat> planes;
              ^
/home/aly/projects/gsoc_projects/nomacs/ImageLounge/src/DkViewPort.cpp:2776:16: error: ‘planes’ was not declared in this scope
    vector<Mat> planes;
                ^
make[2]: *** [CMakeFiles/nomacs.dir/src/DkViewPort.cpp.o] Error 1
make[1]: *** [CMakeFiles/nomacs.dir/all] Error 2
make: *** [all] Error 2

**Comment by sfiel** [comment]
strange error

we are just releasing a new version and thus updating the master branch ... could you please check in 1-2 hours (the best would be when the new release is announced on our homepage) if the error still exists? because we changed a lot. Thanks

**Comment by alyosama** [comment]
build succeeded now
Thanks
