### ISSUE TITLE
No frame bug

### ISSUE THREAD

**Issue by Xagunto** [nomacs/nomacs#130]
Hello, recently I tried the "no frame" feature on a photo, and now the software won't even open, even if I reinstall it. The logo appears on the side bar, but I cannot access it.
![frame bug](https://user-images.githubusercontent.com/29675562/27508839-5aa9f940-58ee-11e7-9286-0353ed6ec473.png)

**Comment by diemmarkus** [comment]
this should not happen...
your fix is: open nomacs (without seeing it) and hit F10.
answering these questions would help us to fix the bug:
- did you change your screen configuration (w. external screens)?
- it appears that your computer has a low resolution - can you please report the exact resolution?

**Comment by Xagunto** [comment]
Hi, it was related to a external screen, yes. I wanted to rescale some
photos and that might have caused it. It ended up fixing with F10 and
waiting for some minutes (large size photo). Thanks!

2017-06-26 9:15 GMT+02:00 Markus Diem <notifications@github.com>:

**Comment by diemmarkus** [comment]
cool - thanks!
