### ISSUE TITLE
Zoom - Should follow the mouse

### ISSUE THREAD

**Issue by Stamimail** [nomacs/nomacs#134]
The same pixel the mouse point, should be im place when zoom in.

> it does - unless the image is smaller than the window

when it is smaller than the window - can't this be fixed?

**Comment by diemmarkus** [comment]
no - it is on purpose (the image should be in the window's center)

**Comment by Stamimail** [comment]
Perhaps it depends on the loaction of cursor when begining to ZOOM IN.
If it over the image, then should follow the mouse.
If it outside the image, the image should be in the window's center.
