### ISSUE TITLE
Legacy appstream metadatas

### ISSUE THREAD

**Issue by agaida** [nomacs/nomacs#137]
```
W: nomacs: appstream-metadata-in-legacy-location usr/share/appdata/nomacs.appdata.xml
E: nomacs: appstream-metadata-legacy-format usr/share/appdata/nomacs.appdata.xml
```
Hi, some lintian whining - unfortunately lintian is right most of the time: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html

**Comment by sfiel** [comment]
can you please check again?
thanks

**Comment by agaida** [comment]
aber klar doch

**Comment by agaida** [comment]
perfect - regarding lintian
