### ISSUE TITLE
reproducible builds

### ISSUE THREAD

**Issue by agaida** [nomacs/nomacs#139]
The date macro will prevent reproducible builds - aka the debian team that take care of that will write me a bug and i will patch that out - normally that will go down through all derivatives. It would be nice if you could remove that upstream.

```
src/DkGui/DkDialog.cpp:230:16: warning: macro "__DATE__" might prevent reproducible builds [-Wdate-time]
  vt += QString(__DATE__) + "<br>";
                ^~~~~~~~
```

**Comment by diemmarkus** [comment]
sure, I'll fix it... thanks!
