### ISSUE TITLE
batch processing unstoppable

### ISSUE THREAD

**Issue by stephanf3** [nomacs/nomacs#141]
When batch processing is started, nomacs goes into a "no response" mode under Windows 7. The result list of processed files is not updated and it's impossible to stop the batch processing other by killing the nomacs process.

**Comment by diemmarkus** [comment]
there is a 'no response' phase during indexing (for it is not threaded) - how many files are you processing?

**Comment by stephanf3** [comment]
In this case I tried resizing about 500 files and it happened after I started the batch conversion.
So the thumbnails were already displayed, the resizing parameters and output folder set. The files to be converted were selected.
Normally after clicking on the start button, nomacs starts instantly writing out the results of the file processing but here it simply stopped any action and the first click on any item resulted in the display greying out and the (no response) text appeared in the window title.

Since batch resizing didn't work anyway I had to revert to the last 2.4 version.

**Comment by diemmarkus** [comment]
That should be fixed in nomacs 3.10
