### ISSUE TITLE
View > Show GPS Coordinates always opens up www.google.at/maps

### ISSUE THREAD

**Issue by TeutonJon78** [nomacs/nomacs#143]
It would be helpful to either allow Google to pick the appropriate country (if possible) or to allow the user to configure what address to open to go to. Default to Google Austria with German isn't so helpful for non-German speakers.

**Comment by TeutonJon78** [comment]
Perhaps that link could be part of the translatable strings.

**Comment by diemmarkus** [comment]
I guess using google.com (in the source) should also fix it - right?
