### ISSUE TITLE
Very sluggish start-up on Win10 x64

### ISSUE THREAD

**Issue by hydhyd** [nomacs/nomacs#146]
Been using nomacs for a year or so until I replaced my older system SSD with a newer/faster SSD and reinstalled Windows.

Windows 10 Pro, clean install. Then this happens: https://gfycat.com/EmptyFlamboyantFeline

Basically, it takes about 5 seconds for it to open a 1280x960 190kb jpeg. Same with any kind of pics/formats, really. Then it's totally alright, as illustrated.

Both nomacs and the jpg in question are on the same, rather fast, SSD. Have been experiencing no performance hits anywhere else whatsoever since the reinstall otherwise, quite the contrary.

Kindly advise. Not sure whether it's a proper nomacs issue or not. Maybe there's a debug/verbosity option present within the the executable? Both IrfanView and Fastone are lightning fast. As was nomacs before the reinstall. Any hidden dependencies maybe? As in, I'm definitely missing a lot of video codecs at the moment, could that be an issue?

Windows 10 Pro x64 latest/nomacs x64 latest/i7 6700k/32GB RAM/GTX 970/Samsung 960 Pro 1TB SSD

Thanks!

**Comment by diemmarkus** [comment]
it's hard to tell why this happens...
you could try to open `Settings > Advanced` and check _Use Log File_ and post the resulting log here

**Comment by hydhyd** [comment]
Did try enabling log files and, what do you know, once I did that, the issue magically went away. It's basically as fast as it was before. Was experiencing the isssue right before that. So go figure. 

Attaching the log just in case; guess 641ms is fast enough. Marking it solved/closed.

Cheers.

```
Hi there
plugins dir set to:  "C:/Program Files/nomacs - Image Lounge/nomacs-x64/plugins"
CSS loaded from:  ":/nomacs/stylesheet.css"
LAN client created in:  0 ms
Initialization takes:  58 ms
[Warning] deleting illegal EXIV orientation...
"C:/Users/xxx/Desktop/Дождик/724fb7ff-2ed7-4642-87a1-8e538a1c8305.jpg" loaded in 14 ms
local client created in:  641 ms
Cache size:  16333
```
