### ISSUE TITLE
Creating Mosaic images resaves some original images

### ISSUE THREAD

**Issue by perk11** [nomacs/nomacs#149]
I was experimenting with nomacs, and tried Mosaic Images feature.The next day I see in my backup reports that some files I used for the Mosaic were edited. I didn't even save the Mosaic and I didn't expect it to touch original files at all.

Here is an example of such a file: [file_edited.zip](https://github.com/nomacs/nomacs/files/1254156/file_edited.zip)

**Comment by diemmarkus** [comment]
thanks - that should of course not happen!
