### ISSUE TITLE
Unable to update translation

### ISSUE THREAD

**Issue by R3gi** [nomacs/nomacs#154]
Hi,
when I run translation update using the Update Translation option in Main menu, the translation is not updated, even if updated strings are present on Crowdin.

For example Czech translation in app contains untranslated strings, which are now translated on Crowdin (translated 6 days ago) and its seems I cannot update them in the app using "Update Translation" option in menu. It seems the check is performed (the update dialog appears for a moment, but then it disappears) and if I run it again the app says my translation is up-to-date.

Nomacs v3.6.1.1108 x64, running on Windows 7 HP SP1 x64, installed in \Program Files\nomacs\, no info about update in app log. I tried to run it with admin rights, reinstall it, check firewall rules…nothing solved the problem.

Please, could someone take a look at this problem? It worked in the past…

**Comment by R3gi** [comment]
The problem seems to be no longer present. This issue can be closed.

**Comment by diemmarkus** [comment]
thx!
