### ISSUE TITLE
toolbar skins

### ISSUE THREAD

**Issue by eadmaster** [nomacs/nomacs#155]
is it possible to change the icons shown in the toolbar and the menus?

The default nomacs icons are colorless and not very good to my eyes, there are [many good alternatives here](http://www.irfanview.com/skins.htm).

**Comment by diemmarkus** [comment]
hi,
you can change the icon colors in `Edit > Settings > Icon Color`. We won't create skins for they are hard to maintain and not high DPI aware - sorry.
