### ISSUE TITLE
Nomacs 64-bit doesn't show up in Windows 10 default apps

### ISSUE THREAD

**Issue by StefanBrand** [nomacs/nomacs#156]
Hey everybody, 

for whatever reason Nomacs 64 bit doesn't show up in Windows 10 default apps. I cannot choose it as the default photo viewer and not for individual file extensions. 

The latter only works in the legacy system control view. There I can choose Nomacs for a specific file extension (e.g. jpg) after searching it in my Program Files folder. Windows doesn't suggest it in the selection list. 

When I uninstall 64-bit and install 32-bit, Nomacs shows up in the Windows 10 settings and I can choose it as the default photo app. 

I'm running Windows 10 Pro 64-bit. 

Best, Stefan

PS.: I'm using the 32-bit version now, I guess it won't make a difference in my use cases.

**Comment by crr0004** [comment]
It should show up after running for the first time and registering file associations. I am running Windows 10 64bit. Windows 10 shows those defaults app by checking the registry in `HKEY_CURRENT_USER\Software\RegisteredApplications` for `nomacs.ImageLounge.3.7.0.1144` with the value of `Software\nomacs\Image Lounge\Capabilities`

Can you check your registry to ensure those values are there?

Can you also export `HKEY_CURRENT_USER\Software\nomacs` and upload here so we can check the values?

**Comment by StefanBrand** [comment]
Hi, I used the 32-bit version since October and just now tried it again with nomacs 3.8.0 64-bit and this time it worked alright. Most files\* are associated with nomacs immediately after the first start of nomacs.

\* See #189

**Comment by diemmarkus** [comment]
can we close this too?
