### ISSUE TITLE
Broken links after using maintenance tool to switch from 64-bit to 32-bit

### ISSUE THREAD

**Issue by StefanBrand** [nomacs/nomacs#157]
When modifying the installation using the maintenance tool (removing 64-bit and adding 32-bit versions), the respective link to Nomacs in the start menu does not get updated. It still says "[x64]" and complains that the target is not to be found.

Expected behaviour is that like during first installation the links get created anew.

I'm on Windows 10 Pro 64-bit.

Best, Stefan

**Comment by diemmarkus** [comment]
thanks for the hint - we are about to move to a msi installer so I guess that should avoid this issue (or
