### ISSUE TITLE
Pinch to zoom

### ISSUE THREAD

**Issue by StefanBrand** [nomacs/nomacs#159]
I've gotten accustomed to *pinch to zoom* from touch devices, and also multitouch touchpads on laptops have the ability to use two fingers to zoom in some programs.

Can this be integrated in nomacs, as an alternative to scroll to zoom?

**Comment by diemmarkus** [comment]
if you uncheck `Mouse Wheel Zooms` in _Edit > Settings_ you will get the expected behavior. Then, _CTRL+Mouse Wheel_ and the _Pinch_ gesture zoom while _Mouse Wheel_ & _Zoom_ gesture browse through images.

**Comment by StefanBrand** [comment]
Oh thanks, that was easy! I was confused by the setting "Change mouse 
wheel behaviour while zooming" in *Edit > Settings > Display*.

The setting that you told me about should be there too.


Am 23.09.2017 um 15:59 schrieb Markus Diem:
