### ISSUE TITLE
Feature request: lossless JPG rotation

### ISSUE THREAD

**Issue by ericjs** [nomacs/nomacs#165]
Please add lossless (right angle) rotation of JPGs. Most people do not realize that simple rotation of a JPG degrades it's quality, but there are algorithms to avoid this. (I believe same may be true or crop.)

**Comment by AlexDaniel** [comment]
For some reason I was assuming that a nice editor like Nomacs would already have this :) 👍

**Comment by diemmarkus** [comment]
Rotating images is lossless (we just set the exif value accordingly)
