### ISSUE TITLE
Navigating with the keyboard in the file pane has no effect

### ISSUE THREAD

**Issue by armageddon51** [nomacs/nomacs#166]
I think it's a long standing request but moving through file/folder name in the file explorer with the keyboard arrows does not update the corresponding picture in the view pane. This function is a must for a graphic program and very common on almost all of them. The others software do no go dwon to individual file in the browser but open the folder.

 Please look at the possibility of implementing that as It quite a serious drawback.

Thanks

**Comment by diemmarkus** [comment]
Hi,

you can already do this: right click into the explorer dock > check `Open Selected Images`

best,
markus
