### ISSUE TITLE
Double keybinding for CTRL+R

### ISSUE THREAD

**Issue by dglava** [nomacs/nomacs#169]
CTRL+R is assigned for both "Reload File" and "Resize Image".

I looked through `ImageLounge/src/DkCore/DkActionManager.h` and couldn't find a shortcut definition for "Reload File". Where does the shortcut for that come from? Would it be possible to change either of those to something else, so it doesn't conflict by default?

I assume that resizing is probably something that people use more often, so perhaps leave CTRL+R for resize and find something else for "Reload File"?

**Comment by k0ste** [comment]
I can confirm.

```
[WARNING] QAction::eventFilter: Ambiguous shortcut overload: Ctrl+R
[WARNING] QAction::eventFilter: Ambiguous shortcut overload: Ctrl+R
[WARNING] QAction::eventFilter: Ambiguous shortcut overload: Ctrl+R
[WARNING] QAction::eventFilter: Ambiguous shortcut overload: Ctrl+R
```

**Comment by diemmarkus** [comment]
this is because we use (OS dependent) Qt keybindings for reload - you can (for now) manually fix it: `Edit > Keyboard Shortcuts > File > Reload File` and set it to e.g. F5

**Comment by dglava** [comment]
Thanks, manually changing it works for now. I guess this should remain open until a proper solution is found.
