### ISSUE TITLE
Codecov - profiling: cannot create directory

### ISSUE THREAD

**Issue by dglava** [nomacs/nomacs#170]
I am getting a lot of messages printed when I close Nomacs. A short snippet can be found below and a link to the full output.

What's causing this? Is there a compile time option to disable this profiling?

I am running Nomacs 3.8 on Arch Linux.

https://pastebin.com/raw/y5pF30kJ
```
~ nomacs 
[INFO] Hi there
[INFO] plugins dir set to:  "/usr/lib/nomacs-plugins"
[INFO] local client created in:  6 ms
[INFO] CSS loaded from:  ":/nomacs/stylesheet.css"
[INFO] LAN client created in:  0 ms
[INFO] Initialization takes:  83 ms
profiling:/build:Cannot create directory
profiling:/build/nomacs/src/nomacs-3.8.0/build/CMakeFiles/nomacs.dir/nomacs_autogen/mocs_compilation.cpp.gcda:Skip
profiling:/build:Cannot create directory
profiling:/build/nomacs/src/nomacs-3.8.0/build/CMakeFiles/nomacs.dir/3rdparty/quazip-0.7/quazip/quazipnewinfo.cpp.gcda:Skip
profiling:/build:Cannot create directory
...
```

**Comment by dglava** [comment]
Building Nomacs and running the executable from the build directory (without `make install`) creates a `src` directory in `nomacs-master/ImageLounge/build/CMakeFiles/nomacsCore.dir`. It containts some *.gcda* files.

After some searching, it appears to be related to code coverage (from this https://github.com/nomacs/nomacs/commit/b367eca05b34a577391510efdde1ae8759ad5331 commit onwards). I removed [these](https://github.com/nomacs/nomacs/blob/master/ImageLounge/CMakeLists.txt#L25-L29) lines from CMakeLists.txt to build it without code coverage (to remove the lcov dependency). But this doesn't seem to be a good solution, because of the above mentioned issues.

Do you have any suggestions on how to solve this? Perhaps make code coverage an optional build option?

**Comment by diemmarkus** [comment]
I have added a flag that is by default set to OFF - I hope that fixes your issue...

**Comment by dglava** [comment]
Thanks, the it builds fine without lconv now and the messages are gone.

Some new warnings popped up though. Is this related to this and should I create a new issue for it?

I built it with `-DCMAKE_INSTALL_PREFIX=/usr -DENABLE_PLUGINS=OFF`

```
[WARNING] QObject::connect: Cannot connect (null)::runPlugin(DkViewPortInterface*, bool) to nmc::DkControlWidget::setPluginWidget(DkViewPortInterface*, bool)
[WARNING] QObject::connect: Cannot connect (null)::applyPluginChanges(bool) to nmc::DkControlWidget::applyPluginChanges(bool)
[WARNING] QObject::connect: Cannot connect (null)::runPlugin(DkPluginContainer*, const QString&) to nmc::DkViewPort::applyPlugin(DkPluginContainer*, const QString&)
```
