### ISSUE TITLE
Frameless images no longer have transparent background?

### ISSUE THREAD

**Issue by djinnsour** [nomacs/nomacs#171]
Previously I could open an image in frameless mode, resize it using the mouse wheel, and drag it out of the way of other applications to use as reference.  Since the recent update a frameless image takes up the entire screen with a black background, so the image may only take 10% of the screen but the Nomacs window covers the entire screen. Is this a bug or is it working as intended?

**Comment by dglava** [comment]
Which operating system are you using?
If you're on a Linux distribution, make sure you're running a compositor. Otherwise you aren't able to have transparency.

**Comment by djinnsour** [comment]
You are correct.  I'm running Xubuntu 16.04 which uses Xfwm as the default compositor and for some reason it was disabled after a recent update.  Enabling it again brought back the transparent functionality.  Thanks.

**Comment by diemmarkus** [comment]
thanks for resolving!
