### ISSUE TITLE
centering

### ISSUE THREAD

**Issue by jdub06** [nomacs/nomacs#172]
auto center of image on canvas seems buggy with a multi monitor set up. when next image is pressed its often rendered in a corner of the canvas/window area.  zooming out and back in centers it but its far from expected behavior. guessing this has something to do with api reporting desktop area as a combo of both screens resolution and your function is doing some calcs off that with a window size to calculate how to center. Im observing this bug on windows 7 havent tried to replicate on any other oses

**Comment by diemmarkus** [comment]
in frameless mode?

**Comment by jdub06** [comment]
No just regular windowed
