### ISSUE TITLE
“Hide All Panels” option is not remembered after restart

### ISSUE THREAD

**Issue by AlexDaniel** [nomacs/nomacs#175]
“Hide All Panels” was implemented for https://github.com/nomacs/nomacs/issues/70. However, this option is not remembered when you close nomacs, which in a way ruins the purpose (using nomacs as a minimalistic image viewer, and opening all of the toolbars with a button press when needed).

**Comment by diemmarkus** [comment]
this state is not remembered on purpose: if _Hide All Panels_ is checked & a user opens a new panel, it's state won't be remembered - now if you forget it being toggled you feel like the show/hide state is buggy. I think UI profiles would better fit your usecase...
