### ISSUE TITLE
Please provide a current QuaZip

### ISSUE THREAD

**Issue by agaida** [nomacs/nomacs#178]
QuaZip works fine with the current version and Qt5 - but the find module and the third party code is a little bit outdated. I can help with, if needed.

**Comment by diemmarkus** [comment]
True. You are welcome to do this, in case you find the time.

**Comment by agaida** [comment]
No problem - i have just to update my package first

**Comment by diemmarkus** [comment]
I have now removed Quazip from the nomacs repo - is there an official Quazip package for Linux? If so we just need to change our CMake accordingly

**Comment by agaida** [comment]
the major distributions have this packaged: https://repology.org/metapackage/quazip/versions

**Comment by diemmarkus** [comment]
thanks again for helping!
- `QUAZIP` is now enabled for all OS except APPLE
- It is disabled in `.travis.yml` since 14-04 (trusty) does not seem to have `libquazip5-dev` -> enable it as soon as the environments are updated
