### ISSUE TITLE
Files copy is being created in AppData folder

### ISSUE THREAD

**Issue by kayteck1** [nomacs/nomacs#184]
When I open a file from my mobile connected to the computer (through "My Computer>This PC>Phone", nomacs creates a copy of each photo I have viewed in {system drive}\ Users\ {username}\AppData\Local\Microsoft\Windows\INetCashe\IE\ {random letters folder}\ {original filename}[1].{extension}

Generally, this would not be a problem, but the files are not being deleted after nomacs is closed and also are visible as additional files in the folder to view if the new viewed file had been copied to existing {random letters folder} catalog.

I have Log Recent Files turned off
Maximum Cache Size 1MB
History Size 1MB

System is Windows 10
nomacs portable version 3.8.0.1170

**Comment by diemmarkus** [comment]
Hi,

I am sorry, but it is Windows that copies these files (hence the folder Microsoft\Windows\INetCashe\IE) - nomacs only reads/writes to `C:\Users\{username}\AppData\Local\nomacs` (the settings) and `C:\Users\{username}\AppData\Local\Temp` (log files if enabled).

cheers,
markus
