### ISSUE TITLE
feature request : batch croping

### ISSUE THREAD

**Issue by da-sti** [nomacs/nomacs#185]
I noticed that it's not (yet) possible in nomacs :-)

xnview mp has this feature, in automatic or fixed, it's quite good but it's also missing some
- i.e. crop to get a picture of this size 600x600 from centered/left/right/top/top-left ...etc... of the original 

As an example I put pictures of this feature in xnviewMP that could inspire you

![2018-01-24 16_39_26-batch convert](https://user-images.githubusercontent.com/22189964/35322427-3f5fb992-0125-11e8-8773-3b87bd0f4337.png)

**Comment by diemmarkus** [comment]
done : )

**Comment by da-sti** [comment]
whao ! impressive !!!!!! thanks a lot !
I will test that as soon as the new version comes out !
