### ISSUE TITLE
Shortcut "Hide All Panels" can't be changed

### ISSUE THREAD

**Issue by geniusupgrader** [nomacs/nomacs#186]
Everytime I change the keyboard shortcut: "Hide All Panels" and restart nomacs,
the setting is written to the settings.ini file but not read in and the shortcut for Hide All Panels is always the "F" Keyboard Shortcut. I want to change it, in order that I can change Fullscreen to "F"

**Comment by diemmarkus** [comment]
Hi,
I just tested it:
![img-2018-01-29 09 16 11](https://user-images.githubusercontent.com/4182443/35500034-3c284830-04d5-11e8-95c8-ebd6fed94e28.png)
and it seems to work for me. Which keyboard shortcut did you choose?

**Comment by mar04** [comment]
Same for me, I tried setting it to 'U' or 'Backspace' and even to 'ctrl+alt+shift+m' as in the screenshot above, and after closing it and opening again it's back to 'F'.

**Comment by geniusupgrader** [comment]
Yeah, someone else. Thanks for mentioning @mar04

**Comment by geniusupgrader** [comment]
I had thougt, that I already answered @diemmarkus one week ago. But now I see that I didn't send the message. Here is it again:
@diemmarkus have you tried to restart nomacs after setting the shortcut?

Possible way to reproduce:

1. Edit -> Keyboard Shortcuts
2. change the shortcut: Panels -> Hide All Panels to something else: like `ctrl+alt+shift+m` as in the screenshot above
3. restart nomacs
4. the shortcut is resetted

**Comment by mar04** [comment]
> Are you using nomacs 3.8?

Yes, 3.8 from Archlinux repositories.

>Which language are you using?

English.

>Does it apply to other shortcuts too?

No, at least the ones I tried.

>Can you see it in the settings editor:

It's 'Ctrl+Alt+Shift+M' in the settings editor but 'F' in 'Panels' menu in menubar and in 'Keyboard Shortcuts'.

**Comment by mar04** [comment]
I think I've found something.
In the setting.ini file the shortcut is saved as:

>Hide%20%26All%20Panels=Ctrl+Alt+Shift+M

however in DkActionManager.cpp it's:

>mPanelActions[menu_panel_toggle] = new QAction(QObject::tr("&Hide All Panels"), parent);

I've edited settings.ini to move ampersand at the beginning, so it looks like this:

>%26Hide%20All%20Panels=Ctrl+Alt+Shift+M

and it works! The shortcut is properly restored after restart.

**Comment by diemmarkus** [comment]
this is really weird - I will check the parsing of the action name... thanks!

**Comment by mar04** [comment]
I'm using nomacs 3.10 and it's not fixed. Previously mentioned workaround of manually editing configuration file still works.

**Comment by geniusupgrader** [comment]
Thanks for working on this issues at all! Hopefully this wont happen to other things in the config accidantilly
