### ISSUE TITLE
Associate *.CR2 raw files with nomacs

### ISSUE THREAD

**Issue by StefanBrand** [nomacs/nomacs#189]
Hi, I have some *.CR2 files here in a directory and nomacs does not recognize them by default. I have to explicitly tell Windows 10 to open them with nomacs.

Also, when I open one CR2 photo with nomacs, it shows an info message telling me that there are no other photos in the same directory. There are, however, 50+ other CR2 photos in that folder.

The CR2 photo itself opens just fine in nomacs.

**Comment by diemmarkus** [comment]
Hi,
we had a similar issue here: #129. Do you have different architectures of nomacs installed (or more than one version)?

**Comment by StefanBrand** [comment]
Yeah, sorry for the alarm 😅, I was on x86-3.6.0 and now updated to x64-3.8.0 and browsing through CR2 files works.

**Comment by diemmarkus** [comment]
awesome : )
