### ISSUE TITLE
Can't associate any defaults in Windows 10

### ISSUE THREAD

**Issue by vanzos** [nomacs/nomacs#192]
Hi,
Tried both the 32 bit and 64 and ready to give up on this software because I can't get it to be a default pic viewer (no selection in both the control panel or when I right click any photo).   I've seen this issue posted various times.  Any help is appreciated.

**Comment by diemmarkus** [comment]
The problem is, that microsoft became pretty strict about file associations thanks to software like the ASK Toolbar that was bundled with Java.
- You could try from within nomacs `Edit > Settings > File Associations` and then click `Set as Default Viewer`? 
- Another option would be to set nomacs through Windows Explorer: right click an image `Open With > Choose another app`, select nomacs from the list then check `Always use this app to open .png files`.

**Comment by BangDroid** [comment]
Also try:

Run > control /name Microsoft.DefaultPrograms /page pageFileAssoc

Windows Settings app has (uselessly) hijacked file associations in a recent update, this is currently the only way I know to access this part of control panel.

**Comment by AlexanderRydberg** [comment]
Im jumping on this thread.
The issues here are that Windows 10 changed its way of allowing default apps to be... default(?) (as written above).
What I would like is when you installed the msi, that you dont have to run nomacs first for the user to be able to set this as a default viewer. If that isnt done a sys-admin cant add nomacs as default in GPO; `Computer Configuration > Administrative Templates > Windows Components > File Explorer.`.

**Comment by Sirove** [comment]
+1!

**Comment by diemmarkus** [comment]
the same issue is discussed on our [webpage](https://nomacs.org/multi-user-systems/)

here might be a possible solution:
https://kolbi.cz/blog/2017/10/25/setuserfta-userchoice-hash-defeated-set-file-type-associations-per-user/

if somebody knows an easy way how to do it - I would love to add it to nomacs (as a cmd parameter)

**Comment by diemmarkus** [comment]
in [3.10](https://github.com/nomacs/nomacs/releases/tag/3.10.2) we have added a cmd option that allows you to register file associations without opening the UI:
````cmd
REM Register file associations (Windows only).
nomacs.exe --register-files
````
I guess, that's the best we can do here...
