### ISSUE TITLE
nomacs silent install

### ISSUE THREAD

**Issue by andrle** [nomacs/nomacs#193]
By default nomacs.msi with options /passiv or /qn install to folder C:\nomacs\ not to %ProgramFiles%\nomacs.

**Comment by andrle** [comment]
Yes, x64 works fine, but x86 not work correct.
I am test 3.8.0 on Russian Windows 7. I think problem in MSI installer for x86. You use not correct path for x86. On image you can see Orca setting for x86 installer. I think it is not correct path...
![orca_2018-02-27_10-53-56](https://user-images.githubusercontent.com/30503831/36709852-c9a348c0-1bac-11e8-9d1d-5379f1605834.png)

**Comment by diemmarkus** [comment]
ah - I get. I will check the x86 installer too, thanks!

**Comment by diemmarkus** [comment]
I will close this issue - since we won't create new x86 installers
