### ISSUE TITLE
Multiple screens

### ISSUE THREAD

**Issue by Richard127** [nomacs/nomacs#195]
Hi. Love the programme but have to uninstall for now as there is a display problem. I have 2 screens and, when viewing borderless by pressing F10, Nomacs displays the image half and half and in the middle across both screens (See Below).
![2screens-problem](https://user-images.githubusercontent.com/36739322/36550459-41d79bac-17ed-11e8-816f-3cb2edce65f6.png)

**Comment by diemmarkus** [comment]
hmm, the issue seems to be that nomacs messes up the screen geometries here - I think it's best to let users choose the preferred screen in frameless mode... - thanks for reporting!

**Comment by Richard127** [comment]
Thanks for quick response. It's not actually a deal breaker as I hadn't
noticed the F11 full-screen option and thought that F10 was the only option
I had (my bad). Wonderful software. Thanks.
