### ISSUE TITLE
Sort according to folder structure

### ISSUE THREAD

**Issue by mhpreiman** [nomacs/nomacs#198]
It would be nice (actually necessary) to view images in the order of how they are sorted in the folder.

I love the program overall, but unfortunately this has become very annoying and need to find a program that can do that.
After all, it is the default behaviour in windows and I believe that also in many other image viewers.

For example, the current options don't support sorting by tags.

**Comment by diemmarkus** [comment]
that's not an easy task (for nomacs would have to find the corresponding windows explorer) - I actually don't know any image viewer (except those developed by Microsoft) who can do this...
