### ISSUE TITLE
Arch Linux package broken due to libqpsd

### ISSUE THREAD

**Issue by dvzrv** [nomacs/nomacs#203]
Hi!
It seems it's currently [impossible to rebuild nomacs 3.8.0 for Arch Linux](https://bugs.archlinux.org/task/57882), as the included libqpsd version is causing trouble (quazip, as well actually).

`libnomacsCore.so.3.8.0: undefined reference to 'vtable for QPsdPlugin'
`
I've now tried to provide libqpsd system-wide (but using [qmake is a nightmare](https://github.com/Code-ReaQtor/libqpsd/issues/20)) and finally had to give up, because there actually is no integration for having a system-wide libqpsd in the cmake files for nomacs (yet). Building with the current version of libqpsd cloned to the 3rdparty directory also doesn't solve this.

It would be great, if you could have a look into this.

**Comment by rindeal** [comment]
This has been fixed in https://github.com/nomacs/nomacs/commit/92a95cd288dd64829e33aeb5d8c6e9725219e6bd

**Comment by dvzrv** [comment]
@rindeal cool! If possible, please do a release!

**Comment by diemmarkus** [comment]
I just updated our libqpsd & drafted a release for b55441c525d802ad9ae5b229e804ca86a3b4f31f (see [3.8.1](https://github.com/nomacs/nomacs/releases/tag/3.8.1) . Do you need anything else to fix this?

**Comment by dvzrv** [comment]
@diemmarkus thanks!
Can you also tag a new release for the nomacs-plugins, so they stay in parity?

**Comment by diemmarkus** [comment]
[sure](https://github.com/nomacs/nomacs-plugins/releases/tag/3.8.1) - I forgot about it, sorry!

**Comment by dvzrv** [comment]
excellent! will try the build tonight

**Comment by rindeal** [comment]
works nice, thanks all

**Comment by dvzrv** [comment]
Just pushed 3.8.1 to the repos.
Thanks!
