### ISSUE TITLE
navigation in v. 3.8.0 in Fedora Linux slows badly with increasing number of images in folder

### ISSUE THREAD

**Issue by Coasting** [nomacs/nomacs#205]
Upgrading to v 3.8.0 in Fedora 26 (Linux) causes the image-to-image transition to become painfully slow when the number of images in a folder increases. Downgrading to v 3.6.1 fixes it. Deleting all nomacs config files after removing 3.6.1 does not allow the upgrade to 3.8.0 to act normally. This issue is seen in two separate Fedora 26 installations. 

The slowness of clicking through images makes 3.8.0 unusable in these systems which both have fast 8-thread i7 processors and 16GB RAM.

**Comment by diemmarkus** [comment]
thanks for reporting - i will have a look at it...

**Comment by diemmarkus** [comment]
Is this issue still there with nomacs 3.10?
