### ISSUE TITLE
Thumbnail preview Drag&Drop improvements

### ISSUE THREAD

**Issue by kai-uwe-rommel** [nomacs/nomacs#206]
I like the thumbnail preview (Shift+T) and use it a lot. I often use it to sort a batch of photos and to identify those - for example - that belong to a series that I need to convert to a panorama. I can already mark such a series of photos and drag and drop them together onto my stitching software (MS ICE). 
What I am missing in Nomacs: 
- it would be great if I could create new subdirectories in the file explorer panel directly from within Nomacs
- then it would be also great if I could drag and drop marked photos from the thumbnail view into another directory in the file explorer panel
- and - of course - by pressing Ctrl or Shift to select if I want to copy or move them by dropping the dragged photos

**Comment by diemmarkus** [comment]
done - thanks for the suggestions
