### ISSUE TITLE
Can't read 32 bit TGA files with alpha

### ISSUE THREAD

**Issue by Skeevy** [nomacs/nomacs#210]
As the title says. A sample is attached. Thanks!

[Sample.zip](https://github.com/nomacs/nomacs/files/1873399/Sample.zip)

**Comment by diemmarkus** [comment]
the file is missing the TGA signature at the end of the datastream (the nomacs loader right now only loads TGA files that comply with the standard...)

**Comment by Skeevy** [comment]
Thanks for your reply.
The TGA signature is an optional extension of the original file format. You shouldn't deny a load if it's not available, because it's optional and many programs just doesn't support that.
As a consequence, nomacs is so far the only app on my machine that can't read this file. I have tested and verified compliance for the following programs:
* GIMP
* XNView
* Fast Stone Viewer
* PhotoShop
* Irfan View
* Corel  Photo Paint

They all can ready and write the file as expeccted. So, in fact nomacs is the only app that denies a read.

Thanks,
Kind Regards.

**Comment by diemmarkus** [comment]
... the only app you tested : )
-> I had a look at it again (saved the image from PS and it works fine...) after a bit of googling it seems to be another issue than what I mentioned before. The Qt TGA loader cannot deal with the run-length encoding (RLE) that your image seems to be compressed with.
To summarize, nomacs supports:
- 16-bit TGA
- 24-bit TGA
- 32-bit TGA
and it does _not_ support:
- 16-bit TGA - RLE
- 24-bit TGA - RLE
- 32-bit TGA - RLE

**Comment by diemmarkus** [comment]
update:
nomacs now supports RLE compressed TGA files

**Comment by Skeevy** [comment]
Thanks a lot, much appreciated!
