### ISSUE TITLE
Feature request: View current mouse pixel-coordinates

### ISSUE THREAD

**Issue by ashwhall** [nomacs/nomacs#211]
I work in computer vision and use nomacs as my image-viewer of choice. It's a really common task that I need to quickly see inspect an image, to see where a particular set of coordinates lies. I currently go to crop mode and begin drawing a crop from the top-left corner, just so that I can have the mouse coordinates displayed on screen.
What I'd love is for the current mouse coordinates to be displayed somewhere on the screen when just viewing an image (MsPaint does this in the status bar).

Is this a possibility?

**Comment by diemmarkus** [comment]
Hi,

yes we also display it in the status bar: `Panels > Toolbars > Statusbar` or simply: `CTRL+I`. 

cheers, 
markus
