### ISSUE TITLE
Linux Settings

### ISSUE THREAD

**Issue by agaida** [nomacs/nomacs#214]
Get a bug about changed settings filename and path - and the user was right. Is it possible to have an XDG-compat settings handling again for Linux?

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=893677

**Comment by diemmarkus** [comment]
true, the thing is that we wanted to get rid of the Windows registry. But if XDG settings are more convenient for Linux, we can change it back, sure!

**Comment by agaida** [comment]
the xdg part is especially useful for multiuser setups - or just for distributions who want to provide their own settings.
