### ISSUE TITLE
Slideshow and Frameless bug

### ISSUE THREAD

**Issue by tosime2** [nomacs/nomacs#218]
In slideshow mode (press spacebar), when I change to frameless (F10), the next image moves to a default location on the screen (top right), from where I had previously dragged it.

How can I keep an image in a location I dragged it to when I switch to frameless mode?

It appears to have worked previously, then just stopped working.

My aim is to have several gif images running simultaneously in slideshow mode in different parts of the screen.

**Comment by diemmarkus** [comment]
Hi,

if you open _Edit > Settings > Display_ you will find a section `When Displaying New Images` - there you have to check _Always keep zoom_

best,
markus

**Comment by Chillstice** [comment]
Sorry to bring this back from the dead, I just discovered this program and I'm also experiencing this issue. I have some more details:

When opening a folder of images in frameless mode, zooming to shrink the image, and placing it in a corner of a screen the next image in the slideshow ignores the position entirely and moves the frameless slideshow to the center of the selected monitor. 

The `Always keep zoom` option does work - as in - it keeps the zoom level between images in the slideshow, but it does not save the position.

This functionality is almost perfect. I'm loading a bunch of images of characters in a slideshow, shrinking them down, and placing them on top of my taskbar. It harkens back to a time when people had desktop pets, but it's modernized and more customizable.

Windows 10 18363
Nomacs 3.16 (Installed)
I'm using a folder full of transparent pngs

Another little thing that doesn't require it's own issue:
Why is there a cap on the slideshow `Display time`? If possible, I would set my slideshow to something like 10 minutes.

**Comment by Furretar** [comment]
If you go fullscreen (f11), press windows + right arrow, then press frameless (f10), the image will be right-aligned (does not work for the left, strangely)
