### ISSUE TITLE
feature request: transparent fullscreen when starting app

### ISSUE THREAD

**Issue by StephanBusch** [nomacs/nomacs#220]
When the app starts, I would prefer a transparent black window design as it is in Xlideit or in FastPictureViewer. Also, watching images on fullscreen is better than in a window (but maybe this can be adjusted).

There doesn't seem to be a win compile of latest Nomacs available here, so my impressions are from Nomacs 2.4.6.

**Comment by StephanBusch** [comment]
here's an example:
www.squeezechart.com/xlideit.jpg

**Comment by diemmarkus** [comment]
hi,

nomacs has a transparent fullscreen (see screenshot below). You can open it with View > Frameless...

best,
markus

![img-2018-05-28 14 48 03](https://user-images.githubusercontent.com/4182443/40615276-67056f4c-6286-11e8-8e51-a5b321b18883.png)
