### ISSUE TITLE
Button Set nomacs as Default Viewer

### ISSUE THREAD

**Issue by GregoryPINAULT** [nomacs/nomacs#225]
Hello,

Bug seen on Windows 7 x64 - nomacs installed with the x64 MSI. 

Under the menu Edit > Settings > File Association, the button "Set as Default Viewer" don't work for files such as .PNG or .JPG (I dont have more "exotic" file for testing). 

If you choose at first lauch of nomacs to set it as default viewer, it's good, but not if you try to do it later with the button in the menu. 

Thanks for all.

**Comment by diemmarkus** [comment]
that's true. this is bad UI behaviour - actually you have to check/uncheck any extension in the dialog to do so
