### ISSUE TITLE
copy & past unter Linux (opensuse Leap) funktioniert nicht

### ISSUE THREAD

**Issue by derLinuxUser** [nomacs/nomacs#226]
Nomacs Version  3.8 unter Linux Opensuse

Markieren eines Bereichs und anschließendes Kontext-Kopieren bzw Strg-C führt zum Kopieren des ganzen Bilds und nicht des markierten Ausschnitts

**Comment by diemmarkus** [comment]
sorry wegen der späten Antwort. Wie markierst du den Bereich?

lg markus
