### ISSUE TITLE
Toolbars Issues in Frameless & Fullscreen Mode

### ISSUE THREAD

**Issue by Nostaljaded** [nomacs/nomacs#229]
To reproduce: Set all toolbars (Menu, Toolbar, Statusbar, Pseudocolor Function) as active.

**Frameless Mode**

> 'Toolbar' visible at top of screen upon entering _Frameless mode_
> 
> 'Pseudocolor Function' deactivated upon exiting _Frameless mode_

**Fullscreen Mode**

> 'Pseudocolor Function' visible at top of screen upon entering _Fullscreen mode_
> 
> Activating 'Hide All Panels' does not hide 'Pseudocolor Function'
> 
> Deactivating 'Hide All Panels' unhide all toolbars

 Activating/deactivating 'Pseudocolor Function' toolbar will cause nomacs window to disappear for half a second.

_System:_ nomacs 3.10 tested on both Win7 & Win8; no such issues before switch from nomacs 3.6.1

_Edit 1:_
Startup Logo can be seen temporarily when entering _Frameless mode_ on low-spec computers

**Comment by diemmarkus** [comment]
thanks for reporting - actually we always restart nomacs for pseudo color & frameless mode - that explains it being disappeared... 
@Edit 1, the startup logo should not appear - I will check that...
