### ISSUE TITLE
Windows 10: Broken themes with nomacs 3.10.3

### ISSUE THREAD

**Issue by TheGaladras** [nomacs/nomacs#230]
I just updated from nomacs 3.8 to the latest version a few hours ago. It seems that the new themes which you introduced with nomacs 3.8.1 (not available on Windows, I know, but nevertheless they´re now included in nomacs 3.10 with a light and a dark theme) broke the theming on Windows. nomacs looked like a classic from Windows 2000 after the update has finished. Would be nice if you could solve this.

OS: Windows 10 64-bit Build 17134.x

![nomacs 3103](https://user-images.githubusercontent.com/8669826/42219659-eec26acc-7ecc-11e8-817b-73f68fef345c.PNG)

**Comment by tonyram57** [comment]
I agree it is ugly looking now.

**Comment by diemmarkus** [comment]
thanks for the report - it seems that the new Qt version needs an extra dll for win10 themes. We will ship an update today...

**Comment by diemmarkus** [comment]
theming is working again - you can [download ](http://download.nomacs.org/)the new version (v 3.10.1) to get the beauty back : ).
![img-2018-07-05 10 42 38](https://user-images.githubusercontent.com/4182443/42312280-3b48f5cc-8040-11e8-889b-63bdbe6cd574.png)
