### ISSUE TITLE
How to install to custom directory not %ProgramFiles%/nomacs?

### ISSUE THREAD

**Issue by SylwesterZarebski** [nomacs/nomacs#234]
Hi,
  I would like to know how to install program to custom directory and not default %ProgramFiles%/nomacs?

I've tried popular way:
```
msiexec /i nomacs-setup-x64.msi TARGETDIR="X:\Custom\Path" /qb
```
but it did not work.

**Comment by diemmarkus** [comment]
Hi,
you have to change the `INSTALLDIR`, e.g.:
````
nomacs-setup-x64-beta.msi INSTALLDIR="C:\temp\nomacs\"
````
