### ISSUE TITLE
Endlosschleife mit vielen Bildern II    -     Bug #837

### ISSUE THREAD

**Issue by Gratha80** [nomacs/nomacs#235]
Beschreibung:
Die Endlosschleife funktioniert gut, solange relativ wenige Bilder (eine Handvoll zum Testen) im Ordner liegen. Wird der Ordner aber zu groß, läuft die Diashow nur einmal durch und nomacs wird beendet.
nomacs läuft hier auf einem Raspberry Pi 3B mit Raspbian.

Historie
#1 Von Markus vor 2 Tagen aktualisiert
Hi,

das Bug ist bei uns nicht reproduzierbar. Könnten wir ein Logfile haben? (Settings > Advanced > Use Log File). Hier ist übrigens der aktuelle bug tracker: https://github.com/nomacs/nomacs/issues

lg markus

Danke für die schnelle Antwort. Hier das Log:

Hi there
local client created in:  24 ms
CSS loaded from:  ":/nomacs/stylesheet.css"
LAN client created in:  1 ms
Cache size:  1024
Initialization takes:  1 sec
[Warning] deleting illegal EXIV orientation...
[Warning] deleting illegal EXIV orientation...
[Warning] deleting illegal EXIV orientation...

[...]

Wenn bei der Option "Beim Laden der Bilder die Exif-Ausrichtung ignorieren" kein Haken gesetzt ist, bricht die Diashow immer bei einem bestimmten Bild ab und nomac wird beendet.
Wenn der Haken gesetzt ist, läuft die Diashow endlos durch. Jedoch werden dann Bilder, die zuvor gedreht wurden wieder in ihrer ursprünglichen Ausrichtung angezeigt.

**Comment by diemmarkus** [comment]
Hi,

kannst du mir bitte dieses Bild schicken (auch gerne privat an diese Adresse: diemmarkus@gmail.com)?

lg markus

**Comment by diemmarkus** [comment]
hi,

vorweg, auf meinem system läuft es auch mit dem Bild durch. Meine beste Idee momentan wäre, dass nomacs zu wenig memory hat. Der Raspberry müsste ca. 1GB RAM haben (?!) - das Problembild benötigt mit seinen 50MP ~441 MB:
![239-exif-orientation-on](https://user-images.githubusercontent.com/4182443/43884026-4cdf25be-9bb5-11e8-82d1-f949028cfaee.png)

Wenn die Exif Orientation ignoriert wird benötigt nomacs etwas weniger (~410 MB):
![239-exif-orientation-off](https://user-images.githubusercontent.com/4182443/43884012-44584a42-9bb5-11e8-9a5d-3d842afe2e02.png)

Das könnte dann schon zu viel sein. Tritt dieses Bug auch auf anderen Systemen (mit mehr RAM auf?).
Btw. die nomacs Version ist nicht die aktuellste : )

lg markus

**Comment by Gratha80** [comment]
Hi,

 

ja, der pi hat 1GB RAM.

Könnte natürlich sein, dass die 30MB mehr dann der sprichwörtliche Tropfen sind, der den RAM zum Überlaufen bringt.


Auf meinem Windowsrechner läuft es problemlos.

Mir war gar nicht bewusst, dass die Version von nomacs auf dem pi nicht aktuell ist. Ich habe sie mit apt-get installiert, was neueres kommt da auch nicht.

Ich habe dann versucht, die aktuelle Version manuell zu installieren und zu kompilieren. Nach dem Kompilieren bekomme ich es aber nicht ans Laufen (siehe Screenshot).

Nachdem ich ein paar Stunden versucht habe, diese Fehler in den Griff zu bekommen, habe ich dann erstmal aufgegeben...^^

 

Grüße

Elvio


Gesendet: Donnerstag, 09. August 2018 um 09:31 Uhr
Von: "Markus Diem" <notifications@github.com>
An: nomacs/nomacs <nomacs@noreply.github.com>
Cc: Gratha80 <burnwtc@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [nomacs/nomacs] Endlosschleife mit vielen Bildern II - Bug #837 (#235)


hi,

vorweg, auf meinem system läuft es auch mit dem Bild durch. Meine beste Idee momentan wäre, dass nomacs zu wenig memory hat. Der Raspberry müsste ca. 1GB RAM haben (?!) - das Problembild benötigt mit seinen 50MP ~441 MB:


Wenn die Exif Orientation ignoriert wird benötigt nomacs etwas weniger (~410 MB):


Das könnte dann schon zu viel sein. Tritt dieses Bug auch auf anderen Systemen (mit mehr RAM auf?).
Btw. die nomacs Version ist nicht die aktuellste : )

lg markus

**Comment by diemmarkus** [comment]
bzgl. kompilieren kann ich leider nicht weiterhelfen, da der screenshot leider fehlt. Ich schließe dieses issue erst mal (da es wahrscheinlich das oben angesprochene problem ist)
