### ISSUE TITLE
[Feature request] Display filename in status bar

### ISSUE THREAD

**Issue by MarcRdC** [nomacs/nomacs#236]
Would be useful to have the filename displayed in the status bar — to quickly distinguish similar consecutive pictures, for example, without having to hover over the thumbnail or losing space with another panel. Is it, more generally, possible to customize the content of the status bar?

**Comment by diemmarkus** [comment]
thanks for your request. Did you notice that the filename is displayed in the titlebar- or is this not visible on your system?

best,
markus

**Comment by MarcRdC** [comment]
You are right, it is indeed visible. However, I hide the title bar of maximized windows in my desktop environment — and Nomacs window is often maximized. As the status bar already contains some file information like the size and the modified date as well as graphic properties, I think that filename would be a useful addition.

**Comment by MarcRdC** [comment]
Thank you very much for the commit!
