### ISSUE TITLE
Missing cmake and pkg-config as dependencies for MacOS in README and some newbie quesitons

### ISSUE THREAD

**Issue by sgon00** [nomacs/nomacs#238]
Hi, I was a linux user and new to MacOS. When I try to build nomacs in MacOS, I found out `cmake` and `pkg-config` are the two dependencies I don't have and not listed in the README for MacOS section. 

Some newbie questions:

* If I run `nomacs/build/nomacs.app/Contents/MacOS/nomacs <args>` directly without `make install`, everything works fine. But if I run `open -a "nomacs" <args> <relative_path>` or `open -a "nomacs" --args <args> <relative_path>` after `make install`, none of them works. I am new to MacOS, how to run an app properly in command line? Is that possible? OR maybe I just don't make install and use the build script directly. 

* In thumbnail preview mode, `nomacs <directory>`, how can I move selection between the thumbnail images and open one image? I tried many keyboard buttons and combinations and none of them works. I can only use mouse to click on it. Can I use keyboard for this purpose? 

* In thumbnail preview mode, I found out I could zoom in the thumbnails, but it's just zoom in. The thumbnail image size actually does not change and it makes the image blurry. Is that possible to increase the default thumbnail size?

* In thumbnail preview mode, can I hide the file names? I just want to see a list of image thumbnails, the filenames covers most of the image since the thumbnail size is too small. 

* Can I ask where does thumbnail cache store in MacOS? I really don't find it anywhere...

Sorry about too many questions. I am a linux user and just switch to MacOS. I have infinite number of image viewer choices in Linux, but for MacOS, I just found nomacs. and I consider it's the best one in MacOS. In linux, I can do whatever configuration I want, in MacOS, I am just lost.

**Comment by diemmarkus** [comment]
> When I try to build nomacs in MacOS, I found out cmake and pkg-config are the two dependencies I don't have and not listed in the README for MacOS section.

thanks - I'll add this

> If I run nomacs/build/nomacs.app/Contents/MacOS/nomacs <args> directly without make install, everything works fine. But if I run open -a "nomacs" <args> <relative_path> or open -a "nomacs" --args <args> <relative_path> after make install, none of them works. I am new to MacOS, how to run an app properly in command line? Is that possible? OR maybe I just don't make install and use the build script directly.

sorry, I don't know that either (-> I am not using MacOS)

> In thumbnail preview mode, nomacs <directory>, how can I move selection between the thumbnail images and open one image? I tried many keyboard buttons and combinations and none of them works. I can only use mouse to click on it. Can I use keyboard for this purpose?

currently you can only use the mouse - but using the keyboard arrow keys would be nice here. I opened an issue accordingly: #240

> In thumbnail preview mode, I found out I could zoom in the thumbnails, but it's just zoom in. The thumbnail image size actually does not change and it makes the image blurry. Is that possible to increase the default thumbnail size?

we only use exif thumbnails for this preview (for speed & memory reasons) - so that's not possible...

> In thumbnail preview mode, can I hide the file names? I just want to see a list of image thumbnails, the filenames covers most of the image since the thumbnail size is too small.

sure - you can toggle filenames in the toolbar or in the context menu:
![img-2018-08-06 10 02 49](https://user-images.githubusercontent.com/4182443/43704428-ea56c822-995f-11e8-94f1-cdce2d7d2e77.png)

> Can I ask where does thumbnail cache store in MacOS? I really don't find it anywhere...

That's the good news: we don't cache them...

best,
markus

**Comment by sgon00** [comment]
@diemmarkus thank you very much for the detail reply and explanation. Since I was a Linux user, I prefer keyboard to mouse. 
(1) I hope the keyboard support can be more elegant in the future.  
(2) I hope it's possible to set custom thumbnail size and cache them. So that I can have a bigger and clear thumbnail photo wall. It can be just an option so that people can still use exif thumbnails if they want.
(3) `make install` is kinda useless in MacOS right now. After installation and I choose a image in `Finder` (like explorer in WIndows) and open the image with `nomacs.app`, the image can not be opened.  The app does launch and opened the **fake** `Recent Files`. The reason why I said "fake" is because it's actually not really the latest Recent Files. and I am not sure how to update the Recent Files' cache. but whatever.

Thank you very much again and I am closing this issue.
