### ISSUE TITLE
panning via keyboard is undocumented and unconfigurable

### ISSUE THREAD

**Issue by aspiers** [nomacs/nomacs#242]
Unless I'm missing something, there's no way to pan around an image with the keyboard.  I checked the Keyboard Shortcuts menu, but couldn't see any actions there which could be bound to keys.

Coupled with the inability to pan via mousewheel (#237) or via scroll bars (#241) this  only leaves two options I could find for panning:

- Click-dragging the image with the mouse
- Enabling the overview and click-dragging on that

This is a significant flaw in an otherwise awesome program, since:

- neither of these allow panning purely horizontally or vertically (i.e. isolating panning to a single dimension)
- neither of these allow more precise control of the panning speed in a large and/or highly zoomed-in image

**Comment by aspiers** [comment]
A related issue is that IMHO the default bindings of the cursor keys violate the Principle of Least Surprise for many users by not panning.  However this is a similar discussion to #237 where there are good arguments on both sides:

- Cursor keys and mouse-wheel default to panning in a great many other UIs, so this is what many users expect.
- OTOH, if the image fully fits within the window's viewport, there is no need for panning, so having cursor keys and mouse-wheel default to no-op in these situations isn't ideal either.

As with #237 the most logical solution is to make it configurable so that users can always set it up the way they prefer.

**Comment by diemmarkus** [comment]
that might be hidden, but it's possible: CTRL + cursor keys... I guess this issue is more about lacking documentation than implementation.

**Comment by aspiers** [comment]
Thanks, that works!  But then why aren't CTRL+cursor keys listed anywhere under the Keyboard Shortcuts dialog?

**Comment by diemmarkus** [comment]
Old code : ) - I'll add it there - thanks for the hint!

**Comment by supersexy** [comment]
Sorry to annoy in this closed issue, but @diemmarkus could you please add that to some kind of obvious place in the GUI? I just spent way too much time searhing for this! Also @aspiers is absolutely right about the principle of least surprise - I was very surprised that "arrow down" did not pan the picture, but instead switched to the next one. Also the mouse wheel did not, what I expected.
