### ISSUE TITLE
Second Monitor and Edit Toolbar

### ISSUE THREAD

**Issue by keboen** [nomacs/nomacs#243]
Hi,

Nomacs is the greatest image viewer ever. However, in 3.1.2 on Win 10, when an image is moved to a second monitor, it becomes unresponsive. 

Another issue is that an Edit toolbar always appears in frameless mode. Although it can be closed, opening an image without it was one of the best features of earlier versions.

Thanks for great product.

Bob

**Comment by Nostaljaded** [comment]
> Another issue is that an Edit toolbar always appears in frameless mode. Although it can be closed, opening an image without it was one of the best features of earlier versions.

Reemphasizing here as it may have been overlooked when it was also mentioned in #229. :)

**Comment by diemmarkus** [comment]
thanks!
