### ISSUE TITLE
Support Animated GIFs

### ISSUE THREAD

**Issue by asjones987** [nomacs/nomacs#245]
It would be nice if Nomacs supported animated GIFs.  The ability to open, view the animation and even when copied from a website pasting them into Nomacs like one can do with other images.

**Comment by asjones987** [comment]
I did a right click copy image in Firefox and pasted it into nomacs to find the issue for my case.

**Comment by davehorner** [comment]
+1 for better animated sequences.  thresholding/histogram/etc break the animation.  there's no way to control speed of playback that I can find.

**Comment by diemmarkus** [comment]
>  thresholding/histogram/etc break the animation or done update per frame of the animation.

nomacs does not support editing gif sequences (so you can only apply thresholding etc to the currently displayed frame



>  there's no way to control speed of playback that I can find.

also playback is animated as saved in the gif (if you change speed there, nomacs will adjust the animation)

**Comment by diemmarkus** [comment]
animation of downloaded gifs is fixed in the upcoming release (related: #460)
