### ISSUE TITLE
Images Pasted Disappear When Switching Tabs

### ISSUE THREAD

**Issue by asjones987** [nomacs/nomacs#250]
I had an image open in nomacs from a file and hit CTRL+T to open a new tab.  I then pasted an image to the new tab then switched back to the other tab with an image.  Then when I went back to the tab that I had pasted the image the image was gone. 

seeing this in nomacs 3.10 and beta 3.11 built on 31-Aug-2018

Windows 7

**Comment by diemmarkus** [comment]
thanks for reporting!
