### ISSUE TITLE
file filters don't work

### ISSUE THREAD

**Issue by deathtrip** [nomacs/nomacs#26]
nomacs browses inside zip files, even when the option is turned off
registring a file type, from the settings menu, also doesn't seem to work under KDE 5.12

**Comment by diemmarkus** [comment]
registering file types is windows only. we'll check for the zip browsing, thank you...

**Comment by deathtrip** [comment]
zip browsing problem is gone for me in the newest version. thanks for the fast response.

**Comment by sfiel** [comment]
you are welcome
