### ISSUE TITLE
Replace Lena with a free image

### ISSUE THREAD

**Issue by jondo** [nomacs/nomacs#268]
**Description:**
I'm sorry for criticizing your easter egg, but [quoting a Pillow issue](https://github.com/python-pillow/Pillow/issues/884):
> According to Debian bug 758442, Lena is not a free, redistributable image.
> 
> ```
> According to
> Hutchison, Jamie (May–June 2001). "Culture, Communication, and an
> Information Age Madonna" (PDF). IEEE Professional Communication
> Society Newsletter (archive) 45 (3).
> 
> This file is not free:
> When I explained everything to them [playboy] , they told us that they
> would notinterfere as long as the use was for research and education"
> (page 5 second column second paragraph)
> 
> [1] http://www.cs.cmu.edu/~chuck/lennapg/pcs_mirror/may_june01.pdf
> ```

The newsletter is still available [on archive.org](https://web.archive.org/web/20180218234226/http://www.cs.cmu.edu/~chuck/lennapg/pcs_mirror/may_june01.pdf).

**To Reproduce**
1. Load the lena image [as documented](https://nomacs.org/nomacs-around-the-world/): Press CTRL+SHIFT+ALT+L, then type lena.
2. Observe that the Lena image is shown.

**Expected behavior**
The Lena image should not be redistributed.

**Environment:**
 - Win7-64
 - Nomacs 3.10.2.1917 [x64]

**Comment by Hrxn** [comment]
How is that a problem? In the real world, I mean..

**Comment by diemmarkus** [comment]
This is discussed in #96 and #28. We'll probably replace it in nomacs 3.12 because of the repeated issues maintainers run into. I will keep you posted...

**Comment by jondo** [comment]
Sorry for not finding these duplicates on my own.
