### ISSUE TITLE
build nomacs on a headless server

### ISSUE THREAD

**Issue by ClaudioCimarelli** [nomacs/nomacs#269]
I am receiving this error when running nomacs:
./nomacs: symbol lookup error: /home/users/ccimarelli/bin/opencv/lib/libopencv_world.so.4.0: undefined symbol: _ZTVN3cvv4view20TranslationMatchViewE

I built nomacs only with OpenCv support using the latest version found on the respective git repos.

I check the library file with:  ` mn -D | grep _ZTVN3cvv4view20TranslationMatchViewE `
found this: ` U _ZTVN3cvv4view20TranslationMatchViewE ` 

Hope you can help. Thanks.

EDIT: I just noticed that I did not run sudo ldconfig as I am compiling this on a server without root access. Is this possible?

**Comment by ClaudioCimarelli** [comment]
Thanks, I will try this version.

 Yes, I am trying to use it on a headless server on which I have to build more or less everything from scratch.

**Comment by diemmarkus** [comment]
ai : )
-> you can keep posting issues in this thread...
