### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by fullinterest** [nomacs/nomacs#27]
Is it possible that nomacs read SVG files? On Linux OS, it's not that hard to read them, there's some others images viewers, but on Windows, there's not much, and really, it would be good. I don't know if it's hard or not to do, I just ask to know if you want/plan it.

**Comment by diemmarkus** [comment]
in theory it is not so hard - because Qt supports SVGs however, we have to take a look at the zooming etc (it's way different to zooming images)

**Comment by fullinterest** [comment]
When I upgraded to Windows 10, I was surprised that svg is that much unsupported, compared to Linux OS where even themes use svg. Yeah I guess zooming an svg is re-rendering it in bigger size, or something like that, right?

So, can hope to have support of it some days? And thanks

**Comment by diemmarkus** [comment]
yes - and yes : )

**Comment by fullinterest** [comment]
Can't do much to help you except encouraging you to continue this great work
