### ISSUE TITLE
Nomacs 3.10 crashes after opening specific .tif-files - How to debug?

### ISSUE THREAD

**Issue by Starbase12** [nomacs/nomacs#272]
Dear Team,

since version 3.10.x, Nomacs is crashing instedly after opening some specific .tif-images. Because these TIF files are prototype data of our customers, we can not upload them without prior consultation. While using the Version 3.8.x, we never faced issues like that.

Is there any way for Debugging? Maybe we're able to find the differences and therefore the root cause of the crashes. It's not the filename-length or the size of the Image.

Thanks in advanced.

**Comment by diemmarkus** [comment]
Hi,

that's bad. Of course, it would be easier if you could provide such a file - but I do understand the copyright issues. 

The best we can try now is to open the file with logging turned on (`Settings > Advanced > Logging` - check `Use Log File`). Restart nomacs and load the problematic image. A log file named `nomacs-DATE-log.txt` will now appear in `%TEMP%` (or the default temp folder of your system). You can then upload this log file here if it does not contain sensitive data.

You could also try the latest [beta](download.nomacs.org/nomacs-setup-x64-beta.msi) if you have Windows.

best,
markus

**Comment by Starbase12** [comment]
Hi Markus,

I've created 3 logfiles for you with 3 test-files. File "1.tif" is working well. "2.tif" and "3.tif" not. The application crashed directly after Opening. You'll find the logfiles attached.

After installing the latest beta (v.3.11.0.3938) all seems to work now. Let me test it a few days.
But it Looks very good. What has changed between the stable and the beta one?



[Working_file1.txt](https://github.com/nomacs/nomacs/files/2487531/Working_file1.txt)
[Not_working_file2.txt](https://github.com/nomacs/nomacs/files/2487532/Not_working_file2.txt)
[Not_working_file3.txt](https://github.com/nomacs/nomacs/files/2487533/Not_working_file3.txt)

**Comment by diemmarkus** [comment]
Hi,

it seems that nomcas is capable of loading these tiffs but not displaying them. Out of curiosity: are they encoded as grayscale/binary (or any other unusual color space)?
Let's see if the current beta truly fixed the issue - if so we're fine here since it will be released soon...

best,
markus
