### ISSUE TITLE
Multiple Pages TIFF

### ISSUE THREAD

**Issue by sontal** [nomacs/nomacs#273]
Dear Sir,

First of all I would like to thank you for all your hard work regarding this free image viewer.

I did notice a bug though or an issue in general which I did reproduce again and again. I moved a multi-page tiff file from Thunderbird to a folder on my desktop and changed its name from English characters to Greek. Just the filename. I did not save it again. After that I could only see the first page of the tiff file.

I did that with two such files. The first one worked ok when I utilized english (latin) characters when renaming. The weird thing is that with the second file (which was almost exactly the same as the first one), the second page disappeared (or I could not view it) after renaming, even with english characters.

Do you happen to have any idea why this is happening? I use the latest version of the program.

Thank you in advance.

**Comment by diemmarkus** [comment]
fixed - thanks for reporting!
