### ISSUE TITLE
Segmentation fault when clicking on "Background Color" checkbox

### ISSUE THREAD

**Issue by sicklylife-jp** [nomacs/nomacs#274]
**Steps to reproduce the behavior:**
1. Tools -> Batch Processing -> Adjustments -> Background Color
2. Segmentation fault (core dump)

**Desktop:**
 - OS: Windows 10 64bit, Ubuntu 18.10 64bit
 - Version: 3.12.1, 3.12

**Screenshots:**
![2018-10-26_01-24](https://user-images.githubusercontent.com/43719368/47515505-05f30a80-d8be-11e8-9d30-9a90a1618167.png)

**Comment by diemmarkus** [comment]
stupid mistake... thanks for reporting!
