### ISSUE TITLE
Option to hide cursor in fullscreen

### ISSUE THREAD

**Issue by yaomtc** [nomacs/nomacs#275]
I would like an option to automatically hide the cursor once it's been still for a second or two in fullscreen mode. This is a pretty universal feature now of viewers that can go fullscreen.

Some FOSS image viewers with this feature:
* [Gwenview](https://userbase.kde.org/Gwenview)
* [gThumb](https://github.com/GNOME/gthumb)
* [Eye of GNOME](https://wiki.gnome.org/Apps/EyeOfGnome/)

**Comment by diemmarkus** [comment]
done - thanks for reporting!

**Comment by yaomtc** [comment]
Wow, quick! Thank you!
