### ISSUE TITLE
Default Japanese user interface font has been changed from ClearType font to Bitmap font

### ISSUE THREAD

**Issue by sicklylife-jp** [nomacs/nomacs#277]
**Describe the bug**

Nomacs 3.12.1 on Windows 10 uses a Japanese bitmap font by default, but it's not modern.
Please revert to the old Japanese font settings.

**Desktop:**
 - OS: Windows 10
 - Nomacs: 3.12.1
 - Language: Japanese

**Screenshots**

1. Nomacs 3.10.1 (font name: Yu Gothic UI)
![nomacs 3 10 1](https://user-images.githubusercontent.com/43719368/47717787-0d356200-dc8a-11e8-96c4-d5c210dcf5c9.png)

2. Nomacs 3.12.1 (font name: MS UI Gothic)
![nomacs 3 12 1](https://user-images.githubusercontent.com/43719368/47717802-17eff700-dc8a-11e8-9ce3-aa4ffecd1339.png)

**Comment by diemmarkus** [comment]
thanks for pointing this out - we will revert the font in the upcoming release... 
Until then, you could fix the style of your nomacs by adding these lines to your theme file: `"C:\Program Files\nomacs\bin\themes\Light-Theme.css"` (you will need admin rights to edit this file)
```css
QWidget {
		font: light "Yu Gothic UI";
}
```
nomacs 3.12 will then look like this:
![img-2018-11-02 13 05 21](https://user-images.githubusercontent.com/4182443/47914684-cf5e5680-dea0-11e8-81d4-e3ec570c2b1f.png)

best,
markus

**Comment by sicklylife-jp** [comment]
> "C:\Program Files\nomacs\bin\themes\Light-Theme.css" (you will need admin rights to edit this file)
> QWidget {
>     font: light "Yu Gothic UI";
> }

Thanks!
