### ISSUE TITLE
lenna-lintian-warning

### ISSUE THREAD

**Issue by agaida** [nomacs/nomacs#28]
Hi,
packaging nomacs for debian i get the lintian warnings:
<pre>
E: nomacs source: license-problem-non-free-img-lenna src/img/lena-full.jpg
E: nomacs source: license-problem-non-free-img-lenna src/img/lena.jpg
</pre>

Can you change this upstream please, rationale: https://www.preining.info/blog/2015/07/amusing-lintian-error-lenna/

DISCLAIMER: I'm old enough now and i'm not offended - but this image is non-free :D 

Cheers Alf

**Comment by diemmarkus** [comment]
hi,

thank you for the hint. We know that lenna is non-free - but it is [distributable](https://en.wikipedia.org/wiki/File:Lenna.png#cite_note-Wired-2):
> Permission: Use of this 512x512 scan is "overlooked" and by implication permitted by Playboy

In our software, the image is used as easter-egg rather than for testing purposes.

cheers markus

**Comment by agaida** [comment]
if it is a easter-egg - it is not used in any documentation? So i could remove this from sources and the package without replacement - if so, i will do, the debian rules are strict in that case - and unfortunally with Lena the package would not fit for the main repository, it would render the whole package as non-free :)

**Comment by diemmarkus** [comment]
sorry for leaving the question open up until now... yes you can remove it for debian (or replace it by the attached picture)
![affen](https://cloud.githubusercontent.com/assets/4182443/10283344/815244e8-6b7f-11e5-81bc-9a37760e1d1d.jpg)

**Comment by agaida** [comment]
:D - gekauft.  Copyrights? // agaida geht sich mal schnell verstecken.

**Comment by diemmarkus** [comment]
Haben wir gemacht... Habs unter CC gestellt (ist in den Metadaten)

**Comment by agaida** [comment]
Danke
