### ISSUE TITLE
Config file in linux now under "~/.config/https:/nomacs.org/nomacs.conf"?

### ISSUE THREAD

**Issue by robschi** [nomacs/nomacs#281]
**Describe the bug**
Before  nomacs "3.12" the config file was located under "~/.config/nomacs/Image Lounge.conf", and the system wide config was stored under "/etc/xdg/nomacs/Image Lounge.conf" (https://github.com/nomacs/nomacs/issues/214).

Now the location of the config has changed to "~/.config/https:/nomacs.org/nomacs.conf"?
The sub folder "https:" does not look like sane to me, and where to store the system wide config now?

**Desktop (please complete the following information):**
 - OS: Debian Testing
 - DE: LXQt

**Comment by agaida** [comment]
@roboschi - thanks for spotting this - the reason is that i wanted to stuck with the "old" place but made a fault while patching. Should be fixed in Sid soon - so you had to wait some days until it hit testing.

@sfiel - it might be a good idea not to change file locations release based - esp. for configurations :D

**Comment by agaida** [comment]
bah, forget it - installation paths like  

    /usr/share/nomacs/Image Lounge/translations/
    /usr/share/nomacs/Image Lounge/themes/

could be considered as fugly, but ok, if they don't change anymore. So not to patch anything is a good idea - sorry for the noise. Please don't rename 'Image Lounge' to 'ImageLounge' or so :)

(/Me should really learn to read and write in the very near future)

Menno, ich hatte das alles nur noch verschlimmbessert, sorry.

**Comment by diemmarkus** [comment]
alles klar : )
so I'll leave it as is...
