### ISSUE TITLE
Add option to revert to previous anti-aliasing

### ISSUE THREAD

**Issue by AnotherDimension-Ex** [nomacs/nomacs#282]
Hi there,

Could you please add option to revert it to previous anti-aliasing.
The anti-aliasing in 3.12.1 it so worse than 3.8.0 and it's so slow, it makes my browsing experience so terrible and very slow, and keeps re-apply anti-aliasing when zooming and this is very annoying.

I'm looking for something fast when browsing.
And please don't tell me to disable the anti-aliasing, it will make the images worse than it should be.

Comparing with other image viewer.
Photos app (windows 10 default viewer) it applies anti-aliasing on time.
Nomacs re-apply anti-aliasing when zooming.
Is there's any way maybe nomacs could do the same.

_I was having much better browsing experience with v3.8.0._

![7](https://user-images.githubusercontent.com/34074375/48409230-4cfd4e80-e74c-11e8-86f2-30a53dea17df.gif)

**Comment by diemmarkus** [comment]
Hi,

I have drafted a fix that reduces the (visible) effects of the issue you are describing in ae01ab8e4762348a419420830a5e01e4ba2d0ce7.

however, we won't bring back the old anti-aliasing strategy, since it had clear (quality + performance) drawbacks compared to the new one.

best,
markus
