### ISSUE TITLE
Might be an issue with "show pixels if zoom level is above" option

### ISSUE THREAD

**Issue by AnotherDimension-Ex** [nomacs/nomacs#284]
Hi,

I'm not exactly sure what causes this issue, it could because the new anti-aliasing but.....
I think "show pixels if zoom level is above" option not working in 3.12.1 and I could be wrong.

This issue only if zoom > 100% (when zooming image).

I started having this issue with 3.12.1, and previous version 3.10.2 it was working without problems.
I always set "show pixels if zoom level is above" to 500%, and anti-aliasing enabled.

_Summary: when zoom > 100% the smooth pixel not working._

<br>

**Nomacs 3.12.1** (open image in new tab to see the full size)

![04182 v](https://user-images.githubusercontent.com/34074375/48646663-91ae1180-e9fa-11e8-9cb4-f5c46bf8cc92.jpg)

<br>

**Nomacs 3.10.2** (open image in new tab to see the full size)

![04183](https://user-images.githubusercontent.com/34074375/48646664-9246a800-e9fa-11e8-9701-e6a1b02d383f.png)

**Comment by diemmarkus** [comment]
yes, there is an issue with zooming > 100% which is already fixed: bbbd5faac51b18b778043735fcffdc7f426fa4e6

thanks for reporting!
