### ISSUE TITLE
basic markup

### ISSUE THREAD

**Issue by bjlockie** [nomacs/nomacs#286]
Can basic markup be added (eg. add circles, lines, text)?

**Comment by bjlockie** [comment]
Fount the Paint Plugin but it's Windows-only.
Is there a plan to so something for Linux?

**Comment by diemmarkus** [comment]
Hi,

the paint plugin is also available on Linux - which distribution/nomacs version are you using?

best,
markus

**Comment by bjlockie** [comment]
v3.10 of Nomacs.

I use Lubuntu-18.10

There is no plugin menu and 
https://www.nomacs.org/plugins/how-to-install-plugins/ says:

> Note: Plugins are currently only supported on Windows.
>
> Open the Plugin Manager via the menu Plugins -> Plugin Manager
>

**Comment by agaida** [comment]
Right. nomacs in debian and derivatives is built without plugins - we found them sub-par times ago.

**Comment by bjlockie** [comment]
Do you why this decision was made?

**Comment by agaida** [comment]
yes, i know it - i would likely have packaged them if there would be a way to build them separated. But this seems to be impossible. But the solution might be a ppa - just download the sources, mix them (following the build instructions) and upload it to lp - i guess will not spend time on it.

**Comment by agaida** [comment]
@diemmarkus - had to check it how to handle two tarballs and the resulting source. To be honest, had looked into the plugins  1 1/2 years ago and was not so impressed at all - had to look again. After the initial nomacs packaging i was in a bit of dilemma - the permanently changing libs :smile: - solved it that way that i moved them to a private place and put libs and binaries into one package. Not the most recommended way, but legit. Second problem ist the new tarball for the plugins - this yells for own package - but without dev libs and such things it will be hard - aka i has to learn a bit. As long you can promise that the combination of released nomacs and released plugins will build i'm fine i guess.

**Comment by bjlockie** [comment]
I guess I can download the source and compile it myself.
I wanted it to be official but I'd rather have the plugin.

**Comment by bjlockie** [comment]
The instructions for building the plugins are incomplete.
I did a git clone on nomacs-plugins in the ImageLounge directory and then renamed "nomacs-plugins" to just "plugins".

-- ----------------------------------------------------------------------------------
--  nomacs - Image Lounge 3.13  <https://nomacs.org>
-- 
--  nomacs will be compiled with OPENCV support .................. YES
--  nomacs will be compiled with LIBRAW support .................. YES
--  nomacs will be compiled with extended TIFF support ........... YES
--  nomacs will be compiled with QuaZip support .................. YES
--  nomacs will use system QuaZip ................................ NO
--  nomacs will use system QPSD .................................. NO
--  nomacs will be compiled with plugin support .................. YES
-- ----------------------------------------------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: linux/nomacs/ImageLounge
$ make
[  1%] Automatic MOC for target nomacsCore
[  1%] Built target nomacsCore_autogen
[  2%] Building CXX object CMakeFiles/nomacsCore.dir/src/DkGui/DkDialog.cpp.o
/storage/downloads/linux/nomacs/ImageLounge/src/DkGui/DkDialog.cpp:100:10: fatal error: quazip5/JlCompress.h: No such file or directory
 #include <quazip5/JlCompress.h>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/nomacsCore.dir/build.make:217: CMakeFiles/nomacsCore.dir/src/DkGui/DkDialog.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/nomacsCore.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

I did:
$ sudo apt-get install libquazip5-dev
and it compiled but won't link:
[ 66%] Linking CXX executable nomacs
/usr/bin/ld: libnomacsCore.so.3.13.0: undefined reference to `QuaZip::~QuaZip()'
/usr/bin/ld: libnomacsCore.so.3.13.0: undefined reference to `QuaZipFile::~QuaZipFile()'
/usr/bin/ld: libnomacsCore.so.3.13.0: undefined reference to `QuaZipFile::open(QFlags<QIODevice::OpenModeFlag>)'
/usr/bin/ld: libnomacsCore.so.3.13.0: undefined reference to `QuaZip::open(QuaZip::Mode, zlib_filefunc_def_s*)'
/usr/bin/ld: libnomacsCore.so.3.13.0: undefined reference to `QuaZipFile::QuaZipFile(QuaZip*, QObject*)'
/usr/bin/ld: libnomacsCore.so.3.13.0: undefined reference to `QuaZip::QuaZip(QString const&)'
/usr/bin/ld: libnomacsCore.so.3.13.0: undefined reference to `QuaZip::close()'
/usr/bin/ld: libnomacsCore.so.3.13.0: undefined reference to `QuaZipFile::close()'
/usr/bin/ld: libnomacsCore.so.3.13.0: undefined reference to `JlCompress::extractFile(QString, QString, QString)'
/usr/bin/ld: libnomacsCore.so.3.13.0: undefined reference to `QuaZipFile::getZipError() const'
/usr/bin/ld: libnomacsCore.so.3.13.0: undefined reference to `QuaZip::setCurrentFile(QString const&, QuaZip::CaseSensitivity)'
/usr/bin/ld: libnomacsCore.so.3.13.0: undefined reference to `JlCompress::getFileList(QString)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/nomacs.dir/build.make:111: nomacs] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/nomacs.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

Ideas?

**Comment by diemmarkus** [comment]
Hi,

our cmake defaults are not good since the last QuaZip update, sorry.
you can either specify, that you are using the system QuaZip:
````console
markus@ubuntu:~/nomacs/build$ cmake -DUSE_SYSTEM_QUAZIP=ON ../ImageLounge/
````
or disable QuaZip:
````console
markus@ubuntu:~/nomacs/build$ cmake -DENABLE_QUAZIP=OFF ../ImageLounge/
````

best,
markus

**Comment by diemmarkus** [comment]
> As long you can promise that the combination of released nomacs and released plugins will build i'm fine i guess
@agaida no problem - since 3.12 we draft a release in [nomacs-plugins](https://github.com/nomacs/nomacs-plugins/releases) too (that is compatible)

**Comment by agaida** [comment]
@diemmarkus - cool, good news

@bjlockie - if you try to recompile nomacs - just use the debian/ubuntu way to do things (should be read as: cmake/make/make install are not recommended, use devscripts and dh. It might be a little learning curve but **never ever** build and install things with c/m/m i - it will wreck apt and your system sooner or later - ok, tbh, sooner.

**Comment by agaida** [comment]
@bjlockie - the debian new maintainer guide is a good read about, to make it short:
```
uncomment the sources for apt, you will need them
apt update
apt install devscripts debhelper
apt source nomacs
apt build-dep nomacs
cd nomacs-$foo
change debian/source/format to 1.0
add the plugins sources to the plugin dir
change debian/rules configur to build the plugins
delete the downloaded tar balls - *.orig.tar.xz and *.debian.tar.xz

debuild
cd ..
apt install ./*deb
start nomacs
```
it might be helpful to create a new changelog entry with dch

**Comment by bjlockie** [comment]
> @bjlockie - if you try to recompile nomacs - just use the debian/ubuntu way to do things (should be read as: cmake/make/make install are not recommended, use devscripts and dh. It might be a little learning curve but **never ever** build and install things with c/m/m i - it will wreck apt and your system sooner or later - ok, tbh, sooner.

I was going to run nomacs out of my build directory but I will read up on the devscripts.

**Comment by bjlockie** [comment]
> markus@ubuntu:~/nomacs/build$ cmake -DENABLE_QUAZIP=OFF ../ImageLounge/

It compiles but the paint plugin only partially works.
I can draw on the image but I can't click on any of the buttons.
lockie.ca/lxqt/nomacs_paint.jpg
I can draw using the default (wide) brush.
Otherwise, nomacs seems to be working.

It might be related to this error I see on the console:
[WARNING] QObject::connect: No such slot nmc::DkNoMacsIpl::showToolBar(QToolBar*, bool)
[WARNING] QObject::connect:  (sender name:   'DkPaintViewPort')
[WARNING] QObject::connect:  (receiver name: 'DkNoMacs')

The description of the plugin on:
https://www.nomacs.org/plugins/
Only says:
>Paint Plugin2.2.0
>December 16, 2015
>description
>Adds simple paint functionality to nomacs
Do you know if it supposed to draw straight lines, circles, etc?
Maybe I need to learn Qt programming.

**Comment by diemmarkus** [comment]
Hi,

the plugins were not in sync with the current master (usually it's best to checkout the respective releases). I fixed the code to reflect the changes in cec0be635b43ad59fe05d3c5f6eb67053341c7c4. So if you now pull both, nomacs and nomacs-plugins - the plugins will work. 

> Do you know if it supposed to draw straight lines, circles, etc?

No - the Paint Plugin is designed for free hand drawings with the mouse:
![img-2018-11-26 13 00 27](https://user-images.githubusercontent.com/4182443/49012914-4377db80-f17b-11e8-9e50-adb596ab5f3d.png)

but I would love to see a simple mark-up plugin (I can support the development in case you want to create it)

best,
markus

**Comment by diemmarkus** [comment]
> No promises.
no problem : )

**Comment by bjlockie** [comment]
![image](https://user-images.githubusercontent.com/303873/50567781-fc02e300-0d16-11e9-9f67-001d12b4795d.png)
****
It does nothing but draw the menu.
