### ISSUE TITLE
why does git do this?

### ISSUE THREAD

**Issue by bjlockie** [nomacs/nomacs#287]
> From https://github.com/nomacs/nomacs-plugins
>    e5ece39..0803d3a  master     -> origin/master
> Updating e5ece39..0803d3a
> error: Your local changes to the following files would be overwritten by merge:
>         AffineTransformations/src/DkAffineTransformationsPlugin.json
>         FakeMiniaturesPlugin/src/DkFakeMiniaturesPlugin.json
>         PageExtractionPlugin/src/DkPageExtractionPlugin.json
>         PaintPlugin/src/DkPaintPlugin.json
> Please commit your changes or stash them before you merge.
> Aborting

I haven't changed any files so why does git think I did?

**Comment by diemmarkus** [comment]
Hi,

our post-build step updates the `DateModified` tags after each build. You can simply revert these files before pulling...

best,
markus
