### ISSUE TITLE
sync files with index number

### ISSUE THREAD

**Issue by diemmarkus** [nomacs/nomacs#289]
as suggested by [Samuel B](https://nomacs.org/nomacs-3-12/) we could parse the index of filenames (like we do in [naturalCompare](https://github.com/nomacs/nomacs/blob/759750b385a25304c0c18ea4f8d1682e58ccf000/ImageLounge/src/DkCore/DkUtils.cpp#L189)) to keep files in sync....

**Comment by scrubbbbs** [comment]
We use QFileSystemWatcher now which is a better solution.
