### ISSUE TITLE
copyright webp

### ISSUE THREAD

**Issue by agaida** [nomacs/nomacs#29]
Can you please include COPYING, PATENTS, AUTHORS into 3rdparty/libwebp - without the file headers would make no sense:
<pre>
// Use of this source code is governed by a BSD-style license
// that can be found in the COPYING file in the root of the source
// tree. An additional intellectual property rights grant can be found
// in the file PATENTS. All contributing project authors may
// be found in the AUTHORS file in the root of the source tree.
</pre>

**Comment by diemmarkus** [comment]
added - thank you!
