### ISSUE TITLE
Add .avif (AV1 Image File Format) support

### ISSUE THREAD

**Issue by EwoutH** [nomacs/nomacs#292]
The AV1 Image File Format (AVIF) is a new image format based on the AV1 video codec. It would be great if support for this format could be added.

The AVIF spec can be found here: https://aomediacodec.github.io/av1-avif/
Netflix published a bunch of test images: http://download.opencontent.netflix.com/?prefix=AV1/Chimera/AVIF/

**Comment by diemmarkus** [comment]
I'll have a look at it - thanks!

**Comment by EwoutH** [comment]
[libavif](https://github.com/joedrago/avif) tagged a new release, [0.1.3](https://github.com/joedrago/avif/releases/tag/v0.1.3). See [Colorist](https://github.com/joedrago/colorist) for an example [implementation](https://github.com/joedrago/colorist/blob/master/lib/src/format_avif.c).

**Comment by novomesk** [comment]
I just installed nomacs and I observed that it opens AVIF and AVIFS files.
I develop a Qt Image Plugin with AVIF support and I think that maybe nomacs loaded the *.AVIF files because it is a QT application.
![nomacs](https://user-images.githubusercontent.com/52529860/76639268-1e64d300-654e-11ea-8db0-a44a6f6ec135.png)

**Comment by diemmarkus** [comment]
> I develop a Qt Image Plugin with AVIF support and I think that maybe nomacs loaded the *.AVIF files because it is a QT application

for sure - nomacs uses any qt image plugins that are available on the system. is your image plugin open source? if yes, I will add it to the default installer on windows.

**Comment by novomesk** [comment]
Yes, my plug-in is free.
I am preparing a new improved version but it is not public yet.
So far you can see how the old version of my plug-in looks like, I shared sources here:
https://bugs.kde.org/show_bug.cgi?id=416941
The old version of my plug-in works with libavif 0.5.7 but doesn't work with 0.6.x (New version will work with 0.6.x).
I can notify you when the new version is ready.
You will need to prepare two libraries: [libaom](https://aomedia.googlesource.com/aom/) and [libavif](https://github.com/AOMediaCodec/libavif). cmake is needed in the configuration process. Libaom needs to be not very old, at least v1.0.0-errata1-avif.

**Comment by diemmarkus** [comment]
> I can notify you when the new version is ready.

yes please!

**Comment by novomesk** [comment]
The new version of my plug-in:
http://188.121.162.14/avif/qt_avif_image_plugin_2020-03-20.zip

**Comment by diemmarkus** [comment]
is it already ready to use? If so, I'll test it on my system...

**Comment by novomesk** [comment]
Yes, I believe it is ready. It works on Linux, I tried Gentoo and Ubuntu, other people used it on Arch. I haven't tried with Windows yet.
The plug-in itself is simple. Just to build libavif with recently new libaom.

**Comment by novomesk** [comment]
@diemmarkus 
Did you have success to build my plug-in on Windows?
In the past I used only MSYS2,
but today I tried to build libaom and libavif using Visual Studio 2019 and when these 2 libs were ready, Qt Creator built **qavif.dll** (my plug-in).
I plan to create Windows instructions in the near future anyway.

**Comment by diemmarkus** [comment]
no : )
-> I stopped when I saw that there are a few additional dependencies. I am currently making things ready for appveyor (#488). I will add avif there if time permits (of course you are very welcome to support me in this process : )

**Comment by EwoutH** [comment]
@diemmarkus I contributed to the libavif [AppVeyor configuration](https://github.com/AOMediaCodec/libavif/blob/master/appveyor.yml). Please let me know if you need any help building libavif!

**Comment by diemmarkus** [comment]
@EwoutH I am pretty sure you can help here : )
Since I am new to AppVeyor, I have a few starter questions:
what is the best way for me to make use of compiled libavif packages? 
- should I download the latest static lib zip in my appveyor script (and hope compilers did not change)?
- or is there a mechanism that allows me to use your appveyor config?

**Comment by novomesk** [comment]
Today I tried AppVeyor, I reused some portions of the configuration made by EwoutH.
https://ci.appveyor.com/project/novomesk/qt-avif-image-plugin
Result is qavif.dll
I combined it with your files from nomacs-portable.zip and I was able to open AVIF files.

**Comment by novomesk** [comment]
Marcus,
can you add something like this into DkSettings.cpp please?
`if (qtFormats.contains("avif"))     app_p.saveFilters.append("AV1 Image File Format (*.avif)");`
so we can save AVIF via nomacs too.

**Comment by diemmarkus** [comment]
> can you add something like this into DkSettings.cpp please?

sure.... if like, you can added & create a pull request (then it's your contribution). does avif save need parameters?

**Comment by diemmarkus** [comment]
I set up a [branch](https://github.com/nomacs/nomacs/tree/292-save-avif) to add these features. There you can change compression values in [DkSaveDialog.cpp#106](https://github.com/nomacs/nomacs/blob/411bc5bf773d225e323014bf13af5a569b4889bd/ImageLounge/src/DkCore/DkSaveDialog.cpp#L106) and apply them in the `init()` function (see [line 174](https://github.com/nomacs/nomacs/blob/411bc5bf773d225e323014bf13af5a569b4889bd/ImageLounge/src/DkCore/DkSaveDialog.cpp#L106)).

**Comment by novomesk** [comment]
OK, I started to work on that. I will let you know when I finish.
![nomacs_avif_settings](https://user-images.githubusercontent.com/52529860/84682164-8bb14700-af35-11ea-9cf5-045b2bb8169c.png)

**Comment by diemmarkus** [comment]
@novomesk there is one last wish (as always : ): can you attach the appveyor's artifact to the github release? this way I can use the latest stable in nomacs rather than the latest nightly.

**Comment by novomesk** [comment]
I will do it for future releases.
I would like to do it after next release of libavif. There were some breaking changes/big refactor/important improvements. So I wait for the right time. I hope it is a matter of few more days.

**Comment by diemmarkus** [comment]
I just realized, that [libheif](https://github.com/strukturag/libheif/releases) now also supports avif. since I have the feeling, that you guys know much more about the codec than I do: is there any advantage of choosing libavif over libheif for loading? from my point of view: libheif is LGPL, libavif has a license which I don't know (but should do for us).

**Comment by novomesk** [comment]
libavif and libaom use the [BSD 2-Clause License](https://aomedia.org/license/software-license/) which says, "as is", "no warranty", "no liability" - it is even more free than LGPL.
new libheif (1.7.0) also uses libaom to encode/decode AV1-codec compressed data like libavif.
I started to use libheif recently and I have to say that **libavif is best for AVIF so far**.
When I tested libheif 1.7.0 I encontered few issues and reported them (you can check what I reported there). Some of them are resolved already. There are still some things to verify and to implement in libheif. I keep following the progress in libheif and to provide feedback there.

**Comment by diemmarkus** [comment]
thanks for the fast feedback. updating to libheif 1.7.0 just broke everything on my side : )

**Comment by novomesk** [comment]
I attached DLL to the
https://github.com/novomesk/qt-avif-image-plugin/releases/tag/v0.2.0
Will you merge the [292-save-avif](https://github.com/nomacs/nomacs/tree/292-save-avif) branch later? Just curious.

**Comment by novomesk** [comment]
I observed that in order to play AVIFS animation, it is enough to do modify DkImageContainer.cpp
Original in `DkImageContainer::hasMovie()`:
`return newSuffix.contains(QRegExp("(gif|mng|webp)", Qt::CaseInsensitive)) != 0;`
AVIFS added:
`return newSuffix.contains(QRegExp("(avifs|gif|mng|webp)", Qt::CaseInsensitive)) != 0;`
Can you add it?

**Comment by diemmarkus** [comment]
> Will you merge the [292-save-avif](https://github.com/nomacs/nomacs/tree/292-save-avif) branch later? Just curious.

292-save-avif is on top of appveyor that currently causes troubles with the updated libheif : ) -> I will merge it after appveyor is merged

> Can you add it?

sure
