### ISSUE TITLE
Default icon color makes toolbar icons invisible

### ISSUE THREAD

**Issue by l2dy** [nomacs/nomacs#293]
**Describe the bug**
After first start or "Reset All Settings", toolbar icons are invisible as shown in the first screenshot, and it seems that there are no color presets available. However, after resetting the three colors individually, the icon color was made darker and became visible as shown in the second screenshot.

**To Reproduce**
1. "Reset All Settings"
2. Restart nomacs
3. See invisible icons

**Expected behavior**
1. Toolbar icons should be clearly visible.
2. There should be color presets available in Color Settings.

**Screenshots**
<img width="1392" alt="screen shot reset-all" src="https://user-images.githubusercontent.com/14329097/50380560-ea5c7400-0662-11e9-9472-06eea68bd400.png">
<img width="1392" alt="screen shot reset-colors" src="https://user-images.githubusercontent.com/14329097/50380567-fcd6ad80-0662-11e9-93de-1c3bc39f9b79.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser ?
 - Version 99fc9ac445988a41036635edf0d2a9c2dab6a41c

**Additional context**
I'm building nomacs with MacPorts. Nomacs 3.10.2 also has no color presets in Color Settings, but its toolbar defaults to the light theme and icons are visible. Since Nomacs 3.12 the toolbar defaults to dark theme with invisible icons.

**Comment by diemmarkus** [comment]
thanks for reporting. this is possibly an issue with our CMake. Can you check if you find a line like this (when starting nomacs):
````cmd
[INFO] theme loaded from "C:/coding/nomacs/build2017-x64/Debug/themes/Light-Theme.css"
````
best,
markus

**Comment by l2dy** [comment]
Hi, here's the console log when starting nomacs 99fc9ac445988a41036635edf0d2a9c2dab6a41c.

```
[INFO] Hi there
[INFO] plugins dir set to:  "/Applications/MacPorts/Nomacs.app/Contents/lib/nomacs-plugins"
[INFO] local client created in:  26 ms
[INFO] init...
[INFO] could not load theme from "/Applications/MacPorts/Nomacs.app/Contents/Resources/themes/Light-Theme.css"
[INFO] CSS loaded from:  ":/nomacs/stylesheet.css"
[WARNING] QObject::startTimer: Timers cannot have negative intervals
[WARNING] QObject::startTimer: Timers cannot have negative intervals
[INFO] Initialization takes:  403 ms
[INFO] init...
QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once QUrl("http://nomacs.org/version/version_mac_stable")
```

**Comment by l2dy** [comment]
This seems to be a MacPorts-specific issue, thanks for your help.

**Comment by l2dy** [comment]
I updated nomacs to 3.12 for MacPorts, copying theme files to `Resources` in https://github.com/macports/macports-ports/commit/a4478fe74b10f58e01746b701aeab7e3d0d8031b.

The port manages the `Resources` directory because nomacs's CMake didn't handle these.
