### ISSUE TITLE
can this do or not do this, custom/manual sorting

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [nomacs/nomacs#295]
move images & folders where you actually want them, and keep memory/state of where they were moved? 

custom/manual sorting 

how to do?

any easy way to find the info of how to do?

**Comment by diemmarkus** [comment]
nomacs features different sort options (i.e. date created, random) but you can't sort images manually...

**Comment by SolveAllProblemsRightNow** [comment]
............................

maybe this software/app would be good for something else one day....
