### ISSUE TITLE
can this make screenshots?

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [nomacs/nomacs#296]
a specific section of a webpage for example

 

or drawing a custom shape to screenshot?
 

if so how?

 

if it cant, what is the easiest software to use for this?

**Comment by diemmarkus** [comment]
Hi,

you can take a screenshot using your OS (typically it's the `Print` Key or `ALT+Print` to grab a specific window). Then, you can paste the screenshot to nomacs with `CTRL+V`. nomacs has a crop feature to extract specific sections of the screenshot and a paint plugin to highlight areas.

best,
markus

**Comment by SolveAllProblemsRightNow** [comment]
.................why do we need 2 diff steps to do something simple when the software/app itself shoud be able to do basic things...
