### ISSUE TITLE
Colour rendering is too cool.

### ISSUE THREAD

**Issue by GlenAndersonNZ** [nomacs/nomacs#298]
nomacs is rendering images in a cool tone. This now means that it can no longer be used to view photographs for proofing as the colour is now incorrect.
The image being shown below is being rendered from raw, with no editng applied at all (i.e. straight from camera)

nomacs rendering:
![image](https://user-images.githubusercontent.com/9869539/50536865-ecbc5200-0bbd-11e9-9366-7fcf3ee70e6e.png)

correct rendering:
![image](https://user-images.githubusercontent.com/9869539/50536867-01004f00-0bbe-11e9-9cdd-03e75e97b990.png)

**Comment by diemmarkus** [comment]
Hi,

you are correct, the RAW feature of nomacs should be seen as sneak preview because it is hard to correctly load all proprietary RAWs out there. However, if you load the embedded jpgs (see Settings) - colors will be displayed correctly (and faster : )

best,
markus

**Comment by diemmarkus** [comment]
Hi Glen,

if you load the embedded jpg, nomacs typically displays the colors the way your camera manufacturer intended them to be. Still I have also noticed a different (better) rendering of the same RAW when loaded using Photoshop. If you load the jpg using Photoshop you will also notice that it's not as good as the RAW rendering. Considering that this is Photoshop's core business - I think we can't compete here, sorry : )
_ICC profiles:_ our engine unfortunately does not support them - so we need to wait until Qt comes up with a solution here (and it doesn't [look good](https://bugreports.qt.io/browse/QTBUG-6582)).

best,
markus
