### ISSUE TITLE
Die Paketabhängigkeiten können nicht aufgelöst werden

### ISSUE THREAD

**Issue by commander-keen** [nomacs/nomacs#299]
> We also mantain our own launchpad repository, where the newest stable version can be found. If you want to use it:
> First you have to add “ppa:nomacs/stable” to your repositories

There are only "Addons" visible which require NoMacs 3.6, but the repository of Linux Mint 19 Tara currently has NoMacs 3.8, so installation fails:
```
nomacs-plugins-affinetransformation: Depends: nomacs (= 3.6.0-1~97~ubuntu18.04.1) aber 3.8.0+dfsg-4 soll installiert werden
                                     Depends: libgcc1 (>= 1:3.4) aber 1:8.2.0-1ubuntu2~18.04 soll installiert werden
                                     Depends: libqt5core5a (>= 5.9.0~beta) aber 5.9.5+dfsg-0ubuntu1 soll installiert werden
                                     Depends: libqt5gui5 (>= 5.2.0) aber 5.9.5+dfsg-0ubuntu1 soll installiert werden
                                     Depends: libqt5widgets5 (>= 5.0.2) aber 5.9.5+dfsg-0ubuntu1 soll installiert werden
                                     Depends: libstdc++6 (>= 4.1.1) aber 8.2.0-1ubuntu2~18.04 soll installiert werden
nomacs-plugins-paint: Depends: nomacs (= 3.6.0-1~97~ubuntu18.04.1) aber 3.8.0+dfsg-4 soll installiert werden
                      Depends: libgcc1 (>= 1:3.4) aber 1:8.2.0-1ubuntu2~18.04 soll installiert werden
                      Depends: libqt5core5a (>= 5.9.0~beta) aber 5.9.5+dfsg-0ubuntu1 soll installiert werden
                      Depends: libqt5gui5 (>= 5.2.0) aber 5.9.5+dfsg-0ubuntu1 soll installiert werden
                      Depends: libqt5widgets5 (>= 5.0.2) aber 5.9.5+dfsg-0ubuntu1 soll installiert werden
                      Depends: libstdc++6 (>= 4.1.1) aber 8.2.0-1ubuntu2~18.04 soll installiert werden

```

**Comment by agaida** [comment]
The solution is dead simple, use current sources

**Comment by commander-keen** [comment]
Shouldn't the PPA provide a recent Nomacs and its corresponding AddOns for users who don't compile software themselves? (or do you mean that there's a current PPA elsewhere?)

**Comment by agaida** [comment]
https://launchpad.net/ubuntu/+source/nomacs
https://tracker.debian.org/pkg/nomacs

Maybe one should change the distribution or learn a bit about - it might be that ppa's (personal package archives) are up to date, sometimes they are not. There might be several reasons, why they appear not to be maintained.

**Comment by commander-keen** [comment]
Is it incorrect understanding that the PPA is maintained by the developers of Nomacs? (then I will close this report)
According to your links I would expect Nomacs 3.8 and addons to be provided via PPA für Ubuntu 18.04 based Mint 19. Seeing 3.6 makes no sense to me without further clarification.

**Comment by commander-keen** [comment]
Is it incorrect understanding that the PPA is maintained by the developers of Nomacs? (then I will close this report)
According to your links I would expect at least Nomacs 3.8 and addons to be provided via PPA für Ubuntu 18.04 based Mint 19. Seeing 3.6 makes no sense to me without further clarification.

**Comment by agaida** [comment]
You should see this different - there was times when nomacs was not in the official repositories - so a ppa was the only chance to provide software built for different versions of ubuntu. It still is, with a big but: In the the very most cases it make no sense to provide bleeding edge software to a LTS version and maintaining a ppa cost developer time.

**Comment by commander-keen** [comment]
Hum, okay.
From my perspective it has been the other way around: Using a SW via PPA offers a possibility to stay updated on a software where the OS doesn't offer more recent versions.

**Comment by diemmarkus** [comment]
Hi,
@agaida is right, we discontinued our ppa since there is an official one. We have now removed it to prevent future confusions.
best,
Markus
