### ISSUE TITLE
force close when saving batch processing profile

### ISSUE THREAD

**Issue by commander-keen** [nomacs/nomacs#300]
**Describe the bug**
Error: XMP Toolkit error 203: Duplicate property or field node
Warning: Failed to decode XMP metadata.
[INFO] batch profile written to:  "/home/user/.local/share/nomacs/Profiles/Web640.pnm"
Speicherzugriffsfehler (Speicherabzug geschrieben)

**To Reproduce**
1. Open Tools => Batch Processing
2. Set Transform to Long Side 640px and shrink only
3. Create New Profile (use new name or overwrite existing one) 
4. See error, NoMacs closes

**Expected behavior**
no crash/closing on save

**Desktop (please complete the following information):**
 - OS: Linux Mint 
 - Version 19 Tara
 - "Latest" NoMacs 3.8 from Repository

**Comment by commander-keen** [comment]
Saving the profile leads to an error related to images, that surprises me.  Is there image-specific data in the profile after setting resize options as stated above?
I tried to save a profile now without selecting a source image, the force close also happens then.

I tried to fetch a later version via PPA, but wasn't successful: https://github.com/nomacs/nomacs/issues/299
Installing the dev packages according to the readme to try a compile on my own require more than 600 MB of download for me, which I cannot afford these days.

**Comment by diemmarkus** [comment]
Hi,

I tried reproducing the issue with nomacs 3.8 & with the current version without luck... you could try to use the latest [snap](https://snapcraft.io/nomacs/releases) - note that the snaps are not stable though...

best,
markus

**Comment by commander-keen** [comment]
I suceeded installing snapd package and the Nomacs snap (3.7.11).

It looks like 1995:

![nomacssnap](https://user-images.githubusercontent.com/179097/51807151-a4a75280-2283-11e9-8333-b50ecbd57c1f.png)


and throws several errors/warnings:

> ** (nomacs:4718): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-eZdKGdTiFu: Permission denied
Qt: Session management error: None of the authentication protocols specified are supported
I could not find the default settings file:  "/snap/nomacs/105/bin/default.ini"
defaults loaded from "/snap/nomacs/105/bin/default.ini"
[INFO] Hi there
[INFO] plugins dir set to:  "/snap/nomacs/105/lib/nomacs-plugins"
[INFO] theme loaded from "/snap/nomacs/105/bin/themes/Light Theme.css"
[INFO] CSS loaded from:  ":/nomacs/stylesheet.css"
[INFO] local client created in:  25 ms
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: MESA-LOADER: failed to retrieve device information
[WARNING] QNetworkManagerInterface::QNetworkManagerInterface(QObject*) propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.77\" (uid=1000 pid=4718 comm=\"nomacs \" label=\"snap.nomacs.nomacs (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=776 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
[WARNING] QNetworkManagerInterface::QNetworkManagerInterface(QObject*) nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.77\" (uid=1000 pid=4718 comm=\"nomacs \" label=\"snap.nomacs.nomacs (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=776 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
[WARNING] "Object path cannot be empty"
[WARNING] QObject::connect: No such slot nmc::DkNoMacsIpl::restart()
[WARNING] QObject::connect:  (receiver name: 'DkNoMacs')
[INFO] Initialization takes:  7 sec
[INFO] "/snap/nomacs/105/lib/nomacs-plugins/libaffineTransformPlugin.so.3.11.0" loaded in 1 ms
[INFO] "/snap/nomacs/105/lib/nomacs-plugins/libfakeMiniaturesPlugin.so.3.11.0" loaded in 0 ms
[INFO] "/snap/nomacs/105/lib/nomacs-plugins/libpageExtractionPlugin.so.3.11.0" loaded in 35 ms
[INFO] "/snap/nomacs/105/lib/nomacs-plugins/libpaintPlugin.so.3.11.0" loaded in 0 ms
[INFO] 4 plugins loaded in 59 ms
[INFO] no profiles found in "/home/martin/snap/nomacs/105/.local/share/nomacs/Image Lounge/Profiles"
[INFO] batch profile written to:  "/home/martin/snap/nomacs/105/.local/share/nomacs/Image Lounge/Profiles/Web640.pnm"
[INFO] settings loaded with 0 warnings
[INFO] batch profile written to:  "/home/martin/snap/nomacs/105/.local/share/nomacs/Image Lounge/Profiles/Profile 1.pnm"
[INFO] settings loaded with 0 warnings


but it doesn't crash on saving a profile.

**Comment by diemmarkus** [comment]
ok - thanks for testing. the issues you name are the reason why we do not officially promote the snaps. I think we could fix a lot of issues using `confinement: classic`. A possible fix for the theming could be found [here](https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235).

**Comment by diemmarkus** [comment]
snap will be discontinued in favor of [flathub](https://flathub.org/apps/details/org.nomacs.ImageLounge) ...
