### ISSUE TITLE
Set Date Time as Last Modified Meta

### ISSUE THREAD

**Issue by e58** [nomacs/nomacs#304]
**Is your feature request related to a problem? Please describe.**
Recently I've upgraded my phone's external storage wreaking havoc to the date the images were taken.
Windows 10 no longer has the **Date Picture Taken** column and the only way I could view this info is by using nomacs. Each photo and video's **Date Modified** column has been set to the date when they were moved.

**Describe the solution you'd like**
I can't edit
`Metadata Info > File > Date > Last Modified`
Is there a way to change it to the value of
`Metadata Info > Exif > Image > Date Time`

Can I do this in bulk without having to name them one by one if ever such feature exists?

**Comment by diemmarkus** [comment]
Hi,

the File > Date is set by the OS - I don't know of a straight forward way to change this, sorry.

best,
markus
