### ISSUE TITLE
Not possible to go back to thumbnail wall

### ISSUE THREAD

**Issue by gerroon** [nomacs/nomacs#306]
Hi

I am using 3.12 on Debian buster.

Open a folder

Opens it in thumbnail wall (at least I call ti that way)

Double click on an image

It opens the image and shows the thumbnails at the top.

From that view it seems not possible to go back to the thumbnail wall again.

it would be nice if there is an easy way to switch bakc views.

thanks

**Comment by Jzarecta** [comment]
How can I get back to the Thumbnail wall?

**Comment by diemmarkus** [comment]
you can use `Panels > Thumbnail Preview` or `SHIFT + T`
