### ISSUE TITLE
0.00 second slideshow transition by default (no transition animation by default)

### ISSUE THREAD

**Issue by AlexDaniel** [nomacs/nomacs#307]
In fullscreen mode, switching to another image (with Left/Right keys or `<`/`>` buttons) starts a “Swipe” animation. This feature can be disabled like this:

![image](https://user-images.githubusercontent.com/5507503/51574195-79081f00-1eb5-11e9-8896-013f28025638.png)

I struggle to understand why would somebody want the animation by default. I find it annoying and nauseating. I suggest having it turned off by default.

**Comment by diemmarkus** [comment]
hi,

we won't change defaults (other users like it) sorry... 
btw. you just need to choose appear (you don't need to set it to 0.00 sec)

best,
markus

**Comment by SirGawain99** [comment]
> This feature can be disabled like this...

Thank you, AlexDaniel! I spite of being the closest alternative to IrfanView via wine on Linux, this swipe-in transition was very nearly a deal breaker. When flipping quickly through images, the slide/swipe effect wastes time, exhausts the eyes, and quickly leaves the viewer.

**Comment by AlexDaniel** [comment]
Exactly. :) The animation itself is really shitty too, it's just a linear swipe without any dynamic curves.

**Comment by Anangaya** [comment]
I nearly uninstalled this right after installing because it wasn't obvious how to disable the image transition. I had to search for github issues to find this.

**Comment by scrubbbbs** [comment]
Animations disabled by default in the current beta version
