### ISSUE TITLE
Auto Crop of Common Color Around an Image

### ISSUE THREAD

**Issue by asjones987** [nomacs/nomacs#309]
A nice open source screenshot tool I use called Greenshot https://getgreenshot.org/help/ has a really need feature called Auto Crop I think would be good to addition to Nomacs. If there is a solid border (white, red, green, etc) it sets a crop window around the image up to the change. This is nice to get rid of extra white space around an image etc.

I have found myself loading images into Greenshot for that initial clean crop. The crop is "cleaner" as it is done programmatically and not by hand and trying to get it just "right"

As described in their help file:
Auto-Crop: If you need to crop a border of solid background color from your screenshot,
simply choose Auto-Crop from the Edit menu and Greenshot will automatically
select the area for cropping. 

thanks

Alan

**Comment by diemmarkus** [comment]
we will consider this feature - thanks!

**Comment by diemmarkus** [comment]
suggestions for new cropping features are now collected in #345
