### ISSUE TITLE
Can't get make files

### ISSUE THREAD

**Issue by nihelmasell** [nomacs/nomacs#310]
**Describe the bug**
Cant build make file

**To Reproduce**
1. brew install qt5 exiv2 opencv libraw quazip cmake pkg-config
2. git clone https://github.com/nomacs/nomacs.git
3. cd nomacs
4. mkdir build
5. cd build
6. Qt5_DIR=/usr/local/opt/qt5/ cmake -DQT_QMAKE_EXECUTABLE=/usr/local/opt/qt5/bin ../ImageLounge/.

**Expected behavior**
Get makefile, as said in instructions for MACos

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version Mojave

**Additional context**
Output 

$ Qt5_DIR=/usr/local/opt/qt5/ cmake -DQT_QMAKE_EXECUTABLE=/usr/local/opt/qt5/bin ../ImageLounge/.
-- QuaZip disabled because you are using a mac
-- QMake found: /usr/local/opt/qt5/bin
-- A release build (non-debug). Debugging outputs are silently ignored.
-- exiv2 version by pkg-config: 0.25
-- exiv2 contains exiv2.hpp, using it
-- Checking for module 'opencv>=2.1.0'
--   No package 'opencv' found
CMake Error at cmake/Mac.cmake:43 (find_package):
  Could not find a configuration file for package "OpenCV" that is compatible
  with requested version "2.1.0".

  The following configuration files were considered but not accepted:

    /usr/local/lib/cmake/opencv4/OpenCVConfig.cmake, version: 4.0.1

Call Stack (most recent call first):
  CMakeLists.txt:115 (include)

-- Configuring incomplete, errors occurred!
See also "/Users/jonicoeneas/nomacs/build/CMakeFiles/CMakeOutput.log".

**Comment by diemmarkus** [comment]
on mac we are building nomacs using:
````bash
brew install -v opencv3 --without-eigen --without-opencl --without-openexr --without-python --without-numpy
brew ln opencv3 --force
````
the second line is currently needed because of an [issue](https://github.com/Homebrew/homebrew-science/issues/2466) with homebrew/opencv

please let me know if that fixes your issues...

best,
markus

**Comment by david-leon** [comment]
The same problem encountered here.  @diemmarkus It doesn't fix the issue, for the command
```
brew install -v opencv3 --without-eigen --without-opencl --without-openexr --without-python --without-numpy
```
It prompted `Error: invalid option: --without-eigen`

**Comment by diemmarkus** [comment]
hi,
I would recommend to use the commands from our [readme](https://github.com/nomacs/nomacs#build-nomacs-macos). please let me know if this works on your machine.

best,
markus

**Comment by david-leon** [comment]
@diemmarkus I think there's a misunderstanding. I followed the commands from the readme at the first place and encountered the exact same problem with @nihelmasell. It seems opencv 2.1.0 is required but the brew installed opencv 4.0 instead.

**Comment by diemmarkus** [comment]
ah - get it, thx!
-> I have now removed the requirements in d182fce4bcd9a25bd15e3de065ca67849a32458c. Please let me know if it works now. If it still does not work with OpenCV 4, you can try this (basic OpenCV 3 without additional options):
````shell
brew install -v opencv3
````

**Comment by david-leon** [comment]
It works, great! Now I can continue to use nomacs on Mac, my favorite image viewer.
There's still one more problem (not related to this topic thread though): I set nomacs as default app for opening image files, but every time I double clicked the file, only a blank nomacs window opened, the image is not loaded

**Comment by diemmarkus** [comment]
for debugging: you could click `Panels > Show Log`, close nomacs, then double-click an image again. If you then paste the content of the `Console` here, we could try to analyze the issue (unfortunately we cannot debug nomacs on mac os here). But please open a new issue - since it is not related to this one.
