### ISSUE TITLE
Nomacs exit after startup or hovering mouse at menu

### ISSUE THREAD

**Issue by tempTestAcc2** [nomacs/nomacs#312]
**SCENARIO 1:**
**Describe the bug**
Nomacs just exit without any other activity.
First it ended right after start (the main window of nomacs blinked for a half of second).
I run nomacs from terminal to get error and it was something like this: (first line is from my mind because I cannot reproduce scenario 1 again and second line is translated from my language): 
```
QPointer::begin return 0 type 2
error in floating point calculations (memory dump)
```

**To Reproduce**
1. Install nomacs
2. Open nomacs from icon, either terminal

**SCENARIO 2:**
**Describe the bug**
Then I play with resolution (setting resolution to lower few times). After that nomacs opened. After that playing with resolution even when I back to 4k resolution nomacs opened! But when I hover mouse or click at some of the top menu (File, Panels, Synchronisation, Addons) the list expanded and after second nomacs crashed again. There is no crash when I click or hover at rest of the menu (like View for example).
The error in terminal:
`error in floating point calculations (memory dump)`

**To Reproduce**
1. Install nomacs
2. Open nomacs from icon, either terminal
3. Hover mouse or click at one's of top menu (File, Panels, Synchronisation, Addons) and wait 1 seconds (repeat this few times if not happened after first time).

**Expected behavior**
No crash.

**Desktop (please complete the following information):**
 - Linux Manjaro 18.0.2 64 bit with Deepin environment (this can be specific)
 - 4k (3840x2160 pixels) monitor

**Additional context**
I have exactly same environment (same version of Manjaro Linux) at laptop with low resolution, 15 inches screen and is working ok. 
So I guess 4k is a matter. 
I have tested almost 10 image viewers for Linux recently and nomacs seems to be the best for me. I would love to use it. Hope this can be quick fix or I can get workaround for 4k.

EDIT: At the end I figure out the problem doesn't occur at all when I disable scaling of desktop at the system configuration. This is problematic because in order to change scale you need to relog user in system and menu is too small without scaling 150%.

**Comment by diemmarkus** [comment]
Hi,

this is bad - and pretty hard to debug (reproduce) for us. Since the menus are created using Qt, I am not sure if we can fix it at all. If you find the time (and want to invest it to further investigate this issue) - you could build nomacs on your system & debug it. If we know the reason for the crashes, we can probably fix them...

best,
markus
