### ISSUE TITLE
Add "Save Copy" menu option or "[original]" file type under Save As

### ISSUE THREAD

**Issue by naturalspringwater** [nomacs/nomacs#314]
Hello,

I use nomacs as main image viewer on all my systems. Frequently I wish to save an original copy of an image - in its original format, completely unchanged - into a different folder while browsing images from nomacs.

This is quite simply a request for a simple 1:1 file copy function, analogous to the delete function. It could be a new menu item (fast & efficient access) or be listed as "Original" under file types in the Save As dialog (to save space in File menu? I like this less personally, it is slower access).

I find in the current behavior, if I use Save As in nomacs with a PNG, it seems to preserve the original file, but with JPGs it always asks for a compression so I could not figure out how to save a copy of the JPG without modifying the file in some way.

Example of this feature can be found in the Ristretto Image Viewer (xfce) under File -> Save copy... it is the (one) feature of Ristretto I took for granted.

_Note:_ if it already exists in some form, I have simply missed it and if you could point to it that would be great.

Thank you

**Comment by diemmarkus** [comment]
Hi,

thanks! This feature does not exist yet - but I like the idea. I guess `File > Save copy...` would be the best option.

best,
markus
