### ISSUE TITLE
Snap crop to edge of image

### ISSUE THREAD

**Issue by mica** [nomacs/nomacs#315]
When dragging the crop boundary beyond the edge of an image, instead of stopping there (as most editors do), it continues on, adding whitespace to the resulting image. 

Snapping to the edge should be the default behaviour, with maybe a key modifier for going beyond.

**Comment by diemmarkus** [comment]
cropping snaps to the original image edges - which nomacs version are you using?

**Comment by Mintonne** [comment]
Same issue here

![image](https://user-images.githubusercontent.com/39894801/59165855-ecd85a80-8b2a-11e9-8786-bf4d14b78e69.png)

nomacs version 3.12.1.4206 [x64]

**Comment by diemmarkus** [comment]
@Mintonne: cool sample image : ) 
To clarify: cropping beyond the image border is a feature. If you move the crop rectangle close to the original image edges, nomacs will snap to them. Holding CTRL while moving the rectangle will disable snapping.

**Comment by diemmarkus** [comment]
I have created a new issue: #345 - you can add suggestions there...
