### ISSUE TITLE
Start in thumbail preview when directory passed as argument

### ISSUE THREAD

**Issue by kovidgoyal** [nomacs/nomacs#32]
It would be nice if nomacs would start in the thumbnail preview when passed a directory as an argument on the command line. Saves having to press Shift+T every time on startup.

If you dont want that to be the default gehavior, then an option to turn it on would work, either as a command line switch or a preference in settings.

**Comment by diemmarkus** [comment]
I like this idea - I added it for the 3.0 release

**Comment by kovidgoyal** [comment]
Thanks :)
