### ISSUE TITLE
Krita (.kra) support

### ISSUE THREAD

**Issue by ErebosGR** [nomacs/nomacs#321]
Is it possible to support preview of Krita project files (.kra)?

> Krita is a free and open source digital painting application. It is for artists who want to create professional work from start to end. Krita is used by comic book artists, illustrators, concept artists, matte and texture painters and in the digital VFX industry.
>https://krita.org/
>https://phabricator.kde.org/source/krita/

From Krita devs:
>The KRA file is a ZIP format with a PNG inside on the top level named 'mergedimage.png'. If they can get that out, they can preview the image.

**Comment by diemmarkus** [comment]
Hi,

you can already load Krita files if you rename the files to zip (i.e. `sample.kra` -> `sample.zip`) and then load it with nomacs.

best,
markus
