### ISSUE TITLE
svg renders with black instead of white background

### ISSUE THREAD

**Issue by ke352802081770314** [nomacs/nomacs#322]
**Describe the bug**
svg renders with black instead of white background

**To Reproduce**
1. download https://www.abs38.de/files/maps/ABS_38_IA/img/map_01.svg
2. open the file in Nomacs
3. observe that due to black background the image is mostly unreadable

**Expected behavior**
I expected it to be rendered on white background, like in Firefox

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.2, LXDE desktop
 - Version nomacs 3.8 OpenCV 3.2.0 Qt 5.9.3
retry with nomacs_3.10.2+dfsg-1_amd64.deb built for Ubuntu cosmic: same result.
(sorry, installing 3.12 for disco was not possible due to dependencies)

**Additional context**
the svg file passes https://validator.w3.org without errors. As shown b y the URL, I am only viewing it, I have no involvement in its creation. Source says 
Note that when opening with eog, checkered background is shown indicating that the file likely contains transparent background.

Thank you in advance for looking into it.

**Comment by diemmarkus** [comment]
thanks!
remark for me:
the svg contains definitions that miss `fill="none"`:
```svg
	<defs>
		<rect id="SVGID_1_" width="1280" height="570"/>
	</defs>
```
this would work:
```svg
	<defs>
		<rect id="SVGID_1_" width="1280" height="570" fill="none"/>
	</defs>
```
