### ISSUE TITLE
Can't find a way to prevent thumbnail toolbar from showing history

### ISSUE THREAD

**Issue by Meteor0id** [nomacs/nomacs#324]
**Describe the bug**
I rather not have the thumbnail toolbar show previously opened files, I only wish to see the currently opened files.

**To Reproduce**
1. in option disable "log recent files" and set History size yo 0 MB.
2. open some files and close the app
3. open the app again
4. enable the thumbnail toolbar

**Expected behavior**
After closing the app the app has no recollection of previously opened files, and thus can't show them anywhere.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1803

**Additional comment**
Nomacs is one of the least intuitive apps on Windows these days. This project needs a gui redesign if it ought to be understandable.

**Comment by diemmarkus** [comment]
thanks for reporting

**Comment by diemmarkus** [comment]
I tested this again: if you disable `log recent files` & click the `X` in the right corner of recent folders, the history is gone...
