### ISSUE TITLE
Snap segfault

### ISSUE THREAD

**Issue by revyh** [nomacs/nomacs#325]
I have the `Segmentation fault (core dumped)` error when I just try to run nomacs. I use v3.11.7 from `beta` channel. I'm on xubuntu 19.04 although this started on earlier versions.

I tried to find core dump, but with no luck. I'll search it better if you need it. Or I would be grateful if you tell me where it can be.

**Comment by diemmarkus** [comment]
unfortunately, we have only played with snaps to date - we will need some extra time to create proper snaps of nomacs...

**Comment by i3v** [comment]
Same here for CentOS7.1810 (KDE).
I've tried to follow https://snapcraft.io/install/nomacs/centos . It told me to do `sudo snap install nomacs --beta`, which installed nomacs  version ` beta: 3.11.7 2018-10-05 (105) 117MB `. Installation process was fine, but now I only get `Segmentation fault`, `bash killed by SIGSEGV` (`bash-4.2.46-31.el7`), snap version: `2.42.2-1.el7`) 
```
warning: core file may not match specified executable file.
[New LWP 1872]
Core was generated by `/bin/bash /snap/nomacs/105/bin/desktop-launch nomacs'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f336d70ced6 in ?? ()

Thread 1 (LWP 1872):
#0  0x00007f336d70ced6 in ?? ()
No symbol table info available.
#1  0x000000000041f2c4 in gather_here_documents ()
No symbol table info available.
#2  0x0000000000000000 in ?? ()
No symbol table info available.
No shared libraries loaded at this time.
No symbol table is loaded.  Use the "file" command.
No symbol table is loaded.  Use the "file" command.
rax            0x7ffd0752ec74	140724726328436
```

Interestingly, there's also a newer version (except that 3.11.0 doesn't look newer than 3.11.7), on the "edge" channel, ` edge:      3.11.0 2019-12-16 (614) 120MB`. So I tried `# snap refresh nomacs --edge`, and now `$ nomacs` command starts the app. I was able to open some test pics without issues.

However, "Sync->Synchronize" says "no clients found" (which is the functionality I've installed nomacs for). And there's also a total of 12 "notifications" from SELinux (not tried to fix that) - so, sadly, I still cannot say nomacs works for me.

**Comment by diemmarkus** [comment]
closing this issue because snap support is discontinued in favor of [flathub](https://flathub.org/apps/details/org.nomacs.ImageLounge)
