### ISSUE TITLE
Rotating and resizing crop area resets crop rotation

### ISSUE THREAD

**Issue by TaiTair** [nomacs/nomacs#327]
In Nomacs 3.12.

When I use the crop tool, if I rotate it a bit it's fine. But if I try adjusting the size of the crop box after rotating, it will reset the rotation of the crop box.

Is there a way to change this behaviour so that the rotation of the crop box persists even after modifying its dimensions?

**Comment by diemmarkus** [comment]
Hi,

this is a bug - the only way to crop with rotation is to first adjust the dimensions, then rotate, sorry!

best,
markus

**Comment by TaiTair** [comment]
Ok I hope this bug gets resolved.

Thanks!
