### ISSUE TITLE
Keyboard shortcuts not being saved by default within "Export Settings" ini file

### ISSUE THREAD

**Issue by eeik** [nomacs/nomacs#328]
**Describe the bug**
When backing up nomacs settings to either transfer to a new computer or rebuild an existing one, the keyboard shortcut settings are not being included by default in the .ini file generated through "Export Settings"

**To Reproduce**
1. [CTRL]+K or Edit->Keyboard Shortcuts to customize shortcut settings
2. Assign new or alternative keyboard shortcuts to the features you use most
3. Save them, use them, awesome!
4. Export settings to move to new computer or rebuild existing machine
5. Re-install nomacs, import settings
6. Customized keyboard shortcut settings are not valid

**Expected behavior**
Keyboard Shortcuts are user specific settings that often evolve over days if not months of usage of an application. These settings should be included in the "Settings.ini" export that is ostensibly performing the task of "exporting settings".

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 3.12.1.4206 [x64]

**Additional context**
Steps above should suffice...

Thanks for your consideration 👍

**Comment by diemmarkus** [comment]
thanks for reporting, I'll look into this...

**Comment by diemmarkus** [comment]
this issue is fixed in nomacs 3.14
