### ISSUE TITLE
Lock Window Hotkey Not Reflected In Help Text

### ISSUE THREAD

**Issue by eeik** [nomacs/nomacs#329]
**Describe the bug**
When re-assigning the "Lock Window" hotkey within the hotkey settings, the help text continues to show the default hotkey assignment instead of reflecting the updated settings

**To Reproduce**
1. Reset hotkey for "Lock Window" to anything other than the default
2. Activate the "Lock Window" feature via the newly assigned hotkey
3. Observe the helptext that shows the original default hotkey assigned to the feature

**Expected behavior**
This helptext should reflect the changed setting to properly inform the user of the way to unlock the window

**Screenshots**
![Window Locked Hotkey](https://user-images.githubusercontent.com/5521252/57403771-a3959380-7197-11e9-9bfc-346954ea4c53.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 3.12.1.4206 [x64]

**Additional context**
N/A

**Comment by diemmarkus** [comment]
thanks!
