### ISSUE TITLE
potential misshandling of svg % scalars

### ISSUE THREAD

**Issue by GitHubRulesOK** [nomacs/nomacs#331]
**Describe the bug**
Interesting that the w3C site has its own "Shoot self in the foot" entry :-)
This SVG renders well in a browser but is to a degree distorted scale wise in nomacs
w3c it is offering an "invalid" roadmap (see below) however it would be useful if there were a means to override such misbehaviour in nomacs since it does render scalewise ok in browser

Have I missed such a setting ?

**To Reproduce**
1. Go to ' https://validator.w3.org/todo.html '
2. Scroll down to 'Roadmap
Multi-engine validator '.
2. Click on '... SVG version) to download https://validator.w3.org/images/roadmap/validators-chart.svg 
4. See distortion in nomacs

NOTE w3c validates that it has errors **duh!**
error https://validator.w3.org/check?uri=https%3A%2F%2Fvalidator.w3.org%2Fimages%2Froadmap%2Fvalidators-chart.svg&charset=%28detect+automatically%29&doctype=Inline&group=0&verbose=1&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices

**Expected behavior**

**Gracefully handle scale definition similar to within a browser**
`<rect xmlns="http://www.w3.org/2000/svg" fill="white" width="1154" height="792" />`  
viewBox="0 0 1154 792" width="1154pt" height="66pc" 
looks like the poor 66pc definition may be = 66(~69) % but nomacs reads as 66px or pt

**Screenshots**
ODDLY nomacs saves it just like this long blank image **V here V**
![validators-chart](https://user-images.githubusercontent.com/12754913/57572113-1c058a00-740e-11e9-82ab-aba45c23bb43.png)
ODDLY nomacs saves it just like this long blank image **^ here ^**

Secondary Question/Bug? why no colours on save as png  ? How should I have saved image to include colours ?

**Desktop (please complete the following information):**
 - OS: [win 10]
 - Version [3.12.1]

**Additional context**

**Comment by diemmarkus** [comment]
uh, that is bad. btw this is what I when saving it as png:
![validators-chart](https://user-images.githubusercontent.com/4182443/58155723-c1252b80-7c74-11e9-8850-1a1eff2b3bb9.png)
the problem here is, that we rely on Qt's svg loader - hence we need to wait for upcoming releases that might fix this issue - sorry!

**Comment by diemmarkus** [comment]
I'll close this issue - as there is no solution for improved SVG support yet...
