### ISSUE TITLE
Bright pink color cast with (some?) DNG files

### ISSUE THREAD

**Issue by afontenot** [nomacs/nomacs#334]
**Describe the bug**
All of half a dozen or so DNG files I tested display in nomacs with a bright pink color cast (much stronger than can be explained by something like nomacs ignoring embedded white balance information). The DNG image displays correctly in Lightroom, Darktable, gThumb, and RawTherapee. TIFF images created using dcraw also do not have this problem.

**To Reproduce**
1. Convert a Canon RAW file (.CR2) to Adobe's DNG format (Camera Raw version 11.2) using Adobe tools (e.g. Lightroom). Lossy DNG mode is **not** enabled. 
2. Open the image in nomacs.

**Expected behavior**
The image displays correctly.

**Screenshots**
![Screenshot_20190517_105955](https://user-images.githubusercontent.com/3870410/57947159-fb688480-7892-11e9-8c08-9129436cb0a3.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Linux kernel version 5.0.13
 - nomacs version 3.12

**Additional context**
Issues with pink images have sometimes occurred with other raw files and other programs, as a web search will quickly reveal. However, I haven't been able to find a common thread to all of them. At least in this case, other image viewers and raw file editors are displaying the image correctly.

I have included a sample image in case you can't replicate this with raw files of your own: https://drive.google.com/file/d/1ilDcG_8jvYp9hoVbPo9_qmlg7feQIlzv/view?usp=sharing

**Comment by afontenot** [comment]
Some additional information: I've since found that for a certain subset of raw files, RawTherapee and other dcraw based programs show the same bug. The difference is that every DNG file I've tested with nomacs has shown this problem. https://github.com/Beep6581/RawTherapee/issues/4695

**Comment by diemmarkus** [comment]
thanks for reporting - I'll have a look at it

**Comment by mdnava** [comment]
Try converting to a lesser DNG version. I prevent the magenta/pink cast in Adobe DNG Converter by using the "-dng1.3" command line option (without quotes).

**Comment by dashuigang** [comment]
how to fix it for win？
![捕获](https://user-images.githubusercontent.com/51685445/76868702-42078080-68a2-11ea-9cd3-1d78d6422ac3.JPG)

**Comment by dashuigang** [comment]
### **the mobile phone**

![捕获](https://user-images.githubusercontent.com/51685445/76871208-c0195680-68a5-11ea-8316-ca7d670f87af.JPG)

**Comment by diemmarkus** [comment]
![img-2020-04-22 14 28 28](https://user-images.githubusercontent.com/4182443/79982603-d8812000-84a6-11ea-82fd-d520df7144db.png)

**Comment by afontenot** [comment]
Awesome work, thanks!

**Comment by incodnita** [comment]
> 
> 
> ![img-2020-04-22 14 28 28](https://user-images.githubusercontent.com/4182443/79982603-d8812000-84a6-11ea-82fd-d520df7144db.png)

I still have this problem with the last nomacs stable and beta builds. I'm using Windows 10. It happens with all the RAW (.dng) files from my OnePlus 7T. In the others apps they looks as they have to.
Maybe this fix is not implemented yet? Maybe this fix doesn't work with all RAW files?
Thank you for your work and sorry for my poor english.

**Comment by ANDALACA** [comment]
Hi - still an issue here with a DNG from Pixel6Pro, running x64 3.17.2206. Dark purple/violet here. 
![image](https://user-images.githubusercontent.com/19207128/147309348-39a16ac8-e6e7-43bc-840c-7d32fc8e0bab.png)
where it should be
![image](https://user-images.githubusercontent.com/19207128/147309376-babc3a8d-6f59-4940-a6eb-f3294da76db1.png)
