### ISSUE TITLE
Cropping tool doesn't work when using dark theme

### ISSUE THREAD

**Issue by sianhulo** [nomacs/nomacs#336]
**Describe the bug**
If dark theme is enabled one can't use the mouse to crate a cropping selection (and if the selection is created manually using the keyboard, said selection can't be interacted with using the mouse)

**To Reproduce**
1. Enable dark theme in the settings.
2. Close nomacs
3. Open it and try to crop any picture

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Version Current git version

If the theme is changed to light theme it works again.

**Comment by diemmarkus** [comment]
closing this because cropping will be re-designed: #345.
