### ISSUE TITLE
Setting defaultJpgQuality stuck to 97

### ISSUE THREAD

**Issue by Boboss74** [nomacs/nomacs#338]
Hi, the setting `AppSettings > defaultJpgQuality` is reset to 97 when the program start.

![image](https://user-images.githubusercontent.com/835901/58186494-4a5c5280-7cb5-11e9-92ae-bfe77e7d3785.png)

nomacs version: 3.12.1.4206
OpenCV 3.4.3-dev
Qt 5.11.1
Windows 10

**Comment by diemmarkus** [comment]
thanks for reporting!
