### ISSUE TITLE
"Use Fixed Zoom Levels" setting doesn't save 

### ISSUE THREAD

**Issue by Ferpentas** [nomacs/nomacs#340]
When "Use Fixed Zoom Levels" setting is enabled it doesn't save when I exit and open nomacs again. Every other display setting does stay enabled after exiting though.

Screenshots

All display settings enabled
![enabled](https://user-images.githubusercontent.com/51099235/58441979-8fa8c780-809b-11e9-98e0-ce75aa4aa18c.png)

"Use Fixed Zoom Levels" disabled when nomacs is closed and opened again
![reset](https://user-images.githubusercontent.com/51099235/58441986-9df6e380-809b-11e9-9a2a-0168d985e324.png)

Desktop
 - OS: Windows 10
 - Version: nomacs 3.12.1.4206 [x64]

**Comment by diemmarkus** [comment]
thanks for reporting - unfortunately, I could nor reproduce this issue. did you change the values? (only increasing numbers are allowed in the text edit)

**Comment by Ferpentas** [comment]
The issue happens if the values are changed as well. I tried changing the values to see if the setting will save that way but when I open nomacs again after closing it resets to the default values and the setting is disabled again. 

Values Edited
![values1](https://user-images.githubusercontent.com/51099235/58682508-ae21f380-8325-11e9-8346-2e2dcdc9a6a8.png)

Values reset, option disabled
![values2](https://user-images.githubusercontent.com/51099235/58682541-d27dd000-8325-11e9-86f2-94dfcb01ba79.png)

**Comment by diemmarkus** [comment]
- are other settings (i.e. `invert mouse wheel behavior`) saved
- did you try changing it when only one instance of nomacs is running?
