### ISSUE TITLE
Cannot view multi-page TIFF in thumbnails

### ISSUE THREAD

**Issue by b3n3n** [nomacs/nomacs#341]
Hello,

First I'd like to honor you for making such a great product for free!! Respect.

I have a question. Is it possible to make changes of .tiff file thumbnails preview panel (T).(multiple page file).
So now when I open multiple page .tiff file I get only one thumbnail icon per file in preview thumbnails panel (T). Is it possible to get all thumbnails icons (pages), for every page in this multiple pages .tiff file?
Thank you

**Comment by diemmarkus** [comment]
thanks : )
this is not possible. also: we cannot add this features, as we would have to load every tiff page to create the thumbnails (afaik, tif does not embed a thumbnail for each page), sorry!
