### ISSUE TITLE
Custom plug-in

### ISSUE THREAD

**Issue by mikeleg** [nomacs/nomacs#342]
Hi i saw your program, i possible to add my custom plugin?

**Comment by diemmarkus** [comment]
yes...
you need to fork the [plugins repo](https://github.com/nomacs/nomacs-plugins).
A short introduction can be found [here](https://github.com/nomacs/nomacs-plugins).
Example of more complex pugins are [here](https://github.com/TUWien/ReadModules).
please let me know if you have further questions.

**Comment by mikeleg** [comment]
Thanks but i'm not able to write ccp plugin thanks
