### ISSUE TITLE
Default JPG quality value not getting saved

### ISSUE THREAD

**Issue by Mintonne** [nomacs/nomacs#346]
Hello,

The default JPG quality value is not getting saved. The current setting is almost tripling the file size for JPEGs after cropping them.

Showcase - https://gfycat.com/essentialoblonghyracotherium

**Comment by diemmarkus** [comment]
Hi,

thanks for reporting. This issue was addressed in #338 and fixed in 70003a4cbc6fcfd95110a30550f010ef1d128d7a which will be part of the upcoming release.

best,
markus
