### ISSUE TITLE
Hi,  problem reading .SRW file format of Samsung photo image

### ISSUE THREAD

**Issue by marcusa62** [nomacs/nomacs#354]
The APP close itself meanwhile is reading PHOTO.SRW file format, thank you for supporto and nice program !
Best regards Marco

**Comment by diemmarkus** [comment]
is it possible to upload a sample image so that we can test it?
thanks!

**Comment by marcusa62** [comment]
Hi, thanks for answering the photo link is below,
https://drive.google.com/file/d/1jI-RU5vDzzb-DPkesKkyvYFfYLygLjrA7Q/view?usp=drivesdk

**Comment by diemmarkus** [comment]
thx
