### ISSUE TITLE
Batch processing : create profil ?

### ISSUE THREAD

**Issue by Trogonite** [nomacs/nomacs#355]

**Comment by Trogonite** [comment]
hello, when I use batch processing, when I want to create a profile the program closes. I am on MX linux 18.3

**Comment by diemmarkus** [comment]
hi, which nomacs version are you using?

**Comment by Trogonite** [comment]
I use Nomac 3.8

**Comment by commander-keen** [comment]
Duplicate of #300 
https://github.com/nomacs/nomacs/issues/300
