### ISSUE TITLE
Add 'scalable' options to the anti-aliasing

### ISSUE THREAD

**Issue by Jalopyy** [nomacs/nomacs#358]
https://gfycat.com/embarrassedwellinformedgardensnake

Gfycat is what I'm talking about. From talking to Markus, it happens because Nomacs is specifically told to bring back the highest quality image as fast as possible, then apply a filter. This can make it when changing between images, they can appear blurry for a moment before snapping into clarity. 

I'd be lying if I said I knew exactly how to word this, but a way so the image quality doesn't change so drastically quickly as it does on other image viewers like Honeyview or default ones would be nice. From what I can tell you can either turn the option on or off, so there's no real middle ground to try to attain functionality similar to those other programs.

**Comment by alicektx** [comment]
With 3.0 (default under Xenial 16.04),
i experienced this intermediate blurriness heavily...
Weirdly enough, when i tested the latter 3.6 from the (then active) ppa, 
situation was actually worse...almost unbearable, grrr :-/

Was thinking myself of possibly asking here as well about it,
so i went on to first compile such back on December, 
3.13.x from git here actually before doing so. And then...
i found that such is rarely obtrusive / barely noticeable here, 
almost next to perfect... :-)
Not even remotely a programmer myself, 
somehow i believe this commit is likely what did the magic though:
https://github.com/nomacs/nomacs/commit/ae01ab8e4762348a419420830a5e01e4ba2d0ce7
(thank you devs!)

Would still love myself to understand if such was what did the trick...

**Comment by diemmarkus** [comment]
oh cool, @alicektx what you are saying is, that it is already fixed in the current master?! @Jalopyy I will try to get a proper snap running, so you can test the current behavior. Nevertheless, I would suggest to leave this issue open until then.

best,
markus

**Comment by Jalopyy** [comment]
I will, thank you.

**Comment by diemmarkus** [comment]
this issue is fixed in the current [flathub](https://flathub.org/apps/details/org.nomacs.ImageLounge) version, right?!
