### ISSUE TITLE
Thumbnails animation delayed severely

### ISSUE THREAD

**Issue by YinlinHu** [nomacs/nomacs#359]
**Describe the bug**
The animation of the thumbnails panel delayed severely when handling directory with a large number of images.

When the directory has about 5K images, it still works perfectly.

While when the directory has about 110K images, the animation starts to slow down.
The image has come out for nearly 6 seconds, the thumbnails panel is still in animation.

I use the images at here: http://images.cocodataset.org/zips/train2017.zip

This may be a corner and extreme case. I think the developer can use this dataset for test. It has over 110K images in one directory, nearly all popular viewer, such as Gwenview, Xnview, Eye, etc. hardly can open this directory. Nomacs is the best performer by far, except this tiny problem.

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Version [3.12]

**Comment by diemmarkus** [comment]
thanks for reporting! I will check if/how we can improve scrolling.

**Comment by diemmarkus** [comment]
I have now improved animation speed if a folder has more than 2000 images. I would be very happy if you could test it using your system. Using the coco dataset, the animation was a bit sluggish on my system (before the fix), but not as bad as reported.

**Comment by YinlinHu** [comment]
Cool, the thumbnail panel is OK now. But, another related problem. When I open the **thumbnail preview** panel in this large directory. The GUI is frozen by about 10 seconds, and it is hard to scroll after recover from frozen. I think the threads of loading images should not affect the GUI.
