### ISSUE TITLE
The "Show 100%" doesn't show 100% image on the first click

### ISSUE THREAD

**Issue by ghost** [nomacs/nomacs#360]
Hello,
I've noticed that pressing the "Show 100%" prefers zooming to fit on first click instead of zooming to 100%. This happens when zooming in the image.

Is that intentional? Because to me it doesn't make much sense, since there's already a button for that. When I press zoom to 100%, that's what I'm expecting to happen.

(Also a little off topic question - is there a way to disable mouse button swipe controls? I can't find an answer for this anywhere..)

**Comment by diemmarkus** [comment]
hi,

thanks for reporting - this is indeed unintended behavior.

best,
markus
