### ISSUE TITLE
File Explorer

### ISSUE THREAD

**Issue by Stamimail** [nomacs/nomacs#361]
1. Selecting images by keyboard arrows doesn't change the images in main window.
2. Shift+Delete for permanently delete is not supported yet.

**Comment by diemmarkus** [comment]
>     1. Selecting images by keyboard arrows doesn't change the images in main window.
this is optional: right-click the file explorer then select `Open Selected Image`
>     2. Shift+Delete for permanently delete is not supported yet.
Shift+Delete is supported from the main window (then you see the image) - I think we should not add it to the file explorer because of potential damage when hitting it accidentally...

**Comment by Stamimail** [comment]
I had a group of pictures, and I was trying to delete pictures that I didn't want.
My method to do it, I thought about viewing all images one by one, and when see unwanted image, to delete it.

**Comment by diemmarkus** [comment]
> My method to do it, I thought about viewing all images one by one, and when see unwanted image, to delete it.

That should be possible. Currently `Delete` will ask before removing the image (on windows, the image is moved to trash) while `SHIFT + Delete` removes the image without asking. Note that you have to focus the viewport rather than the File Explorer

**Comment by Stamimail** [comment]
In my Windows Explorer:
Delete - asks before removing the image to trash.
SHIFT + Delete - asks before removing the image permanently.
The focus should be on a File list (File Explorer).

**Comment by diemmarkus** [comment]
as said before, deleting images won't be added to the file explorer. also there are other tools (like windows explorer) who can do that... our delete is intended for usecases where you skip through all images (with a large view) and delete those that are not needed...
