### ISSUE TITLE
Doesn't Open Grayscale TGA

### ISSUE THREAD

**Issue by Genomo** [nomacs/nomacs#362]
Hi!
Nomacs can't open TGA images with grayscale mode, for RGB color works fine.

**Comment by diemmarkus** [comment]
Hi,

you are right. nomacs cannot load 8-git TGA and it has issues with 32-bit TGA images. Here are all potential [TGA formats](http://www.paulbourke.net/dataformats/tga/):

| Image Type | Description |
|--------------|------------|
  |  0 | No image data included. |
  |  1 | Uncompressed, color-mapped images.|
  |  2 | Uncompressed, RGB images.|
  |  3 | Uncompressed, black and white images.|
  |  9 | Runlength encoded color-mapped images.|
  | 10 | Runlength encoded RGB images.|
  | 11 | Compressed, black and white images.|
  | 32 | Compressed color-mapped data, using Huffman, Delta, and |
  ||runlength encoding.|
  | 33 | Compressed color-mapped data, using Huffman, Delta, and|
          ||runlength encoding.  4-pass quadtree-type process.|

nomacs supports these formats:
| Image Type | Description |
|--------------|------------|
|  2 | Uncompressed, RGB images.|
| 10 | Runlength encoded RGB images.|

-> this includes 16-bit, 24-bit, 32-bit RGB (uncompressed/RLE compressed) TGA images.
