### ISSUE TITLE
Photos are displayed in different colors than in photoshop, which is lighter

### ISSUE THREAD

**Issue by dashuigang** [nomacs/nomacs#364]
Photos are displayed in different colors than in photoshop, which is lighter，how to fix it？win10

**Comment by xbrakl** [comment]
Can you show us some examples? Do you have the same color mode in both programs? Did you used the same display and showed the image in the same area of the display?

Add for example printscreen of some testing image with nomacs on the left side and photoshop on the right side so we can see difference.

Use for example this calibrating patterns and open them mirrored in symetric pattern.

![Monitor-Calibration-670x335](https://user-images.githubusercontent.com/25900962/63648142-a8bd2500-c72b-11e9-9a6f-b1e0802d1d21.jpg)

![Online-Monitor-Test-HTML-Windows](https://user-images.githubusercontent.com/25900962/63648146-ae1a6f80-c72b-11e9-8c2d-a6d55293df26.png)

**Comment by diemmarkus** [comment]
> Photos are displayed in different colors than in photoshop, which is lighter，how to fix it？win10
when loading raw images? can you provide a sample image? - thx
