### ISSUE TITLE
Dark theme: bad contrast in some dialogues

### ISSUE THREAD

**Issue by xbrakl** [nomacs/nomacs#366]
My current settings

![dialogues - settings](https://user-images.githubusercontent.com/25900962/63647374-ad301080-c720-11e9-8635-751204de6f08.png)

When you are using dark mode, I found 2 dialogues with bad font contrast and one type of menu item with black tick on dark gray background.

Issue 1: 
When renaming image, please dont use icon color for highlight of image filename you can see in this dialog. Change it on white highlight + black font color for filename or in reverse. You will avoid bad combination of highlight and font color if users choose bad icon color.

![dialogues 2](https://user-images.githubusercontent.com/25900962/63647376-b4571e80-c720-11e9-817a-de67969d879c.png)

Issue 2:
I tried to change filename, but it was filename conflict. This filename conflict dialog should use black font color. Buttons are broken in the same way.

![dialogues](https://user-images.githubusercontent.com/25900962/63647375-b28d5b00-c720-11e9-9ea6-1ae0c84f4804.png)

Same problem with window showed by "? -> check for updates" action.

![img-2019-08-31 13 43 13](https://user-images.githubusercontent.com/25900962/64063516-5d0bef00-cbf5-11e9-98ba-a45d3bd5101d.png)

-> about dialog

![about](https://user-images.githubusercontent.com/25900962/64487748-696bf980-d23e-11e9-8fac-8da7e3372ef5.png)

Issue 3:

Ticks should use icon color or white color for better contrast.

![ticks](https://user-images.githubusercontent.com/25900962/63647595-f6359400-c723-11e9-8524-e884d863943f.png)

**Comment by diemmarkus** [comment]
related (extends) #174

**Comment by xbrakl** [comment]
Issue 4:

This red highlighted area in general settings will highlight by light gray when you move over with mouse cursor. After click it restarts Nomacs. It is active without any change of settings.

![img-2019-08-31 13 26 21](https://user-images.githubusercontent.com/25900962/64063374-f33f1580-cbf3-11e9-9a47-865f36dc4e79.png)

**Comment by diemmarkus** [comment]
True, I fixed this while working on the double scrollbars - so if you try the current master, it should be gone...

**Comment by xbrakl** [comment]
issue 2 updated

**Comment by diemmarkus** [comment]
- [ ] issue 1: highlight color
- [x] issue 2: dialogs
- [ ] issue 3: menu checkboxes
- [x] issue 4
