### ISSUE TITLE
Settings: file associations - internal scrollbar

### ISSUE THREAD

**Issue by xbrakl** [nomacs/nomacs#367]
I suggest to remove list of file associations from internal scrollbar in this part of settings. Highlighted red. One outer scrollbar is enough. It will look and scroll better. Make it as simple list without scrollbar.

![file associations](https://user-images.githubusercontent.com/25900962/63647669-013cf400-c725-11e9-9da6-1759dcf3099f.png)

**Comment by diemmarkus** [comment]
thx!

**Comment by xbrakl** [comment]
Me too ;)
