### ISSUE TITLE
Zoom 100% key shortcut

### ISSUE THREAD

**Issue by xbrakl** [nomacs/nomacs#369]
I don't know where this feature started and what is the general habit. I met it for the first time in Firefox. There is shortcut ctrl+0 reserved for Zoom 100%. It is very smart decision because zoom 100% is important when zooming and zero button is easier to hit on numpad than one button.

But Nomacs use ctrl+0 on reset canvas (I consider as useless function) and ctrl+1 for zoom 100%. This is just nuance, but I would like to change it and use ctrl+0 on Zoom 100% function like in Firefox.

Could you redefine this shortcut or tell me how to change this configuration? Thank you

**Comment by xbrakl** [comment]
Ahhh,

these shortcuts are hardcoded in the source code.

https://github.com/nomacs/nomacs/blob/52facca986709011ae858bc38cb1f8206e1b64b4/ImageLounge/src/DkCore/DkActionManager.h#L415-L416

**Comment by diemmarkus** [comment]
the default shortcuts here are inspired by Photoshop. You could customize the shortcuts on your system using `Edit > Keyboard Shortcuts ` then `View > Zoom to Fit`.

> these shortcuts are hardcoded in the source code.
if you change them as mentioned before, we load the shortcuts from the settings file, which - in your case - will look like this:
````
[CustomShortcuts]
Zoom%20to%20Fit=Ctrl+1
Show%20100%25=Ctrl+0
````

**Comment by xbrakl** [comment]
Smart, thanks.
