### ISSUE TITLE
Nomacs do not support RAW

### ISSUE THREAD

**Issue by robSch69** [nomacs/nomacs#371]
I'm using Nomacs graphic editor Version 3.8 (OpenCV 3.2.0, Qt 5.9.3) on OS Linux Mint 19.1. It is working fine with JPG. When I open a PEF-File (Pentax RAW-Format) the photo seems to be overexposed. If I open it with Nomacs 3.4 on OS LMDE3 it looks fine.
If I press button 'F1' in Version 3.4 it is showing: RAW support: Yes.
If I press button 'F1' in Version 3.8 it not showing any message about Raw-Support. But I do not know, if it is showing a RAW-Support in Version 3.8 in a popper working installation at all with 'F1'
![nomacs3 4](https://user-images.githubusercontent.com/54700074/63997186-0079d880-cafe-11e9-810a-4e9038bcd2bb.png)
![nomacs3 8](https://user-images.githubusercontent.com/54700074/63997191-040d5f80-cafe-11e9-9a23-e2b89916c2c4.png)

.

**Comment by diemmarkus** [comment]
this tag was removed. If nomacs can read PEF files, you have RAW support. You could try to check Edit > Settings > Advanced `Always Load JPG if Embedded` and see if this fixes your issues. If not, you could upload a sample PEF, so that we can have a look at it...

**Comment by robSch69** [comment]
The PEW-File is ok, because Nomacs 3.4 on LMDE3 it is shown properly.
The setting you told, I tested already. In Nomacs 3.8 it has no effect what ever I choose in 'Advanced'. Only in 3.4 when I select 'always load RAW  (Immer die RAW Datei laden)' the picture is looking as in 3.8.

**Comment by robSch69** [comment]
If desired, I still can upload a sample PEF.

**Comment by diemmarkus** [comment]
I just checked - there was an issue with RAW loading in 3.8. This is fixed in the current stable (3.12) - is it possible for you to update?

**Comment by robSch69** [comment]
Update: I tried  already, but not possible in lm 19.1. Donnerstag, 05 September 2019, 09:12vorm. +02:00 von Markus Diem  notifications@github.com :

**Comment by robSch69** [comment]
I tried already to update to nomacs version 3.12. But I did not managed. Is there any instuvtion for LM 19.1?

**Comment by robSch69** [comment]
I meaned instruction

**Comment by diemmarkus** [comment]
I think there is no way - other than compiling/installing nomacs yourself using the current stable.
