### ISSUE TITLE
Settings: position of restart button

### ISSUE THREAD

**Issue by xbrakl** [nomacs/nomacs#372]
If you move restart button in settings higher over red line (option 1) or make it part of the menu and move it up as the last item of list just under editor option (option 2), you would stop enforcing the creation of that nasty scrollbar in the window of every setting on the right side.

option 2: copy restart logo and add text "restart".

This problem shows up if u have too small resolution in Y-way. ´This image was done on 1920 x 1080 resolution and you have to scroll down every time to find restart button.

![img-2019-08-31 14 13 47](https://user-images.githubusercontent.com/25900962/64063893-086b7280-cbfb-11e9-89e3-2c409936e47c.png)

**Comment by diemmarkus** [comment]
you should definitely check the current master - this is fixed too : )
-> in 5a1408844f1fd6e5a4c595cb908c92b912bd8e8c and aec07cda1eac92d53c8c5f97fcffc7c3d3fb399a I changed all apparent layout issues in preferences.
