### ISSUE TITLE
Add COPY, CUT, PASTE and SELECT, MOVE tools (feature request)

### ISSUE THREAD

**Issue by xbrakl** [nomacs/nomacs#374]
I think it would be very useful to add tools that would let user to select area on picture at least in rectangle shape, copy or cut this area (to the clipboard) and paste it or move this selected area on image canvas.

Very useful functionality for quick and small edit of image. I am pretty surprised nobody asked for this yet :).

**Comment by diemmarkus** [comment]
when we start moving/copying parts of an image, we need layers for a proper handling. This is where we draw the line between image viewer and image editor (I suggest using gimp/photoshop for these actions). 
Btw. copying image parts to another software is supported: you can crop the image, then copy this part.

**Comment by AlexFolland** [comment]
Copying the image doesn't put it in my clipboard.  I've cropped, and I'm clicking Edit -> Copy, checking clipman, and the cropped image is not in my clipboard.  It's like nomacs is ignoring the copy command completely.
