### ISSUE TITLE
Add PPA for Ubuntu with latest version.

### ISSUE THREAD

**Issue by supersexy** [nomacs/nomacs#376]
PPA with latest version for all LTS versions at least would be great.

**Comment by diemmarkus** [comment]
we stopped packaging nomacs ourselves because it was too much maintenance burden for us and because there are official packages now. However, I am happy if you or someone reading this is willing to maintain ppa/latest packages (I will of course support the packaging as good as I can).

**Comment by supersexy** [comment]
Thanks for your info, I understand that, it is still too much of an adventure to package for all the different distros and it would be great if it would be much easier. Thanks for your attention!
