### ISSUE TITLE
Broken "light" theme with dark system colors

### ISSUE THREAD

**Issue by namazso** [nomacs/nomacs#377]
**Describe the bug**
Light theme (default) with dark system colors (high contrast) makes "Light theme" and first startup near-unusable

**To Reproduce**
1. Set dark high contrast theme on windows
2. Install and start nomacs
3. See bug

**Expected behavior**
Readable menu, either by conforming system theme, or actually having light theme as set in settings by default

**Screenshots**
![image](https://user-images.githubusercontent.com/8676443/65419260-d01c1600-dded-11e9-99f7-5b8bbc416ac8.png)
![image](https://user-images.githubusercontent.com/8676443/65419293-ddd19b80-dded-11e9-8de0-b689178569dd.png)
After finding and changing from light to dark theme it's "fixed":
![image](https://user-images.githubusercontent.com/8676443/65419327-ef1aa800-dded-11e9-8ceb-330c2a9ea216.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1809

**Additional context**
Would be nice to have "system" theme instead of only light and dark, of which the former is a broken mix of light and system theme.

**Comment by diemmarkus** [comment]
thanks for pointing this out - we'll add a ``system theme`` in the upcoming release

**Comment by cryham** [comment]
I can confirm the same issue on OS: Debian 10.
It happens with dark OS themes e.g. "Zion (Reversed)". Can't see menu texts at all.

I hacked/fixed this by editing the file (default theme):
`/usr/share/nomacs/Image Lounge/themes/Light-Theme.css`

and changing:
`FOREGROUND_COLOR: default;`
to
`FOREGROUND_COLOR: #c4c8cc;`

But then of course this goes bad when light OS theme is used.

Dark Theme (nomacs) seems to work okay.

**Comment by diemmarkus** [comment]
![img-2020-04-23 14 29 17](https://user-images.githubusercontent.com/4182443/80100086-bc958100-856f-11ea-9c13-6c63949ab463.png)
