### ISSUE TITLE
Zoom to 100% and Crosshair Cursor Feature Collision

### ISSUE THREAD

**Issue by eeik** [nomacs/nomacs#378]
**Describe the bug**
As clear as I can see things, the [Ctrl]+1 hotkey for zooming to 100% invokes the `zoom to 100%` action, while the bare [Ctrl] hotkey for the crosshair tool attempts to zoom back to fill the screen before displaying its crosshair x,y coordinate plus color values. These two features compete for ultimate supremacy, it seems to me at least, along the "how quick did you hit the `1` with the [Ctrl] key" interaction vector.

**To Reproduce**
0. Load an image that is smaller than your desktop resolution and have fill to fit enabled
1. Hotkeys mapped as noted in screenshot
2. Hit [Ctrl] alone ... crosshair value status bar shown
3. Hit [Ctrl] again ... crosshair value status bar hides (sometimes) ... maybe another bug here, but how do I make the crosshair value status bar hide on command? behavior at the moment seems non-deterministic ...
4. Hit [Ctrl]+1 ... zoom to 100% occurs, but sometimes the crosshair value status bar pops up soon after the zoom shift, and then the image expands back to fill the full screen again negating the zoom to 100% action

**Expected behavior**
This might be a delay issue, but hitting [Ctrl] with maybe 200ms of delay before any other keys are pressed might be expected to show the crosshair value status bar. Hitting [Ctrl]+any of the other hotkeys which are solely rooted w/ [Ctrl] itself should NOT trigger the crosshair value status bar.

**Screenshots**
![Hotkey Ctrl Screenshot](https://user-images.githubusercontent.com/5521252/65446161-04450600-ddf1-11e9-9ac8-39dd0c450cf8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 3.12.1.4206 [x64]

**Comment by diemmarkus** [comment]
thanks for reporting! showing the statusbar on CTRL is sometimes confusing -> I guess we will just remove this feature...
