### ISSUE TITLE
EPS File support

### ISSUE THREAD

**Issue by CasperStekelenburg** [nomacs/nomacs#380]
nomacs currently does not support EPS files. Can you please add support for EPS files?

**Comment by diemmarkus** [comment]
supporting EPS is not trivial and not supported by any of the libraries used - so I don't see EPS support coming in the near future - sorry!

**Comment by cbiere** [comment]
+1 despite being closed. Maybe you reconsider if enough people indicate interest. Opening EPS files on Windows is quite awkward. Office suites offer no preview or direct opening of these files and have also only limited support. There are only a few third-party tools for viewing EPS files (Irfanview, EPS viewer) directly and none of these are open source and, for example, Adobe Bridge while being free to use is massive overkill for this purpose. Also, if I can avoid it, I don't like installing multiple tools with overlapping feature sets just for one or two important features.

**Comment by diemmarkus** [comment]
Sorry : ) 
I can just give a recommendation: if the files are yours, move to SVGs. nomacs partially supports them & the standard is much more open. + It is the standard format for online graphics
