### ISSUE TITLE
There seems to be a link issue

### ISSUE THREAD

**Issue by CerebralFreeze** [nomacs/nomacs#381]
When I try to download nomacs via https://download.nomacs.org/, it takes me to a towing and car recovery service.

DNS issue?

**Comment by diemmarkus** [comment]
thanks a lot! - we will fix this asap

**Comment by diemmarkus** [comment]
prosite is not very supportive in this issue. has anyone a suggestion for a good FOSS hosting service?

**Comment by diemmarkus** [comment]
ok, prosite removed the site (which is good : ) - @sfiel do you know if there is any additional fix we can apply here?

**Comment by diemmarkus** [comment]
binaries are now hosted on github: https://github.com/nomacs/nomacs/releases/latest
