### ISSUE TITLE
Expand info panel to include DPI and print size

### ISSUE THREAD

**Issue by mikeyww** [nomacs/nomacs#383]
Would be great to have more info in the info panel, especially DPI and print size.

**Comment by diemmarkus** [comment]
Hi,

the `Panels > Metadata Ribbon` allows for adding more info. You can customize the info displayed by Right Click (the Metadata Ribbon) > Change Entries. Here is an example with dpi (XResolution/YResolution).
![img-2019-10-23 08 55 12](https://user-images.githubusercontent.com/4182443/67366178-450c7800-f573-11e9-9a6e-75f94b6c2108.png)

best,
markus

**Comment by mikeyww** [comment]
In Windows, when I select "Change Entries", there is no option for DPI.

**Comment by diemmarkus** [comment]
if you cannot select DPI - the image does not contain the corresponding metadata.
in case you want to calculate dpi, you could use the resize dialog (just untick `resample image`)
![img-2020-03-12 15 30 38](https://user-images.githubusercontent.com/4182443/76532111-70d2c080-6476-11ea-9977-c448f47d0c21.png)
