### ISSUE TITLE
Why does this image look different in nomacs vs photoshop?

### ISSUE THREAD

**Issue by Jonatino** [nomacs/nomacs#386]
The image: ![Image](https://dl.dropboxusercontent.com/s/8omaeciyebmq9mc/light-off-icon-25.jpg)

Screenshot:
![Screenshot](https://dl.dropboxusercontent.com/s/bwrqo8rlspks9fd/brave_2019-10-19_22-05-21.png)

I have no plugins installed, reset all settings and even tried uninstalling and reinstalling. Any ideas?

**Comment by britt-orville** [comment]
not sure if this helps... but this seems like a colour management issue to me. if i convert the image in photoshop from cmyk (which this image is) to rgb, and re-save it, the images then look the same in both ps and nomacs.
does this get at the problem at all?

**Comment by diemmarkus** [comment]
yes, nomacs has unfortunately a poor gamut mapping (no ICC profiles) for cmyk images as discussed in #370 and #204 - sorry!
