### ISSUE TITLE
Nomacs auto runs on login when never added to any start up./

### ISSUE THREAD

**Issue by CodeKraft** [nomacs/nomacs#390]
I have never known a program to add itself to auto-start and not show up in the auto-start list.

I have tried several ways of accessing these start up menus and I have to say that I NEVER ADDED THE PROGRAM to the start up and it does not show YET IT RUND EVERY BLOODY TIME I BOOT UP.

WHY?

Its not the OS as there is no evidence of it ever being set or added.

The program actually cause the OS to crash one day I was using the software and it has since then, run itself every time I boot.

I have uninstalled and reinstalled and it still bloody well runs on system boot up.

**Comment by diemmarkus** [comment]
sorry to hear that... our installer does not have any routine to set itself into the system start-up.

- which OS are you using?
- where did you download nomacs?

**Comment by CodeKraft** [comment]
Sorry for the late reply, I have been seriously ill and hospitalised since posting.

So... I am using MX Linux that I understand is the DEBIAN arm of Linux.

-Computer-
Processor		: 2x Intel(R) Celeron(R) CPU  N2830  @ 2.16GHz
Memory		: 3933MB (2339MB used)
Operating System		: MX 18.3 Continuum
User Name		: mark (Unknown)
Date/Time		: Thu 30 Jan 2020 15:47:57 GMT
-Display-
Resolution		: 2646x1024 pixels
OpenGL Renderer		: Mesa DRI Intel(R) Bay Trail 
X11 Vendor		: The X.Org Foundation
-Multimedia-
Audio Adapter		: HDA-Intel - HDA Intel PCH
-Input Devices-
 AT Translated Set 2 keyboard
 Power Button
 Sleep Button
 Lid Switch
 Power Button
 SYN1B7D:01 06CB:2991 Touchpad
 Video Bus
 Acer WMI hotkeys
 HDA Digital PCBeep
 HDA Intel PCH Headphone
 HDA Intel PCH HDMI/DP,pcm		: 3=
 VGA Webcam: VGA Webcam
 Logitech USB Receiver
 Logitech USB Receiver
 ACPI Virtual Keyboard Device
-Printers (CUPS)-
EPSON-Stylus-D92
HP-Photosmart-C4100-series		: <i>Default</i>
Officejet-J5700-series
Officejet-J5700-series-Fax
POS58
Samsung_ML-191x_252x_Series
-------------------

Hope that helps.

**Comment by diemmarkus** [comment]
sorry to hear...
-> I don't think that we can help you here since we don't maintain linux packages of nomacs ourselves. maybe it's best to contact MX maintainers of nomacs?
