### ISSUE TITLE
Nomacs skips over several images after deleting if sorted by mtime

### ISSUE THREAD

**Issue by Vladimir-csp** [nomacs/nomacs#391]
**Describe the bug**
When images are sorted by modification time, deleting an image results in skipping several images ahead

**To Reproduce**
1. Open an image in a directory with multiple images (more than 10-20 preferably)
2. Switch sorting mode to modification time
3. Remove some image with Shift+del
4. Nomacs skips several images ahead.

**Expected behavior**
Next image is shown

**Desktop (please complete the following information):**
 - OS: Debian testing
 - Nomacs 3.12

**Comment by diemmarkus** [comment]
confirmed - thanks for reporting!

**Comment by scrubbbbs** [comment]
We use the sort order to determine our position in the folder after we lose track of a file (either by deleting ourselves or external application), therefore sort methods which often have the same value for each file will put us in the wrong location (e.g. mtime/ctime). This could be corrected by comparing by file name when there is a tie.
