### ISSUE TITLE
Catalan translation not present in nomacs (altough it's in crowdin)

### ISSUE THREAD

**Issue by aseques** [nomacs/nomacs#393]
**Describe the bug**
Nomacs is partially translated to catalan (17% of main file), but it doesn't show in the languages list. I would like it to show so I can do a better translation.
Is there any threshold for a language to appear?

**To Reproduce**
1. Go to language selection
2. No catalan in the list

**Expected behavior**
Catalan should be one of the languages in the list

**Screenshots**
![Screenshot_20191108_101622](https://user-images.githubusercontent.com/555542/68464374-d422bc80-0210-11ea-809b-45eb73632b76.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 3.12

**Comment by diemmarkus** [comment]
translations are only shipped if they are above a certain threshold. But you can add an (unofficial) language:

- [download](http://translate.nomacs.org/project/nomacs/ca/12140) the language file from crowdin
- install Qt Creator (pick the open source installer)
- open a command line and cd to the directory with the downloaded translations (``*.ts``)
Then type:

````bash
# Windows (change the Qt folder accordingly):
> C:\Qt\Qt5.13.0-x64\bin\lrelease.exe nomacs_ca_ES.ts
# Linux:
$ lrelease nomacs_ca_ES.ts
````
Now you should have a file named ``nomacs_ca_ES.qm`` in the same directory. Copy this file to the translations folder of nomacs (on windows: C:/Program Files/nomacs/bin/translations).

``NOTE:`` the Catalan translation does not translate the term ``English`` hence it will be listed as a second English entry in nomacs below bosanski:

![img-2019-11-25 13 56 57](https://user-images.githubusercontent.com/4182443/69542324-7ff73680-0f8b-11ea-88d7-6badf20a5beb.png)

**Comment by aseques** [comment]
Thanks @diemmarkus for your great explanation, I already translated the 'English' so the language appears properly. About the threshold, is there an specific number percentage? I'm slowly getting towards the 100% but still not there.

**Comment by diemmarkus** [comment]
cool, thanks! -> i think there is no specific threshold. afaik @sfiel manually added translations before new releases.
