### ISSUE TITLE
Add Color Management support (display only)

### ISSUE THREAD

**Issue by archont00** [nomacs/nomacs#394]
**Is your feature request related to a problem? Please describe.**
nomacs does not support color management.

**Describe the solution you'd like**
- Images with embedded colour profile should be converted to display color profile.
- Images without embedded colour profile should check metadata about colour space there adhere to.
- Images with no info on colour space should be considered sRGB.
- [linux only] Display profile should be queried from colord (if exists) or directly from X.org ( _ICC_PROFILE atom). See e.g. here for an overview https://wiki.archlinux.org/index.php/ICC_profiles#Loading_ICC_profiles or considered sRGB or user might have the option to set it manually.

**Comment by diemmarkus** [comment]
the problem here is that we rely on Qt which does not support ICC profiles, see also #370, #386, sorry!
