### ISSUE TITLE
hey i need to know whats the main things this does that is helpful (see details inside)

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [nomacs/nomacs#395]
this thing cant do the most basic of things

https://github.com/nomacs/nomacs/issues/295

https://github.com/nomacs/nomacs/issues/296

https://github.com/nomacs/nomacs/issues/301

and none of these thing have been fixed

so what are the main things this thing is helpful for if it doesnt do the above?

**Comment by diemmarkus** [comment]
nomacs is an image viewer. so it's best in viewing images (that are typically stored within a folder) consequtively. it is *not*:
- an image organizer (#295) -> you could use Google Photos/XnView
- an image editor (#296) -> you could use Photoshop/Gimp

nomacs is an open source project that we do in our spare time. hence, the amount of time we put into it varies and we rely on support from the community.
