### ISSUE TITLE
how to take 2 images and auto-puts them side by side into 1 image?

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [nomacs/nomacs#396]

**Comment by diemmarkus** [comment]
you could use gimp for this...

**Comment by GLLM** [comment]
Hello !
Well, if it's for culling ... opening Gimp is overkill, and maybe not appropriate.
Aim is simply to see 2 pics side by side and potentially delete or isolate the lesser of the 2.
I second the initial question :)
Thanks
GLLM
