### ISSUE TITLE
Add a blur function

### ISSUE THREAD

**Issue by pointyointment** [nomacs/nomacs#399]
**Is your feature request related to a problem?**
Yes, to the extent that "nomacs lacks a blur function" is a problem. It wasn't a problem for my first several weeks of lightly using nomacs, because I didn't want to blur anything until today. It wouldn't be a problem for someone who only ever wants to view images or crop them (for example), only for somebody who wants to blur an image at least once.

**Describe the solution you'd like**
Adjustments → Blur… and you get options similar to those of the sharpen function (blur size, blur strength, maybe blur type).

**Describe alternatives you've considered**
I looked at the sharpen function, and saw that it doesn't let me put in a negative value to get a blur (not that it's the same operation under the hood anyway). I looked in the plugin manager and didn't find a blur plugin.

***P.S.***
I see that issue templates seem to be set up, but I had to copy and paste the template when writing this. I don't know if the problem's on my end or what. It looks like other issue-writers are able to use them.

**Comment by diemmarkus** [comment]
thanks for the suggestion!

**Comment by BarryEdmiston** [comment]
December 2022 and still no blur function available?
