### ISSUE TITLE
Frameless mode shows black only screen

### ISSUE THREAD

**Issue by hamy-00** [nomacs/nomacs#402]
Hi
When opening any kind of image it works flawlessly in both normal and full screen
when i open it with Framless/hit F10 its shows full black on desktop..no image..nothing but black, even when zooming or moving.
 my laptop running:
Debian 10 
KDE plasma 5
nomacs 3.12
default compositor.

**Comment by diemmarkus** [comment]
thanks for reporting. the problem here is that some window managers do not support transparent rendering... however, we don't want to disable this feature because it is working on some distributions...
NOTE for me: we could add a warning when entering frameless mode on linux
