### ISSUE TITLE
Batch processing edit default profile

### ISSUE THREAD

**Issue by IanHydes** [nomacs/nomacs#403]
Hello, I'd like to edit the default profile as I generally use batch processing for downsizing images to email. I've created a new profile successfully and it retains my preferred settings but there doesn't appear to be a way to set the new profile as default or edit the original default profile.
Thanks for the great software, keep up the excellent work.

**Comment by diemmarkus** [comment]
the batch UI opens without any profile by default. the idea is, that you load any profile needed (after opening batch) - is that working?

**Comment by IanHydes** [comment]
Yes, the load profile method works, its just that is an extra level of clicking around compared to say, irfanview, which retains the settings from the last batch job. I was hoping there would be a way to alter the default profile.

**Comment by diemmarkus** [comment]
I fear that users would unintentionally manipulate images if a given profile is loaded on opening... I'll close it for now - but we can of course discuss this further...
