### ISSUE TITLE
Crop metadata is shown incorrectly

### ISSUE THREAD

**Issue by AlexDaniel** [nomacs/nomacs#405]
Some photos have crop metadata, it looks like this:

![image](https://user-images.githubusercontent.com/5507503/70949801-767f5c80-2067-11ea-8f91-f3c54199660b.png)

Nomacs is showing the crop location visually, which is an amazing feature. However, it ignores the `AlreadyApplied` field.

Someone [says](https://feedback.photoshop.com/photoshop_family/topics/why-cant-jpeg-originals-be-exported-with-an-xmp-sidecar):
> The AlreadyApplied field is supposed to be True when all the develop settings recorded in the XMP metadata have already been applied to the underlying JPEG image

So we end up with this result:

![nomacsbug](https://user-images.githubusercontent.com/5507503/70950180-88adca80-2068-11ea-8057-c44d2b033142.jpg)

Notice how it cuts into the watermark because the crop was already applied and nomacs is showing the crop on a photo that is already cropped. I think I'd prefer to see the crop location if metadata exists, but with AlreadyApplied the crop should be reversed (it should show the box outside the image).

**Comment by diemmarkus** [comment]
did not know that attribute, thanks!

**Comment by AlexDaniel** [comment]
@diemmarkus But don't we want to show the rectangle anyway? Looking at the code, it seems like it will simply ignore the crop rectangle if the operation was applied. But I always viewed nomacs as a slightly more advanced tool that gives you more information than other viewers. It'd be perfect if the crop rectangle was shown outside the image (to see which part of the original was actually cropped).

Here's a [sample image](https://user-images.githubusercontent.com/5507503/76545130-e26c3800-6491-11ea-973b-8fc8ee51e9db.jpg) you can use for testing. I don't currently have a better one where the crop rectangle is more dramatic.

**Comment by diemmarkus** [comment]
thanks for the sample image. 


> Looking at the code, it seems like it will simply ignore the crop rectangle if the operation was applied.
exactly - this was actually a bug because the crop rectangle is wrong if AlreadyApplied is true.

> But don't we want to show the rectangle anyway?
it appears to me, that the image is actually cropped if AlreadyApplied is true. is that correct?

**Comment by AlexDaniel** [comment]
> it appears to me, that the image is actually cropped if AlreadyApplied is true. is that correct?

Yes, it is cropped. However, it is possible to show the original image dimensions with the crop rectangle. Just to illustrate how that'd look:

![image](https://user-images.githubusercontent.com/5507503/76638474-2a07c800-6555-11ea-8e05-398284fd07db.png)

**Comment by diemmarkus** [comment]
I have the feeling that this would add more (visual) clutter than add information...

**Comment by AlexDaniel** [comment]
Well, the crop rectangle can already be toggled on/off in the settings.
