### ISSUE TITLE
Enhancement Suggestion: Opacity Fade Timer

### ISSUE THREAD

**Issue by eeik** [nomacs/nomacs#406]
Slideshow enhancement suggestion, to enable timer based (or binary step on/off ... min/max) fade support for Nomacs slideshow views where slideshow opacity has been altered.

Let's say two Nomacs slideshow instances are open side by side and have two other nomacs slideshows behind them from different directories ... in order to overlay or interleave directories into view, a 60 second revolving fade could be enabled on the top most Nomacs instance while the image beneath remains fixed at 100% opacity ... the fade then could be set to range in a linear fashion from 0% opacity to 100% opacity across the 60 second span ... 0% ... 100% ... 0% ... 100% ... etc. thereby showing and hiding an image atop the images in the fixed instances behind.

I was imagining a min opacity / max opacity setting to be added to the advanced settings area and a hotkey to "enable" / "disable" the opacity fade sequence...

... this does also introduce the idea that slideshow duration as a setting value might be nice to experiment with pulling forward into either a hotkey faster/slower option or a configurable manual entry that allows itself to be changed when "starting" a slideshow in some sort of obvious but not overly disturbing sort of way to allow, maybe for 3 seconds only, for the speed to be altered on a per-slideshow basis.

Thoughts?

**Comment by diemmarkus** [comment]
I am sorry, but the use case here is hard to understand or the feature is very specific to its context. Can't you create a folder with shortcuts that combines _folder A_ and _folder B_? Then, the normal slideshow fading would do the trick. 

If that does not fit your needs, you could think of creating a script that hits `Alt+J` at the defined time points...
