### ISSUE TITLE
[Feature Request] Detect file type without looking at file extension

### ISSUE THREAD

**Issue by molaeiali** [nomacs/nomacs#407]
**Is your feature request related to a problem? Please describe.**
I some times download some photos from a university website, that will not respect the file extension and rename the file to '_____' for example! I know that is a bug on their website, but until they fix it, I should always go and rename the file to '____.jpg' to be able to open it in nomacs.

**Describe the solution you'd like**
I would like the file type being detected by the file it self, not just reading the extension

**Describe alternatives you've considered**
I think it would be great if the file type is detected using 'file --mime-type' (??) or something else inside the programming language?

**Comment by diemmarkus** [comment]
this is related to #115
