### ISSUE TITLE
Missing iostream.h include breaks build with gcc >= 9

### ISSUE THREAD

**Issue by dvzrv** [nomacs/nomacs#408]
**Describe the bug**
When building 3.12 for Arch Linux the build breaks, because of a  missing include of `iostream.h`.
This has been fixed in #344 . It would be great, if this would be released in a new version.

**To Reproduce**
Build 3.12 using `exiv2 0.27.2`, `libraw 0.19.5`, `opencv 4.2.0`, `gcc 9.2.0`, `qt 5.14`.

**Expected behavior**
Build succeeds with gcc >= 9.

**Screenshots**
n.a.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: n.a.

**Additional context**
The  build log:
[nomacs-3.12-build.log](https://github.com/nomacs/nomacs/files/3991386/nomacs-3.12-build.log)

**Comment by diemmarkus** [comment]
I guess I can close this issue right?
