### ISSUE TITLE
make install still looks for dropped graphics file and hence fails

### ISSUE THREAD

**Issue by pmattern** [nomacs/nomacs#41]
In recent VCS checkouts `make install` invoked after successfully running `cmake .` and `make`, all in `./nomacs/ImageLounge/`, fails as it still looks for a file `nomacs.png` that was dropped a while ago:
```
[...]
CMake Error at cmake_install.cmake:76 (file):
  file INSTALL cannot find
  "/usr/local/peter/nomacs/ImageLounge/src/img/nomacs.png".
[...]
```

Bisecting suggests it's a regression introduced in e2ad387.

All tests on up to date Arch Linux x86_64.

**Comment by diemmarkus** [comment]
thanks!
