### ISSUE TITLE
Compiling DkImageStorage.cpp with opencv >= 4.2.0 fails

### ISSUE THREAD

**Issue by dvzrv** [nomacs/nomacs#410]
**Describe the bug**
When building 3.12 with opencv 4.2.0 the build fails due to a broken conversion from `cv::Point2d` to   `CvPoint2D32f`.

**To Reproduce**
Build 3.12 with fixes for [opencv >= 4.0.0](https://github.com/nomacs/nomacs-plugins/issues/26) and [gcc >= 9](https://github.com/nomacs/nomacs/issues/408) applied on top against opencv 4.2.0.

**Expected behavior**
The build succeeds.

**Screenshots**
n.a.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: n.a.

**Additional context**
Build log: 
[nomacs-3.12-build.log](https://github.com/nomacs/nomacs/files/3991662/nomacs-3.12-build.log)

**Comment by dvzrv** [comment]
Seems this is fixed with #409

**Comment by diemmarkus** [comment]
jup - I merged it today...
