### ISSUE TITLE
nomacs does not recognize .tif if this extension written in capital characters as .TIF !

### ISSUE THREAD

**Issue by Nokia808** [nomacs/nomacs#413]
I discovered that nomacs recognize .tif format if it is written in small characters as .tif
But if extension written in capital characters like .TIF then program will never recognize it & not opened ! 

No such thing with .JPG

I did not examine further formats ...

Please your kind fix.

**Comment by diemmarkus** [comment]
filtering extensions in nomacs is case insensitive. can you upload an example that cannot be opened?

**Comment by Nokia808** [comment]
@diemmarkus 
Hi. I did new test by the following:
1) I opened a jpg file by GIMP 
2) then export it to a tif 
3) finally I change extension into TIF 
4) tried to open the TIF file by your program, & it worked ! 
5) finally, I returned to problematic TIF file & tried to open it again by your program & again it failed !

So,yes, your program is really case insensitive & issue is file specific ! But the problem is that I can not give you the problematic file since it is a personal file (my passport) .......

**Comment by Nokia808** [comment]
@diemmarkus 
I tested issue on flatpak package (version 3.14). It is working without any error ! 
I do not know if error in old version 3.12 or from .rpm Fedora packager .....
I will close this issue.
