### ISSUE TITLE
Cannot remove "Notes" and "Rating"

### ISSUE THREAD

**Issue by DarkTrick** [nomacs/nomacs#414]
Reproduce
==========
- Open any image.
- Notes and Rating are shown.

Actual behaviour:
- There seems to be no option to hide notes and stars. They are always shown

Expected behaviour:
- There is an easy-to-find option (maybe a small 'x' in their top right) to hide Notes and Rating.

**Comment by diemmarkus** [comment]
you could hide it by pressing `I` (or Panels > File Info). Still I like the idea of an x in the corner...

**Comment by scrubbbbs** [comment]
Panel visibility is saved between launches, for some time now. There are options to hide them including view menu, context menu->view.
