### ISSUE TITLE
Option to hide "zoom percentage" in Fullscreen

### ISSUE THREAD

**Issue by R8s6** [nomacs/nomacs#415]
**Is your feature request related to a problem? Please describe.**

In version 3.12, the "zoom percentage" is shown even in fullscreen mode for about 3 seconds, which is distracting.

**Describe the solution you'd like**
An option to disable showing of this percentage.

**Describe alternatives you've considered**
Perhaps consider to completely disabling this option?

**Additional context**
screenshot:
![screenshot](https://i.imgur.com/3QlHGZS.png)

Thank you very much!

**Comment by diemmarkus** [comment]
thanks for reporting
