### ISSUE TITLE
nomacs shows files without authorization

### ISSUE THREAD

**Issue by whitis** [nomacs/nomacs#416]
nomacs ~/Downloads/*.jpg

Shows files I did NOT authorize, including .png when you hit the forward button.   You were not given permission to show any other files.  This is a privacy violation and it confuses things.   Same thing happens if you list a single file.  Same thing happens in "private" mode.  

ii  nomacs         3.8.0+dfsg-4 amd64        image viewer with capability of s
Ubuntu 18.04.2 LTS

**Comment by diemmarkus** [comment]
your command:
````
nomacs ~/Downloads/*.jpg
````
will hint nomacs to index the ~/Downloads folder (the *.jpg filter is ignored). 
- If you don't want images to be opened in nomacs (or any other software), you could actually change their permission using `chmod`.
- To only show images with a certain extension, there is a File > Find & Filter dialog in nomacs. Type *.jpg in this dialog & press Filter to only browse jpg files.
