### ISSUE TITLE
Swipe again to hide thumbnail and metadata

### ISSUE THREAD

**Issue by hsucherng** [nomacs/nomacs#418]
**Is your feature request related to a problem? Please describe.**
Gestures are convenient, and I like that I can do them with the mouse. While it's handy to be able to swipe up for thumbnails and swipe down for metadata, I'd also very much like to be able to easily hide them again so that I can get back to just viewing the image.

**Describe the solution you'd like**
When thumbnails are shown, swiping up should hide them. Similarly, when metadata is shown, swiping down should hide them.

**Describe alternatives you've considered**
Not sure... I thought about just hiding the thumbnails and metadata whenever nomacs is closed, or adding the option to disable swiping up and down, but both aren't as ideal.

**Additional context**
N/A

Thank you. :)

**Comment by diemmarkus** [comment]
this is already implemented. if you swipe up in the upper half of the window thumbails will be closed again. same applies for metadata (swipe down, starting from the lower half of the window)
