### ISSUE TITLE
Hola Florian, 

### ISSUE THREAD

**Issue by jotadoc** [nomacs/nomacs#421]
Quería hacer un pedido, si es posible para facilitar el manejo del programa, recién ayer comencé a usarlo. Me parece que un ícono o atajo de teclado que invoque el modo mosaico o miniatura de la carpeta en uso, en cada pantalla, sería excelente. Muchas Gracias !!!
Quiero volver al modo mosaico desde las diapositivas y no encuentro como hacerlo, disculpa. 
Saludos !!!

I wanted to make an order, if possible to facilitate the management of the program, just yesterday I started using it. It seems to me that an icon or keyboard shortcut that invokes the mosaic or thumbnail mode of the folder in use, on each screen, would be excellent. Thank you so much !!! I want to return to the mosaic mode from the slides and I can't find how to do it, excuse me. Regards !!!

josé castro
jotadoc@gmail.com
Santa Rosa, La Pampa
Argentina

**Comment by diemmarkus** [comment]
`Shift+T` will open the thumbnail preview. You can always customize shortcuts in `Edit > Keyboard Shortcuts`

cheers,
markus
