### ISSUE TITLE
add support for .7z and .rar, and fix .zip support.

### ISSUE THREAD

**Issue by wtfiwinomgs** [nomacs/nomacs#427]
currently .zip archive can be opened by nomac but if they are .gif files and any compression exist, nomac shows them as still images and no animation is played, please fix this!

also, please add .rar and .7z so nomac can also read them in the future, thank you!

**Comment by diemmarkus** [comment]
.rar and .7z won't be added in the near future since we would need to add and maintain additional packages, sorry!
