### ISSUE TITLE
Nomacs exits when trying to open images with extreme aspect ratios

### ISSUE THREAD

**Issue by milo2509** [nomacs/nomacs#428]
This certainly requires further investigation and I'm pretty sure it has something to do with the window size vs image size pixel-wise and zoom levels.

Windows 10, screen resolution 1920 x 1080

Steps to reproduce:
- create images with sizes 1 x 1986 and 1 x 1987 or 3840 x 1 and 3841 x 1 and open them

(now this will probably depend on the "zoom when opening new images" setting)

- smaller image displays fine, larger one opens but then suddenly closes program window
- if window fills entire screen while opening the smaller image, resizing it will shut down Nomacs as well - unless you zoom in first

**Comment by diemmarkus** [comment]
I have recently experienced this issue in the current beta too. It is most probably related to anti-aliasing. so disabling anti-aliasing (A) could temporarily fix this issue.
