### ISSUE TITLE
New Release soon

### ISSUE THREAD

**Issue by agaida** [nomacs/nomacs#429]
Hi, is it possible to issue a new release soon? The current one don't build in Debian/Sid anymore for some reasons, master do.

**To Reproduce**
1. Install a current sid
2. get the sources: apt sources nomacs
3. Try to build and have fun

**Expected behavior**
It should build

**Build log and RC bug**
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=950310

**Desktop (please complete the following information):**
 - OS: Debian Sid

**Additional context**
I'm not eager to patch the old release - did the include dance (mentioned in the bug) too - and it still don't work. The current code from master do - so a waste of my time if i would dig deeper.

**Comment by diemmarkus** [comment]
sure...
there are still a few issues in the current master, which I would like to fix before releasing.
I will update progress here...

**Comment by diemmarkus** [comment]
hope it was soon enough : )
