### ISSUE TITLE
Slideshow stops on .xml, .pp3... files from Darktable, RawTherpee...

### ISSUE THREAD

**Issue by Francois-C** [nomacs/nomacs#430]
V 3.12.1.4206 Windows 64 portable.

When the slideshow stumbles on a text file from a processing software, nomacs tries to read it, then stops slideshow with error message: 'Sorry, I could not load xxx.xml'. Maybe text file extensions should be excluded?

Thanks for the great and neat software.

**Comment by diemmarkus** [comment]
you could check if XML is listed in the File Associations (`Edit` > `Settings` > `File Associations`)

**Comment by diemmarkus** [comment]
closing issue for this should be configurable in the preferences...
