### ISSUE TITLE
Nomacs doesn't crop any more, it seems

### ISSUE THREAD

**Issue by JimH44** [nomacs/nomacs#432]
I'm running version 3.8 on Ubuntu Linux 18.04.
I was cropping easily, but then Nomacs stopped cropping.
I click the crop button (the shortcut "C" doesn't work) or open Adjustments and select Crop Image. Then I select an area, either unconstrained or set to 16:9 ratio, and then click the other Crop button or tap Enter, and now, instead of cropping to my selection, the crop disappears.
I hope there is a fix, because Nomacs used to be easier than The GIMP for cropping.
Thanks for thinking about this problem,
Jim
--
Jim.Henderson44@gmail.com

**Comment by diemmarkus** [comment]
does the crop button in the menu work for you?
![img-2020-02-18 16 22 08](https://user-images.githubusercontent.com/4182443/74749787-fba30f80-526a-11ea-9f36-9a1a50abd6a6.png)

**Comment by JimH44** [comment]
Sorry about the delay.
No, when I type "c" and select an area, and then I can see that crop button and click it, the selection disappears. I was expecting the area around the selection to disappear.
Similarly, when I have the area selected and tap Enter or double-click the selection, the same happens, the selection disappears, leaving the image as it was before I typed "c" for Adjustments->Cr_o_p Image.
The same problem is reported at [nomacs.org/questions-and-answers/](https://nomacs.org/questions-and-answers/). Search for the word "crop" to see people's comments.
Is there a howto document that describes how to crop an image, keeping just a part of it?

**Comment by diemmarkus** [comment]
I just tested this with nomacs 3.8 and ubuntu 18.04. crop is working as expected on my end. can you export your settings (Edit > Settings > Export Settings) and send them to us (developer@nomacs.org)?

**Comment by JimH44** [comment]
I sent the settings file a couple of days ago. I hope you received it OK.

**Comment by diemmarkus** [comment]
no, sorry! you can try sending it to diemmarkus [at] gmail.com

**Comment by JimH44** [comment]
Ok, I sent it on March 20. Did it arrive?
Thanks again for thinking about this.

**Comment by diemmarkus** [comment]
thanks for the reminder. I checked your settings - nothing suspicious. recently we released nomacs through [flathub](https://flathub.org/apps/details/org.nomacs.ImageLounge). you could try by installing this (most recent) version.

**Comment by JimH44** [comment]
Thanks Markus,
I clicked on Install at the link you sent and opened the flatpack file. It said my Nomacs was up-to-date.
I tried the program again, same problem.
Then I noticed that "Crop to metadata" was turned on. I turned it off, and that solved the problem :-) I can now click the crop button in the toolbar, select and area and tap Enter, and the image is cropped to the selection :-)
What does "Crop to metadata" mean anyway?

**Comment by diemmarkus** [comment]
ah ok - I guess we can close this now. crop to metadata means, that the coordinates are saved in the image metadata. software like photoshop (or your own software) can than apply this cropping later on. this feature is especially useful if you batch process a lot of images...
