### ISSUE TITLE
Certain types of .tga not working

### ISSUE THREAD

**Issue by fcore117** [nomacs/nomacs#433]
Cannot open .tga if it is not bug i would appreciate if you support it in future.
sample here:

[T_fence_base_AO.zip](https://github.com/nomacs/nomacs/files/4209817/T_fence_base_AO.zip)

**Comment by diemmarkus** [comment]
I will check it, thanks!

**Comment by diemmarkus** [comment]
this is related to #362 -> we currently only support 32-bit TGA files, sorry.

**Comment by fcore117** [comment]
Will there ever plan to support these types of formats? they are mostly used in texture&3D industry

**Comment by diemmarkus** [comment]
good question - not in the near future because it's not straight forward.
