### ISSUE TITLE
.jpe is shown as thumbnail in full image view

### ISSUE THREAD

**Issue by gerroon** [nomacs/nomacs#435]
Hi

It seems like when Nomacs opens a  .jpe format  it shows the embedded thumbnail instead of the actual image.

Please test it with the attached image.

I am using it on Windows 10 3.12.1.4206

thanks

[RevM3DA%2006_13_p0.zip](https://github.com/nomacs/nomacs/files/4240672/RevM3DA.2006_13_p0.zip)

**Comment by diemmarkus** [comment]
thanks for reporting!
It is fixed in upcoming releases. But there is a temporary fix for nomacs 3.12 or 3.14: 
check: ``Settings > Advanced > Load JPG if it Fits the Screen Resolution``

(nomacs wrongly treated _jpe_ as RAW images)
