### ISSUE TITLE
so,where is the Simplified Chinese in new version？

### ISSUE THREAD

**Issue by dashuigang** [nomacs/nomacs#439]
### just Traditional Chinese i can choice 

![捕获](https://user-images.githubusercontent.com/51685445/76853100-a6691680-6887-11ea-9ae3-7eb5a22c7366.JPG)

**Comment by diemmarkus** [comment]
we had some issues with translations lately, sorry!
quick fix: 
- download the translation: [nomacs_zh_CN.zip](https://github.com/nomacs/nomacs/files/4343402/nomacs_zh_CN.zip)
- extract it
- copy the `nomacs_zh_CN.qm` to `C:\Program Files\nomacs\bin\translations`

it will then be listed in the settings:
![img-2020-03-17 13 24 25](https://user-images.githubusercontent.com/4182443/76856007-a569c200-6852-11ea-994f-f6751cea6a8d.png)

**Comment by dashuigang** [comment]
thank you very much，and i change the the file in page just now ，dont let my changed pass，just forget it
