### ISSUE TITLE
Build fails with Quazip disabled

### ISSUE THREAD

**Issue by kensington** [nomacs/nomacs#44]
DkImageLoader.cpp:515:120: error: ‘class nmc::DkImageContainerT’ has no member named ‘getZipData’
  if (mCurrentImage && (newFileIdx < 0 || newFileIdx >= mImages.size()) && mCurrentImage->isFromZip() && mCurrentImage->getZipData()) {

**Comment by kensington** [comment]
Ifdefing the block in DkImageLoader.cpp causes build to pass, but I'm not sure if that's the correct solution or not.

```
+       #ifdef WITH_QUAZIP
        if (mCurrentImage && (newFileIdx < 0 || newFileIdx >= mImages.size()) && mCurrentImage->isFromZip() && mCurrentImage->getZipData()) {
 
                // load the zip again and go on from there
@@ -523,6 +524,7 @@ QSharedPointer<DkImageContainerT> DkImageLoader::getSkippedImage(int skipIdx, bo
 
                return getSkippedImage(newFileIdx);
        }
+       #endif
```

**Comment by diemmarkus** [comment]
I guess that should do the trick - the problem is, that we do not frequently compile nomacs without these dependencies : ) - thank you! (shall I fix it or do you want to send a pull request)?

**Comment by kensington** [comment]
Whichever is easier for you.

**Comment by diemmarkus** [comment]
since I broke the current master on linux due to some project reorganization, I fixed it... (the master should work again within the next couple of days) thanks again!
