### ISSUE TITLE
3.14 broke SVG support

### ISSUE THREAD

**Issue by Mintonne** [nomacs/nomacs#440]
**Describe the bug**
Just updated to 3.14 and reopened a SVG file I had open and nomacs no longer displays it. I have confirmed the file is not corrupted

**To Reproduce**

Open a SVG file

**Expected behavior**

SVG file should be displayed.

**Screenshots**

![image](https://user-images.githubusercontent.com/39894801/76879023-b7655800-6886-11ea-91ca-4cf6fda797e0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1909

**Comment by diemmarkus** [comment]
can you try loading this svg (which works for me):
[nomacs.zip](https://github.com/nomacs/nomacs/files/4345351/nomacs.zip)

given that our logo is loaded correctly on your system, can you send us a sample of an svg that does not open correctly?

**Comment by Mintonne** [comment]
I was not able to open the file.

I did a clean nomacs install but that did not fix it. I also tried in a sandbox and that did not work too.

**Comment by Nostaljaded** [comment]
Same issue as Mintonne, but on Win7.

Same error message with your attached nomacs svg logo on 3.14 portable version, no svg issue for currently-installed 3.12 version.

**Comment by diemmarkus** [comment]
ok thanks, I'll investigate it...

**Comment by diemmarkus** [comment]
I found the issue (I linked the qsvg.dll wrong - sorry!)
A patched installer will be shipped today...

**Comment by diemmarkus** [comment]
The patch is released now [available](https://github.com/nomacs/nomacs/releases/latest/download/nomacs-setup-x64.msi) can you please check if SVG loading works now?

**Comment by Mintonne** [comment]
> Can you please check if SVG loading works now?

It works. SVG files are loaded successfully.

I do keep getting this error when I open SVG files.

![image](https://user-images.githubusercontent.com/39894801/76984368-cd8b1b00-694f-11ea-995f-b555c32445ce.png)

The file is displayed correctly. Trying to move to the next/previous image does not work.

![BskVgjKhm7](https://user-images.githubusercontent.com/39894801/76983936-3b831280-694f-11ea-86ea-76486aabc10b.gif)

I am able to cycle through `png` and `jpeg` files just fine.

**Comment by diemmarkus** [comment]
this might be related to file filters. can you check if it is in the list `Edit > Settings > File Associations`?
![img-2020-03-18 19 44 09](https://user-images.githubusercontent.com/4182443/76995985-0081de80-6951-11ea-99b2-65339f178094.png)

If it is there, checking Browse should fix the issue. If it's not there, I would recommend to wipe your settings:
- Open a windows explorer and type `%appdata%`
- open nomacs/ImageLounge
- rename `settings.ini` to `settings-old.ini`

**Comment by Mintonne** [comment]
That fixed it. `Browse` was unchecked.
