### ISSUE TITLE
[Feature request] Add support for saving output file as PDF

### ISSUE THREAD

**Issue by Nokia808** [nomacs/nomacs#442]
I noticed that nomacs currently not support save output file as PDF.

I would like to suggest to add support saving output file as PDF format in both "Save as" & "Convert" option in batch processing. This will be useful.

I'm not sure is this compatible with aims of nomacs or not. Feel free to close this issue if not.

**Comment by diemmarkus** [comment]
Though it is a nice feature (and pretty straight forward to add), I think it does not fit an image viewer. + there are plenty of good tools out there, which can create PDFs from multiple images.
