### ISSUE TITLE
nomacs crashes when trying to start batch resize

### ISSUE THREAD

**Issue by meilon** [nomacs/nomacs#445]
**Describe the bug**
nomacs crashes after ticking the checkbox for batch resizing on windows

**To Reproduce**
1. Go to Tools > Batch Processing
2. Select one or more images (doesn't matter the number or file type of the images)
3. Click on Adjustments
4. Try to tick the checkbox next to Resize

**Expected behavior**
App lets me continue with the workflow

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1903, latest updates

**Additional context**
Here the APPCRASH details from the event log:
P1: nomacs.exe
P2: 3.14.2.4827
P3: 5e71eb3f
P4: Qt5Widgets.dll
P5: 5.13.0.0
P6: 5d4c1be5
P7: c0000005
P8: 000000000004c95c
P9: 
P10:

**Comment by diemmarkus** [comment]
confirmed - thanks for reporting
