### ISSUE TITLE
Setting QT_SCALE_FACTOR breaks UI

### ISSUE THREAD

**Issue by morfikov** [nomacs/nomacs#450]
When the `QT_SCALE_FACTOR` env variable is set to `1` , everything is fine with nomacs UI, but when I set it to something different like `1.125` or `2` then the UI looks like this.

![nomacs](https://user-images.githubusercontent.com/3797768/77160863-32ee2180-6aa0-11ea-9b6d-cf9e3e75b474.png)

I have many other QT apps which behave normally when I use the following QT vars:

```
$ env | grep QT
QT_ACCESSIBILITY=1
QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_QPA_PLATFORMTHEME=qt5ct
QT_SCALE_FACTOR=1.125
```

Sysinfo:
Debian sid, standalone Openbox/Xserver.

```
$ nomacs -v
qt5ct: using qt5ct plugin
[INFO] Hi there
Image Lounge 3.12
```

**Comment by diemmarkus** [comment]
this could be related to #277 
Maybe it's best if you try 3.14, which is available on [flathub](https://flathub.org/apps/details/org.nomacs.ImageLounge) since today.

**Comment by morfikov** [comment]
I'll try to build the newer version and see whether that helps. I'll get back to this when I test it.

**Comment by morfikov** [comment]
I just installed the newer version:

```
$ nomacs -v
qt5ct: using qt5ct plugin
[INFO] Hi there
Image Lounge 3.14
```

Still the same issue.

**Comment by geckolinux** [comment]
Hi there, I'm the creator of bug #464. It looks like the package I use from openSUSE isn't built with qt5ct support? I'm not sure if that would make a difference?

``````````
nomacs -v
[INFO] Hi there
Image Lounge 3.14

**Comment by diemmarkus** [comment]
> Still the same issue.

since I am having a hard time reproducing/understanding the issue. could you try if applying the system theme changes anything? (Edit > Settings > General > System)

**Comment by morfikov** [comment]
I've just built using the latest git, and it looks like the problem was fixed.

**Comment by diemmarkus** [comment]
cool, thanks!
