### ISSUE TITLE
Nomacs crashes when enabling resize in batch processing dialog

### ISSUE THREAD

**Issue by sfiel** [nomacs/nomacs#452]
**Describe the bug**
Crash when trying to enable the resizing in batch processing dialog, all other adjustments can be enabled

**To Reproduce**
1. Go to Batchprocessing
2. Click on adjustments
2. Click on Resize
4. Watch nomacs crash :)

**Desktop (please complete the following information):**
 - OS: Windows 10

nomacs vers. 3.14.0.4805

Liebe Grüße :)

**Comment by b3n3n** [comment]
I have the same problem!
Nomacs 3.14.2.4827 x64 
I'm running it under windows 10 1809

**Comment by diemmarkus** [comment]
thx : )
this duplicates #445 right?

**Comment by b3n3n** [comment]
yes, but I think I have closed it after seeing this one :)

**Comment by diemmarkus** [comment]
fixed in the current master...
