### ISSUE TITLE
add qt4 compatibility

### ISSUE THREAD

**Issue by rtlanceroad** [nomacs/nomacs#46]

**Comment by diemmarkus** [comment]
nomacs does not support Qt4 anymore (since maintaining 2 Qt distributions is not necessarily a coders heaven) - so if you definitely need Qt4 I would recommend to go with nomacs 2.4: https://github.com/nomacs/nomacs/tree/2.4

**Comment by rtlanceroad** [comment]
The reason why I ask for this is because some distros have not prepared for qt5 imigration yet.
