### ISSUE TITLE
Add SSL support

### ISSUE THREAD

**Issue by eddmy** [nomacs/nomacs#460]
Windows 10
Nomacs 3.12.1.4206 (x64)

file > open > https://cdn.svgporn.com/logos/now.svg

Freeze

**Comment by diemmarkus** [comment]
freezing is strange. nomacs is missing openssl - that's why it should just display an error message...

**Comment by eddmy** [comment]
Yes, SSL support would be a very much appreciated feature !

**Comment by diemmarkus** [comment]
done
