### ISSUE TITLE
Crop tool coordinates not zero-based

### ISSUE THREAD

**Issue by lkrms** [nomacs/nomacs#462]
When cropping an image, the correct x and y coordinates of the selected region are displayed in the tooltip (assuming the top-left of the image is 0,0), but the coordinates in the cropping toolbar represent the centre point of the selected region.

To illustrate:

<img width="854" alt="Screen Shot 2020-04-08 at 12 41 15 am" src="https://user-images.githubusercontent.com/2563783/78683146-47e90280-7932-11ea-9fd0-1534fa8079b6.png">

And when coordinates of 0,0 are applied, the selected region moves as follows:

<img width="792" alt="Screen Shot 2020-04-08 at 12 41 46 am" src="https://user-images.githubusercontent.com/2563783/78683160-4d464d00-7932-11ea-9908-fae7c7e991fb.png">

This isn't the behaviour I'd expect, but if it's by design, I apologise for the bug report.

I'm running nomacs 3.14.2 on Arch Linux.

Thank you for all of your work on nomacs :)

**Comment by diemmarkus** [comment]
I totally agree that this might be counter-intuitive, but we need to report the center if the rectangle is rotated. a new crop tool (#345) that transforms the image rather than the rectangle would resolve these issues.

**Comment by lkrms** [comment]
That makes sense. It hadn't occurred to me that the coordinates would be irrelevant with a rotated selection (I don't use this feature myself).

I'm guessing the same limitations would apply to "snapping" to 0,0? (This seems to work when dragging the resize handles, but not when moving the selection). It seems the only way to crop to an exact size while also having the origin at 0,0 is with precise mouse movement (time consuming).

Anyway, it's certainly not a dealbreaker, and I'm glad a new tool is in the works.

Thanks again for this excellent software!

**Comment by diemmarkus** [comment]
> That makes sense. It hadn't occurred to me that the coordinates would be irrelevant with a rotated selection (I don't use this feature myself).

jup

> (This seems to work when dragging the resize handles, but not when moving the selection). It seems the only way to crop to an exact size while also having the origin at 0,0 is with precise mouse movement (time consuming).

there is another option (my favorite): you can start dragging outside the image. the crop rectangle is then bound to the image border:

![2020-04-08 13-52-39](https://user-images.githubusercontent.com/4182443/78781393-79001c00-79a0-11ea-96a4-e3c0b2a7723c.gif)
