### ISSUE TITLE
Segmentation fault on Profile Load or Save 

### ISSUE THREAD

**Issue by hansaplasst** [nomacs/nomacs#463]
**Describe the bug**
When opening or saving/writing a Profile in Batch mode nomacs crashes with a Segmentation fault

**To Reproduce**
1. Go to 'Tools - Batch Processing'
2. Click on 'Profiles'
3. Choose 'Default' (or 'Create New Profile' - 'OK')
4. Error: 'Segmentation fault (core dumped)'

**Expected behavior**
Trivial. It should not do that.

**Desktop (please complete the following information):**
- Linux [hostname] 5.3.0-45-generic #37-Ubuntu SMP Thu Mar 26 20:41:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
- Version: Image Lounge 3.12
- Cannot find the debug switch for detailed logging.

**Comment by diemmarkus** [comment]
> Trivial. It should not do that.

I like that line : ) - thanks for reporting!
Unfortunately, I cannot reproduce it on Windows - I will try it with Ubuntu later... in the meantime you could test if this issue still exists with nomacs 3.14 using [flathub](https://flathub.org/apps/details/org.nomacs.ImageLounge)...

**Comment by hansaplasst** [comment]
Hi Markus,
3.14 doesn't have this problem. The Github build works for me. 
Thanks!
