### ISSUE TITLE
JPEG file size estimate depends on size of dialog box

### ISSUE THREAD

**Issue by Daniel-Beardsmore** [nomacs/nomacs#467]
When saving an image as a JPEG (JPEG or JPEG 2000), the estimated size of the resulting image file is proportional to the size of the dialog box in which you choose the image quality. As you resize that dialog box, the estimate changes accordingly.

Steps to reproduce:

1. Open any fairly large image (e.g. screen-size)
2. File → Save As
3. Set the file type as JPEG or JPEG 2000, and click Save
4. The _JPG Settings_ or _J2K Settings_ dialog box appears: observe the File Size readout at the bottom right (which will give a totally bogus figure, such as a simple 236 kB PNG being estimated at ~310 kB in medium quality; actual result was 73 kB)
5. Change the size of the JPG Settings or J2K Settings dialog box and observe that the estimate decreases as the window shrinks, and increases as the window shrinks

My attention was drawn to this initially not because of the window resizing bug, but because the initial estimate was clearly false, as it could not possibly be significantly larger than that of the PNG original.

nomacs version 3.14.2.4827 (current at time of writing), Windows Server 2016 RDS environment (build 14393), equivalent to Windows 10 64-bit.

**Comment by diemmarkus** [comment]
We estimate the file size from the patch that is compressed and displayed in the dialog. Hence, the bigger the Window, the better the estimate. I think there is no straight forward solution to improve this behavior while keeping a low CPU profile.

**Comment by Daniel-Beardsmore** [comment]
The problem is that the estimate can be miles out. I was really confused when I got an estimate that was 30% greater than the size of the PNG file that I had open. The estimate is so worthless under those conditions it is not even useful to show it, and may result in users lowering the quality excessively in an attempt to combat the indicated file size bloat that will not really occur.

What kind of CPU profile are you targeting where compressing a JPEG image is that slow? If there is a desired finite time limit on the calculation, is it possible for the worker thread running the calculation to be allotted a certain number of milliseconds (e.g. 500 or 1000), and report back whatever compression ratio it achieved from however much of the image it processed within that time slot? That is, base the limiting factor on the computer, not on the size of the window. The window size has no relationship of any kind with the CPU, and as the window defaults to a very small size, it starts out with a very wrong estimate accordingly.

**Comment by diemmarkus** [comment]
>  The window size has no relationship of any kind with the CPU,

it does: currently this estimation is a byproduct of something that we compute anyhow (the preview which is related to the window size) - so there is 0 extra CPU load (j2k compression pretty heavy btw). maybe we could think about adopting the dialog's size to the screen resolution, which improves the estimation anyhow...

**Comment by Daniel-Beardsmore** [comment]
The window size has no relationship with the performance of the CPU.

JPEG encoding on the remote desktop server I am using (Xeon E5-2690) is fast enough that you can resize the JPG Settings window in real time (over RDP) and it can redraw the preview perfectly fast. There is more than enough CPU time to compress more of the image to get a proper estimate of file size.

JPEG 2000 does indeed take more CPU time. However, with the processing moved to a background thread (for both JPEG and JPEG 2000), the program could calculate the estimate without interfering with the UI, and the estimate would show as “Calculating …” while sufficient time elapses. There is no reason why the image cannot be drawn uncompressed during the window resizing (to keep up with the UI) and revert to its compressed form once enough time has elapsed to present it. The image could be dimmed in its uncompressed form to show that it is simply a placeholder.

**Comment by diemmarkus** [comment]
> The window size has no relationship with the performance of the CPU.

I know : ) BUT: the bigger the window, the bigger the preview, the more CPU load we have...! pooling the computation is a good idea (i think it's not pooled yet because this is very ancient code...)

I'll close this issue now - as the todo's are clear here
