### ISSUE TITLE
Resize Image dialog does not resize correctly

### ISSUE THREAD

**Issue by Daniel-Beardsmore** [nomacs/nomacs#468]
The Resize Image dialog box (Adjustments → Resize Image, too easy to confuse with the truly bizarre Adjustments → Resize) does not resize correctly.

There are two panels within the dialog box: one shows the original image, and the other shows the image as it would appear following a resize.

When the dialog box is resized, this second (right-hand) pane does not resize. Changing one of the parameters within the window causes it to be redrawn and at that point, it will jump into position.

nomacs version 3.14.2.4827 (current at time of writing), Windows Server 2016 RDS environment (build 14393), equivalent to Windows 10 64-bit.

**Comment by diemmarkus** [comment]
that's a bug, thanks for reporting!

>  too easy to confuse with the truly bizarre Adjustments → Resize

that one is maximally simple - while the dialog you mean is intended for advanced users...

**Comment by Daniel-Beardsmore** [comment]
The problem is having resize twice in the same menu, with the castrated version more prominent. I didn’t think to look in the same menu for a second resize command.

**Comment by diemmarkus** [comment]
> castrated version

😄 

that's fair - I'll try to improve that...
