### ISSUE TITLE
HEIC not working 3.14.2.2 in linux

### ISSUE THREAD

**Issue by jw323** [nomacs/nomacs#469]
nomacs unable to load HEIC\HEIF image

Install nomacs 3.14. pacman -S nomacs, which installs nomacs 3.14.2-2
Open HEIC\HEIF image

Tried this using the latest Arch. Also tried using the flatpak image.

Is something else required? I don't see any documentation that I need to install something else.

**Comment by diemmarkus** [comment]
you need to install the [heif plugin](https://github.com/jakar/qt-heif-image-plugin).
but you're right, we could add this to the flatpak.

> Is something else required? I don't see any documentation that I need to install something else

would it be enough if we add this to the `README`?

**Comment by jw323** [comment]
Thanks, its working with qt-heif-image-plugin. I just had the regular libheif1 installed before..

Yes adding to the README would be good. Maybe the downloads page on your website?

**Comment by chaserene** [comment]
how can I add the plugin to a Flatpak installation of Nomacs?

**Comment by geroldmeisinger** [comment]
you can manually the .deb here: https://github.com/jakar/qt-heif-image-plugin/releases/tag/0.3.3
