### ISSUE TITLE
Improved SVG support/replacement SVG renderer

### ISSUE THREAD

**Issue by Daniel-Beardsmore** [nomacs/nomacs#470]
It seems that the Qt SVG renderer (also used by the SVG Explorer Extension for Windows) is pretty limited. It does not seem to recognise line breaks in text, and it does not understand blur. Sometimes it ignores clones, and I don’t know why, as that’s not consistent. It also does not correctly clip to the page box: some items just off the edge of the page creep into the frame.

I’ve attached a couple of images from Inkscape 0.93. One is “Inkscape SVG” and the other is “Plain SVG”.

The flowed text box does not work anywhere (not nomamcs, not Firefox, not Chrome and not MSIE). The manually-wrapped text appears in nomacs but without any line breaks. The circles should appear blurred, but do not.

I figured that this behaviour within SVG Explorer Extension is because it is old and largely abandoned (but irreplaceable) but it seems Qt is just bad at SVG!

I sometimes use rsvg-view-3 in Windows as a quick SVG viewer. This understands SVG a lot better, but rsvg’s typography handling is abysmal (same problem when putting SVGs into MediaWiki as that also butchers them with rsvg to needlessly make PNGs out of them), but it too does not understand whatever Inkscape does with flowed text (giving me a black box instead).

Browser SVG support by and large matches anything I draw in Inkscape (give or take a few glitches in IE/Edge and the lack of gradient mesh support), so maybe there is some alternative option for nomacs that is not as limited as Qt. (It would be nice to have a decent SVG thumbnail renderer in Windows, too; all that exists for that is Qt too … so I have a lot of mangled and weird thumbnails as a result.)

[Test images.zip](https://github.com/nomacs/nomacs/files/4492928/Test.images.zip)

**Comment by diemmarkus** [comment]
Qt does not have the best SVG support one could wish for. I already investigated this issue and there is no straight forward (light-weight) solution to this issue. Similar to the RAW support, I would recommend to regard nomacs as a nice-to-have quick preview and use dedicated software for anything else.

Thanks for providing test samples. Both SVG's have errors if validated with [W3C](https://validator.w3.org/):
``nomacs test, Inkscape SVG.svg``
````
Error Line 93, Column 74: SVG element flowRoot not allowed as child of SVG element g in this context. (Suppressing further errors from this subtree.)
… transform="matrix(0.26458334,0,0,0.26458334,-4.2333334,160.21042)"><flowRegion
````
``nomacs test, plain SVG.svg``
````
 Line 69, Column 28: SVG element flowRoot not allowed as child of SVG element g in this context. (Suppressing further errors from this subtree.)
       xml:space="preserve"><flowRegion
````
related issues: #291 #322
