### ISSUE TITLE
Frameless

### ISSUE THREAD

**Issue by KraXen72** [nomacs/nomacs#471]
the frameless is really weird  
sometimes i can get true frameless without any other elements. This is expected behaviour.   
BUT  
sometimes i get this background dim. Is it possible to remove it/reliably get frameless without the background dim?
thank you

**Comment by diemmarkus** [comment]
does the `dim background` look like this?

![img-2020-04-21 13 05 55](https://user-images.githubusercontent.com/4182443/79859163-e19fbd80-83d0-11ea-9463-ea79dd32bf9d.png)

**Comment by KraXen72** [comment]
yes, i want to have a way to consistently achieve frameless without this background dim (i use frameless to view multiple images at once and it doesen't make sense if they are different opacity because of the dim from other images)

**Comment by diemmarkus** [comment]
this is the `fullscreen/presenter` view. nomacs could have entered it if you unintentionally double clicked an image. This can be disabled by unchecking `Double Click Opens Fullscreen` in Edit > Settings.
please let me know if that solves the issue.

**Comment by KraXen72** [comment]
![image](https://user-images.githubusercontent.com/21956756/79861166-414b9800-83d4-11ea-9d1a-fa03b5ccc8c5.png) this is before

this is after:
![image](https://user-images.githubusercontent.com/21956756/79861319-87086080-83d4-11ea-8ae2-3a244878dd06.png)

i got this on first try, thank you, but does this work reliably - will i never get that dim?
thank you

**Comment by KraXen72** [comment]
i think i know
when you are selecting monitors , and you click on the selected monitor,  it goes into this:
![image](https://user-images.githubusercontent.com/21956756/79861464-bb7c1c80-83d4-11ea-99e3-5a612f11b834.png)
is that the intended behaviour? can i fully disable the presenter view?

**Comment by diemmarkus** [comment]
once you close nomacs in presenter view, it will remember that state. But you can easily exit the presenter view by hitting ESC.

**Comment by KraXen72** [comment]
but then a toolbar and sidebar appears:
![image](https://user-images.githubusercontent.com/21956756/79861913-7c020000-83d5-11ea-8faf-ad8c14f7fc6a.png)
i don't want that, i want to reliably achieve this:
![image](https://user-images.githubusercontent.com/21956756/79861943-891eef00-83d5-11ea-90d4-d0acf6c12159.png)

**Comment by diemmarkus** [comment]
- the menubar should disappear after a few seconds
- press (T) to hide the thumnails or (F) to hide all panels

**Comment by KraXen72** [comment]
thank you, pressing t Worked, but i still have the menubar. Any solution?

**Comment by KraXen72** [comment]
it dissapears - and if not, its not that big of a deal. Thank you for help, diemmarkus.
