### ISSUE TITLE
Add "Extract Multipage PCX" functinality

### ISSUE THREAD

**Issue by Nokia808** [nomacs/nomacs#473]
Hi. At this time when you add support for .pcx file format, it is suitable to asking for this feature.

PCX format, like that for TIFF, could be a multipage file. So, it will be very useful if nomacs has "Extract Multipage PCX" feature added to it to be corresponding to "Extract Multipage TIFF" already existing feature under "Tools".

Thank you for your hard efforts to develop this great program which is really Irfanview of Linux ....

**Comment by diemmarkus** [comment]
could you provide such a file? - from reading the docs of [libqpcx](https://github.com/roniemartinez/libqpcx) it appears, that only the first image is loaded in this case...

**Comment by Nokia808** [comment]
@diemmarkus 
Kindly, wait me please for several days, because I need a Windows PC to generate it ..... Currently, I have no such device.

**Comment by Nokia808** [comment]
@diemmarkus 
Hi. Today I got Windows machine from my friend. Really I'm sorry! It seem that I was confused with other format called .JMP 
When I was on Windows OS, I was using Irfanview, which allow to create 3 multipages formats (.TIFF, .PDF, .JMP)
I will close this issue. 
Kindly, accept my apologize ....
