### ISSUE TITLE
.zip archives do not loop

### ISSUE THREAD

**Issue by heyytonytony** [nomacs/nomacs#475]
**Describe the bug**
When viewing .zip archives, navigating BACK from the first image or FORWARD from the last image moves focus to the next file in the archive's parent folder instead of looping the image inside the archive.

**To Reproduce**
setup - folder with a .zip and another image file (e.g., a .jpg) [nb: this setup's just to better demonstrate the behaviour, a .zip archive on it's own is fine too]
1. open .zip archive with nomacs
2. navigate BACK from the first image

**Expected behavior**
display shows the last image in the archive

**Actual behaviour**
display shows the .jpg image in the archive's parent folder

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Microsoft Windows Version 1909 (OS Build 18363.778)
 - nomacs v. 3.14.0.4805 [x64]

**Additional context**
To expand on the nb above - an attempt to navigate BACK from the first image in a .zip archive that's in a folder without any other images in it will "break" the archive viewer, i.e. it won't be able to navigate forwards to the next image in the archive anymore.  From the behaviour when there _is_ another image in the parent folder, this seems to be because the navigation context has moved from within the archive to the parent folder, i.e. now it is trying to open the next .zip as an image.

A tangential feature request (that would break this looping scenario, but be an alternative implementation to navigation) might be for nomacs to support drilling into archives at the parent folder level, e.g.:
```
EXPORT /
    SPLASH.JPG
    CONTENT00.ZIP
    CONTENT01.ZIP
    ENDCARD.JPG
```
Opening the EXPORT folder in nomacs would show SPLASH.JPG, then all the contents of CONTENT00.ZIP, then CONTENT01.ZIP, then ENDCARD.JPG, and then loop back to SPLASH.JPG.

This is beyond the scope of the bug, and would fall under some kind of folder navigation feature request, though.  Included here for overzealous context :^)

**Comment by diemmarkus** [comment]
Hi,

this is partially intended behavior. If you open `Edit > Settings > File Associations` and check Browse for ZIP archive, the behavior will be exactly what you were asking for in additional context (browsing through the parent dir, then into the zip and so on...). 

But you are right, I will add looping if browse zip is not turned on - because the current behavior is not intuitive...

**Comment by heyytonytony** [comment]
Ahhhh, thanks!  I completely missed the `.zip` file association option x)

cheers
