### ISSUE TITLE
taskbar icon visible only in first instance

### ISSUE THREAD

**Issue by deathtrip** [nomacs/nomacs#48]
When i open multiple images, the taskbar icon is only visible in the instance that was launched first.
I use the latest KDE on Arch Linux and Nomacs 3.0.

**Comment by sfiel** [comment]
This issue does not exist on Kubuntu and on XFCE on archlinux ... it will take some time until I can test it on KDE on Arch

Thanks

**Comment by deathtrip** [comment]
after the upgrade to Qt 5.6/Frameworks 5.20, the icon's gone even from the first instance

**Comment by derlunz** [comment]
I can report, that the issue is not present on my 16.04 ubuntu, KDE 3.8.5 (ppa) machines.
My version is 'Image Lounge 3.7 (git: 3.6.1-48-g3494189-dirty)'. It works also with packaged nomacs 'Image Lounge 3.7 (git: 3.6.1-48-g3494189-dirty)' 

Does the issue still exists for you?

**Comment by deathtrip** [comment]
seems the issue is resolved. using nomacs .3.6.1 on  arch linux

**Comment by diemmarkus** [comment]
cool - thx : )
