### ISSUE TITLE
Add option to see a minimap when a geodata exist

### ISSUE THREAD

**Issue by GLLM** [nomacs/nomacs#481]
First,

thanks a lot for Emacs, which is my daily photos viewing tool (while I'm not in Darktable working on them) !

When I browse my pics, I regularly would like to see on a minimap where the GPS data put that picture.

Therefore, I would love to have an option to show a pin on a minimap displayed over the photo (such as the Overview or Histogram panels).
If this minimap could be zoomable, it would be even better !!

From an execution standpoint : ideally, this would use an opensource data source, such as OpenStreeMaps ...  if too complicated, revert back to Bing, or last resort to Google.

Thank you very much ! :)

GLLM

**Comment by diemmarkus** [comment]
this is absolutely a nice to have. however, it implies a technological barrier that I don't want to cross: we would need a web-engine to render the maps... So I think we will stick here with opening the pin in an external browser. however, we will make the link editable (see #373)

**Comment by GLLM** [comment]
Hi @diemmarkus 
I'm sad but I understand ;)
If we could choose the map source, indeed, it'd be nice ;)
