### ISSUE TITLE
Zooming in with Ctrl++

### ISSUE THREAD

**Issue by tigertorus** [nomacs/nomacs#485]
Menu says the hotkey for zooming in on an image is Ctrl++, but that doesn't work. Hotkey Shift++ does, however. (I wish there were an easier way for users to report bugs than having to sign up for a GitHub account! I almost didn't bother.)

**Comment by diemmarkus** [comment]
Thanks for reporting. Did you re-assign shrotcuts? My version says `CTRL++` and this does the trick. Which version OS/nomacs are you using?
