### ISSUE TITLE
Open With Icons Error

### ISSUE THREAD

**Issue by ghost** [nomacs/nomacs#486]
**Describe the bug**
The Open With Icons looks has sizing error

**To Reproduce**
1. Right Click
2. Click "Open With"

**Expected behavior**
The icon should look normally instead of squeezed ones

**Screenshots**
![image](https://user-images.githubusercontent.com/44415788/82106896-78ecfc00-9756-11ea-8b85-bba3d8135355.png)

**Desktop (please complete the following information):**
 - OS: Windows x64 (Latest Stable)
 - Version 3.14.2.4827 [x64]

**Comment by diemmarkus** [comment]
thanks for reporting!
