### ISSUE TITLE
[Feature Request]  Mouse middle button as a keyboard shortcut

### ISSUE THREAD

**Issue by IgnatMiller** [nomacs/nomacs#490]
Hi,
Using keyboard is not always possible, as many of us for example eat while sitting in front of a computer. Operating software only with a mouse is a good practice so you have 50% of your hands free. Mouse middle button usually serves for panning or closing things. You can close a tab in Chrome with a middle button for instance and it gives so much comfort. I miss an option to exit nomacs with mouse middle button click.

Please, make mouse middle button available as a keyboard shortcut.

**Comment by diemmarkus** [comment]
not sure if I understand the feature request correctly: mouse middle button also closes tabs in nomacs. do you want to be able to assign the mouse middle button in the keyboard shortcuts dialog to any action?
