### ISSUE TITLE
[LINUX] Fix move to trash

### ISSUE THREAD

**Issue by ItsDrike** [nomacs/nomacs#493]
**Is your feature request related to a problem? Please describe.**
I had an issue with deleting my images a while ago using nomacs.
The problem was that when I pressed <kbd>delete</kbd> key, an error popped up in the bottom-left corner of the window saying `Sorry I could not delete image [image name]`.

**How I solved it**
For a long time, I didn't know what to do and I had to use my file manager to remove the files manually.
A solution that solved it was to remove everything from my `/home/itsdrike/.local/share/Trash/files/` I assume that there either was already a file with the same name as the image I was trying to remove or that there was some kind of limit for the Trash size.

**Describe the solution you'd like**
While I'm still not sure what exactly caused the error, there should be a more intuitive message as to why nomacs couldn't delete the image.

It really took me a while to figure out the solution to this (I didn't even found it anywhere on the internet) since the error message didn't provide me with any context as of what exactly went wrong.
I think a much more intuitive message would be something like this: `Unable to delete image, image name already exists in Trash` (that is if the error was caused by that)

Also it might be a good idea to instead of just print this error message, fixing the issue directly (possibly by renaming the file to something like [original name]-2). Once again assuming that the error was caused by the same file already being in trash and not it being too full.

**Comment by diemmarkus** [comment]
thanks for the feedback. you are right: on linux moving to trash is a simple rename. I will fix this!
