### ISSUE TITLE
Nomacs add ability to compensate image displacement in synchronize mode 

### ISSUE THREAD

**Issue by OmTatSat** [nomacs/nomacs#495]
**Is your feature request related to a problem? Please describe.**
When i open 4 or more images, kind of not perfectly aligned, and zoom in I see a different part of images. The more images you view at the same time, the more pronounced the problem and more need of proposed feature.

**Describe the solution you'd like**
In FastStone i used hotkey modifier CTRL, which temporarily disables synchronization for mouse pan and zoom, when i released the hotkey, edited position and zoom of the image are saved for further synchronized viewing. 

**Describe alternatives you've considered**
Add hotkey modifier for temporarily unsynced mouse pan and zoom, after release hotkey modifier, save edited position and zoom properties for further synchronized viewing. 

**Additional context**
A short video with a demonstration in Nomacs and FastStone
https://drive.google.com/file/d/18gt9Sp1APhHCyNybfK_rux8MIdknLCNJ/view?usp=sharing

and screenshot 
https://drive.google.com/file/d/12NV7gOYNBOvjaeuAXqPMxHpf35lsLZOe/view?usp=sharing

**Comment by diemmarkus** [comment]
Hi,

there is a (probably undocumented) shortcut, that should solve your issue

**method 1**
- toggle `Sync All Actions` off
- zoom with the mouse wheel -> only your instance zooms
- hit <kbd>ALT</kpd> and zoom with the mouse wheel -> all instances should zoom
same goes for panning

**method 2**
if the views are out of sync, you can hit <kbd>CTRL</kbd>+<kbd>D</kbd> to sync them again.

I hope this resolves the issues

**Comment by OmTatSat** [comment]
> 
> 
> there is a (probably undocumented) shortcut, that should solve your issue
> 
> **method 1**
> 
>     * toggle `Sync All Actions` off
> 
>     * zoom with the mouse wheel -> only your instance zooms
> 
>     * hit ALT and zoom with the mouse wheel -> all instances should zoom
>       same goes for panning
> 
> 
> **method 2**
> if the views are out of sync, you can hit CTRL+D to sync them again.
> 
> I hope this resolves the issues

Thank you, I tried right now your advice, but unfortunately, it does not work. When I toggle Sync All Actions off in all instances, align the position of objects in the images in all instances and after i start pan and zoom with presed ALT, all images go back to their default position. I can record screen video with demonstrations. I am using last version 3.14.2

**Comment by diemmarkus** [comment]
now I get it - this is actually a bug. normally, you should be able to sync relative with <kbd>ALT</kbd>+<kbd>SHIFT</kbd> & panning. the bug is fixed in the current master & will be shipped with the next version

**Comment by OmTatSat** [comment]
I downloaded nightly nomacs-3.15.1619
I can panning with alt + shift, but i can't zoom both of them simultaneously with image displacement. How can i do this?

Is it very hard to add hotkey for temporarily unsynced mouse pan and zoom, after release hotkey, save edited position and zoom properties for further synchronized viewing with compensated image displacement?

**Comment by diemmarkus** [comment]
> zoom both of them simultaneously with image displacement. How can i do this?

this is not possible because a) the implementation would be very tricky and b) I think the behavior would be hard to understand for users.

> save edited position and zoom properties for further synchronized viewing with compensated image displacement?

yes, that's hard. there are a lot of constraints that could be violated i.e. images could get lost outside the frame etc...

**Comment by OmTatSat** [comment]
a) the implementation would be very tricky
I see(( 
but maybe you can find out how it is implemented in FastStone?

b) I think the behavior would be hard to understand for users.

why? this is like just the simultaneous zooming of several pictures. The only difference is you can use it for not perfectly aligned to each other photos.

"images could get lost outside the frame etc..." as for me, this is not very scary, you always can zoom out and see both pictures
