### ISSUE TITLE
Exposure time show not normalized format

### ISSUE THREAD

**Issue by OmTatSat** [nomacs/nomacs#496]
**Describe the bug**
Exposure time show not normalized format instead of 1/222 like in all programs, showing 2243/500000

**To Reproduce**
1. open https://drive.google.com/file/d/18nFwKBmlZ4Pmy8a4Vn4Lf4S0uoRkTmKj/view?usp=sharing
2. press hot key M to show Exposure time

**Expected behavior**
Showing exposure time in format 1/222

**Comment by diemmarkus** [comment]
currently we only normalize if it matches exactly (your example would give 1/222,9). but you are right, for the sake of simplicity, we could fix that...

**Comment by OmTatSat** [comment]
> 
> 
> currently we only normalize if it matches exactly (your example would give 1/222,9). but you are right, for the sake of simplicity, we could fix that...

Great! Thank you! If it will show 1/222,9 it will be great)

**Comment by diemmarkus** [comment]
for windows, the nightly build is on [appveyor](https://ci.appveyor.com/project/diemmarkus/nomacs/build/artifacts)

**Comment by OmTatSat** [comment]
Best Fix!) Thank you a lot!)
