### ISSUE TITLE
"zoom to fit" is not maintained when toggling F11

### ISSUE THREAD

**Issue by ke352802081770314** [nomacs/nomacs#502]
**Describe the bug**
When a zoom-to-fit image is switched to fullscreen or back using F11, it keeps the same size instead of fitting again (regression 3.12, worked as expected in 3.10 - please excuse my timing: I just upgraded ubuntu LTS from 18.04 to 20.04, resulting in this nomacs upgrade.)

**To Reproduce**
1. set Settings -> Display -> when displaying new images "Always zoom to fit" checked 
2A. open some image, observe that it fits the display area within nomacs
3A. press F11
4A. see background border around image (have to press "cursor-up" to resize to fit)

also:
2B. press cursor-up in the F11 full-screen image as described above, it fits the screen
3B. press F11 to return to GUI 
4B. see only part of the image visible, as it keeps the size fitted to full-screen (have to press cursor-down to resize and see whole image)

**Expected behavior**
A. In 3.10, when pressing F11 on an image that fitted the display area, it was resized to fit the full screen. this is what I expect. 
B. Also, when pressing F11 again when it fitted the full screen, in 3.10 it was resized to fit the display area and be entirely visible, this is also what I expect.

**Screenshots**
not needed

**Desktop (please complete the following information):**
 - Ubuntu 20.04 (LTS), LXDE desktop
 - nomacs:amd64 (3.12.0+dfsg-3), nomacs-l10n:amd64 (3.12.0+dfsg-3)

**Comment by diemmarkus** [comment]
this issue still exists in 3.14 (but I could also reproduce it in 3.10)

**Comment by ke352802081770314** [comment]
according to the update log, the previous version was nomacs:amd64 (3.10.2+dfsg-1), nomacs-l10n:amd64 (3.8.0+dfsg-4), in case this makes a difference. Sorry about being unspecific.

**Comment by diemmarkus** [comment]
thanks!

**Comment by brainchild0** [comment]
"Zoom to fit" is also not preserved for ordinary window resizing. Is this behavior subsumed under the current issue, and its fix?
