### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by fenugrec** [nomacs/nomacs#505]
**Describe the bug**
I've had trouble compiling from git on linux.

**To Reproduce**
1. git clone results in no files inside ImageLounge/plugins
2. running cmake then make :
```
-- setting plugins dir
-- using plugin directory: .../makepkg/nomacs-git/src/nomacs/ImageLounge/plugins
CMake Error at CMakeLists.txt:212 (add_subdirectory):
  The source directory

    .../makepkg/nomacs-git/src/nomacs/ImageLounge/plugins

  does not contain a CMakeLists.txt file.
```

As a workaround, I had to checkout 1ec25651 to be able to compile.

I may be doing something wrong, any hints ?

**Comment by diemmarkus** [comment]
sorry for this, the master branch is currently not perfect as it is waiting for a merge. I think the easiest way is to disable plugins:
```
cmake -DENABLE_QUAZIP=OFF -DENABLE_RAW=OFF -DENABLE_PLUGINS=OFF ../ImageLounge
```
here I also disable quazip & raw support...

**Comment by diemmarkus** [comment]
compilation is now fixed in the master... (without the need of cmake variables)
