### ISSUE TITLE
Qt5Config.cmake

### ISSUE THREAD

**Issue by bastiano** [nomacs/nomacs#51]
Hi, I've got in a mess for being adventurous. 
Installing in ubuntu 15.10 following the instructions from the readme file:
 

1._ sudo apt-get install debhelper cdbs qt4-qmake libqt4-dev libexiv2-dev libraw-dev libopencv-dev cmake libtiff-dev git_ -Done-
2. _git clone https://github.com/nomacs/nomacs.git_ -Done-
3._ Go to the nomacs/ImageLounge directory and run cmake to get the Makefiles
				cmake . _-Done-

When running

>  cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_QT5=ON -DENABLE_QUAZIP=OFF -DQT_QMAKE_EXECUTABLE=/usr/bin/qmake-qt5

Command output:

> -- QMake found: path: /usr/bin/qmake-qt5
> CMake Error at cmake/Utils.cmake:243 (find_package):
>   By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "Qt5", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5" with any of
>   the following names:
> 
>     Qt5Config.cmake
>     qt5-config.cmake
> 
>   Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
>   to a directory containing one of the above files.  If "Qt5" provides a
>   separate development package or SDK, be sure it has been installed.
> Call Stack (most recent call first):
>   CMakeLists.txt:92 (NMC_FINDQT)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/mcx/nomacs/ImageLounge/CMakeFiles/CMakeOutput.log".
> 

Then I don't know what to do.

**Comment by sfiel** [comment]
Hi,

sorry, unfortunately I forgot to update the compile instructions when upgrading to Qt5. Following packages are now required (regarding Qt): qt5-qmake qttools5-dev-tools qt5-default libqt5svg5-dev qt5-image-formats-plugins
then nomacs should compile

Cheers,
Stefan

**Comment by bastiano** [comment]
I've installed those extra packages. 
Then, when running cmake:

> Could not find a package configuration file provided by "Qt5LinguistTools"
>   with any of the following names:
> 
>     Qt5LinguistToolsConfig.cmake
>     qt5linguisttools-config.cmake

**Comment by sfiel** [comment]
sorry I forgot to add the qt5tools-dev package ... now it should work :)

**Comment by diemmarkus** [comment]
this should be fixed by the last pull request by @saivig, am I right?
