### ISSUE TITLE
Windows UPW Apps Icons Overriden

### ISSUE THREAD

**Issue by amaranthROSA** [nomacs/nomacs#510]
Hi there!
This is not really an "issue" but rather a matter of "aesthetics". I noticed that after Nomacs was installed it overrided the Windows Store default "blank icon". In one computer (without Nomacs) while seraching for the app, it shows the "Windows 10 Photos" thumb icon... in the other (who has Nomacs), the Nomacs thumb icon is shown while searching for the app.

Thanks! 😁

Obs.: sorry, the Windows language is in pt-BR.

![computer2](https://user-images.githubusercontent.com/47352625/85785136-5eb41f80-b6ff-11ea-9c22-dfd4af770b1a.png)
![computer1](https://user-images.githubusercontent.com/47352625/85785148-61af1000-b6ff-11ea-9aec-e66f0ec7683b.png)

**Comment by diemmarkus** [comment]
thanks for the feedback.
I don't fully understand what is happening here: does the nomacs icon override an app icon? or is Notas Autoadesivas an image?

In general, nomacs should only override the icons of images if you set it as 'default viewer'.

one more thing: shouldn't the first screenshot look like this:
![img-2020-06-26 09 59 31](https://user-images.githubusercontent.com/4182443/85834532-dcc20600-b793-11ea-857c-50fc5a10e03a.png)

**Comment by amaranthROSA** [comment]
Hi.
I'm aware the explanation above might not be much clear 'cause it's hard to explain exactly what's happening. "Notas Adesivas" is not an picture but rather the app "Sticky Notes". "Calculadora" means calculator and "Notas Adesivas" means "Sticky Notes".
What I noticed is that Nomacs might override the icons of some apps when he's set as default but not all of them. Mine calculator (on the laptop) seems fine btw.

The shots above are from two different environments (1st desktop, 2nd laptop). I know the apps I demonstrated before are different on those two scenarios but that was only intended to show the "Nomacs thumb" overriding the app default icon in the Windows which has Nomacs installed rather than the other (who got not Nomacs).

![Calc](https://user-images.githubusercontent.com/47352625/85912621-44179e80-b804-11ea-8cee-660d5d23181a.png)

**Comment by diemmarkus** [comment]
I am only aware of one issue with default icons and nomacs. In `Settings > File Associations` be sure to uncheck *.ico Register:
![img-2020-07-01 09 27 51](https://user-images.githubusercontent.com/4182443/86215783-4c156c80-bb7d-11ea-9c2e-824e5708607d.png)

Otherwise nomacs is set as default software of *.ico files which causes troubles if software incorrectly links to its icon (adobe acrobat used to have issues I know of).

**Comment by tfriedel** [comment]
I have the same issue! Many apps that were shipped with windows 10 like calculator, calendar or settings now show the nomacs icon. I'd really like the old icons back!

The settings were already like in the screenshot above, i.e. *.ico [x] browse [ ] register.
Any help is much appreciated!
