### ISSUE TITLE
position of "previous - next arrows" ?

### ISSUE THREAD

**Issue by 0lm** [nomacs/nomacs#512]
hi!
this is maybe a really simple question and sorry if the solution is obvious, but i could not find out how to move the "previous file - next file" buttons. i would like them to be either left and right on the sites of the image, or below the displayed image. i noticed when i go to fullscreen, for a short time the arrows appear below the displayed image and in the mid is a diashow-play button.
but even in fullscreen, after a few sec, the buttons disappear and even if i hover with a mouse over there, they dont re-appear. then when i accidently clicked "space" (be it fullscreen mode or not), it starts a diashow and the buttons appear for a moment agian, just to disappear forever aggain.
is there a possibility to set them up, so they stay? or at least properly re-appear when i hover the mouse over the spot below the displayed image?
i know there are arrows on the top left, and i know i can use keybaord button arrows. but i like to use a computer mouse instead and having the buttons at the top left feels strange. and since it seems like somehow the arrows actually can appear at the bottom of the displayed image, i thought it wont hurt to ask how to make that feature available permanently - or at least while the mouse is hovered over that certain spot.

**Comment by diemmarkus** [comment]
you can hit <key>P</key> or `Panels > Player` to display them permanently
