### ISSUE TITLE
Batch processing - raw input files incorrecly modified/rotated

### ISSUE THREAD

**Issue by novomesk** [nomacs/nomacs#514]
Hello,
I tried to convert CR2 files to AVIF using Batch Processing. Input files looked like this:
![before](https://user-images.githubusercontent.com/52529860/86530719-658b2100-bebb-11ea-9525-62463b1a59c6.png)
After the conversion I have correct output files, but the input files got modified unexpectedly (they are rotated now):
![after](https://user-images.githubusercontent.com/52529860/86530807-37f2a780-bebc-11ea-85bc-b86b0dafc31b.png)
I don't understand why it is happening.

**Comment by diemmarkus** [comment]
that (of course) shouldn't happen. can you attach one cr2 before and the same after batch transforming? plus is it the current beta?

**Comment by novomesk** [comment]
BTW encoding these these 21Mpx photos to AVIF is a memory hungry operation (more than older image formats). When batch processing runs with 8 threads, it seems to consume 8x more memory and my Linux become unresponsive (lot of swap space used) for few minutes. It's OK when I lower Number of Threads in Settings/Advanced.

**Comment by diemmarkus** [comment]
I just had a read up: the bug was actually related to [exiv2](https://github.com/Exiv2/exiv2/issues/1066) not supporting avif yet : )

**Comment by novomesk** [comment]
I suggest to investigate this again.
I am using build from Jul 9 2020 and I observe that when saving raw files (Save As to AVIF format), the file size of original input files changes.
