### ISSUE TITLE
.exif files viewable but not indexed

### ISSUE THREAD

**Issue by User486375** [nomacs/nomacs#518]
**Describe the bug**
When I open a .exif image file, nomacs views it fine, but if I switch to the next or previous image it's no longer indexed in the list of images in said folder and you can never get back to it without opening it individually. It also doesn't show in the thumbnail preview of nomacs as a result. Also .exif files don't show a thumbnail on windows 10 at least with nomacs but maybe that's a separate issue?

**To Reproduce**
1. Rename a file to .exif or download one
2. Open said file
3. Scroll left or right with other non .exif images in a folder

**Expected behavior**
The image to be "indexed" in the list like all other compatible file types

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1903
 - nomacs version: 3.15.1616

**Comment by diemmarkus** [comment]
Thanks for reporting.  
Is ``*.exif`` an official image extension? If yes, we will add it. Otherwise you can:
- Open `Tools > Add Image Format` in nomacs
- Drop an exif image into that dialog
Exif images will now behave as jpg etc...

**Comment by User486375** [comment]
I don't really know if it's an "official" image extension or not, or much about file formats in general but when googling around I only really see mentions of exif metadata in jpeg images. Though I can say it is used around the web a lot in the last 2 years when downloading images from various websites, e.g. twitter. I had usually just renamed them to `.jpg` as I didn't realize I could add custom image formats to nomacs as I have the menu bar hidden, I can confirm that adding it works fine for my needs but I don't see the harm in supporting it by default if it's used a decent amount around the web.
