### ISSUE TITLE
AV1 static image format(AVIF) support

### ISSUE THREAD

**Issue by chinakook** [nomacs/nomacs#520]
**Is your feature request related to a problem? Please describe.**
I think that the open source, royalty-free AVIF image format will be popular in the future. I wish nomacs can add this format to it.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by diemmarkus** [comment]
avif support will be here soon: #292 
-> you can already test it in this [beta](https://github.com/nomacs/nomacs/releases/tag/3.15.1616)
