### ISSUE TITLE
[Feature request] slideshow improvement or add video view

### ISSUE THREAD

**Issue by ttsesm** [nomacs/nomacs#522]
**Is your feature request related to a problem? Please describe.**
At the moment the way slideshow is applied is a bit disturbing since it adds a predefined delay and when image is changing there is this animation that floats it out on the left side. Thus, if someone wants to visualize a bunch of images/frames in a continues way, like as a video sequence it is not really practical.

**Describe the solution you'd like**
To have the option to modify the speed of the slideshow and remove the float out animation.

**Describe alternatives you've considered**
Or another alternative would be to add to the viewer tab the option to view the images as a continuous sequence/video specifying the frame rate given a default value of e.g. 25/30 frames initially let's say.

**Comment by diemmarkus** [comment]
you can change the Settings in `Edit > Settings > Display`. These settings would pretty much do what you are asking for:
![img-2020-07-16 08 44 23](https://user-images.githubusercontent.com/4182443/87636244-c24ecd00-c740-11ea-9db4-ec588d42dfda.png)

**Comment by ttsesm** [comment]
Perfect, apparently I've overlooked these settings.

Thanks Marckus.
