### ISSUE TITLE
[Question/Feature request] Why not syncing on a split view rather than on a new window instance?

### ISSUE THREAD

**Issue by ttsesm** [nomacs/nomacs#523]
@diemmarkus apologies for my multiple openings :$, but I've got my hands today with the software and I really think that it is a nice work and it has potential for being a nice scientific tool except of a nice and light viewer.

**Is your feature request related to a problem? Please describe.**
At the moment if someone wants to sync multiple folder of images, he needs to open a corresponding number of nomacs windows and load the images in there.

**Describe the solution you'd like**
Wouldn't be a better solution to split the view in the current window and sync the files within the same window?

**Describe alternatives you've considered**
Another idea would be to provide the option of synchronization both on different windows as well as on a split view.

**Comment by diemmarkus** [comment]
in the beginning we considered this option too (this would actually be easier to implement than the current sync). but the 'window' approach has in my opinion a few advantages:

- users can sync images with different aspect ratios
- overlaying images without changing the viewport
- you can select images to be synced from your file explorer
- sync/desync is straight forward

**Comment by ttsesm** [comment]
I see, well I cannot argue since your points are valid indeed :-). Though I believe what you've mentioned in principle should be possible to be implemented in split views as well. 

In any case, literally it is a subjective preference. 

Thanks for the feedback though :-).
