### ISSUE TITLE
Strange desktop entries: org.nomacs.ImageLounge.*

### ISSUE THREAD

**Issue by tieugene** [nomacs/nomacs#528]
What this strange naming for?
Application is 'nomacs', so all desktop files must be nomacs.*.
Nomacs is not Java class.

**Comment by diemmarkus** [comment]
That's flathub naming - Has nothing to do with Java... does the naming cause issues somewhere?

**Comment by tieugene** [comment]
> That's flathub naming - Has nothing to do with Java... does the naming cause issues somewhere?

No problem - you can use "org.nomacs.ImageLounge - Super Image Processor.desktop" file.
But what for?
If I want to find nomac's things - I will do "find ... -name "nomacs.*" and nothing else.
App name == *.desktop name == icon name. Very simply.
