### ISSUE TITLE
Wrong translation file nomacs_als.ts

### ISSUE THREAD

**Issue by tieugene** [nomacs/nomacs#529]
There is no such ISO country code 'als'.
So Linux installer prodices an error during finding translation files.

**Comment by diemmarkus** [comment]
That's a [German dialect](https://de.m.wikipedia.org/wiki/Vorarlbergerisch#:~:text=Vorarlbergerisch%20(auch%20Vorarlbergisch)%20ist%20eine,der%20Sprachgruppe%20der%20alemannischen%20Dialekte.) but since it also causes issues with crowdin, I'll remove it.
