### ISSUE TITLE
Text size in nomacs menu & UI is small & need to enlarged !

### ISSUE THREAD

**Issue by Nokia808** [nomacs/nomacs#532]
Hi.

Currently, with version 3.16.0 (from FlatHub), the size of text that appearing in nomacs menus & GUI is small so that it is not clear enough ! This is also true for icon size. But for icon size - in Display section of settings - user can change it higher than default 16 pix. But "text" size has no such option. So, kindly to fix this by increase default text size. 

I did not post this as feature request, but as a bug. So, all what I asking is just to increase size of text from your side, without bothering yourself to add new option to change text size ....

Thank you.

**Comment by diemmarkus** [comment]
the font size is determined by the system - can't you change it there?

**Comment by Nokia808** [comment]
@diemmarkus 
Dear the default size of your program menus text is small & need to be enlarged ! Why other programs not menus text size are larger than that of your program though I use with them same system font size setting ?

**Comment by scrubbbbs** [comment]
The font sizes are now set by stylesheet.css, which sets 10pt. 12pt is more common.
