### ISSUE TITLE
[Question] What author of nomacs recommend: distros specific package or flatpak package

### ISSUE THREAD

**Issue by Nokia808** [nomacs/nomacs#534]
Hi dear. As title asking. 

I'm on Fedora Linux, & I installed nomacs as flatpak from FlatHub due to official Fedora repository .rpm package of nomacs has no plug-ins ....

It seem that, soon, Fedora .rpm package (packaged by 3rd party not by nomacs' author) will fix plug-ins & plug-ins will be available for it. So, I would like to asking: what the author of nomacs recommend to install & use, .rpm package (non-official) or flatpak universal package (official) ?

**Comment by diemmarkus** [comment]
it depends : )

## rpm
\+ best integrates into your system: maintainers know much more about the respective OS than I do (i.e. #531)

## flathub
\+  if you are eager to try new features and get updates on the day we release them
\- it seems to have limitations w.r.t file permissions (I think you have already experienced them)

**Comment by Nokia808** [comment]
Thank you. I see now more clear. I will use flatpak version till plug-ins become mature enough specially paint-to-image plug-in. When become mature, I will wait further till the mature version reach official Fedora repositories. At that time I will shift back to .rpm version.

Issue resolved. I will close it.
