### ISSUE TITLE
FR: Open the folder of the currently open image in the tree view

### ISSUE THREAD

**Issue by gerroon** [nomacs/nomacs#536]
**Is your feature request related to a problem? Please describe.**
It would be nice if the the folder tree is synced with the currently opened image.

**Describe the solution you'd like**
The folder tree should be expanded to the cuirrent image's folder

I am using it on Windows 10 3.16.1709

**Comment by diemmarkus** [comment]
if you browse to C:/ in the address bar, the tree will automatically expand...

**Comment by gerroon** [comment]
Sure that is really not ideal especially when the sue rhas many drives. My fr is about bypassign that and making it automatic. I feel like this was not the default behavior in the past.

**Comment by diemmarkus** [comment]
> I feel like this was not the default behavior in the past.

it wasn't. This was introduced in #465. I have the feeling that you are right, maybe it's best to disable it on Windows.
