### ISSUE TITLE
Mouse over text and translation mixed up for some zoom functions in toolbar vs. view menu

### ISSUE THREAD

**Issue by L--U--P--U--S** [nomacs/nomacs#538]
**Describe the bug**
I think that the mouse over text for the two toolbar buttons, which are located _between_ the "full screen" and "show image location" buttons, is kind of misleading and not equivalent to the text of the same icons in the view menu. The same is true for the corresponding German translation. I guess it is the same for all translations, because they are linked to the initial strings in English. Maybe the translation is even more mixed up.

**To Reproduce**
Steps to reproduce the behaviour:
1. open any image in nomacs
2. hover mouse over the two buttons mentioned before and read mouse over hint
3. click both buttons
4. evaluate: do both texts really describe what happens?
5. compare text in view menu to mouse over text for same icons
6. switch language and repeat

**Expected behavior**
The "full screen" button is working and translated as intended, both in the view menu and toolbar, both in English and German.

The one right of it seems to zoom/fit the image the current window size of nomacs. The text in the view menu does match this function, but could be improved. It says "zoom to fit" ("Bild einpassen"). I think "zoom image to fit window" ("Bild an Fenster anpassen") is more precise. The corresponding toolbar text does _not_ match the function, because it says "no zooming" (English and German).

The next icon right of it (read "1:1"?) zooms the 100%. This is fine for both the view menu and the English toolbar text, but not the German toolbar text. It says "Bild an Monitorgröße anpassen", which could be a description of the _former_ button, although slightly inaccurate (monitor size vs. window size).

Finally, there is the "Fit window" ("Fenster anpassen") function in the view menu (no toolbar counterpart, no icon). The description matches the function, but "Fit window to image" ("Fenster an Bild anpassen") would be more precise and better goes with the text suggested for the "zoom image to fit window" button.

**Screenshots**
![zoom](https://user-images.githubusercontent.com/1579186/89878840-63a33480-dbc2-11ea-9ee3-66b4bfa05d9a.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - nomacs version 3.16.1709

**Additional context**
I am specifically talking about those strings:
- https://github.com/nomacs/nomacs/blob/master/ImageLounge/translations/nomacs_de.ts#L806-L807
- https://github.com/nomacs/nomacs/blob/master/ImageLounge/translations/nomacs_de.ts#L816-L817

**Comment by diemmarkus** [comment]
thanks! I have changed the source strings... `(no zooming)` was simply wrong.
a more general comment: the german translation is [community based](https://crowdin.com/project/nomacs), so I am happy if you directly contribute changes there.

**Comment by L--U--P--U--S** [comment]
> the german translation is community based, so I am happy if you directly contribute changes there

Done.

I was looking for a link to crowdin or something similar here in the github repo, but couldn't find one. After your comment I looked again and found the link on nomac's main website. May it be a good idea to add the crowdin link to `CONTRIBUTING.md` and/or `README.md`, too?
