### ISSUE TITLE
Rendering issue with av1f with included alpha channel

### ISSUE THREAD

**Issue by johnyb0y** [nomacs/nomacs#542]
**Describe the bug**
This issue recently emerged in the Chromium bug tracker, and nomacs is affected as well.
Relevant threads: 

https://bugs.chromium.org/p/chromium/issues/detail?id=1115483

https://github.com/strukturag/libheif/issues/279

**To Reproduce**
1. Download the linked png and av1f files in the Chromium Bug-Thread. (I can't attach av1f on Github).
2. Open them using nomacs. 

**Expected behavior**
After decoding they should look identical.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/12081528/90118031-f9bc9380-dd57-11ea-8e4b-9f3e29ba0ebf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
 - Version: Nomacs 3.16.1709

**Additional context**
There's some interesting analysis at the end of the Chromium Bug-Thread. There seems to be a difference in how libavif and libheif handle the alpha channel and how Chromium interprets it. I suspect they same is going on in Nomacs.
This issue is just to make you aware :)

**Comment by diemmarkus** [comment]
thanks for reporting. I think there is nothing that we can do (other than waiting for a fix in libavif).
this could also be of interest to @novomesk

**Comment by novomesk** [comment]
It is about libheif vs libavif compatibility. Reported to libavif https://github.com/AOMediaCodec/libavif/issues/280 so they can investigate.

**Comment by diemmarkus** [comment]
closing since it appears to be an issue during encoding...
