### ISSUE TITLE
Renaming changes image displayed if file order changes

### ISSUE THREAD

**Issue by shankarsivarajan** [nomacs/nomacs#548]
Suppose you have two files in a folder, say "a.jpg" and "c.jpg", and you're viewing "a". Renaming "a" to "b" works as expected, but renaming it to "d" changes the image currently viewed to "c".

**Comment by diemmarkus** [comment]
this behavior is intended, see #244 
-> it is convenient if you want to rename more files in a folder

**Comment by SanskritFritz** [comment]
Could this be an option? I find it very annoying when Nomacs switches to another picture after renaming one.
