### ISSUE TITLE
nomacs not in "default programs"

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [nomacs/nomacs#55]
Why nomacs doesn't appear on the "default programs" in Windows 10? It makes it much harder to assign file types.

**Comment by diemmarkus** [comment]
hi,

editing the registries for becoming a 'default program' is a bit harder than I thought (especially if you do not want to use Admin rights). However, nomacs registers itself in the new Win10 UI:  win key -> Default Programs' (the new icon) -> Photo Viewer. There you can choose nomacs.

cheers,
markus

**Comment by ZatsuneNoMokou** [comment]
Thanks for your answer, so, it's mainly because of the rights in Windows
