### ISSUE TITLE
AVIF thumbnails.

### ISSUE THREAD

**Issue by RozeFound** [nomacs/nomacs#553]
I think a big description isn't needed to this request. I just wanna see thumbnail as I see it on png files.
![NVIDIA_Share_ZxljqrHJEj](https://user-images.githubusercontent.com/68745888/91723633-414f7600-ebc6-11ea-8244-a53ce3f2a431.png)

**Comment by novomesk** [comment]
The image is from Desktop or somewhere in nomacs application?

In order to activate thumbnails in Windows 10 itself (Desktop, explorer - folder view), install **AV1 Video Extension** from Microsoft Store. However I don't know if MS extension can handle all possible AVIF images.

**Comment by RozeFound** [comment]
@novomesk In explorer. And i have this extension installed, so why I can't see thumbnails?

**Comment by novomesk** [comment]
> And i have this extension installed, so why I can't see thumbnails?

I don't know yet. I can see thumbnails on my system. Can you attach the AVIF file to see if it is supported by Microsoft?

**Comment by RozeFound** [comment]
Idk maybe i need to install "Microsoft Photos" from store?
[Avichan.zip](https://github.com/nomacs/nomacs/files/5162625/Avichan.zip)

**Comment by novomesk** [comment]
Your picture is high quality AVIF with YUV444 pixel format and it seems it is not supported by Microsoft decoder yet.

If you save it as medium quality AVIF with YUV420 sub-sampling, you can see the thumbnail.

**Comment by RozeFound** [comment]
@novomesk I was try encode my picture with 8 bit depth and YUV420, and i don't see thumbnails anyway. Can you send me RIGHT avif picture for test?

**Comment by novomesk** [comment]
I see thumbnail with the picture I converted: [Avichan2.zip](https://github.com/nomacs/nomacs/files/5163307/Avichan2.zip)

**Comment by RozeFound** [comment]
I don't know what's wrong with my windows, but i can't see avif thumbnails. Thanks for your attempts to help @novomesk , reinstall windows may help i think, but I don't wanna do this.

**Comment by RozeFound** [comment]
> Your picture is high quality AVIF with YUV444 pixel format
@novomesk Sorry for writing in closed issue, but, how did u know this?

**Comment by novomesk** [comment]
```
avifdec --info Avichan.avif
Image decoded: Avichan.avif
 * Resolution     : 1811x2597
 * Bit Depth      : 10
 * Format         : YUV444
 * Alpha          : Present
 * Range          : Limited
 * Color Primaries: 1
 * Transfer Char. : 13
 * Matrix Coeffs. : 1
 * ICC Profile    : Absent (0 bytes)
 * XMP Metadata   : Absent (0 bytes)
 * EXIF Metadata  : Absent (0 bytes)
 * Transformations:
    * pasp (Aspect Ratio)  : 1/1
 * 1 timescales per second, 1.00 seconds (1 timescales), 1 frame
 * Frames:
   * Decoded frame [0] [pts 0.00 (0 timescales)] [duration 1.00 (1 timescales)]
```
Inside the file, there is information that you used **cavif**

**Comment by novomesk** [comment]
For example my https://github.com/novomesk/gimp-avif-plugin/releases/tag/v2.99.1.2 can save metadata to AVIF.
