### ISSUE TITLE
Image gets downgraded to 8bit and alpha channel lost when saving to AVIF

### ISSUE THREAD

**Issue by novomesk** [nomacs/nomacs#554]
When image has `QImage::Format_RGBA64` format and saving to .avif, following code in DkBasicLoader.cpp cause conversion to 8bit without alpha channel:
```
		if (!hasAlpha && img.colorTable().empty() && !fInfo.suffix().contains(QRegExp("(j2k|jp2|jpf|jpx|png)"))) {
			sImg = sImg.convertToFormat(QImage::Format_RGB888);
```

The previous call `bool hasAlpha = DkImage::alphaChannelUsed(img);` seems to work for 8bit images only.

We should avoid the conversion, my qt-avif-image-plugin can handle input in `QImage::Format_RGBA64`, `QImage::Format_RGBX64` or other formats.

**Comment by diemmarkus** [comment]
should we simply add avif to the exception?
we need this conversion because we get crashes for some plugins otherwise...

**Comment by novomesk** [comment]
Yes, exception for .avif will help.
