### ISSUE TITLE
Custom default window size after start

### ISSUE THREAD

**Issue by Stefan-Olt** [nomacs/nomacs#555]
This was never a big issue for me until I got an High-DPI display: Nomacs always starts with a fixed window size (850x504), which is really tiny on a 4k display. As a workaround I changed that to a higher value in the DkNoMacs.cpp

As a better solution for all users I think a setting for that would be great in the preferences, with the following radio options:
Dimensions for a new Nomacs window
-Custom size: ____ x ____ Position: ____ x ____ (-1 for center) [Button: Use current window dimensions]
-Use window dimension of last closed window

Additional options (checkboxes)
-Start maximized
-Reduce window size to match image aspect ratio (only if image is loaded during start)

I think these options would give users a great flexibility a shouldn't be to hard to implement (I never worked with Qt, therefore I'm not going to make a pull request).

Best regards,
Stefan

**Comment by diemmarkus** [comment]
Hi Stefan,
nomacs should remember the last window size & position. did you try changing the window size, closing nomacs & opening it again?

best,
markus

**Comment by Stefan-Olt** [comment]
Hi Markus,
I found the problem: At some point in the past I must have opened Nomacs as root and it changed the file owner of the "Image Lounge.conf" in my user directory to root. As the config file is probably read-write opened it couldn't be opened at all and the default was always used.
Nonetheless the above options would be a nice addition.
Best regards
Stefan

**Comment by diemmarkus** [comment]
Good to know : )

**Comment by scrubbbbs** [comment]
> -Start maximized

We restore maximized state now.

> -Reduce window size to match image aspect ratio (only if image is loaded during start)

We have frameless mode now which gives this effect.
