### ISSUE TITLE
Saving as JPEG 2000 always loses transparency

### ISSUE THREAD

**Issue by ghost** [nomacs/nomacs#557]
**Describe the bug**
Saving image as JPEG 2000 (.jp2) forces you to choose a new background color if image has embedded transparency (and doing so it removes the latter one), although this image format itself has a [full support for transparency and alpha planes](https://en.wikipedia.org/wiki/JPEG_2000#Side_channel_spatial_information).

**To Reproduce**
1. Load image that has a transparent background
2. Save it as JPEG 2000
3. 'J2K Settings' will pop up and force you to select a new background color for the image

**Expected behavior**
Either save image with transparency kept intact or an option to select between these two (keep transparency or replace it with color).

**Desktop (please complete the following information):**
 - OS: Fedora (Linux)
 - Version 32

**Comment by diemmarkus** [comment]
I'll check that, thanks for reporting!

**Comment by leejuyuu** [comment]
Closing as completed by #585.
