### ISSUE TITLE
Add true rotate option

### ISSUE THREAD

**Issue by ItsDrike** [nomacs/nomacs#558]
**Describe the bug**
Currently, when a file is rotated it's done only through metadata. While doing it like this provides a speed benefit many other photo viewers aren't able to read that and causes problems. I've tried to upload a photo to google images and whenever I uploaded a rotated image, google images had problems reading it, it showed it properly for a while, then it rotated back to the original and then tried to use their rotate system it showed me the original (unrotated) image and went from there, problem is that that adds true rotation but doesn't remove the metadata. Meaning if that image is downloaded back, it is not badly rotated when I use nomacs.<br>
Note that this isn't specific just to Google Images, I've also tried to open rotated images in editor called `feh`  and while that didn't cause any problems when rotating or viewing the image, it disregarded the metadata completely.

**To Reproduce**
1. Open any image
2. Use <kbd>Ctrl+R</kbd> to rotate it
3. Save the image and upload it to google images
4. Open that image in google image, (the behavior here is in the main description)
5. Rotate the image in google images
6. Download the image
7. Open the downloaded image in nomacs (bad rotation problem, described in the main description)

**Expected behavior**
I'd like to see something like <kbd>Ctrl+Shift+R</kbd> which would add true rotation to the image, this should assume the current rotation of the image from the metadata as the starting point and then use the already existing rotation interface after a rotation is applied, it should remove the rotation metadata and truly rotate the image.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Kernel Version: linux 5.8.5.arch1-1

**Additional context**
I'd also accept if you replaced the current rotate feature with this true rotation, but that's not necessary as sometimes the speed benefit this provides is worth keeping it.

**Comment by diemmarkus** [comment]
thanks for reporting. You can already get your desired behavior through the settings: `Edit > Settings > Advanced`, then uncheck `Save Exif Orientation`.

**Comment by ItsDrike** [comment]
Oh, I didn't know about that, in that case, it's fine. But it might still be worth it to make a dedicated shortcut since it's possible that someone will need to use Non-Exif rotations on some pictures but not on others and going to settings every time makes this quite inconvenient.
