### ISSUE TITLE
OpenCV 3 support?

### ISSUE THREAD

**Issue by willysr** [nomacs/nomacs#56]
Hi

does nomacs support OpenCV 3?

I got this while building it on Slackware

```
CMake Error at cmake/Unix.cmake:46 (find_package):
  Could not find a configuration file for package "OpenCV" that is compatible
  with requested version "2.1.0".

  The following configuration files were considered but not accepted:

    /usr/share/opencv/OpenCVConfig.cmake, version: 3.1.0

Call Stack (most recent call first):
  CMakeLists.txt:81 (include)
```

**Comment by sfiel** [comment]
Hi,

nomacs works with opencv 3. Are you trying to compile the current master? Because in line 46 of the Unix.cmake there is no longer a minimal version of opencv required, this was the only option to get rid of this error.

Stefan

**Comment by willysr** [comment]
no, i was building the latest tarball (3.0.0).
i guess i will have to look at the git commits and cherry-pick those against 3.0.0 to make it work

**Comment by willysr** [comment]
is this the right commit i should use?
aa3fffc15bb6cbec8ef140a070dc12e6888e79df

**Comment by sfiel** [comment]
yes this is the commit where we removed this requirement. We will "soon" (in April) release a new version with this commit. Either you can apply this commit to the tar ball or you just use the head

**Comment by willysr** [comment]
ok, thanks, marking this issue solved and closing
