### ISSUE TITLE
Symbolic links with . cannot be resolved

### ISSUE THREAD

**Issue by diemmarkus** [nomacs/nomacs#560]
I use nomacs version 3.16.0 (under Debian GNU/Linux)
and have a directory with symbolic links in it.
One link has a point in it's name (like "St. Peter"). This Picture 
is not shown in the "browser" window.
If I rename the link to ("St Peter"), it is shown.
I hope this is not a wanted feature but a (small) bug?

via email

**Comment by scrubbbbs** [comment]
Cannot reproduce and this makes no sense.
