### ISSUE TITLE
JPEG XL decoding support

### ISSUE THREAD

**Issue by BlueSwordM** [nomacs/nomacs#562]
**Describe the solution you'd like**
Now that Action!(screen recording software) and xnView MP have JPEG XL decoding, it would be very nice if nomacs got JPEG XL decoding support, as it seems JPEG XL decoding support is ramping up.

I don't know how long it would take to have decoding support integrated, but it would be great to have it in nomacs, especially since it now supports AVIF.

**Comment by Hrxn** [comment]
>Action!

Is that a new image viewer? Or do you mean the screen recording software?

And by the way, only XnViewMP, not the "old" XnView (Classic). Which is Windows only and 32-bit anyway.

**Comment by BlueSwordM** [comment]
Action! is the screen recording software. It can simultaneously take JPEG XL screenshots and view those screenshots natively in the app.

And yeah, I meant XNView MP, not XNView.

**Comment by novomesk** [comment]
nomacs is a Qt application and it can potentially load any image format when corresponding Qt Image Plugin is available. That's the way how support for HEIC and AVIF was added.

I asked if someone is making such plug-in: https://gitlab.com/wg1/jpeg-xl/-/issues/46

**Comment by BlueSwordM** [comment]
Oh yeah, I always forget about it.

Thanks for the response.

**Comment by novomesk** [comment]
I have a working prototype of Qt plug-in which is able to load some JXL files. I did not publish the code yet (it is in experimental form).

I have impression that JPEG-XL is not yet final and I guess there could be some incompatible changes. Who knows if files saved by older implementation could be opened by future-standard compliant applications.

JPEG-XL has interesting features, I am curious about progress of the format.

**Comment by BlueSwordM** [comment]
The API is still not final yet, but it should be coming relatively soon(at the end of the year or next year).

**Comment by BlueSwordM** [comment]
Great news.

The JPEGXL 0.2 RC version has come, which means the format itself has been frozen.
Bitstream is stable now, so what we encode now will stay decodable.

**Comment by C0rn3j** [comment]
What's the status of this?

@novomesk seems to maintain [qt-jpegxl-image-plugin](https://github.com/novomesk/qt-jpegxl-image-plugin), there's also `kimageformats` with its own plugin, with which I've took the following screenshot:

![image](https://user-images.githubusercontent.com/1641362/165046116-7c852305-3623-480e-accf-48c1aa689d48.png)

I am not sure how this translates to supporting JXL on Windows however

**Comment by novomesk** [comment]
The plugin works also on Windows.
For example here is development build for Windows where it is bundled: https://ci.appveyor.com/project/diemmarkus/nomacs/build/artifacts

**Comment by G2G2G2G** [comment]
that installer works fine on several versions of windows I tested, why is it not just released? last nomacs release is years old

**Comment by novomesk** [comment]
> why is it not just released?

I cannot release. There are parts of the project I don't have under control (for example translations and website). @diemmarkus , can we do something about it?

**Comment by leejuyuu** [comment]
Closing as completed by #585.
