### ISSUE TITLE
nomacs icon is wrong on Wayland session of KDE Plasma desktop environment

### ISSUE THREAD

**Issue by glaubersm** [nomacs/nomacs#563]
**Describe the bug**
On Wayland session of KDE Plasma desktop environment, we see a Wayland generic icon instead of nomacs icon.

**To Reproduce**
1. install nomacs on a linux distribution with KDE Plasma desktop environment
2. start Wayland session of KDE Plasma
3. open nomacs
4. observe Wayland generic icon in the task manager on bottom, in the title bar and in alt+tab menu

**Expected behavior**
nomacs icon should be correct

**Screenshots**
![nomacs](https://user-images.githubusercontent.com/15967631/94872400-e7d7a280-0422-11eb-9fef-f93b9457c817.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux, KDE Plasma 5.20 beta
 - Version: nomacs 3.17.2206

**Comment by diemmarkus** [comment]
3.17 - you rock : )
That's not good - can you check if nomacs can read SVGs?

**Comment by glaubersm** [comment]
yes, it can.

**Comment by diemmarkus** [comment]
then I guess it might be related to the packaging... can anyone have a look at this issue?

**Comment by glaubersm** [comment]
I have just built the source code on neon unstable (a distribution based on ubuntu 20.04)
and I can reproduce this bug.

Maybe this link can help you 
https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Application_Icon

**Comment by Integral-Tech** [comment]
Fixed in https://github.com/nomacs/nomacs/pull/1067

**Comment by glaubersm** [comment]
I have just installed nomacs 3.19.0-1 on Arch Linux and can confirm that this bug is fixed. Thanks. :)
