### ISSUE TITLE
Weird versioning scripts break build

### ISSUE THREAD

**Issue by dvzrv** [nomacs/nomacs#566]
**Describe the bug**
When rebuilding 3.17.2206 against quazip 1.0.0 I ran into issues where a random python script would try to update some version in some file...

**To Reproduce**
1. Patch stuff for quazip 1.0.0
2. Build
3. Explode:

```
[ 44%] Linking CXX shared library libnomacsCore.so
/usr/bin/python3.8 /build/nomacs/src/nomacs-3.17.2206/ImageLounge/../scripts/versionupdate.py /build/nomacs/src/nomacs-3.17.2206/build/DkVersion.h
Traceback (most recent call last):
  File "/build/nomacs/src/nomacs-3.17.2206/ImageLounge/../scripts/versionupdate.py", line 141, in <module>
    update(args.inputfile, args.copy)
  File "/build/nomacs/src/nomacs-3.17.2206/ImageLounge/../scripts/versionupdate.py", line 42, in update
    l = add_git_tag_string(l)
  File "/build/nomacs/src/nomacs-3.17.2206/ImageLounge/../scripts/versionupdate.py", line 107, in add_git_tag_string
    v[-2] = git_tag()
  File "/build/nomacs/src/nomacs-3.17.2206/ImageLounge/../scripts/versionupdate.py", line 116, in git_tag
    tag = subprocess.check_output(["git", "rev-parse", "HEAD"])
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
make[2]: *** [CMakeFiles/nomacsCore.dir/build.make:941: libnomacsCore.so.3.17.0] Error 1
make[2]: Leaving directory '/build/nomacs/src/nomacs-3.17.2206/build'
make[1]: *** [CMakeFiles/Makefile2:275: CMakeFiles/nomacsCore.dir/all] Error 2
make[1]: Leaving directory '/build/nomacs/src/nomacs-3.17.2206/build'
make: *** [Makefile:171: all] Error 2
make: Leaving directory '/build/nomacs/src/nomacs-3.17.2206/build'
```

**Expected behavior**
Arbitrary commands to do some versioning (for what even?) during build are not run.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version n/a

**Additional context**
Many build systems do not allow internet access. If not cloning the entire project it is not possible to build the code base, because the build will explode trying to run git commands while not in a git repo.
This is really bad for robustness and also a bit YOLO ;-)

https://github.com/nomacs/nomacs/blob/5377c452f4f0e1133754c118bc3d9dd4433609d9/ImageLounge/CMakeLists.txt#L191-L208

**Comment by altrupanda** [comment]
This is probably due to the renaming of some libraries in quazip 1.0. 

see
https://github.com/nomacs/nomacs/issues/568

**Comment by dvzrv** [comment]
> This is probably due to the renaming of some libraries in quazip 1.0.
> 
> see
> #568

That issue is unrelated to this one and stems from a partial upgrade on your side.

This issue concerns itself with breaking components in the cmake build system setup.

**Comment by diemmarkus** [comment]
Thanks & sorry for the late response... Since it seems, that you already have a fix, can you create a PR?

**Comment by dvzrv** [comment]
Sorry, I am no longer using nomacs or maintaining it.
