### ISSUE TITLE
Deleted image not put in rubbish bin

### ISSUE THREAD

**Issue by dwaxweiler** [nomacs/nomacs#567]
**Describe the bug**
When I delete an image in nomacs, it is directly deleted entirely instead of being put into the rubbish bin.

**To Reproduce**
1. Make sure your rubbish bin is empty.
2. Open an image in nomacs.
3. Press the 'Delete' key.
3. Go to the rubbish bin.
4. Notice that the rubbish bin is empty.

**Expected behavior**
The deleted image should still be in the rubbish bin so that you can easily restore it when needed.

**Desktop**
 - OS: Pop!_OS based on Ubuntu
 - Version: 20.04

**Comment by diemmarkus** [comment]
This feature is available in the latest version (3.16)

**Comment by dwaxweiler** [comment]
Yes, it is! The version is stuck at 3.12 in the Debian repositories, so I have switched to the Flatpak package. Thank you very much!
