### ISSUE TITLE
MS Windows ®: not system-wide visibility

### ISSUE THREAD

**Issue by tieugene** [nomacs/nomacs#570]
Now nomacs is installing into C:\Program files, it's ok.
But nomacs' shortcut (or how its name in english) is for "current user" (who installed nomacs) only.

**Comment by diemmarkus** [comment]
I would recommend using the multi-user installer for such scenarios: https://github.com/nomacs/nomacs/releases/latest/download/nomacs-setup-x64.exe
Be sure to uninstall the current version first...

**Comment by leejuyuu** [comment]
Closing as the question seems to have been answered.
