### ISSUE TITLE
nomacs website is down

### ISSUE THREAD

**Issue by donniealbar** [nomacs/nomacs#572]
**Describe the bug**
Error establishing a database connection.

**Screenshots**
![image](https://user-images.githubusercontent.com/41316470/96986502-ebef6f80-154b-11eb-8005-0d56b1d34ec3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Where, I can download nomacs installer for Windows 10?

**Comment by leejuyuu** [comment]
Nomacs website is up again now. Please head there for the installation guides.
