### ISSUE TITLE
Getting sorry, i could not load image error

### ISSUE THREAD

**Issue by VanishingBlaze** [nomacs/nomacs#577]
Trying to open an image(.png) that is a bit large (36.6mb) and got this error when trying to open it. To make sure it wasn't the image itself i opened stock photo viewer on windows and it opened fine. Do i need to change something in settings or is this something else?

**Comment by diemmarkus** [comment]
Hmm could you upload the image somewhere, so that we can test it?

**Comment by VanishingBlaze** [comment]
it's very nsfw so don't think it'd be a good idea to post a link to it

**Comment by diemmarkus** [comment]
ok : ) - please post here if you experience the issue again with another image...

**Comment by scrubbbbs** [comment]
Since there isn't any information to go from I'm closing it. We don't know if it is some property of the image or a corrupted file for example.
