### ISSUE TITLE
In AVIF picture with more than one frame only first one is shown

### ISSUE THREAD

**Issue by lucaspir7** [nomacs/nomacs#582]
Like in this pic:

https://i.fiery.me/IpnR0.avif

It should work like a GIF or a WEBP pic bit it does not.
Only Chrome can open it properly.

**Comment by novomesk** [comment]
It works when you change filename to `IpnR0.avifs`
Problem is that right now nomacs has enabled animations for **.avifs** extension but not **.avif**

In the first AVIF specification, the AVIF sequence had .avifs extension but that's changed recently. In the future, .avif extension will be used both for animated and non-animated images.

It is necessary to enable animations for the .avif extension.

**Comment by lucaspir7** [comment]
Nice. Thanks for the info.

**Comment by diemmarkus** [comment]
thanks!
