### ISSUE TITLE
Sort by size

### ISSUE THREAD

**Issue by ghost** [nomacs/nomacs#594]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I cough and Nomacs is missing sort by size option.

**Describe the solution you'd like**
Yes, sort by size, that's what I would like it to happen. Thank you.

**Describe alternatives you've considered**
Also, recognizing windows file explorer sort so I don't have to manually change the sorting type every time.

**Comment by leejuyuu** [comment]
Closing as completed by https://github.com/nomacs/nomacs/pull/933.
