### ISSUE TITLE
Viewer getting stuck upon deletion of the last image of folder

### ISSUE THREAD

**Issue by sakkamade** [nomacs/nomacs#600]
**Describe the bug**
Hello. After deletion of the last picture in folder (tab), viewer getting stuck upon deleted image and is not possible to continue reviewing the folder until re-open another image.

**To Reproduce**
1. Turn off `Loop Images` in `Settings`
1. Open image with `nomacs`
1. Go to the last image in the current view (folder) and delete it
1. Try to press right/left arrow
2. See the message `You have reached the end/beginning`

**Expected behavior**
Upon deletion of the last picture of folder I should see the previous picture when there is no next picture (if `Loop Images` is off).

**Desktop (please complete the following information):**
 - OS: Windows 10 1903 (Linux as well)
 - Version: 3.16 x64 (latest 3.17 beta as well)

**Comment by scrubbbbs** [comment]
Confirmed bug 3.19 [f2c6c4d](https://github.com/nomacs/nomacs/commit/f2c6c4d3d186965fe786ce9866073735ec39577a)

**Comment by leejuyuu** [comment]
#805 could be related or the same bug.
