### ISSUE TITLE
Grouping in taskbar

### ISSUE THREAD

**Issue by Parodocs** [nomacs/nomacs#606]
Hi,
Open instances of Nomacs aren't combining in the taskbar.  All of my other apps are.
I have tried closing and reloading, and removing and reinstalling, without success.
Why is this important? Viewing all instances at once simplifies locating which image I want to open without chasing it through Nomacs or through windows folders.
Not really an issue - I can find another simple image viewer that groups - but I am curious why?
Thank you,
Parodocs

**Comment by sakkamade** [comment]
Duplicate of https://github.com/nomacs/nomacs/issues/95

**Comment by leejuyuu** [comment]
Closing as duplicate of https://github.com/nomacs/nomacs/issues/67.
