### ISSUE TITLE
AVIF quality not selectable in batch

### ISSUE THREAD

**Issue by xzpyth** [nomacs/nomacs#610]
AVIF quality not selectable in batch, it stays at High quality but output seems like the low quality settings... 
![Capture](https://user-images.githubusercontent.com/66422760/106785659-eb3b9e80-664d-11eb-8e60-a75467fe5570.JPG)

**Comment by novomesk** [comment]
The AVIF quality setting is not implemented in batch processing. AVIF files are saved with quality 52 (scale 0-100).

It is not difficult to write the patch but we don't know what is the future of this project.

If you are using Windows and if you are interested, I can compile for you an alternative AVIF plugin, which will save with higher quality by default.

**Comment by xzpyth** [comment]
or you could just change the setting in batch converter (i know you probably won't) to actual high quality (the high quality preset after pressing ctrl + alt + s). it would be less time consuming i think. The High quality preset (in ctrl+alt+s dialogue) looks just a bit less sharp compared to medium webp but size is usually ~30% smaller. Which is huge for me especially with big pictures. Ty for your response tho

**Comment by novomesk** [comment]
AVIF quality for batch processing is now selectable in git master.
