### ISSUE TITLE
Status of nomacs project

### ISSUE THREAD

**Issue by jwatt** [nomacs/nomacs#612]
Hi @diemmarkus. It [looks](https://github.com/nomacs/nomacs/graphs/contributors) like [your work](https://github.com/diemmarkus) on nomacs stopped abruptly in September last year. I guess life circumstances changed. If you can, would you mind taking a moment to let us know what we might expect in terms of future development? If you don't plan any further development, it would be nice to know so the community can figure out what they want to do. Either way, very best wishes and thank you for all your great work over the years to bring us nomacs.

**Comment by novomesk** [comment]
Perhaps @sfiel can tell us.

If the project is revived, I'd like to continue contributing.

**Comment by paulocoghi** [comment]
@novomesk, as @sfiel didn't respond and it's been a long time since @diemmarkus doesn't respond either, I believe that a fork might be necessary.

Ideally, @diemmarkus would give permission to existing contributors, but without this being possible, the community is left with no options other than the fork.

**Comment by paulocoghi** [comment]
Related to https://github.com/nomacs/nomacs/issues/815

**Comment by novomesk** [comment]
@paulocoghi This software is too big to be maintained by single volunteer. More active contributors would be necessary to take care or everything.

**Comment by arrowgent** [comment]
hi, just came to see if there was an update and saw the commit history

can a contributor maintainer pin this on the issues so we know something might need to be done to move forward?

**Comment by c0xc** [comment]
I'd like to contribute. I've been working on a fix for the auto-save bug/feature (#799) and I've been wanting to look into a couple of other things I might change. But I have to say, I hate the new crop feature in v3.17 (see #622).

**Comment by novomesk** [comment]
@c0xc Thank you for you willingness. If we find more people like you we can continue improving the software together in some new fork.

Markus Diem no longer works for Technical University Wien and he stopped maintaining the nomacs.

**Comment by fcore117** [comment]
Would be really good as nomacs is only best irfanview open source alternative in my view and @novomesk thanks for patching heic and heif plugins in current release. World needs a really good, fast IrfanView alternative.

**Comment by novomesk** [comment]
Hello @pvanek , @PeterDaveHello , @ZTFtrue , @cornytrace , @hollaus , @sizeofvoid

are you still active nomacs users? Is some of you willing to help in case a new nomacs fork is created? Or do you know some people who would like to help taking care of nomacs?

**Comment by PeterDaveHello** [comment]
Not sure if I'm mentioned because the pull request #701, I'm no expert of C++, so what I can do will be really limited here, but would be happy to see if someone can take the project.

**Comment by kintaro1981** [comment]
from his linkedin the work on Nomac stop once he entered Snap Inc
https://at.linkedin.com/in/markus-diem-5b6659184

**Comment by PeterDaveHello** [comment]
Hopefully, his deal about the new work doesn't contain stopping doing anything about this project. I took a quick look at all the GitHub profiles of the ones in the project, and looks like most of them aren't active on GitHub, not sure if it's worthy to ping them all, and give some volunteers the project permission to continue the development here.

**Comment by kintaro1981** [comment]
The new work started about 18 months I think that simply he have no spare time.

**Comment by PeterDaveHello** [comment]
Just let you guys know that I've written an email to `developers@nomacs.org`(the email on the organization page on GitHub), let's see if any response will show up.

**Comment by arrowgent** [comment]
so far 100 forks and no one has taken steps to progress the project?

**Comment by PeterDaveHello** [comment]
> so far 100 forks and no one has taken steps to progress the project?

Well ... it's not that easy to volunteer and contribute your own spare free time to host a project, maybe you can be the one to do so ;)

**Comment by kintaro1981** [comment]
> Just let you guys know that I've written an email to `developers@nomacs.org`(the email on the organization page on GitHub), let's see if any response will show up.

If someone have linkedin premium (I don't) could send him a direct message... not for pushing him to return active but, at least, to know if nomacs has a future or not.

**Comment by novomesk** [comment]
It is clear that previous maintainers abandoned the project.

The only possibility beside declaring the project dead is to find a group of people willing to maintain some fork.

So far there is only c0xc and me who declared willingness of occasional future contributions, but that's not enough for such a feature-rich software like nomacs. Few more developers would be needed. They could be contributors with lower frequency but loyal to the project. They could be students for example, this project would offer them big experience to learn.

**Comment by Tosh0kan** [comment]
Wish I knew C++, so I could help, but I'm already busy with Python.

**Comment by sizeofvoid** [comment]
> It is clear that previous maintainers abandoned the project.
> 
> The only possibility beside declaring the project dead is to find a group of people willing to maintain some fork.
> 
> So far there is only c0xc and me who declared willingness of occasional future contributions, but that's not enough for such a feature-rich software like nomacs. Few more developers would be needed. They could be contributors with lower frequency but loyal to the project. They could be students for example, this project would offer them big experience to learn.

Why is two not enough? Maybe others will follow when the project is going to the right direction. Maybe not.
Why not just starting with topics you two interested and let others unmaintained. Maybe it's not necessary to support Windows when nobody will maintain it.

**Comment by Tosh0kan** [comment]
> > It is clear that previous maintainers abandoned the project.
> > The only possibility beside declaring the project dead is to find a group of people willing to maintain some fork.
> > So far there is only c0xc and me who declared willingness of occasional future contributions, but that's not enough for such a feature-rich software like nomacs. Few more developers would be needed. They could be contributors with lower frequency but loyal to the project. They could be students for example, this project would offer them big experience to learn.
> 
> Why is two not enough? Maybe others will follow when the project is going to the right direction. Maybe not. Why not just starting with topics you two interested and let others unmaintained. Maybe it's not necessary to support Windows when nobody will maintain it.

Did Windows have something to do with the project's death or am I missing something else?

**Comment by sizeofvoid** [comment]
> Did Windows have something to do with the project's death or am I missing something else?

It was just an example. It could be hard to support other platforms when your only two devs on mac, or linux (And of course the other way around).

**Comment by Tosh0kan** [comment]
> > Did Windows have something to do with the project's death or am I missing something else?
> 
> It was just an example. It could be hard to support other platforms when your only two devs on mac, or linux (And of course the other way around).

I see. That would absolutely suck for me but such is life lol

**Comment by c0xc** [comment]
> > It is clear that previous maintainers abandoned the project.
> > The only possibility beside declaring the project dead is to find a group of people willing to maintain some fork.
> > So far there is only c0xc and me who declared willingness of occasional future contributions, but that's not enough for such a feature-rich software like nomacs. Few more developers would be needed. They could be contributors with lower frequency but loyal to the project. They could be students for example, this project would offer them big experience to learn.
> 
> Why is two not enough? Maybe others will follow when the project is going to the right direction. Maybe not. Why not just starting with topics you two interested and let others unmaintained. Maybe it's not necessary to support Windows when nobody will maintain it.

Well, I have already forked it to work on a feature I'm interested in, which is the bug when rotating images (#799). I have actually opened a merge request but with this repo being stale, I'll probably just continue in my repo. The next thing I'm probably going to work on is the crop thing, I want to revert the old one from v3.16 as I find the new one unusable. But my time is very limited and I may disappear for weeks before I (hopefully) have some time to continue working on it, and so on.

**Comment by kintaro1981** [comment]
I think that:
- Windows is important*.
- weeks at less then years. :-)
- the readme need to say clearly that more people are needed 

*for example to use it in the public administration where clients are mostly windows os.

**Comment by novomesk** [comment]
Windows build is easy, AppVeyor can build Windows installer after each commit.

There is a volume of unfixed issues. Lot of effort would be needed to handle them. There are some translations, lot of other areas to improve.

If we don't invest sufficient effort, users will move to other software anyway, sooner or later.

In case enough volunteers are not found, it is correct to acknowledge that we don't have enough power to maintain the project and maybe help some another project to improve instead.

**Comment by diemmarkus** [comment]
Hi,
sorry it took so long to respond here (it was actually hard to abandon the project). But yes, the problem is that circumstances changed and I was the only maintainer that was left on the project. I would be very happy if you keep maintaining it. @novomesk since you were contributing quite a lot towards the end of the project, I gave you more rights. Also I think I could review PRs in the future, but I sure cannot do the releases anymore. Also the homepage is in a pretty bad state and might be shut down at some point.

**Comment by fcore117** [comment]
nomacs is my nr1 image viewer(sometimes simple painter, marker when needed)... there are no other like this and Irfanview is closed and Windows only. I do not count some bloated viewers that are not based on C++ QT. I even use nomacs for viewing .dng raw files. It is so good not to depend on system codecs and everything is integrated inside nomacs itself.

Thanks novomesk for your contributions too.

**Comment by novomesk** [comment]
nomacs project need to solve two challenges:
1. Lack of volunteers (it is a big software - require more effort, more people)
2. Previous owners did not granted control over whole infrastructure

Point 2 can be solved by starting a new fork in a new organization, but the point 1 is the major problem to overcome.

**Comment by bbecausereasonss** [comment]
I think we can probably fix this through posting on Reddit and community forums looking for dev help. It's honestly such a great piece of software, it shouldn't be too difficult to find contributors. Especially for cross-platform.

**Comment by novomesk** [comment]
> I think we can probably fix this through posting on Reddit and community forums looking for dev help.

Feel free to do it.

**Comment by 57382** [comment]
Need a fork.

**Comment by leejuyuu** [comment]
Please go to https://github.com/nomacs/nomacs/issues/987 for further discussions.
