### ISSUE TITLE
Can't compile, File name too long after python3 scripts/make.py

### ISSUE THREAD

**Issue by piotao** [nomacs/nomacs#615]
**Describe the bug**
Does not compile. Also, no nomacs in official repo! I'm using Debian 11 'bullseye' with repos:
pio@hebron⠶~bin/nomacs> grep -Pv '#|^$' /etc/apt/sources.list
deb http://ftp.task.gda.pl/debian/ bullseye main non-free contrib universe
deb http://security.debian.org/debian-security bullseye-security main contrib non-free universe
deb http://ftp.task.gda.pl/debian/ bullseye-updates main contrib non-free universe
deb http://ftp.task.gda.pl/debian/ bullseye-backports main contrib non-free universe

**To Reproduce**
Check by apt:
apt update && apt search nomacs  -- NOTHING.

As in README:
0. cd ~/bin
1. git clone https://github.com/nomacs/nomacs.git && cd nomacs
2. git submodule init
3. git submodule update
4. python3 scripts/make.py "/usr/lib/qt5/bin"
THEN the error appears:

pio@hebron⠶~bin/nomacs> python3 scripts/make.py "/usr/lib/qt5/bin"
[WARNING] libpath path does not exist: /home/piotao/bin/nomacs/3rd-party/build
qtpath: /usr/lib/qt5/bin
libpath: 
repopath: /home/piotao/bin/nomacs/3rd-party
builddir: /home/piotao/bin/nomacs/3rd-party/build/opencv
buildconfig: debug
project: ['all']
force: False
configure: False
install: False
name: opencv
additional_cmake_args: []
srcpath: /home/piotao/bin/nomacs/3rd-party/opencv
cmakeonly: False
binaryfile: /home/piotao/bin/nomacs/3rd-party/build/opencv/bin/Release/opencv_core430.dll
opencv ----------------------------------------------
cmake --clean-first -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DBUILD_opencv_java=OFF -DBUILD_opencv_java_bindings_generator=OFF -DBUILD_opencv_python=OFF -DBUILD_opencv_apps=OFF -DBUILD_opencv_dnn=OFF -DBUILD_opencv_calib3d=OFF -DBUILD_opencv_highgui=OFF -DBUILD_opencv_photo=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF -DBUILD_opencv_python_tests=OFF -DBUILD_opencv_python_bindings_generator=OFF -DBUILD_opencv_stitiching=OFF -DBUILD_opencv_video=OFF -DBUILD_opencv_videoio=OFF -B/home/piotao/bin/nomacs/3rd-party/build/opencv /home/piotao/bin/nomacs/3rd-party/opencv
Traceback (most recent call last):
  File "/home/piotao/bin/nomacs/scripts/make.py", line 383, in <module>
    configure_libs(params, c)
  File "/home/piotao/bin/nomacs/scripts/make.py", line 334, in configure_libs
    make_libs(p)
  File "/home/piotao/bin/nomacs/scripts/make.py", line 279, in make_libs
    build(opencv)
  File "/home/piotao/bin/nomacs/scripts/utils/build.py", line 21, in build
    sp.run(cmakeconfig, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 36] File name too long: 'cmake --clean-first -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DBUILD_opencv_java=OFF -DBUILD_opencv_java_bindings_generator=OFF -DBUILD_opencv_python=OFF -DBUILD_opencv_apps=OFF -DBUILD_opencv_dnn=OFF -DBUILD_opencv_calib3d=OFF -DBUILD_opencv_highgui=OFF -DBUILD_opencv_photo=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF -DBUILD_opencv_python_tests=OFF -DBUILD_opencv_python_bindings_generator=OFF -DBUILD_opencv_stitiching=OFF -DBUILD_opencv_video=OFF -DBUILD_opencv_videoio=OFF -B/home/piotao/bin/nomacs/3rd-party/build/opencv /home/piotao/bin/nomacs/3rd-party/opencv'

**Expected behavior**
It should compile or at least do not display this meaningless absurd error: "file name too long". Also, running this command by hand works: https://pastebin.pl/view/af9ca684
I don't know what should be run next to compile nomacs step by step, by hand if necessary.

**Desktop (please complete the following information):**
 - OS: Debian 11 bullseye, 
 - Kernel: 5.10.9-1

**Additional context**
I've installed all required packages for qtcreator, which pulled all sort of dependencies. I assume that my qt5-installion is complete, however:

- when run qtconfig it says:
qtconfig: could not exec '/usr/lib/qt5/bin/qtconfig': No such file or directory

- when run qtchooser -l it displays a list:
4
5
default
qt4-x86_64-linux-gnu
qt4
qt5-x86_64-linux-gnu
qt5

Also, run qtchooser -print-env returns:
QT_SELECT="default"
QTTOOLDIR="/usr/lib/qt5/bin"
QTLIBDIR="/usr/lib/x86_64-linux-gnu"

**Comment by lukasnobody** [comment]
You're trying to build it Windows way.

Just switch to the [right metod](https://github.com/nomacs/nomacs?tab=readme-ov-file#build-nomacs-ubuntu).

**Comment by piotao** [comment]
Thanks bro!
