### ISSUE TITLE
Colors too red in Windows 10

### ISSUE THREAD

**Issue by baloe** [nomacs/nomacs#619]
I observe that the colors in nomacs are shifted towards red when compared to the previews of my raw editors and what the images look like in Adobe Bridge.

Interestingly, colors match those of the native Windows 10 photo app.

Here is a comparison: Adobe Bridge in the background, nomacs, and Windows 10 Photos
![compare_nomacs_photos_bridge](https://user-images.githubusercontent.com/12622691/110544052-6e5b8300-812b-11eb-8647-0b7937f50d57.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by scrubbbbs** [comment]
Nomacs has no color management support. See #459
