### ISSUE TITLE
please fix ambiguous_call_to_abs (patch included)

### ISSUE THREAD

**Issue by sergiomb2** [nomacs/nomacs#62]
/builddir/build/BUILD/nomacs-3.2.0/src/DkGui/DkViewPort.cpp:1254:89: error: call of overloaded 'abs(double&)' is ambiguous
  double speed = mAnimationValue > 0.5 ? abs(1.0 - mAnimationValue) : abs(mAnimationValue);

[nomacs-ambiguous_call_to_abs.patch.txt](https://github.com/nomacs/nomacs/files/272639/nomacs-ambiguous_call_to_abs.patch.txt)

**Comment by sfiel** [comment]
which operating system are you suing since we do not get an error on windows and on different linux machines

**Comment by sergiomb2** [comment]
Linux Fedora rawhide , i.e. I think is GCC6 that detect this problem . 

https://pkgs.fedoraproject.org/cgit/rpms/nomacs.git

**Comment by sfiel** [comment]
so, i applied the patch... Thank you for reporting!
