### ISSUE TITLE
please tag nomacs as 3.2.1

### ISSUE THREAD

**Issue by agaida** [nomacs/nomacs#64]
like in bb45d921 - it would make a nice version number for debian instead a version with git hash and so on. Thanks :P

**Comment by sfiel** [comment]
the current stable version is 3.2.0 ... the master branch currently has 3.2.1 until we release 3.2.2, this is how we can easily check if we are currently running a beta version or a stable version on our computers (if the program does not behave like expected we take a look at the about dialog)

**Comment by agaida** [comment]
ah, ok - any eta for a 3.2.2?
