### ISSUE TITLE
FTBFS on Arch Linux

### ISSUE THREAD

**Issue by pmattern** [nomacs/nomacs#65]
Since some wheeks compiling nomacs on Arch Linux the same way as before is failing.

Unfortunately the `make` output isn't exactly telling to me so please just find it at https://gist.github.com/pmattern/0613ce8ab445135c2a3191c6385edf96.

**Comment by sfiel** [comment]
hi,
this is related to #62 and should be fixed by now with the attached patch

**Comment by pmattern** [comment]
Confirmed. As of 22ea94f nomacs is compiling and working flawlessly again.
