### ISSUE TITLE
The image rotation buttons on the toolbar do not work.

### ISSUE THREAD

**Issue by VaDooM-cyber** [nomacs/nomacs#651]
**Describe the bug**
The image rotation buttons on the toolbar stop working if you first try to rotate the images through the "adjustment"section.

1. Open any image
2. Go to 'adjustment'
3. Click on 'Rotate'
4. Click on the rotation arrows that appear in the editor
5. Click on the rotation arrows that appear in the editor

**Expected behavior**
When the rotation buttons are pressed, the image should rotate.

 - OS: [Windows 7 max]
 - Nomacs version 3.16.1709 [x64]

**Comment by scrubbbbs** [comment]
Fixed in 3.19
