### ISSUE TITLE
Thumbnails overlapping buttons next/previous image 

### ISSUE THREAD

**Issue by Ambidre** [nomacs/nomacs#664]
**Describe the bug**
When thumbnails are showed right or left, it overlapping buttons next/previous image

**To Reproduce**
1. Show thumbnails
2. Show it right/left

**Expected behavior**
Thumbnails located near button

**Desktop (please complete the following information):**
- OS: Windows 10 Education
- Version 3.16.1709 [x64]

**Comment by scrubbbbs** [comment]
Vote  to close. I don't understand the explanation. There is no overlapping that I can see, the right/left buttons are either on the right/left edges or bottom center if player is enabled.

**Comment by leejuyuu** [comment]
Since the author has not responded after a while, I am going to close this. Feel free to reopen.
