### ISSUE TITLE
While togging scale 'resize' image gets big for a split second

### ISSUE THREAD

**Issue by Ambidre** [nomacs/nomacs#665]
**Describe the bug**
Image resized but when togging scale “resize” the image gets big for a split second

**To Reproduce**
1. Go to 'Adjustments'
2. Click on 'Resize'
3. Tog scale 'Resize'

**Expected behavior**
Image resized

**Desktop (please complete the following information):**
- OS: Windows 10 Education
- Version 3.16.1709 [x64]

**Comment by leejuyuu** [comment]
I believe this has the same cause as #711.
