### ISSUE TITLE
Incorrect work of hotkeys after start

### ISSUE THREAD

**Issue by Polymorn** [nomacs/nomacs#669]
**Describe the bug**
Hotkeys works only after interacting with main frame of application.

**To Reproduce**
1. Run the application
2. Use any hotkey
3. Hotkey doesn't work
4. Click on the main frame of app
5. Use hotkey again
6. See it works

**Expected behavior**
Clear work of hotkeys after starting the application

**Screenshots**
![image](https://user-images.githubusercontent.com/80209744/119530570-551eb600-bdad-11eb-8eb1-86441b0b4c09.png)
An area you need to interact with for correct work of hotkeys.

**Desktop:**
 - OS: Windows 10 Enterprise LTSC
 - Version 10.0.17763.1935 [x64]

**Comment by scrubbbbs** [comment]
This has been fixed for the image view panel in 3.19.1. There are some other cases (history panel) where hotkeys do not function as expected.
