### ISSUE TITLE
The application duplicates itself while restarting

### ISSUE THREAD

**Issue by Polymorn** [nomacs/nomacs#670]
**Describe the bug**
The application is restarted without waiting for a user response in a dialog box, thereby duplicates itself.

**To Reproduce**
1. Run the application
2. Go to 'Edit'
3. Click on 'Settings'
4. In the 'General' -> 'Color Settings' change the color theme
5. Click on 'Please Restart nomacs to apply changes' at the bottom of the window
6. See error

**Expected behavior**
The program should wait for the user's response in the dialog box, and then restart without creating a copy of itself. 

**Screenshots**
![image](https://user-images.githubusercontent.com/80209744/119535697-7e8e1080-bdb2-11eb-8e24-2c52289aa5ac.png)

**Desktop:**
 - OS: Windows 10 Enterprise LTSC
 - Version 10.0.17763.1935 [x64]

**Comment by scrubbbbs** [comment]
Duplicate #319
