### ISSUE TITLE
When you restart nomacs in the settings, it duplicates itself

### ISSUE THREAD

**Issue by Deschudes** [nomacs/nomacs#673]
## Describe the bug
When you restart nomacs in the Settings, it opens new window, but doesn't close the previous.

### Precondition:
The application is running

### Steps to reproduce the behavior:
1. Go to Edit → Settings
2. Click on restart button in the lower left corner

## Expected behavior
The previous window closes or the app doesn't restart while you choose the button in the save warning.

## Screenshots
![image](https://user-images.githubusercontent.com/47385858/119795143-662d0b80-bf02-11eb-9ac3-7620e33c055d.png)

![image](https://user-images.githubusercontent.com/47385858/119795160-69c09280-bf02-11eb-8014-a2fa83d4e077.png)

## Environment:
version of app: 3.16.1709
date of the last update: Jul 17 2020
Windows 10

**Comment by scrubbbbs** [comment]
Duplicate #319
