### ISSUE TITLE
Icon color reset returns wrong color in dark theme

### ISSUE THREAD

**Issue by Deschudes** [nomacs/nomacs#674]
## Describe the bug
When the app in dark theme, you can click on icon color reset and the default dark theme color changes. 

### Precondition:
The application is running. 

### Steps to reproduce the behavior:
1. Go to Edit → Settings
2. Make theme dark. Keep in mind the icon color.
3. Click on icon color reset

## Expected behavior
after clicking on reset, the icon color doesn't change

## Screenshots
When you set dark theme:
![image](https://user-images.githubusercontent.com/47385858/119795562-c9b73900-bf02-11eb-8825-dc9c01143d25.png)
When you click on reset:
![image](https://user-images.githubusercontent.com/47385858/119795578-cde35680-bf02-11eb-8bbe-3dee9dcb0d7a.png)

## Environment:
version of app: 3.16.1709
date of the last update: Jul 17 2020
Windows 10

**Comment by scrubbbbs** [comment]
Confirmed, the color chooser is not initialized with the default (theme) color, it uses a hard-coded value. When the theme is switched it also does not update the chooser default.
