### ISSUE TITLE
Adjustments/Edit Image Panel: top-right buttons in dark theme have low contrast

### ISSUE THREAD

**Issue by TitovNS** [nomacs/nomacs#685]
Display window control buttons in Dark Theme.

**Steps to reproduce:**
1. open the program
2. go to the program "Adjustments" - > "Resize"
![Screenshot_2](https://user-images.githubusercontent.com/80142517/120894924-fe369d80-c644-11eb-9ed0-955accc90010.png)

**Environment:** 
version: 3.16
OS: Windows 10

**Comment by leejuyuu** [comment]
Hello @TitovNS, would you mind trying [this test build](https://ci.appveyor.com/project/novomesk/nomacs/builds/50542590/artifacts)?

Here's the comparison on my machine (Arch Linux, Sway WM)

![image](https://github.com/user-attachments/assets/fbf6114b-416e-4dd9-bd87-d55fc77a4645)
