### ISSUE TITLE
Add option to disable horizontal scrolling

### ISSUE THREAD

**Issue by AlexDaniel** [nomacs/nomacs#69]
Trackpoints provide both vertical and horizontal scrolling. However, it is pretty hard to scroll vertically without accidentally moving your trackpoint horizontally.

In nomacs horizontal scrolling switches between pictures in the folder. This means that whenever I try to zoom in I accidentally change the picture (well, unless I'm very accurate). This is very annoying.

Please add an option to disable this functionality for horizontal scrolling.

**Comment by diemmarkus** [comment]
fixed - added a checkbox in Preferences - General

**Comment by AlexDaniel** [comment]
Thank you very much!
