### ISSUE TITLE
[Usability]/[Adjustment panel] The picture jumps and twitches on the main screen and on the thumbnail.

### ISSUE THREAD

**Issue by RatatataBoom** [nomacs/nomacs#711]
Steps to reproduce: 
1. Open file (any image)
2. Click the Adjustment menu.
3. Press "Rotation" or "Scale", "Threshold", "Saturation", etc.
4. Slowly move the scroll bar left or right. 

Expected result: 
The picture smoothly changes in accordance with the variable parameter on the main screen
and on the thumbnail

Actual result:
The picture jumps and twitches on the main screen and on the thumbnail.

Attachments: 
https://drive.google.com/file/d/1bJzhXVoifobPcbyQNvfWEkUOhhadmaOZ/view?usp=sharing

Environment:

Win10 (19042.1052)
Nomacs ver: 3.16.1709[x64]

**Comment by leejuyuu** [comment]
Confirmed on 3.19.0 (eca2377d), Arch Linux.
