### ISSUE TITLE
[Image Viewing] Files with the .ARW extension do not have thumbnails

### ISSUE THREAD

**Issue by RatatataBoom** [nomacs/nomacs#714]
Steps to reproduce:
1. Click the File menu
2. Click "Open file directory". The directory contains .ARW and .jpg files.

Expected Result:
Each file has a thumbnail

Actual result:
Files with the .ARW extension do not have thumbnails.

Environment:

Win10 (19042.1052)
Nomacs ver: 3.16.1709[x64]

**Comment by leejuyuu** [comment]
Seems the same issue as #715, I am going to close this one.
