### ISSUE TITLE
Retag the 3.4 release with an annotated tag

### ISSUE THREAD

**Issue by agaida** [nomacs/nomacs#72]
Please retag the release with an annotated tag - git describe would work better with it. Thanks.

**Comment by diemmarkus** [comment]
sorry for the late answer... the [3.4](https://github.com/nomacs/nomacs/tree/3.4) release is tagged, isn't it?

**Comment by agaida** [comment]
no problem anymore - https://tracker.debian.org/pkg/nomacs
