### ISSUE TITLE
[Guide] Solving libssh.h not found problem on macOS while building.

### ISSUE THREAD

**Issue by libook** [nomacs/nomacs#722]
**Is your feature request related to a problem? Please describe.**
macOS Big Sur 11.4
CMake 3.20.5
Building on macOS failed with missing 'libssh/libssh.h':
```
/usr/local/Cellar/exiv2/0.27.4/include/exiv2/ssh.hpp:27:10: fatal error: 'libssh/libssh.h' file not found
```

**Describe the solution you'd like**
If libssh is already installed with Homebrew, this may be caused by CMake.
It seems that CMake doesn't seek header files in `/usr/include` or `/usr/local/include`.
Try to export environment variables:
```
export C_INCLUDE_PATH=/usr/include:/usr/local/include
export CPLUS_INCLUDE_PATH=/usr/include:/usr/local/include
```
Then run `make`, see whether it works.

**Describe alternatives you've considered**
Well, I don't know.

**Additional context**
I don't know much about C++ development. So there may be something wrong in my description.
I have solved the problem with doing this. Hope help anyone eles.

**Comment by anijatsu** [comment]
In my case I had to use `/opt/homebrew/include` as the dir, so:
```zsh
export CPLUS_INCLUDE_PATH=/usr/include:/usr/local/include:/opt/homebrew/include 
export C_INCLUDE_PATH=/usr/include:/usr/local/include:/opt/homebrew/include 
```

**Comment by hmueller01** [comment]
On macOS 13.4 I only had to add
```
export CPLUS_INCLUDE_PATH=/usr/local/include
```
or
```
CPLUS_INCLUDE_PATH=/usr/local/include make
```

I would appreciate to add this to the README.md (found this after I found out myself). If ok I`ll do a PR.
