### ISSUE TITLE
the program is collapsing

### ISSUE THREAD

**Issue by ViaChe1** [nomacs/nomacs#727]
Describe the bug
using the copy/paste function, not links to images, but a functioning website. the program is collapsing

To Reproduce
1. copy the link different from the image link
2. open nomacs
3. use ctrl+v
4. the application is forced to close

Expected behavior.
     Error window.

Screenshots
![кек1](https://user-images.githubusercontent.com/87058582/124954896-c73b1980-e040-11eb-9949-691ac48a08e9.PNG)

 - OS Windows 10 pro x64
 - Nomacs  3.16.1709 [x64]

remove the ability to process other links other than images at a low level

**Comment by scrubbbbs** [comment]
Cannot reproduce (3.19), I'll reopen if you can give a specific example.
