### ISSUE TITLE
cannot show information

### ISSUE THREAD

**Issue by ViaChe1** [nomacs/nomacs#730]
Describe the bug
 Using the image cropping tool, when the show information module is enabled, when moving the selected area, it cannot show information, the line with information is not displayed completely

 To Reproduce 
1. select adjustment
2. select crop image
3. in the mode that opens, select show information
4. select the cropping area
5. move an area
6. no information available

Expected behavior.
 There is a line with information next to the zone.

- OS Windows 10 pro x64
 - Nomacs  3.16.1709 [x64]

**Comment by scrubbbbs** [comment]
Seems to be fixed now (3.19)
