### ISSUE TITLE
opening image with xdg-open, opens nomacs, on close, another image viewer is opened

### ISSUE THREAD

**Issue by DoTheEvo** [nomacs/nomacs#74]
Arch + i3wm

if I use `xdg-open zzz.png`, it gets opened in nomacs, then after closing, image is open again in another available application for viewing images.

I am not sure if this is nomacs issue, or my system issue, or xdg-open issue
but if I change the default application in mimeapps.list to gpicview or firefox then its fine

opening picture with `nomacs zzz.png` would work just fine, only when coupled with xdg it starts to have issues

Is there some non obvious functionality of nomacs that could be responsible for this?
I tried reseting to default settings and deleting the nomacs folder in ~/.config

when I tried at first removing the secondary opened applications from my system(mupdf, gpicview), it started to on close open nomacs again, and then after secondary close open firefox new tab with the picture

if nothing comes to mind then it might be just my screwed up system

**Comment by diemmarkus** [comment]
I am sorry, but I have no clue why this could happen... we just parse the cmd args and open the image if the first arg is a valid image path...

**Comment by DoTheEvo** [comment]
thought so...
