### ISSUE TITLE
Not all the miniatures are shown in Recent files (ctrl + H) page

### ISSUE THREAD

**Issue by Amaltiirtare** [nomacs/nomacs#743]
**Steps to reproduce**
1. Open the app
2. Go to File -> Recent files (ctrl + H)

**Actual result**
Not all miniatures  are shown
![image](https://user-images.githubusercontent.com/87056645/125114231-e5257e80-e113-11eb-9ddd-6f93f50bb048.png)

**Expected result**
All miniatures are shown

**System**
Win 10 x64
nomacs ver 3.16.1709 [x64]

**Comment by scrubbbbs** [comment]
Duplicate #683
