### ISSUE TITLE
Settings UI issue

### ISSUE THREAD

**Issue by AndreiChistikhin** [nomacs/nomacs#750]
**Describe the bug**
No display of UI part

**To Reproduce**
1. Open app
2. Open image
3. Go to View -> Frameless
4. Right button click on the image -> Settings
5. See the error

**Expected behavior**
All parts of UI displayed correctly

**Screenshots**
![1](https://user-images.githubusercontent.com/78159702/125154579-d0350380-e184-11eb-85fe-e1fc33361853.PNG)

**Desktop (please complete the following information):**
Win 10 x64
Nomacs ver 3.16.1709 [x64]

**Comment by scrubbbbs** [comment]
Related #617
