### ISSUE TITLE
Incorrect work in the "Tools" window 

### ISSUE THREAD

**Issue by Romanij94** [nomacs/nomacs#760]
**Describe the bug**
Incorrect work in the "Tools" window 
Changes the desktop background without user permission or notification.
**Tool Reproduce**

1. Open the app Nomacs.exe
2. Open Image
3. Click on '.Tools>Mosaic image>Wallpaper
4. Changes the desktop background

**Expected behavior**
Correct work of the "Wallpaper" function

**Screenshots**
![image](https://user-images.githubusercontent.com/87686820/126271102-879fce8b-3c31-4ca5-bb40-2fffaa62bf98.png)
![image](https://user-images.githubusercontent.com/87686820/126271122-e9665a03-b7aa-4804-90ca-d68e318ff619.png)
![image](https://user-images.githubusercontent.com/87686820/126271135-3a97fe3c-3cd0-430f-9c1b-d46d3c60d736.png)
![image](https://user-images.githubusercontent.com/87686820/126271157-77983601-43c5-485c-bb45-4a708cc1c38b.png)

**Desktop (please complete the following information):**
 - Win 10x64
 - Nomacs ver 3.16.1709 [x64]

**Additional context**

**Comment by scrubbbbs** [comment]
Cannot reproduce v3.19.1
