### ISSUE TITLE
Panel 'Thumbnails' is not displayed

### ISSUE THREAD

**Issue by LeonidOS23** [nomacs/nomacs#763]
**Description**
Panel 'Thumbnails' is not displayed if 'nomacs' launched after closing all it's instances.

**Severity**
Minor

**System**
OS: Windows 10 Pro
Version 20H2

**Steps to reproduce the behavior**
1. Activate panel 'Thumbnails'
2. Close all instances of 'nomacs'
3. Run 'nomacs'
4. Open directory with function 'Open Directory'
5. Open image
6. Click 'Panels'

**Expected behavior**
Thumbnails are displayed.

**Screenshots**
![nomacs_6xajyVXnsE](https://user-images.githubusercontent.com/37305513/126339350-2f6c38e9-0f3c-4541-9e67-54a899470fbd.jpg)

**Actual behavior**
Thumbnails are not displayed.

**Comment by leejuyuu** [comment]
Reproduced on 3.19.1 (ba263741), Arch Linux, Qt 6.8.0.
The key here is opening the image from "Open Directory".
