### ISSUE TITLE
'Private Mode' inastance becomes standard instance

### ISSUE THREAD

**Issue by LeonidOS23** [nomacs/nomacs#765]
**Description**
'Private Mode' instance becomes standard instance after activating 'Pseudocolor Function'.

**Severity**
Minor

**System**
OS: Windows 10 Pro
Version 20H2

**Steps to reproduce the behavior**
1. Open image
2. Activate 'Pseudocolor Function' (Ctrl+U)

**Expected behavior**
'Private Mode' instance  is displayed with pseudocolor toolbar.

**Video**
https://user-images.githubusercontent.com/37305513/126499340-fade0af8-6d1e-4bc7-afdd-3d5b45d9dcd1.mp4

**Actual behavior**
Standard instance is displayed with pseudocolor toolbar.

**Comment by leejuyuu** [comment]
@LeonidOS23 There's a PR that should fix this. You can test it with the builds from https://ci.appveyor.com/project/novomesk/nomacs/builds/50319582.
