### ISSUE TITLE
'Edit Image' panel isn't docking to the right side in fullscreen mode

### ISSUE THREAD

**Issue by LeonidOS23** [nomacs/nomacs#766]
**Describe the bug**
'Edit Image' panel can't be docked to the right side of fullscreen window by dragging it rightmost with mouse. Dragging it leftmost allows docking panel to the left side of window.

**Severity**
Low

**System**
OS: Windows 10 Pro
Version 20H2

**Steps to reproduce the behavior**
1. Set 'nomacs' window to fullscreen
2. Activate panel 'Edit Image' (D)
3. Click+hold left mouse button on panel's title bar
4. Drag mouse to the rightmost position of screen
5. Release left mouse button

**Expected behavior**
Panel is docked to the right side of main window.

**Video**
https://user-images.githubusercontent.com/37305513/126495218-dff93235-461d-45d3-bf8a-8a08d1d05ff8.mp4

**Actual behavior**
Panel is not docked to the right side of main window.

**Comment by scrubbbbs** [comment]
Cannot reproduce in 3.19.1. Feel free to reopen if the current version shows the same issue.
