### ISSUE TITLE
Incorrect exit from ‘Full screen’

### ISSUE THREAD

**Issue by annfisher** [nomacs/nomacs#781]
**Steps To Reproduce**  
1.	Open nomacs app;
2.	Open image;
3.	Right-click image -> Activate Frameless;
4.	Right-click image -> Activate Full screen;
5.	Right-click image -> Deactivate Full screen.

**Expected behavior**  
Menu bar is not displayed. 
  
**Actual behavior**  
Menu bar is displayed.  
  
**Screenshots**  
![image4](https://user-images.githubusercontent.com/45422530/126618699-790db79b-60c2-415c-a85e-a2d1f78df5a2.PNG)
   
**Environment**  
 - Windows 10 Home [x64] ver 21H1;  
 - nomacs ver 3.16.1709 [x64].

**Comment by scrubbbbs** [comment]
Confirmed 3.19 [f2c6c4d](https://github.com/nomacs/nomacs/commit/f2c6c4d3d186965fe786ce9866073735ec39577a)

**Comment by leejuyuu** [comment]
@annfisher There's a PR that should fix this. You can test it with the builds from https://ci.appveyor.com/project/novomesk/nomacs/builds/50319582.
