### ISSUE TITLE
Incorrect display of windows in ‘Frameless’ mode

### ISSUE THREAD

**Issue by annfisher** [nomacs/nomacs#782]
**Steps To Reproduce**  
1.	Open nomacs app;
2.	Open image;
3.	Right-click image -> Activate Frameless;
4.	Right-click image -> Settings (for example);
5.	Right-click image -> Edit -> Image Adjustment (for example);

**Expected behavior**  
The title bar has a background.  
  
**Actual behavior**  
The title bar has not a background.   
  
**Screenshots**  
![image5](https://user-images.githubusercontent.com/45422530/126618897-7eb2c5bc-69d8-4fde-9225-9135cb2a6687.PNG)
   
**Environment**  
 - Windows 10 Home [x64] ver 21H1;  
 - nomacs ver 3.16.1709 [x64].

**Comment by scrubbbbs** [comment]
Related #617
