### ISSUE TITLE
Scan Folder Recursive no longer works

### ISSUE THREAD

**Issue by drawson1** [nomacs/nomacs#797]
I've just updated to version 3.16 as part of an openSUSE upgrade; recursive scanning no longer works.

If I have:

Folder
   | - sub1
   | - sub2

and I select "Folder", only the files in "sub1" are found and displayed; the program never recurses into "sub2"

**Comment by derkork** [comment]
Same problem on Windows, version 3.16.

**Comment by anarcat** [comment]
> I've just updated to version 3.16 as part of an openSUSE upgrade; recursive scanning no longer works.

could you clarify what version you updated *from*?

**Comment by anarcat** [comment]
@novomesk i think this is a dupe of #297.

**Comment by leejuyuu** [comment]
Closing as duplicate, please continue the discussion at #297.
