### ISSUE TITLE
UWP Apps use nomacs logo

### ISSUE THREAD

**Issue by Smumbo** [nomacs/nomacs#803]
**Describe the bug**
Some of the icons in the search menu have been corrupted and now seem to use the nomacs logo instead of their original logo. This seems to apply to every UWP app included with Windows 10 and installed from the Microsoft Store. These icons have been permanently corrupted for me, even uninstalling nomacs has not fixed the issue.

**To Reproduce**
1. Install nomacs
2. Use the Start Menu/Search function to search for a UWP app
3. Icon uses the nomacs logo instead of its own logo

**Expected behavior**
UWP app icons should retain their original logo, and not use the nomacs logo.

**Screenshots**
![vivaldi_SMUMBO-PC_23-08-21_11-36-02](https://user-images.githubusercontent.com/38147112/130500393-ac097602-a9e3-4267-bc3b-03166772ab56.png)
![vivaldi_SMUMBO-PC_23-08-21_11-37-24](https://user-images.githubusercontent.com/38147112/130500403-77cbb177-2ffd-48dd-bfcf-b693a82ab065.png)
![vivaldi_SMUMBO-PC_23-08-21_11-37-42](https://user-images.githubusercontent.com/38147112/130500406-8814da3e-cb21-47c6-bbdb-b985d29c693a.png)
![vivaldi_SMUMBO-PC_23-08-21_11-42-08](https://user-images.githubusercontent.com/38147112/130500409-7a596200-713e-401f-ba44-81795da925d8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 19043

**Additional context**
This didn't happen immediately after installing nomacs, but some time afterward.

**Comment by balintbabics** [comment]
I have the same issue (Windows 10 Pro, x64, version 21H2 19044), right after the fresh OS install, then nomacs install and reboot. Would be nice if there will be some kind of workaround to change back the UWP apps icons.

**Comment by snowflakeas** [comment]
Same issue - really annoying. 
uninstalling Nomacs does not revert the icons.

**Comment by balintbabics** [comment]
Actually, as I've figured, this issue is nothing to do with nomacs specifically. The Google Drive Client for Windows is responsible for this faulty behavior.

So I think this ticket should be closed.
