### ISSUE TITLE
Segmentation fault when pressing settings button

### ISSUE THREAD

**Issue by MPdaedalus** [nomacs/nomacs#806]
Hi

nomacs just crashes on me when I press the edit>settings button

[INFO] Hi there
[INFO] plugins dir set to:  "/usr/lib64/nomacs-plugins"
[INFO] local client created in:  3 ms
[INFO] theme loaded from "/usr/share/nomacs/Image Lounge/themes/Light-Theme.css"
[INFO] CSS loaded from:  ":/nomacs/stylesheet.css"
[INFO] Initialization takes:  95 ms

(process:41324): Gtk-CRITICAL **: 13:50:34.823: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(process:41324): Gtk-CRITICAL **: 13:50:34.823: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(process:41324): Gtk-CRITICAL **: 13:50:34.823: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
Segmentation fault (core dumped)

on fedora 34 with xfce, latest updates installed

**Comment by scrubbbbs** [comment]
Closing due to old report and not enough information to investigate. OP is welcome to reopen with more information.
