### ISSUE TITLE
Latest stable release tag changed SemVer formats???

### ISSUE THREAD

**Issue by dragon788** [nomacs/nomacs#81]
Just noticed this as it broke the Release Notes URL on Chocolatey.org. They were going on the assumption that MAJOR.Minor.patch was the standard (based on prior releases) and so they created their links with those positions, but the 3.4 tag appears to have dropped the .0 that was present in other releases. Not a huge deal, just wanted to make you aware this could break other things elsewhere.

**Comment by diemmarkus** [comment]
thanks for pointing that out.
I won't update the 3.4 tag since this might break existing links - but we will be more consistent for future releases!

**Comment by dragon788** [comment]
I think you could leave the existing 3.4 tag and add a new 3.4.0 tag and
this would fix the chocolatey usage since multiple tags on a single commit
is perfectly valid for git. Not sure how that translates into releases
though.
