### ISSUE TITLE
Nomacs doesn't render TGA files correctly

### ISSUE THREAD

**Issue by Mloren** [nomacs/nomacs#810]
When I open TGA files in nomacs, they look all washed out and white. I've attached a screenshot comparing the same TGA opened in photoshop to nomacs.

![nomacstga](https://user-images.githubusercontent.com/5114081/133912661-10ac4e53-8712-43fc-9bf6-9eb1f0b2c7f0.png)

I've also attached the TGA (had to zip it to get github to accept it) so you can try it yourself
[image.zip](https://github.com/nomacs/nomacs/files/7190863/image.zip)

**Comment by scrubbbbs** [comment]
The image has an alpha channel, so it blends with the window background. Photoshop probably doesn't recognize it, but nomacs does. Confirmed by loading image with Gimp and disabling the alpha channel.
