### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by 57382** [nomacs/nomacs#815]
This is the best picture viewer I've ever used! Better than ImageGlass.

**Comment by abma** [comment]
@sfiel @diemmarkus @timjerman 

will there be updates or is a fork needed?

**Comment by DJCrashdummy** [comment]
sadly there is an [unanswered question about the status](https://github.com/nomacs/nomacs/issues/612) since early 2021... :frowning_face:

**Comment by fcore117** [comment]
I really hope this project continues as it is the only biggest known open source image viewers, IrfanView is closed and Windows only.

**Comment by Tosh0kan** [comment]
It's dead Jim

**Comment by PeterDaveHello** [comment]
Maybe this issue is just a duplicate of #612

**Comment by abma** [comment]
it doesn't matter if this is a duplicate issue or not: someone needs to fork and maintain it.

**Comment by 57382** [comment]
update
https://github.com/nomacs/nomacs/issues/612#issuecomment-1084678367

**Comment by leejuyuu** [comment]
Please continue discussion at https://github.com/nomacs/nomacs/issues/987.
