### ISSUE TITLE
Remembering visibility settings for toolbar 

### ISSUE THREAD

**Issue by AHLudan** [nomacs/nomacs#82]
Hello
Thanks for the grate app, all grate but I could not make it remember the visibility settings for toolbar, I searched to see whether it possible in the first place [http://nomacs.org/questions-and-answers/](questions-and-answers/):
>" thomas" would like to see it remember the screen layout (toolbar/palette visibility)...
> "markus" nomacs does remember toolbar visibility/position and other elements...

It appears that it's possible , I searched for an option in `settings.nfo` but I didn't find one, other settings like` zoomToFit` is working perfectly .

**Comment by diemmarkus** [comment]
Hi,

if you uncheck `Panels >  Toolbars > Toolbar` and close nomacs, your settings.nfo should have a few lines like:
````
[AppSettings]
firstTime.nomacs.3=false
appMode=0
currentAppMode=0
showToolBar=false
````
can you confirm that?
To avoid conflicts, you should open only one instance of nomacs.

**Comment by AHLudan** [comment]
Thanks now it's working
this line was not originally exist in `settings.nfo ` :
showToolBar=false
