### ISSUE TITLE
Avif and heic have wrong colors

### ISSUE THREAD

**Issue by emperor06** [nomacs/nomacs#827]
**Describe the bug**
I'm not sure if it's related to #801.

The displayed color of avif files is wrong. Visually, it looks like a red shift. Nomacs' statusbar also show a difference: for example, an original pixel with color (65, 169, 232) becomes (66, 166, 230) on avif. This is very visible on monochrome images.

I first thought that was a problem with the avif encoder (I used both avifenc and ImageMagick) but then I tried on Firefox and the avif image did not exhibit this red shift. I then decoded the avif file to png (avifdec) and that png was displayed properly in Nomacs. So I guess the problem is within Nomacs' avif decoder.

**To Reproduce**
You can use the reference image attached here (source.avif)
1. Decode the image to png (avifdec source.avif dest.png)
2. Open both images on Nomacs
3. Switch between the two: the color is different

**Note**
In case I wasn't clear:
- the original image was a jpeg;
- encoded to avif, it displays well on Firefox but is redish on Nomacs;
- decoded back to png, it displays well on both Firefox and Nomacs (same colour as the original jpeg).

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10 LTSC 2021
 - Nomacs 3.16.1709 (x64)

[source.zip](https://github.com/nomacs/nomacs/files/7656428/source.zip)

**Comment by emperor06** [comment]
Actually, the heic decoder also give wrong colors for me. This time, the picture is yellowish.
A blue original pixel (67, 173, 235) is displayed as (66, 173, 234).

**Comment by novomesk** [comment]
I think the AVIF problem is related to https://github.com/AOMediaCodec/libavif/issues/309

The AVIF plug-in included in Windows Nomacs 3.16 installer is very old.

But you can download new version of **qavif.dll** from https://github.com/novomesk/qt-avif-image-plugin/releases and replace the old version in the
`C:\Program Files\nomacs\bin\imageformats\` folder.

The problem with HEIF/HEIC pictures is probably related to old libheif library, I believe it is rounding error which is fixed in recent versions. I think if someone rebuilds the plug-in against new version on libheif, the problem will be resolved.

**Comment by emperor06** [comment]
I just tried with the newer qavif.dll and indeed, the color problem is now gone. That's perfect.

**Comment by Delphox** [comment]
@novomesk Can you make a release on your forked repo with this and other recent improvements you've been working on? At least for the time being as nomacs devs have been MIA for a while, and the appveyor artifacts have expired (they expire after a month).

**Comment by novomesk** [comment]
@Delphox Artifacts with bundled AVIF and JPEG XL plug-in are available here:
https://ci.appveyor.com/project/diemmarkus/nomacs/builds/42006707/artifacts

**Comment by Delphox** [comment]
Thanks friend. Have downloaded them.

**Comment by novomesk** [comment]
[new_heif_plugin_for_nomacs.zip](https://github.com/nomacs/nomacs/files/7835382/new_heif_plugin_for_nomacs.zip)

This is alternative HEIF plug-in for nomacs, there is `readme.txt` with instructions how to install it.

Anti-virus scan: https://www.virustotal.com/gui/file/f336a1374d87ae9b471df2ac4f9b963d1f14abcf01f03465abd7bf3699396d05?nocache=1

**Comment by emperor06** [comment]
I just tested your new HEIF plug-in. It's very nice, the colours are now accurate. The plug-in seems a bit slower (about 36% slower on my computer) but that's not a big deal. Thanks a lot for all your hard work!

**Comment by ManFarang** [comment]
any help/installation for Linux?

**Comment by novomesk** [comment]
On Linux, there is [kimageformats](https://invent.kde.org/frameworks/kimageformats) with AVIF, HEIF and JPEG XL plug-ins.

**Comment by novomesk** [comment]
I am closing this. In AppVeyor Artifacts we usually have new builds of Windows installers. They include new AVIF and HEIF plug-ins.
