### ISSUE TITLE
Nomacs ignores .avif extension

### ISSUE THREAD

**Issue by DrReD** [nomacs/nomacs#828]
Nomacs ignores .avif, .avis and .avio extensions even though it can decode the format.
Can they be added to the list of supported extensions?

**Comment by c02y** [comment]
If you are using Linux, install `kimageformats` package, the name is the package name for Arch Linux, and it is working for avif, not sure about the other two formats.

**Comment by scrubbbbs** [comment]
duplicate #1201  which has more up-to-date information
