### ISSUE TITLE
Change player appearance 

### ISSUE THREAD

**Issue by ShalokShalom** [nomacs/nomacs#83]
Hi there - i like to change the position, opacity and size of the player: Can you implement it as new feature?
Otherwise: Can you link me the position of the source code, which manage that?

Thanks a lot in advance

**Comment by diemmarkus** [comment]
Hi,

you can change the background color/transparency in `Edit > Settings > HUD Background Color`. Or by changing the `stylesheet.css` line 74 e.g.:
````
QPushButton#DkPlayerButton {
	margin: 0px;
	border: none;
	background-color: rgba(60,60,150,0.4);
}
````
Furthermore you can change the size in `DkWidgets.cpp:1256`. Applying the stylesheet & setting height to 100 results in a player like this:
![img-2017-01-11 17 40 46](https://cloud.githubusercontent.com/assets/4182443/21857381/8b1154e2-d825-11e6-926b-05047f6acf6d.png)

I hope this helps...

**Comment by ShalokShalom** [comment]
Ok, thanks a lot, that helps very much  ^-^
