### ISSUE TITLE
Use native Qt icons

### ISSUE THREAD

**Issue by ShalokShalom** [nomacs/nomacs#84]
Hi there 

Is it possible to use my native icons, which are used for every other Qt programm on my system?

**Comment by diemmarkus** [comment]
we won't do this, sorry... (our icons are designed such that we can colorize them according to our/your needs) moreover, we would have to stick to Qts theme when creating icons that are not available in Qt)

**Comment by ShalokShalom** [comment]
I ask, if its possible for me, not to set it as default. 
If yes, how?
