### ISSUE TITLE
nomacs focus when opening

### ISSUE THREAD

**Issue by ToNIX-** [nomacs/nomacs#843]
I'm using nomacs 3.16.1709 x64 on Windows and when opening a picture, I can't use the arrow keys to browse the other pictures without first clicking anywhere inside "nomacs". 

Would it be possible to give nomacs the focus when opening a picture?

**Comment by 1337cookie** [comment]
This also restricts other hotkeys like F10, F11. When changing to and from Full Screen or Frameless mode the window must be refocused again using the mouse.

**Comment by oTnTh** [comment]
If "Meta Data Info" panel is shown by default, after startup, the input focus is in the "Filter" inputbox.

Therefore, shotcuts like Shift+T, won't work unless click the image area by mouse.
