### ISSUE TITLE
Revert crop feature to v3.16 (until there's a better one)

### ISSUE THREAD

**Issue by c0xc** [nomacs/nomacs#850]
**Is your feature request related to a problem? Please describe.**
Hello `<void>`. I am about to revert the new crop tool from v3.17 because it does not allow precise cropping anymore. If anyone has strong negative feelings about this, please leave a comment here.

In the old version you would select a section of the image, which you were able to zoom to make a precise cut. In the new version, it basically works the other way around, so you'd have a white grid centered in the middle of the window and instead of moving that section, you are moving the full image in the background. If you try to zoom out, the grid moves. Sometimes the grid jumps around, I haven't yet figured out when and how, exactly. But it often jumps around, so you'd end up cropping a different section of the image. All I can say is that cropping an image, something which used to be so simple that I never really thought about it, is now very difficult or, if the selection keeps jumping around, impossible.

**Describe the solution you'd like**
I understand that a lot of effort has been put into this new tool and I'm hesitant to revert someone else's work. But to be honest, v3.16 had a crop feature that worked just fine, you could easily select an area, zoom in to make sure you're not cutting something important off, zoom back out and confirm. I still want to be able to crop like that.

**Describe alternatives you've considered**
I've compared both versions. Obviously, my first thought about fixing the new crop feature is to make it work like the old one. But it seems like this would require much more work than reverting the old one. If I have more time later on, I might try to fix it, but for now, I'd rather improve other things and revert this, at least in the master branch.
There are several minor annoyances that could also be improved. For example, in v3.16 when clicking outside of the cropped area, you'd accidentally rotate it. I'm not sure why rotating is integrated into the crop feature at all but it could probably be fixed to rotate only if the corners are clicked. On the other hand, the new crop tool in v3.17 has a slider at the bottom, which only allows rotating up to 45 degrees, apparently. Then, there's a separate rotate feature (Edit menu), which shows a slider in the panel at the right side of the window, but the slider cannot be adjusted using the keyboard (rotating one more degree...) and when clicking on it, it jumps around because there's a preview underneath it which changes in size.
Either way, some of those things could probably be improved but those improvements would not be worth it if the new crop tool stayed the way it is now.

**Additional context**
https://github.com/nomacs/nomacs/issues/345
https://github.com/nomacs/nomacs/issues/547

**Comment by c0xc** [comment]
Video showing the new, buggy crop feature, how the section moves when zooming:
![Peek 2022-10-17 22-29](https://user-images.githubusercontent.com/7249348/196278994-38faa35d-eac6-4b1e-8e3b-b93433cc0fba.gif)

Video showing the old crop feature, which could be used to make a precise cut:
![Peek 2022-10-17 22-30](https://user-images.githubusercontent.com/7249348/196279772-b4275c04-d0c0-4379-8a96-216341624be0.gif)

**Comment by leejuyuu** [comment]
Closing this as completed by #930.
