### ISSUE TITLE
Building for Windows with MinGW

### ISSUE THREAD

**Issue by eddiezato** [nomacs/nomacs#853]
Currently building for Windows is set up in cmake files for MSVC only. It would be good to have it for MinGW also.

I have tried several times to build `nomacs` in `MSYS2/CLANG64` environment, but I don't seem to have enough knowledge to solve all the problems that arise.

**Comment by ChiaYen-Kan** [comment]
Hi:

i create a patch file for build with msys in x86_64 mode

not perfect but it can work, may be someone can make it to more perfect 

patch file:
[0001-fix-for-build-with-msys2.patch](https://github.com/nomacs/nomacs/files/11684606/0001-fix-for-build-with-msys2.patch)

build log:
[nomacs-build.log](https://github.com/nomacs/nomacs/files/11684574/nomacs-build.log)

**Comment by eddiezato** [comment]
@ChiaYen-Kan thanks!
I was finally able to build.

**Comment by eddiezato** [comment]
@ChiaYen-Kan Hey, sorry to bother, can you update your patch file? Want to try to build from the current master with Qt6.

**Comment by ChiaYen-Kan** [comment]
@eddiezato
It seems impossible at the moment
In this project is depend some qt5 function, that's not exist in qt6, and no solution in qt6
and the original patch is base Unix/Linux config, but Unix/Linux config seem not yet full move to qt6(also include plugins project)

https://forum.qt.io/topic/131934/is-there-an-alternative-to-qwintaskbarbutton-in-qt-6/2
https://doc.qt.io/qt-6/extras-changes-qt6.html

**Comment by ChiaYen-Kan** [comment]
@eddiezato 
msys2 + Qt6, drop the Qt5 feature

patch file, see the build log to patch all component
[0-main-0001-fix-build-with-msys2-Qt6.patch](https://github.com/nomacs/nomacs/files/14447706/0-main-0001-fix-build-with-msys2-Qt6.patch)
[1-3rd-party-imageformats-0001-fix-for-qt6.patch](https://github.com/nomacs/nomacs/files/14447705/1-3rd-party-imageformats-0001-fix-for-qt6.patch)
[2-plugins-0001-fix-for-qt6.patch](https://github.com/nomacs/nomacs/files/14447707/2-plugins-0001-fix-for-qt6.patch)

log
[build.log](https://github.com/nomacs/nomacs/files/14447700/build.log)

no test, and you want to build with msys2, please push the nomacs team support it

**Comment by eddiezato** [comment]
@ChiaYen-Kan Thanks! I appreciate your time. Was able to build. Hope devs will pay attention to your patches for future migration to Qt6. But for me nomacs without at least zip support is useless for now.
