### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by C0rn3j** [nomacs/nomacs#86]
Would it be possible to add WebP support to nomacs?

https://en.wikipedia.org/wiki/WebP

**Comment by diemmarkus** [comment]
Hi Martin,
nomacs supports WebP. If not, which platform are you using (& which nomacs version?)

**Comment by C0rn3j** [comment]
Hi Markus,

I'm on Arch Linux, using nomacs 3.4.

This picture opens in Xnview MP but nomacs says that it couldn't open it.

https://www.dropbox.com/s/cwvdp0q0jm8ptt9/photo_2017-01-09_02-08-03.webp?dl=1

**Comment by agaida** [comment]
@C0rn3j - just install qt5-image-formats-plugins - that should solve that, at least it does on debian iirc

**Comment by C0rn3j** [comment]
Installing qt5-imageformats let's me view webp images. 

I will be filling a bug report to add this package as a dependency(or at least an optional one).

Thanks for your help.

**Comment by diemmarkus** [comment]
awesome thx!
