### ISSUE TITLE
Nomacs doesn't exists in Debian 11 official repositories.

### ISSUE THREAD

**Issue by Orange23333** [nomacs/nomacs#860]
# **Is your feature request related to a problem? Please describe.**
At [download page](https://nomacs.org/download/), it said I can install `nomacs` from debian official repositories. But when I tried to install, it said `nomacs` doesn't exists in `Debian 11` official repositories. And I just remeber I could install it in `Debian 10`. What's wrong?

# **Describe the solution you'd like**
Add `nomacs` to official repositories, thanks.

# **Describe alternatives you've considered**
Nope, I'll compile by myself. You can remove the pushed package distribution of `Debian` from the website.
*By the way, the comment feature (`TOUGHTS`) is awful, they're just adult ADs and somthing doesn't about `nomacs`*

# **Additional context**
## Environemnt
OS Version:
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

**Comment by novomesk** [comment]
Debian maintainers decide what is in they repository and what isn't.

I guess they excluded nomacs, because there was no development activity for a long time. They expected fixes for some of the issues they encountered.

**Comment by yMNmZWL8V4** [comment]
Because of this i compiled nomacs from source for Debian 11 and it works exactly as expected.

**Comment by c0xc** [comment]
https://packages.debian.org/en/sid/nomacs

**Comment by leejuyuu** [comment]
Because this is not currently actionable by us, I am closing this issue for now. Please contact the Debian package maintainers to move Nomacs back into the official repository. I think understanding exactly why Nomacs was excluded could be helpful, like knowing which bugs are blocking them, etc.

Feel free to comment or reopen. Thanks!

**Comment by OParczyk** [comment]
As far as I can tell this is what kept nomacs out of bullseye and bookworm: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=974616

**Comment by leejuyuu** [comment]
@OParczyk The #1049 a few days ago seems to have fixed that.
