### ISSUE TITLE
RAW support for the OM Systems / OM-1

### ISSUE THREAD

**Issue by JJausF** [nomacs/nomacs#861]
Can I hope that you will still provide RAW support for the OM Systems OM-1? The camera came on the market in February. The old Olympus cameras are also supported by nomacs. I would be very happy.

Greeting Joerg

PS: Text was automatically translated

**Comment by novomesk** [comment]
nomacs use https://github.com/LibRaw/LibRaw to read RAW files.

So it depends if support is added to LibRaw first.

**Comment by novomesk** [comment]
![om1_nomacs](https://user-images.githubusercontent.com/52529860/184191030-17b0b2da-2c11-4db1-b565-2fb8ecca67f9.png)
The newest build for Windows is able to open .ORF raw from OM-1.
Download is temporarily available at https://ci.appveyor.com/project/diemmarkus/nomacs/builds/44443339/artifacts
