### ISSUE TITLE
PNG and HEIC image preview in explorer.exe

### ISSUE THREAD

**Issue by lx30011** [nomacs/nomacs#869]
**Is your feature request related to a problem? Please describe.**
These are two very popular image formats but nomacs only does JPEG thumbnails in explorer.exe

**Describe the solution you'd like**
Implement PNG and HEIC preview

**Describe alternatives you've considered**
N/A

**Additional context**
Thanks

**Comment by WeaverWorks** [comment]
Hi @lx30011 

PNG and HEIC thumbnails are working fine for me in Windows 10 with Nomacs as default viewer.

Could you plese check you don't have "Always show icons, never thumbnails" ticked in the folder options?

![File Options](https://user-images.githubusercontent.com/108929963/178166324-4ab9476c-52ef-46cf-a293-21892d9732d0.jpg)

**Comment by lx30011** [comment]
It must have been a hickup because after a restart it has been working ever since. Sorry for not troubleshooting before creating this issue.
