### ISSUE TITLE
Thumbnail Panel on footer, instead of header

### ISSUE THREAD

**Issue by devirrived** [nomacs/nomacs#893]
**Is your feature request related to a problem? Please describe.**
Thumbnails on top (header) are covering some important information on some screenshoots that I take, like the title of the window/document that I was using

![Captura de Tela (224)](https://user-images.githubusercontent.com/45222946/192179455-c37ec9a0-2b56-4c89-975b-986611677edb.png)

**Describe the solution you'd like**
Using the Thumbnails Panel on Footer, like Windows Photos does, only covers the Windows bar, so there's no important information being covered.

![Captura de Tela (225)](https://user-images.githubusercontent.com/45222946/192179476-3eb80a9b-4b45-4045-83d9-f4a62d99945b.png)

So I'd like to have an option of changing the position of Thumbail (T) Panel from the header to the footer of the screen/photo

**Comment by scrubbbbs** [comment]
@devirrived you can right-click over the thumbnail strip and pin it to the bottom
