### ISSUE TITLE
Allow browsing photos using the keyboard from the file explorer

### ISSUE THREAD

**Issue by sporto** [nomacs/nomacs#914]
If I have the File Explorer panel selected I can use the keyboard arrows to change directories and photos on a directory.
However the preview panel on the right does nothing, I need to click on a photo to see it.

**Describe the solution you'd like**
As I use up / down on the File explorer, I would like the panel on the right to show the highlighted photo on the left.

Thank you

**Comment by scrubbbbs** [comment]
This is possible by enabling "Open Selected Image" in the context menu of File Explorer. It has been that way for awhile. Use the up/down and left/right arrow keys to navigate.
