### ISSUE TITLE
can't open .webp

### ISSUE THREAD

**Issue by klownie** [nomacs/nomacs#926]
**Describe the bug**
cant open webp

**To Reproduce**
try to open a webp in nomacs

**Expected behavior**
opens the image

**Screenshots**
![image](https://user-images.githubusercontent.com/104706690/221840217-9a999815-7f43-40ba-a6c8-d7246cb7a2aa.png)

**Desktop (please complete the following information):**
 - OS: Archcraft
 - 6.1.12-arch1-1 

**Additional context**
i'm using dwm

**Comment by klownie** [comment]
sorry i found the answer to my question.
https://github.com/nomacs/nomacs/issues/86

**Comment by anrxc** [comment]
If you land here from first Google result because you could not open _some_ webp images on Windows 10  (up to version 3.17.2289) . Know that from version 3.17.2297 it seems to be fixed, they are now opening.
