### ISSUE TITLE
.avif files created by nomacs in Arch does not load

### ISSUE THREAD

**Issue by klownie** [nomacs/nomacs#929]
**Describe the bug**
After saving an image as a .avif the newely created image can not be viewed by nomacs
I have the qt-avif-plugin and I have tried creating a .avif on windows. The .avif created from the windows nomacs in viewable in linux but the one created in linux is not viewable in both OS.

**To Reproduce**
1. Go to 'File'
2. Click on 'Save as'
3. Scroll down to 'Choose to save as .avif'
4. See error (could not load)

**Expected behavior**
can view the .avif

**Screenshots**
unviewable .avif image created in linux nomacs
![image](https://user-images.githubusercontent.com/104706690/222671554-37f21f11-4f7d-47f0-a99f-425449cb161f.png)
here is a sample of the image 
https://drive.google.com/file/d/1jHm6OKEqYfe0L-FpYuYPVAgtV02ASiY4/view?usp=share_link

viewable .avif created in windows nomacs and viewed with linux nomac
![image](https://user-images.githubusercontent.com/104706690/222671971-4de7111e-356e-4008-a104-e38b17aedb30.png)

**Desktop (please complete the following information):**
 - OS: Archcraft
 - Version : 6.2.1-arch1-1 

**Additional context**

**Comment by uservar** [comment]
I have the same issue on manjaro.

**Comment by uservar** [comment]
Turns out installing the more recent nomacs-git version from the AUR fixes this problem for me. It was missing some requirements though so I had to install opencv and quazip-qt5 for it to build.

**Comment by klownie** [comment]
> 

thanks that fixed the issue :)
