### ISSUE TITLE
Why don't they release releases? Compiling only?

### ISSUE THREAD

**Issue by procobain** [nomacs/nomacs#931]
Lots of commits and no releases since 2020, why?

**Comment by Tosh0kan** [comment]
The repo owner doesn't have time anymore to have anything to do with this project.

**Comment by Galaxoid-333** [comment]
> The repo owner doesn't have time anymore to have anything to do with this project.

As far as I know, the application was made by a group of developers. All of them have no interest in developing Nomacs? Such good viewers are rare.

**Comment by 57382** [comment]
hi! you can download the latest release here.
https://ci.appveyor.com/project/diemmarkus/nomacs/build/artifacts

**Comment by 57382** [comment]
hi! you can download the latest release here.
https://ci.appveyor.com/project/diemmarkus/nomacs/build/artifacts

**Comment by Galaxoid-333** [comment]
> hi! you can download the latest release here. https://ci.appveyor.com/project/diemmarkus/nomacs/build/artifacts

what's new in this version?

**Comment by 57382** [comment]
> > hi! you can download the latest release here. https://ci.appveyor.com/project/diemmarkus/nomacs/build/artifacts
> 
> what's new in this version?

fixed silent writing to raw file after rotating image. the user is now asked if they want to write to the file to save changes. better metadata support. add new translations. and more...

**Comment by Galaxoid-333** [comment]
> > > hi! you can download the latest release here. https://ci.appveyor.com/project/diemmarkus/nomacs/build/artifacts
> > 
> > 
> > what's new in this version?
> 
> fixed silent writing to original file after rotating image. the user is now asked if they want to write to the file to save changes. better metadata support. add new translations. and more...

OK. Are you a Nomacs developer? Or do you have access to the application code?

Another question. The latest version of the app is here 3.17.2206 Beta. According to your link, the version of the application is 3.16.454. There was a fork?

**Comment by c0xc** [comment]
> > The repo owner doesn't have time anymore to have anything to do with this project.
> As far as I know, the application was made by a group of developers.

See issue #612 where the original author has left a [comment](https://github.com/nomacs/nomacs/issues/612#issuecomment-1084588625).

> fixed silent writing to original file after rotating image. the user is now asked if they want to write to the file to save changes.

I'm happy that someone out there finds my [fix](https://github.com/nomacs/nomacs/issues/799) useful.

**Comment by leejuyuu** [comment]
You can download the lastest windows builds at https://github.com/nomacs/nomacs/releases. I am closing this issue for now. Feel free to reopen :)
