### ISSUE TITLE
Bilinear filtering for low-res images

### ISSUE THREAD

**Issue by weter11** [nomacs/nomacs#934]
**Describe the bug**
Viewer by default uses nearest filtering instead of modern standarts when resizing images

**To Reproduce**

Open any image which have lower resolution than your screen, or even photo, if you have 8K TV

**Expected behavior**

A bit blurry with letters, numbers smoothed but not jaggy image like from 1990

**Additional context**

It would be nice to see modern filters like Anime4k or waifu2x, but at least bilinear filter. Sadly this viewer one of the best, even can show you photo geolocation and full data from exif but because of this bug it's useless for some graphics, pictures with low-res and I don't know how to limit one viewer for high-res and another for all other low-res images.
Also as I know project is dead, because #581 was opened 3 years ago and still no any answer from devs. Antialiasing option only work for some anime/cartoon-style pictures, which have resolution higher than your display, but if you have 4K monitor number of such images hugely decreases.

**Comment by scrubbbbs** [comment]
Duplicate #581
