### ISSUE TITLE
Don't secretly re-write files

### ISSUE THREAD

**Issue by lx30011** [nomacs/nomacs#936]
**Describe the bug**
When you rotate an image in the viewer it re-writes the files
I verified nomacs rewrites file by comparing xxd output, it changes after rotating

**To Reproduce**
Rotate image

**Expected behavior**
Modifications to the original file should only be applied on explicit user action, clicking disquette icon

**Desktop (please complete the following information):**
 - OS: Windows
 - Version can't find version info

**Additional context**
retarded

**Comment by novomesk** [comment]
Try to download developement build
`nomacs-setup-x64.msi` from

https://ci.appveyor.com/project/diemmarkus/nomacs/builds/46510221/artifacts (download will expire in one week)

to see if the issue persist or it was fixed there meanwhile.

**Comment by 57382** [comment]
> Try to download developement build `nomacs-setup-x64.msi` from
> 
> https://ci.appveyor.com/project/diemmarkus/nomacs/builds/46510221/artifacts (download will expire in one week)
> 
> to see if the issue persist or it was fixed there meanwhile.

fixed.

**Comment by leejuyuu** [comment]
Closing as finished.
