### ISSUE TITLE
Wrong Coordinates in Menubar when using Crop (V 3.16.1709)

### ISSUE THREAD

**Issue by SystemSpam** [nomacs/nomacs#944]
Hello.

I found NoMac Image Lounge when I was looking for a cross-platform alternative for IrfanView.
I like your tool very much, but I have found an unsightly behavior when i mark a area for crop.

When I select an area with the "Crop"-Function, other coordinates are stored in the menu bar than the real start coordinates of the marker  (see Picture attached)
I use this manual Crop to detect the Coordinates for a later Batch-Processing, but the Crop-Area doesn't match.

Is this intentional or can it be adjusted so that the correct marked start coordinates?

![NoMac_Bugreport_Coordinates](https://user-images.githubusercontent.com/132557010/236157934-a894c2a2-800e-4be9-b1e3-9bf2247c59ca.png)

with best regards

Robert

**Comment by novomesk** [comment]
I don't remember. I only know that crop was modified several times during last years.

**Comment by leejuyuu** [comment]
Got it. This inconsistency feels unintended, so I will mark this as a bug and investigate for now.

**Comment by haferburg** [comment]
@leejuyuu I attempted to fix it myself. Feel free to take a look.
