### ISSUE TITLE
Single Instance Option

### ISSUE THREAD

**Issue by diemmarkus** [nomacs/nomacs#95]
if user open an image by double clicking it from a file browser, a tab should be added to an existing instance rather than opening a new instance.

**Comment by artofit** [comment]
In 3.17 no change
Next milestones?

**Comment by Parodocs** [comment]
I'm guessing that there isn't a solution. Odd. All of the other icons in the taskbar stack.
No worries - new software.
Bye.

**Comment by Zector** [comment]
got really excited this would be a feature when i realized settings opens in a new tab. what's up with that?

**Comment by leejuyuu** [comment]
Closing because of duplicate.
