### ISSUE TITLE
Nomacs NOT Working at Arch Linux

### ISSUE THREAD

**Issue by velan001** [nomacs/nomacs#952]
In few days nomacs are not opening in my system . I will check where is the problem by opening nomacs through terminal the output is nomacs: error while loading shared libraries: libexiv2.so.27: cannot open shared object file: No such file or directory

My System is Arco Linux based on Arch.

**Comment by FabioLolix** [comment]
@velan001 every time you get an error like
 `error while loading shared libraries: libXXX.so.XXX: cannot open shared object file: No such file or directory`
mean you need to rebuild the pacakge, the AUR pkgbuild have already been updated with a patch for building with the new exiv2 version when you posted

also don't use caps lock when writing

**Comment by iq2luc** [comment]
Hello @velan001, see https://github.com/nomacs/nomacs/issues/951#issuecomment-1584107223 for a working PKGBUILD.

**Comment by FabioLolix** [comment]
This has been resolved and can be closed
