### ISSUE TITLE
Not switching to other images

### ISSUE THREAD

**Issue by TobiasReich** [nomacs/nomacs#954]
I'm not sure if this is a bug or a feature. But I recently noticed something has changed.
In earlier days I was able to open one image and then switch through the other pictures of the same folder.
This still works in some folders (e.g. home) but not in other directories (e.g. /tmp).
I could swear that was different not long before but I'm not even sure this is a bug or a feature (or some setting I have missed).

1. Open a picture in your home directory
2. Switching through the pictures workes fine
3. Open a picture in another folder like /tmp
4. Switching does not work, preview shows only one image (even though I copied the exact folder here)

**Desktop (please complete the following information):**
 - OS: Arch Linux (Manjaro)
 - Version 3.16

Is this a permission thing? I did not change any but maybe I missed something.

**Comment by leejuyuu** [comment]
Hello @TobiasReich , I cannot produce this with nomacs 3.19.1 (ba263741) on Arch Linux. Could you try a new version? 

If you suspect this is due to the file permissions, please also check whether they are different in the two directories.

**Comment by leejuyuu** [comment]
Glad to hear that it works. Thanks!
