### ISSUE TITLE
crash on startup: error loading libopencv

### ISSUE THREAD

**Issue by strangeQuark1041** [nomacs/nomacs#960]
Running `nomacs` in zsh gives the following error:
```
nomacs: error while loading shared libraries: libopencv_core.so.407: cannot open shared object file: No such file or directory
```
A recent system update seems to have deleted the `libopencv_core.so.407` file.
I copied it back from a backup into `/usr/local/lib`, however it gives the same error.
Re-installing nomacs does not help.

Context: nomacs installed via pacman on garuda-linux

**Comment by jmainhard** [comment]
Reinstalling worked for me 🤔
