### ISSUE TITLE
Zoom percentage no longer appearing at the lower-left corner

### ISSUE THREAD

**Issue by EboniLM** [nomacs/nomacs#964]
**Describe the bug**
The zoom percentage is no longer visible at the lower-left corner as of a couple of updates ago. There doesn't appear to be anywhere within the Settings to manually toggle this either. 

It seems that the only way to view a zoom percentage is when the "Overview" is enabled, which is not ideal as this tool itself covers the upper left portion of the image. 

Was this an intended change? Or is it possible to add this back to the app?

If there does happen to be a setting to re-enable this, I do apologize. I've been checking non-stop and have been unable to find one.

**Desktop (please complete the following information):**
```
Operating System: Arch Linux                      
Kernel: Linux 6.4.2-arch1-1
Architecture: x86-64
```

**Comment by nrvos** [comment]
I noticed this as well, also that the window title was no longer displaying the image size. I narrowed it down to commit 9c53a6a breaking it, and applying this patch fixed it for me:
```
diff -ruN nomacs/ImageLounge/src/DkGui/DkNoMacs.cpp nomacs-fix/ImageLounge/src/DkGui/DkNoMacs.cpp
--- nomacs/ImageLounge/src/DkGui/DkNoMacs.cpp	2023-06-26 15:45:23.687370365 -0400
+++ nomacs-fix/ImageLounge/src/DkGui/DkNoMacs.cpp	2023-07-10 19:51:31.307581778 -0400
@@ -1715,9 +1715,9 @@
     auto vp = getTabWidget()->getViewPort();
 
     if (!size.isEmpty())
-        attributes.asprintf(" - %i x %i", size.width(), size.height());
+        attributes.sprintf(" - %i x %i", size.width(), size.height());
     if (size.isEmpty() && vp && !vp->getImageSize().isEmpty())
-        attributes.asprintf(" - %i x %i", vp->getImage().width(), vp->getImage().height());
+        attributes.sprintf(" - %i x %i", vp->getImage().width(), vp->getImage().height());
     if (DkSettingsManager::param().app().privateMode)
         attributes.append(tr(" [Private Mode]"));
 
diff -ruN nomacs/ImageLounge/src/DkGui/DkViewPort.cpp nomacs-fix/ImageLounge/src/DkGui/DkViewPort.cpp
--- nomacs/ImageLounge/src/DkGui/DkViewPort.cpp	2023-06-26 15:45:23.694037032 -0400
+++ nomacs-fix/ImageLounge/src/DkGui/DkViewPort.cpp	2023-07-10 19:51:45.587581783 -0400
@@ -530,7 +530,7 @@
         return;
 
     QString zoomStr;
-    zoomStr.asprintf("%.1f%%", mImgMatrix.m11() * mWorldMatrix.m11() * 100);
+    zoomStr.sprintf("%.1f%%", mImgMatrix.m11() * mWorldMatrix.m11() * 100);
 
     if (!mController->getZoomWidget()->isVisible())
         mController->setInfo(zoomStr, 3000, DkControlWidget::bottom_left_label);
```
The Qt documentation says the QString function `sprintf` is "obsolete" but apparently changing that to `asprintf` was what broke this. If you're on Arch, you can add the patch to the PKGBUILD from the AUR, rebuild and install the package, and it should work.

[nomacs-window-title-zoom-level.patch.txt](https://github.com/nomacs/nomacs/files/12017623/nomacs-window-title-zoom-level.patch.txt)

**Comment by novomesk** [comment]
@v-tyrtov What do you think about it?
