### ISSUE TITLE
Regression in 2282: When "Mouse wheel zooms" is checked, Alt+Scroll wheel always navigates the images backwards, even when scrolling down

### ISSUE THREAD

**Issue by perk11** [nomacs/nomacs#968]
**Describe the bug**
After upgrading from version 1:3.17.2206-12 to version 1:3.17.2282-3 from AUR, Alt+Scroll wheel started to ignore the direction of the wheel and always load previous image.

**To Reproduce**
1. Enable "Mouse wheel Zooms" in the settings.
2. Open an image with at least 3 images in that folder
3. Hold Alt and scroll the mouse wheel down
4. Previous image is displayed.

**Expected behavior**
Next image is displayed. This how it worked in previous versions and also this is how it works when "Mouse Wheel Zooms" isn't checked.

**Screenshots**
All settings:
![image](https://github.com/nomacs/nomacs/assets/1924829/2249da79-96b3-42ba-b672-4772638868ae)
![image](https://github.com/nomacs/nomacs/assets/1924829/094495c8-13f0-404f-8745-5944842815fd)
![image](https://github.com/nomacs/nomacs/assets/1924829/2eab0edb-f935-46cc-9aad-8352ffb2a4c7)
![image](https://github.com/nomacs/nomacs/assets/1924829/b1b2bc01-d8e2-44a3-9717-19bb52fed510)

**Desktop (please complete the following information):**
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.10
Kernel Version: 6.1.38-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 3700X 8-Core Processor
Memory: 62.7 GiB of RAM
Graphics Processor: AMD Radeon RX 5700 XT

**Comment by perk11** [comment]
I did a git bisect, and it was broken recently:

9c53a6a1f3391497668162939835a5f6c99d2456 is the first bad commit
commit 9c53a6a1f3391497668162939835a5f6c99d2456
Author: Daniel Novomeský <dnovomesky@gmail.com>
Date:   Wed May 10 17:37:37 2023 +0200

    Replace obsoleted Qt code
    
    Reusing portion of work by v-tyrtov to prepare the application
    to support future Qt versions.

**Comment by perk11** [comment]
@novomesk  I narrowed it down to this line https://github.com/nomacs/nomacs/blob/master/ImageLounge/src/DkGui/DkViewPort.cpp#L1265

It seems like when Alt is pressed, that swaps x() and y() axis. So if I change that to       if (event->angleDelta().x() < 0), it now works with Alt pressed, but not if I uncheck "Mouse wheel Zooms" option.

**Comment by novomesk** [comment]
@v-tyrtov Vyacheslav, please take a look. Do you have any suggestion?

**Comment by v-tyrtov** [comment]
I've created https://github.com/nomacs/nomacs/pull/971 to fix the incorrect behavior

Would be great to test on non-Linux platforms

**Comment by perk11** [comment]
I tried the version 3.17.2287, and when using "Ctrl and Alt Switched" Setting,  Alt+Scroll wheel doesn't work anymore. It just doesn't scroll. It works if I disable this setting with "Ctrl+Scroll". 

Alt+Scroll works on version 3.17.2206 with "Ctrl and Alt Switched" Setting turned on.

**Comment by v-tyrtov** [comment]
I looked into this during porting to Qt5.15
The behavior itself was a bit complicated depending on vertical or horizontal scroll and swap or not Ctrl and Alt
Indeed the horizontal scroll was broken - which I addressed in https://github.com/nomacs/nomacs/pull/1022/commits/a46483923fce75b1227e9002b853d62d0e017417

Still it's unclear what is the proper user journey with both vertical and horizontal scrolling and scroll on wheel mode.

**Comment by v-tyrtov** [comment]
@perk11 could you please check if it was fixed with https://github.com/nomacs/nomacs/releases/tag/3.17.2295 ?

**Comment by perk11** [comment]
Just tried on 3.17.2295, getting the same behavior.
With the following settings:
![image](https://github.com/nomacs/nomacs/assets/1924829/3fdd64ba-9f89-4ce9-96df-9f3dfdb8b6c0)
Scroll and Ctrl+Scroll goes through images in the directory, Alt+Scroll does nothing.

With the following settings:
![image](https://github.com/nomacs/nomacs/assets/1924829/b1ef29d7-27d6-4a36-b0c6-b9de748cb5ce)
Scroll goes through images in the directory, Ctrl+Scroll zooms in, Alt+Scroll does nothing.

**Comment by perk11** [comment]
Seems like there is also #1044 but I can't reproduce it.

**Comment by v-tyrtov** [comment]
@perk11 if I'm reading right you have an issue in Linux.
What is the Qt  version used?

My observations:
1) My local build for Linux works also as expected for both Qt5.15.12 and Qt6 (Alt-scroll can move though images or zoom depending on corresponding settings)
2) The last build for Win (3.17.2297 Qt5.15.2) indeed has Alt behavior degradation in comparison with 3.17.2206 (Qt 5.14.2)
Zoom / scroll doesn't work when Alt is used - seems it's close to the described in https://github.com/nomacs/nomacs/issues/968#issuecomment-1985114582

@perk11 wold you be able to build nomacs locally with the latest Qt5.15?

**Comment by perk11** [comment]
@v-tyrtov yes, this is on Linux. I have nomacs 3.17.2295-2 from AUR with Qt 5.15.12.

**Comment by v-tyrtov** [comment]
Thanks - I narrowed it down to the graphic platform (I tested it with Wayland before)

And actually it's interesting one - we have different Qt(?) behavior for X11 and Wayband
https://bugreports.qt.io/browse/QTBUG-91556

Looks like in case of X11 and Win X and Y axis are swapped in case of Alt modifier (but not for Wayland)

Created https://github.com/nomacs/nomacs/pull/1046

Still, for nomacs we have too complicated options with unclear priorities:
1) swap horizontal and vertical scroll
2) swap Ctrl and Alt
3) swap zoom and scroll 

I have no idea what is the proper behavior in a half of these cases.
