### ISSUE TITLE
Offline installer doesn't work

### ISSUE THREAD

**Issue by manad777** [nomacs/nomacs#97]
The "nomacs-setup-offline.exe" doesn't work without an Internet connection. It tries to connect to the network, then refuses to install. 

The "nomacs-setup.exe --script install-script.js" approach doesn't work. It also tries to connect to the network instead of using the local script.

Please rethink nomacs' architecture because its current state is terrible.

Forget about repositories, forget about making users download a 25MB "online installer" (this is the first time I see one larger than 2MB), forget about forcing updates at launch. You're not writing an operating system here. Have you ever seen any software application that does this stuff (and worse, fail at it)? 

Just make a simple installer that works. nomacs is extremely overengineered for such a simple app, to the point of literally being unusable. 

At the very least, the next time there's a release, before you publish it online, the offline installer should be tested by disconnecting the Internet.

**Comment by diemmarkus** [comment]
thanks for pointing that out, we have fixed it. A simple statement like 
> The offline installer does not operate offline.
would suffice next time...

cheers,
markus

**Comment by manad777** [comment]
I'm sorry, I was frustrated when I wrote that, due to relying on the offline installer without thinking of testing it first.

I stand by my criticism, though not the way it was worded. The app does seem unnecessarily overengineered considering it's a lightweight image viewer, which is why this bug exists. Simpler code leads to fewer bugs.

But sorry once again.
