### ISSUE TITLE
nomacs not support cuda 12.2

### ISSUE THREAD

**Issue by xsqkv** [nomacs/nomacs#970]
I use Arch Linux and when i update cuda to 12.2 version and when download and try to compile nomacs from the sources build log writes this in terminal:
```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find CUDA: Found unsuitable version "12.2", but required is exact
  version "12.1" (found /opt/cuda)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:598 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindCUDA.cmake:1268 (find_package_handle_standard_args)
  /usr/lib/cmake/opencv4/OpenCVConfig.cmake:86 (find_package)
  /usr/lib/cmake/opencv4/OpenCVConfig.cmake:108 (find_host_package)
  cmake/Unix.cmake:41 (find_package)
  CMakeLists.txt:110 (include)


-- Configuring incomplete, errors occurred!
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: nomacs-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
nomacs - exit status 4
```
Please solve this problem, i can't use my favorite image viewer nomacs.

**Comment by FabioLolix** [comment]
Hello @xsqkv, I'm the AUR maintainer of nomacs stable pkgbuild, this issues is stilll relevant?

I have build nomacs quite a lot of times but my system have an AMD video card but I have looked at cmake options sevral times and didn't see a reference to CUDA, now for testing I had made a build using Arch's devtools to include CUDA in the makedepends; the build succeded and didn't see any ref to CUDA, can you paste a full log?

**Comment by xsqkv** [comment]
> Hello @xsqkv, I'm the AUR maintainer of nomacs stable pkgbuild, this issues is stilll relevant?
> 
> I have build nomacs quite a lot of times but my system have an AMD video card but I have looked at cmake options sevral times and didn't see a reference to CUDA, now for testing I had made a build using Arch's devtools to include CUDA in the makedepends; the build succeded and didn't see any ref to CUDA, can you paste a full log?

Hello @FabioLolix , Now it's works fine
