### ISSUE TITLE
nomacs website

### ISSUE THREAD

**Issue by gattsuchan** [nomacs/nomacs#997]
brother the website was stolen by steroid sales person

**Comment by C0rn3j** [comment]
You don't need to buy anything, you can see that it's registered since 2011 and has a pending transfer.

https://lookup.icann.org/en/lookup

**Comment by mmahmoudian** [comment]
The website is not stolen. We were (and still are) in the process of handling the website and bringing it to Github Pages. It was previously hosted privately and it was not feasible any more. The old website for the time being can be accessed via https://nomacs.cvl.tuwien.ac.at/ and the new website has its own dedicated Github repo in the following address: https://github.com/nomacs/nomacs.github.io

The goal is to transfer the information of the previous website to the new website and do some changes to the style as well. Sorry for the inconvenience.

**Comment by leejuyuu** [comment]
Because this issue became inactive, I am closing this for now. As mentioned in the previous comment, the new website has been developed at https://github.com/nomacs/nomacs.github.com. Please reopen or create a new issue if any questions or suggestions comes up, thanks!
